DFE-Digital/claim-additional-payments-for-teaching

- app/views/admin/claims/show.html.erb
- app/views/admin/tasks/_claim_summary.html.erb
- spec/features/admin_claim_without_personal_data_spec.rb
- spec/features/admin_duplicate_claims_spec.rb
Relates to PR https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/994 
Make the new "task list" view of a claim the primary screen for working with claims.
Claims with personal data removed now indicate those fields with "Removed" as we do on the "Full claim view" within the task view page.
Warning banners for matching claims and missing payroll gender have now been removed from the "Full claim view"
**Before:**
**After:**
> Other task view changes

- CHANGELOG.md
- app/controllers/admin/notes_controller.rb
- app/models/claim.rb
- app/models/note.rb
- app/views/admin/claims/_tabs.html.erb
- app/views/admin/notes/_form.html.erb
- app/views/admin/notes/index.html.erb
- config/routes.rb
- db/migrate/20200330135833_create_notes.rb
- db/schema.rb
- spec/factories/notes.rb
- spec/features/admin_claim_notes_spec.rb
- spec/models/note_spec.rb
- spec/requests/admin_notes_spec.rb
- spec/support/request_helpers.rb
This adds a simple notes feature that allows service operators to add notes against claims:
> Service operators can add notes to claims

- app/views/admin/amendments/index.html.erb
A simple change that adds the "Amend claim" link to the amendments tab where a service operator may expect to see it.
> Add amend link to amendments tab

- docs/release-process.md
The UI has been shuffled around and the instructions didn't correspond with what you see when you log in to Azure DevOps.
> Update DevOps instructions in release process

- CHANGELOG.md
- app/views/admin/decisions/_decision_form.html.erb
- config/locales/en.yml
- spec/features/admin_claim_with_inconsistent_payroll_information_spec.rb
This is the code side tweaks to help support the offline process service operators will follow to resolve payroll discrepancies. We now split up the text to it is a bit less heavy and it is now divided into chunks explaining the problem and what they can do to resolve it.
> 1387 make sure we set the service team up to deal with payroll discrepancies if they occur

- CHANGELOG.md
- app/controllers/admin/notes_controller.rb
- app/controllers/admin/support_tickets_controller.rb
- app/models/claim.rb
- app/models/support_ticket.rb
- app/views/admin/claims/_tabs.html.erb
- app/views/admin/notes/index.html.erb
- app/views/admin/support_tickets/_widget.html.erb
- config/routes.rb
- db/migrate/20200402093512_create_support_tickets.rb
- db/schema.rb
- spec/factories/support_tickets.rb
- spec/features/admin_claim_notes_spec.rb
- spec/features/admin_claim_support_tickets_spec.rb
- spec/models/support_ticket_spec.rb
- spec/requests/admin_support_tickets_spec.rb
This allows a support operator to add a support ticket directly to a claim.
A future PR will add the ability to edit the support ticket URL.
> Service operators can add a support ticket to a claim

- azure/resource_groups/app/parameters/production.template.json
In preparation for rotating the certifications we need to configure the
VSP to accept the new SAML encryption key while still using the old
one. The rotation will happen in a separate change.
> Add secondary SAML encryption key for VSP

- azure/resource_groups/app/parameters/production.template.json
GOV.​UK Verify has deployed the new signing certificate for our Verify Service Provider in production. The key exists in the key vault.
> Add new SAML signing key for production VSP

- azure/resource_groups/app/parameters/production.template.json
We're now successfully using the new certificates so we can remove the old key and make the new key the primary one.
> Make the new SAML encryption key primary and remove old

- CHANGELOG.md
- app/controllers/admin/qualification_report_uploads_controller.rb
- app/models/automated_checks/dqt_report_consumer.rb
- app/models/maths_and_physics/dqt_record.rb
- app/models/student_loans/dqt_record.rb
- spec/features/admin_automated_qualification_check_spec.rb
- spec/fixtures/files/example_dqt_report.csv
- spec/models/automated_checks/dqt_report_consumer_spec.rb
- spec/models/maths_and_physics/dqt_record_spec.rb
- spec/models/student_loans/dqt_record_spec.rb
- spec/requests/admin_qualification_report_upload_spec.rb
- spec/support/fixture_helpers.rb
This updates the DQT report upload so that it will automatically mark identity confirmation tasks as a PASS if the date of birth and surname held in the claimant's DQT record matches the details we received from GOV.UK Verify. It will not automatically confirm identity for claims without GOV.UK Verify identity information, these will need to be manually confirmed.
> DQT Report consumer performs automated identity confirmation

- docs/govuk-verify-rotating-keys-and-certificates.md
It is necessary to be able to complete the GOV.UK Verify journey if
rotating the certificates on production to check the new keys and
certificates are working as expected.
It is mentioned futher down that a real account is needed but stating
the requirement up front may help decide who carries out and when the
rotation is done. Signing up to an identity provider isn't always
instant and may take several days.
> Clarify requirements of rotating the certificates

- bin/azure-deploy
The latest version of shellcheck highlighted potential risk of non-quoted variables being split or glob expanded. See https://github.com/koalaman/shellcheck/wiki/SC2086 for more details.
Developers will also want to `brew upgrade shellcheck` to get their local version updated.
> Quote variables to prevent word splitting/globbing

- CHANGELOG.md
- app/helpers/admin/claims_helper.rb
- app/views/admin/tasks/_claim_summary.html.erb
- app/views/admin/tasks/index.html.erb
- spec/features/admin_views_completed_claim_spec.rb
- spec/helpers/admin/claims_helper_spec.rb
When a decision is made on a claim, the claim's task view will now show the result within the header.
For claims which haven't had a decision made, the task view page will just display the claim reference (as shown in the before screenshot)
**Before:**
**After:**
This ticket has taken longer than expected to complete, so I have broken it up into separate Pull Requests as I believe that this can be merged alone. 
The next parts to this ticket are:
- to show the payroll status
- to show the claim amount
- to remove other information that will be scrubbed
> Display decision result on the task view page for a claim

- CHANGELOG.md
- app/models/student_loans/eligibility.rb
It’s inconsistent with the question wording and also the GOV.UK style
guide recommends avoiding negative contractions.
> Remove negative contraction from validation error

- CHANGELOG.md
- app/helpers/admin/claims_helper.rb
- app/views/admin/tasks/_claim_summary.html.erb
- spec/features/admin_views_completed_claim_spec.rb
- spec/helpers/admin/claims_helper_spec.rb
The task view now displays the `Payroll status` and the `Claim amount` 
**Before:** 
**After:**
> Task view shows the claims payroll status and claim amount

- docs/first-line-support-developer-runbook.md
This adds documentation for the support process of removing the 'downloaded' state from a payroll run, so that it can be downloaded again.
> Document removing downloaded state from payroll

- CHANGELOG.md
- app/models/claim.rb
- spec/models/claim_spec.rb
- spec/requests/admin_amendments_spec.rb
In our current claim journey we only collect the claimant’s student loan
plan type if they tell us they’re still paying off their student loan.
This is because when we designed the claim journey, the only reason we
needed to know the plan type was so payroll could calculate the correct
student loan contributions to be deducted from the claim amount.
We recently had a case where a service operator amended a claim where
the claimant was no longer paying off their student loan, to set the
loan plan type to Plan 2.
Their reason for doing so was sensible – we also need to know the plan
type to be able to check the claim amount for TSLR claims. However, once
this claim was sent to Cantium, they saw the claim as having “no student
loan” and also having a plan type, which from their point of view …
> Forbid amending student loan plan when no loan

- docs/infrastructure-deployment.md
These are “reference-style links” according to
https://www.markdownguide.org/basic-syntax#reference-style-links.
See https://github.com/DFE-Digital/claim-additional-payments-for-teaching/issues/1063
> Fix broken links in documentation

- CHANGELOG.md
- A service operator isn’t allowed to amend student loan plan when the
claimant has already paid off their student loan
> Release 075

- README.md
- docs/developer-onboarding.md
- Add note about Azure's maximum password length
- Added step for fetching DFE_SIGN_IN_API_SECRET from the key vault in
order to run the `db:setup` rake task
> Improve development documentation

- CHANGELOG.md
- app/models/claim/personal_data_scrubber.rb
- spec/models/claim/personal_data_scrubber_spec.rb
A claim with an undone rejection should not be considered as rejected
and hence this rejection should not contribute to its eligibility to be
anonymized.
We recently accidentally scrubbed the personal data from some claims
which had been rejected and then subsequently approved, and only noticed
this when the payroll CSV file generation blew up because the payroll
gender was missing. We had to restore these claims' personal data from a
database backup.
https://dxw.zendesk.com/agent/tickets/11941
> Ignore undone rejections when anonymizing claims

- CHANGELOG.md
- When removing personal data from claims, don’t treat a claim as
rejected if the rejection has been undone
> Release 077

- CHANGELOG.md
- app/models/claim/personal_data_scrubber.rb
- db/data/20200622125327_scrub_banking_name_from_scrubbed_claims.rb
- spec/models/claim/personal_data_scrubber_spec.rb
It seems like we missed this one when we were choosing which fields to
scrub.
Our data retention policy [1] says that the only personal data we keep
are TRN and email address.
We already remove first_name, last_name, and all bank account numbers.
So I see no reason why we should be keeping banking_name.
This includes a data migration to fix the already-scrubbed claims.
[1] https://dfedigital.atlassian.net/wiki/spaces/TP/pages/1086193761/Data+handling+and+retention
> Remove banking_name when scrubbing personal data

- CHANGELOG.md
- app/models/payment_confirmation.rb
- spec/models/payment_confirmation_spec.rb
This adds contextual information for confirmation reports with incorrect data (to make diagnosis easier), as well as attempting to get around the issue when Excel adds thousand seperators to numeric columns when saving / editing a CSV.
> Handle common errors in confirmation reports

- CHANGELOG.md
- Add contextual information when incorrect data is in a confirmation report
- Remove thousand seperators from numeric columns in confirmation reports
> Release 079

- CHANGELOG.md
- app/controllers/verify/authentications_controller.rb
- spec/features/govuk_verify_spec.rb
As advised by Verify, the maximum amount of time people can spend in the
Verify flow has been increased from 90 minutes to 120 minutes. This
increases our application timeout to match, making sure people who spend
longer in Verify will not return to an expired session.
> Increase Verify timeout to 120 minutes

- CHANGELOG.md
- app/helpers/admin/payment_helper.rb
- app/models/payroll_run.rb
- app/views/admin/payroll_runs/show.html.erb
- spec/models/payroll_run_spec.rb
When viewing a Payroll Run in admin:
- Add a breakdown of the number of claims and total claim amount under each policy
- Add the total amount of each payment to the list of payments
- In the list of payments, where a payment includes multiple claims, include one row for each claim
- Add the policy of each claim to the list of payments
- Add the amount of each claim to the list of payments
> Break down display of payment information by claim in payroll admin

- CHANGELOG.md
- app/models/student_loans/admin_tasks_presenter.rb
- spec/models/student_loans/admin_tasks_presenter_spec.rb
Previously, this check would always display the 2018-19 financial year. It now generates the string based on the academic year of the claim.
> Display the correct financial year in employment check

- azure/resource_groups/app/parameters/development.template.json
At the latest certificate renewal, a new certificate name was created. This commit changes the deployed configuration to use that certificate name, so it does not revert to the old (expired) certificate each deploy.
> Update name of certificate to match version in Azure

- app/jobs/geckoboard/update_undecided_claims_job.rb
- lib/tasks/geckoboard.rake
- spec/jobs/geckoboard/update_undecided_claims_job_spec.rb
This changes the behaviour of the Geckoboard update job and reset task to only include claims from the current academic year (as configured).
Geckoboard will still need manually resetting each time the academic year is updated.
> Limit Geckoboard updates to the current academic year

- app/models/payment.rb
- app/models/payment_confirmation_csv.rb
- app/models/payroll/payments_csv.rb
- spec/features/admin_payroll_runs_spec.rb
- spec/models/payment_confirmation_csv_spec.rb
- spec/models/payment_confirmation_spec.rb
- spec/models/payment_spec.rb
- spec/models/payroll/payment_csv_row_spec.rb
- spec/models/payroll/payments_csv_spec.rb
- spec/requests/admin_payment_confirmation_report_upload_spec.rb
This adds a new column to the payroll report, which lists the policies involved in that payment as an alphabetically-sorted comma-delimited string.
**Do not merge** until we have confirmed what the response column will be in the confirmation report.
> Add column to payroll report which lists the policies involved in any payment

- CHANGELOG.md
- app/models/payment.rb
- spec/models/payment_confirmation_csv_spec.rb
- spec/models/payment_spec.rb
Cantium's CSV parser doesn't like commas in columns, so we're splitting the policies with a space instead
> Seperate policies in payment with a space

- CHANGELOG.md
- app/models/payroll_run.rb
- spec/models/payroll_run_spec.rb
The `total_claim_amount_for_policy` calculation is currently summing the claim's payment award amount, not the acutal claim's award amount. This works when payments are only for one policy (i.e. the claim's award amount and the payment's award amount are equal). However, if a claimant has claimed for multiple policies, both policies are double counted, resulting in incorrect breakdowns via policy.
I've tweaked the code to sum at the code level using https://apidock.com/rails/Enumerable/sum, rather than https://apidock.com/rails/ActiveRecord/Calculations/sum. This does mean that all the rows have to be loaded into memory to do the calculation, but I think this is a reasonable trade-off, given that this page is only loaded once or twice per claim window.
> Fix incorrect summing with claims by policy

- CHANGELOG.md
- app/views/admin/payroll_runs/show.html.erb
We were using two different ways to gather the list of claims to be
displayed for a payment. Each of these imposes a different ordering on
the claims in the SQL that it generates:
1. payment.claims.first: this does ORDER BY claims.created_at
2. payment.claims: this does no ORDER BY and hence returns Postgres's
default order, which is undefined [1].
This means that when the Postgres default order doesn’t match the
created_at order, these two sources of data won’t agree and hence we
might see duplicate and missing claims against a payment.
This commit changes it so that we only use one source of data -
payment.claims.
I haven’t added a regression test here because I’m not sure how I’d set
up example data where the Postgres order doesn’t match the created_at
order, given that the Postgres …
> Fix incorrect display of claims in payroll run

- app/views/claim_mailer/approved.text.erb
- app/views/claim_mailer/submitted.text.erb
- spec/mailers/claim_mailer_spec.rb
The client requested that we remove the additional information about
phoning the claimant to verify their identity. The email is now the same
regardless of whether the claimant’s identity is already verified or
not. This is because they have had to “change (their) processes”.
This tweaks the original change made in e5a4543.
(No change to the `CHANGELOG` since it's already covered in the "Unreleased" section there.)
> Remove some extra detail from claim submitted email

- CHANGELOG.md
- app/views/claim_mailer/rejection_reasons/_maths_and_physics.text.erb
- app/views/claim_mailer/rejection_reasons/_student_loans.text.erb
Zendesk: https://dxw.zendesk.com/agent/tickets/13584
Add an additional rejection reason to the rejection email which is seent out to
both Maths & Physics and Student Loans claims. The reason reads:
`- We have been trying to contact you regarding your claim but we have not heard from you and therefore cannot resolve your claim.`
> Add an additional claim rejection reason

- azure/resource_groups/alerts/parameters/development.template.json
There's noone actively working on the project, the alerts for
development are mostly ignored and generate noise.
This can easily be reversed when people start sprinting on the project
again.
The production alerts will continue to notify us but they may need some
tweaking as they are also generating a lot of noise.
> Disable alerts on development

- docs/dfe-sign-in.md
On discussion for the ticket there was mention that the section on 'Obtain Security Approval' was redundant. This was raised by Kristi Beak and discussed with @mattonfoot.
This PR actions the outcome of that discussion.
[ECP-194](https://dfedigital.atlassian.net/browse/ECP-194)
> [feature/ECP-194] - remove 'obtain security approval' section

- Gemfile.lock
This is related to the existing versions of the gem below 0.3.7 having been removed from rubygems due to change of licensing to GPL-2.
Here is the issue referenced in this weeks rubyweekly - https://github.com/rails/rails/issues/41750
https://rubyweekly.com/link/105250/web
https://rubyweekly.com/issues/545 top article
> [task/ECP-410] - bump mimemagic from 0.3.6 to 0.3.9

- CHANGELOG.md
- azure/templates/app_alerts.json
The high response time alert is triggering a lot. Looking at the history
it seems to get back to normal after ~5 minutes. The impact on the user
would be minimal so I don't think it's worth investigating the
underlying cause just yet.
We previously reduced the sensitivity of the high CPU usage alert (in
f1e949da55a5c9b5e7c56d763801ce4d30b6d68b). I've opted to use the same
thresholds as that change.
> Reduce sensitivity of high response time alert

- CHANGELOG.md
- app/models/claim.rb
- app/models/early_career_payments.rb
- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/eligibility_answers_presenter.rb
- app/models/early_career_payments/slug_sequence.rb
- app/models/policies.rb
- app/views/claim_mailer/rejection_reasons/_early_career_payments.text.erb
- app/views/early_career_payments/claims/nqt_in_academic_year_after_itt.html.erb
- config/locales/en.yml
- db/data/20210408143440_add_early_career_payments_to_policy_configurations.rb
- db/migrate/20210408151248_create_early_career_payments_eligibilities.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/early_career_payments/eligibilities.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/fixtures/policy_configurations.yml
- spec/helpers/application_helper_spec.rb
- spec/models/claim_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
- spec/models/early_career_payments_spec.rb
- spec/models/policy_configuration_spec.rb
- spec/requests/admin_claims_spec.rb
- spec/requests/admin_payroll_gender_tasks_spec.rb
- spec/requests/admin_tasks_spec.rb
- spec/support/request_helpers.rb
- Add Early Career Payments policy
- Add seed for Early Career Payments
- Add root 'early_career_payments' top level to English (default) translations
- Create table early_career_payments_eligibilities
- Create Early Career Payments Eligibilities and SlugSequences
- Update first view to display error message when invalid
- Add EarlyCareerPayments to request helper
- Add 'check-your-answers' slug
- Update translations file
- Add 'nqt_in_academic_year_after_itt' to EDITABLE_ATTRUIBUTES
- Fix failing specs for 'short_name', 'locale_key',
'notify_reply_to_id', 'eligibility_page_url', 'award_amount',
'qts_award_year' (mainly in ClaimMailer)
- Add missing page expectation for 'feedback_url'
- Make specs for Admin Journey for ECP conditionally pending
- Add 'notify_reply_to_id' value
- Add …
> User Journey Page 1 - 'Did you do your NQT the academic year after your ITT?'

- app/models/automated_checks/update_admin_claim_tasks_with_dqt.rb
- spec/factories/claims.rb
- spec/features/admin_checks_maths_and_physics_claim_spec.rb
- spec/features/admin_checks_student_loan_claim_spec.rb
- spec/fixtures/files/example_dqt_report.csv
- spec/models/automated_checks/dqt_report_consumer_spec.rb
- spec/support/fixture_helpers.rb
- Remove verified trait from submittable claim factory
- Fix automated checks update admin claim tasks with DQT
- Fix automated checks DQT report consumer spec
- Fix admin checks claim specs
Bugs are fixed but UX needs some work, especially admin tasks identity confirmation:
- The question for outstanding claims that went through Verify don't mention it
- The question for claims that haven't gone through Verify say they haven't which is technically true but, apart from the above, we're not actually using Verify anymore.
> Fix GOV.UK Verify removal [ECP-593]

- azure/resource_groups/alerts/template.json
- azure/resource_groups/app/parameters/development.template.json
- azure/resource_groups/app/parameters/production.template.json
- azure/resource_groups/app/parameters/test.template.json
- azure/resource_groups/app/template.json
- azure/templates/vsp.json
Reverts DFE-Digital/claim-additional-payments-for-teaching#1274
This is being reverted because on investigation into why Releases are failing on Azure Development (and would be too on Production) are caused by the incorrect sequencing of resource deletion.
It turns out that the last Microsoft component to be deleted is the `AppServicePlan` so that needs to be decoupled from this removal.
As per this article from Microsoft - https://docs.microsoft.com/en-us/answers/questions/169500/unable-to-delete-virtual-network-and-a-resource-gr.html
Also reverting as about to go into Private Beta. Prior to this we want to be have the code deployed in Azure development for our Business colleagues to perform exploratory testing against.
Approach discussed and investigation by @WorkSutton and …
> Revert "[task/ECP-319] - remove references to GOVUK Verify from Azure scripts"

- app/helpers/claims_helper.rb
- app/models/claim.rb
- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/slug_sequence.rb
- spec/factories/claims.rb
- spec/helpers/claims_helper_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
- Don't show any student loans screens if the claimant answered 'No' to 'has_student_loan'
> [bug/ECP-643] - fix broken logic flows for 'Student Loans' sections of ECP journey

- app/helpers/early_career_payments_helper.rb
- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/school_check_email_data_export_presenter.rb
- app/models/early_career_payments/school_eligibility.rb
- app/models/school.rb
- app/views/early_career_payments/claims/_ineligibility_reason_ineligible_current_school.html.erb
- app/views/early_career_payments/claims/ineligible.html.erb
- app/views/early_career_payments/claims/personal_details.html.erb
- config/locales/en.yml
- spec/factories/schools.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/helpers/early_career_payments_helper_spec.rb
- spec/models/early_career_payments/school_eligibility_spec.rb
- New district area codes for ECP claims covering all secondary schools within England
- Ineligible page wired up
- Tests built around new criteria for eligible and ineligible schools with the ECP schools
- Extra - Personal details padding fixed
> story/ECP-480-474 ineligible school for ECP claim 

- app/helpers/early_career_payments_helper.rb
- app/mailers/claim_mailer.rb
- app/views/claim_mailer/ecp_email_verification.text.erb
- app/views/early_career_payments/claims/_one_time_password.html.erb
- lib/one_time_password.rb
- spec/helpers/early_career_payments_helper_spec.rb
This is borne out of work from our UCD colleagues who have determined 15 minutes is an appropriate duration.
**_Evidence_**
N.B. This is from the logs, but the wording is correct
> [story/ECP-873] - change duration of OTP from 60 to 900 seconds

- app/models/early_career_payments/eligibility.rb
- spec/models/early_career_payments/eligibility_spec.rb
The original delivery of the Postgraduate Doctoral and Masters Loan questions and then the subsequent removal of those questions when a claim does not have a student loan left a bug in the system.
This was due to no conditional validation occurring on the attributes currently held on the EarlyCareerPayments::Eligibility model:
- `postgraduate_doctoral_loan`
- `postgraduate_masters_loan`
> [bug/ECP-903] - fix issue when 'No' is selected for Student Loans question and claim could failing valid?(:submit)

- app/helpers/claims/show_helper.rb
- app/models/early_career_payments/eligibility_matrix_calculator.rb
- app/views/early_career_payments/claims/eligible_later.html.erb
- config/initializers/early_career_payments/eligibility_matrix.yml
- config/initializers/early_career_payments/eligibility_matrix_calculator.rb
- spec/features/eligible_later_for_early_career_payments_spec.rb
- spec/helpers/claims/show_helper_spec.rb
Show the base amount and the uplifted amount based on subject and academic ITT year
Add details of criteria in an initializer file
> [story/ECP-908] - change to using correct award amounts in eligible later 2022 screen

- app/helpers/claims_helper.rb
- spec/helpers/claims_helper_spec.rb
Fixed all edit links that go to the personal details page (Full name, Date of birth and National Insurance number)
> [bug/ECP-907] - Edit National Insurance Number from the ECP Personal Details page is broken

- CHANGELOG.md
- app/models/automated_checks/claim_verifiers/identity.rb
- app/models/automated_checks/claim_verifiers/qualifications.rb
- spec/features/admin_claim_tasks_update_with_dqt_api_spec.rb
- spec/models/automated_checks/claim_verifiers/identity_spec.rb
- spec/models/automated_checks/claim_verifiers/qualifications_spec.rb
We were returning the wrong response when stubbing the request, ie, worked locally but not when deployed.
ECP-1056
> Fix admin claim tasks update with DQT API without matching DQT identity

- CHANGELOG.md
- app/helpers/admin/policy_configurations_helper.rb
- app/views/early_career_payments/claims/eligible_later.html.erb
- spec/features/admin_configure_services_spec.rb
- spec/helpers/admin/policy_configurations_helper_spec.rb
Also, removed redundant JS spec: nothing actually changes in the spec depending on whether JS in enabled or not.
> [story/ECP-632] Change admin manage services accepting claims for academic year select to display four years instead of two

- CHANGELOG.md
- app/helpers/claims_helper.rb
- app/views/claims/address.html.erb
- app/views/claims/postcode_search.html.erb
- app/views/claims/select_home_address.html.erb
- config/locales/en.yml
- spec/features/auto_populating_home_address_from_postcode_search.rb
- spec/features/changing_answers_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/maths_and_physics_claim_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/helpers/claims_helper_spec.rb
- provide links on the address auto-population pages that allow the claimant to enter their address manually
> [story/ECP-836] - Add home address manual screen to ECP journey

- app/models/early_career_payments/slug_sequence.rb
- app/models/maths_and_physics/slug_sequence.rb
- app/models/page_sequence.rb
- app/models/student_loans/slug_sequence.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
- spec/models/maths_and_physics/slug_sequence_spec.rb
- spec/models/page_sequence_spec.rb
- spec/models/student_loans/slug_sequence_spec.rb
- allows 'address' page to be skipped if postcode is present
- allows 'address' page to be shown if claimant chooses to manually enter their address
- allows 'address' page to be accessed from 'Check your answers links'
> [bug/ECP-1128] - Fix for address screens

- CHANGELOG.md
- app/models/early_career_payments/school_eligibility.rb
- app/models/student_loans/school_eligibility.rb
On the evening of 31 March 2021 GIAS will be updated to reflect the Northamptonshire local authority boundary changes (opens in new tab), which are for scheduled for 1 April 2021. The update will:
- Add two new local authorities to GIAS:
- 940 – North Northamptonshire Council
- 941 – West Northamptonshire Council
- Rename the existing 928 – Northamptonshire local authority to Pre-LGR 2021 Northamptonshire.
> [support/CSM-12] - Update local authority for Northamptonshire to reflect boundary changes

- db/data/20210827115900_update_ecp_claims_with_academic_year_2020_to_2021.rb
- PolicyConfiguration for ECP - update current_academic_year from 2020/2021 to 2021/2022
- Find all ECP Claims with attribute 'academic_year' set to 2020/2021 - update to 2021/2022
> [bug/ECP-1158] - One off Data Migration to fix qualifications link throwing error

- app/views/admin/claims/_tabs.html.erb
- this was appearing when attempting the upgrade to 2.7 series
> [task/ECP-1218] - Fix deprecation warning: Passing the keyword argument as the last hash parameter is deprecated

- CHANGELOG.md
- Report school as open when it has a close_date in the future
- Ensure JS school search autocomplete only reports school as closed after close date
- Remove Geckoboard
- ECP
- Fix issue where reminder OTP page link was not going anwyhere (DAC Report)
- TSLR
- How much student loan did you repay page content change
- All Policies
- Adding postgraduate loan contribution to payroll confirmation
- Middle names input field change
> release-103

- CHANGELOG.md
- All policies
- Update school data import to include GIAS OpenDate
- Report school as open when
- it has a close_date in the future
- it has a open_date that is in the past
- Fix Statistics for 2021/2022 AY to be from 6th Sept, 2021
- Amend 'no address found' screen
- Update SLA timescales for claim submitted and claim approved screens and
emails
- ECP
- Ensure claim award_amount is set during claimant eligible journey
- Back-populate existing claims to have award_amount, if payment made use
payment amount, otherwise use value from lookup
> release-104

- CHANGELOG.md
- ECP
- Make Leigh Academy Rainham an eligible school as curently it is not as it
has no local_authority_district.code (GIAS issue)
> release-106

- CHANGELOG.md
- app/helpers/early_career_payments_helper.rb
- app/mailers/application_mailer.rb
- app/mailers/claim_mailer.rb
- app/mailers/reminder_mailer.rb
- spec/features/changing_answers_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/maths_and_physics_claim_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/mailers/claim_mailer_spec.rb
- spec/mailers/previews/claim_mailer_preview.rb
- spec/support/feature_helpers.rb
- for M+P/TSLR/ECP Claim user journey
- for ECP Reminder journey
> [story/ECP-1339] - Change static email content for OTP email verification to use the GOVUK notify OTP template

- CHANGELOG.md
- Admin
- Display results of Dqt API qualification matching status
- Fix ITT year and ITT subject for future years admin ECP qualifications task
- Fix Manual checks to display updated time, not time of claim submission
- Early Career Payments
- DqT temporary use of subject(n) in response to report JACS/HECOS codes used
in the determination of matching DqT response with claim ITT subject
- use QTS Award Date for qualification matching for:
- EEA
- Northern Ireland
- OTT
- OTT Recognition
- QTS Assessment only
- QTS Award only
- Scotland
- Transition to use GOVUK Notify Mail Templates to allow business users to
modify wording
- OTP email verification - All Policies
- OTP ECP Reminders
> release-108

- CHANGELOG.md
- Admin
- Fix how the data for Cantium is presented
- All Policies
- Change how auto-population of addresses in 'select-home-address' screen is
built from the results of the call to Ordnance Survey API, and how the data
is saved
- ECP Policy
- DqT - Match against subject names while not receiving subject codes
> release-109

- CHANGELOG.md
- ECP + TSLR policies transition to use GOVUK Notify Mail Templates to allow
business users to modify wording
- Claim submitted / received
> release-110

- db/test_seeders/base_importer.rb
Reverts DFE-Digital/claim-additional-payments-for-teaching#1861
Its broken the Asset Pipeline with the exit
> Revert "[story/ECP-1393] - Add defensive exits to prevent accidently running DqT CSV data/Payroll UAT test data loaders running in PROD"

- spec/features/school_search_spec.rb
- to prevent the regular CI failures in the JS school searches
> [bug/ECP-1069] - Add individual overrides to Capybara wait time

- Gemfile.lock
- app/models/academic_year.rb
- spec/models/academic_year_spec.rb
Add check to reject invalid academic year strings like '2014/2016' (not consecutive years) or '2014/2013' (decreasing years) which would have been silently accepted before
> Reject invalid `AcademicYear` strings

- spec/features/backlink_spec.rb
- spec/models/school_spec.rb
Removes some RSpec deprecation warnings. Hopefully this will make an eventual RSpec gem upgrade easier.
> Remove RSpec deprecation warnings (seen when running `bundle exec rake`)

- config/initializers/dfe_sign_in.rb
- spec/lib/dfe_sign_in/dfe_sign_in_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-155
Allows the entire spec suite to pass whilst running the app in development. Before this change, two sign-in related specs were failing or you had to comment out two classes.
It still means you need Internet access to sign into the Admin site during local development. This will need to be addressed in the future.
> Allow entire RSpec suite to pass whilst running app locally

- app/controllers/claims_controller.rb
- app/helpers/early_career_payments_helper.rb
- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/eligibility_answers_presenter.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/early_career_payments/claims/nqt_in_academic_year_after_itt.html.erb
- app/views/shared/_backlink.html.erb
- config/locales/en.yml
- spec/features/backlink_spec.rb
- spec/features/claim_journey_does_not_get_cached_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/early_career_payments_landing_page_spec.rb
- spec/features/early_career_payments_trainee_teacher_spec.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/helpers/early_career_payments_helper_spec.rb
- spec/models/claim_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
- spec/requests/claims_spec.rb
- spec/requests/policy_closed_spec.rb
- spec/support/feature_helpers.rb
- spec/support/request_helpers.rb
JIRA: https://dfedigital.atlassian.net/browse/CAPT-167
Moves `choose-school` step to beginning of ECP wizard in preparation for combined ECP/LUP journey.
Two things to note:
* This exposes a problem with the back links which must be rethought in a future ticket. As an aside, they currently use JavaScript because they're calling the Web browser's back button functionality which is wrong and they don't work on Safari; and
* You'll find you be asked about an existing claim more often during development. This is because claims are created on viewing the first page of the wizard rather than when submitting the answer to the first step. I think this makes sense though.
> Move `choose-school` step to beginning of ECP journey

- app/models/levelling_up_payments/academic_year_eligibility.rb
- app/models/levelling_up_payments/award.rb
- app/models/levelling_up_payments/school_eligibility.rb
- app/models/levelling_up_payments/subject_eligibility.rb
- spec/models/levelling_up_payments/academic_year_eligibility_spec.rb
- spec/models/levelling_up_payments/award_spec.rb
- spec/models/levelling_up_payments/school_eligibility_spec.rb
- spec/models/levelling_up_payments/subject_eligibility_spec.rb
The beginnings of LUP eligibility. Adds small classes (which aren't integrated yet) for different aspects of LUP eligibility.
> Add LUP logic without integrating

- app/models/early_career_payments.rb
- app/models/journey.rb
- app/models/levelling_up_payments.rb
- app/models/levelling_up_payments/award.rb
- app/models/levelling_up_payments/eligibility.rb
- app/models/maths_and_physics.rb
- app/models/student_loans.rb
- config/locales/en.yml
- db/migrate/20220511143638_add_early_career_payment_eligibility_attributes_to_levelling_up_payments_eligibilities.rb
- db/schema.rb
- spec/factories/levelling_up_payments/eligibilities.rb
- spec/factories/schools.rb
- spec/features/admin_search_spec.rb
- spec/models/claim/search_spec.rb
- spec/models/levelling_up_payments/award_spec.rb
- spec/models/levelling_up_payments/school_eligibility_spec.rb
- spec/support/admin_searchable_claim_shared_examples.rb
https://dfedigital.atlassian.net/browse/CAPT-221
Adds factory to create LUP claims for testing Admin-side of application.
Adds a copy of the ECP fields to database and an extra field needed for a concurrent ticket. These fields may need to change to better suit LUP but allows things to work for now.
> CAPT-221 Admin search for LUP claims

- app/models/journey.rb
- app/models/levelling_up_premium_payments.rb
- app/models/levelling_up_premium_payments/academic_year_eligibility.rb
- app/models/levelling_up_premium_payments/award.rb
- app/models/levelling_up_premium_payments/eligibility.rb
- app/models/levelling_up_premium_payments/school_eligibility.rb
- app/models/levelling_up_premium_payments/subject_eligibility.rb
- config/locales/en.yml
- db/migrate/20220516095658_rename_levelling_up_payments_eligibilities_to_levelling_up_premium_payments_eligibilities.rb
- db/schema.rb
- spec/factories/levelling_up_premium_payments/eligibilities.rb
- spec/factories/schools.rb
- spec/features/admin_configure_services_spec.rb
- spec/features/admin_search_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/models/claim/search_spec.rb
- spec/models/levelling_up_premium_payments/academic_year_eligibility_spec.rb
- spec/models/levelling_up_premium_payments/award_spec.rb
- spec/models/levelling_up_premium_payments/school_eligibility_spec.rb
- spec/models/levelling_up_premium_payments/subject_eligibility_spec.rb
Renaming to reflect the correct domain term.
Had to shorten database index name to fit inside Postgres's 63 character limit.
> Rename "Levelling Up Payments" to "Levelling Up Premium Payments"

- app/helpers/admin/amendments_helper.rb
- app/models/award_range_validator.rb
- app/models/early_career_payments/eligibility.rb
- app/models/levelling_up_premium_payments/award.rb
- app/models/levelling_up_premium_payments/eligibility.rb
- app/models/student_loans/eligibility.rb
- app/views/admin/amendments/new.html.erb
- spec/features/admin_amend_claim_spec.rb
- spec/features/admin_edit_claim_spec.rb
- spec/helpers/admin/amendments_helper_spec.rb
- spec/models/amendment_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
- spec/models/levelling_up_premium_payments/award_spec.rb
- spec/models/levelling_up_premium_payments/eligibility_spec.rb
- spec/models/student_loans/eligibility_spec.rb
- spec/support/admin_edit_claim_feature_shared_examples.rb
https://dfedigital.atlassian.net/browse/CAPT-208
Allows LUP claims to be edited by an admin in a way consistent with the other policies.
While doing this, I found that some of the validation for monetary values was inconsistent between policies so addressed that.
Also agreed with Chris Williamson to remove the string parsing on the forms for monetary amounts.
> Allow LUP claims to be edited by an admin

- app/models/claim.rb
- app/models/decision.rb
- spec/models/claim_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-307
This allows one to call `Claim#destroy` without orphaned data being left or being blocked by foreign key constraints on child records. Now the child records are destroyed as well.
> Allow deletion of claims with associated records

- app/helpers/early_career_payments_helper.rb
- app/models/academic_year.rb
- app/models/early_career_payments/eligibility.rb
- app/views/early_career_payments/claims/itt_year.html.erb
- config/locales/en.yml
- spec/features/early_career_payments_claim_spec.rb
- spec/helpers/early_career_payments_helper_spec.rb
I updated the radio buttons to include the requested years, but selecting them will make the claim not eligible because I haven't added any new awards. I hijacked the feature specs for the claim to test this. I would appreciate any ideas to make this cleaner.
> CAPT-261: Radio button change on QTS years page

- app/controllers/admin/policy_configurations_controller.rb
- app/helpers/application_helper.rb
- app/models/policies.rb
- app/models/policy_configuration.rb
- app/views/admin/policy_configurations/edit.html.erb
- app/views/admin/policy_configurations/index.html.erb
- db/migrate/20220523175052_change_policy_configuration_policy_type.rb
- db/schema.rb
- db/seeds.rb
- spec/fixtures/policy_configurations.yml
- spec/models/claim_spec.rb
- spec/models/levelling_up_premium_payments_spec.rb
- spec/models/policy_configuration_spec.rb
PolicyConfiguration drives the Service and the Journey, ECP and LUP being a combined journey needs to support multiple `policy_types` and not just a single `policy_type`.
Main things of note:
- Migration
- Adding LUP to the ECP PolicyConfiguration
- Refactoring bits that expected a single policy for a policy configuration
> Multi-policy PolicyConfigurations

- app/controllers/claims_controller.rb
- app/models/claim/permitted_parameters.rb
- app/models/current_claim.rb
- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/slug_sequence.rb
- app/models/levelling_up_premium_payments/eligibility.rb
- app/models/maths_and_physics/slug_sequence.rb
- app/models/page_sequence.rb
- app/models/student_loans/slug_sequence.rb
- app/views/early_career_payments/claims/eligible-degree-subject.html.erb
- app/views/early_career_payments/claims/eligible_degree_subject.html.erb
- app/views/early_career_payments/claims/ineligible.html.erb
- config/locales/en.yml
- spec/factories/early_career_payments/eligibilities.rb
- spec/features/ineligible_early_career_payments_in_2021_and_future_years_spec.rb
- spec/features/ineligible_levelling_up_premium_payments_spec.rb
- spec/features/levelling_up_premium_payments_spec.rb
- spec/models/claim/permitted_parameters_spec.rb
- spec/models/current_claim_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
- spec/models/maths_and_physics/slug_sequence_spec.rb
- spec/models/page_sequence_spec.rb
- spec/models/student_loans/slug_sequence_spec.rb
- spec/support/admin_edit_claim_feature_shared_examples.rb
- spec/support/feature_helpers.rb
Adds the following page when the answer to "Which subject did you do your postgraduate initial teacher training (ITT) in?" is "None of the above".
Issues:
* The next page after clicking continue reads "Do you teach none of the above now?".
* The ineligible page when selecting "No" shows the ineligible reason for ECP claim.
> [CAPT-165] Add eligible degree subject page

- spec/features/ineligible_levelling_up_premium_payments_spec.rb
The functionality is already there. I just covered it with a new spec.
> [CAPT-347] Add test for ECP & LUP ineligible school

- app/models/early_career_payments/slug_sequence.rb
- app/views/reminders/set.html.erb
- spec/features/early_career_payments_trainee_teacher_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
Caveat: not sure what becomes of reminders when a trainee teacher now asks for one. The page says they'll get it in September but doesn't say which year (because we never asked them those details). Could be this September or never. I don't know anything about the reminder service so can't say.
> Stop asking trainee teachers their ITT year

- app/helpers/claims_helper.rb
- app/models/early_career_payments/eligibility.rb
- app/models/levelling_up_premium_payments/eligibility.rb
- spec/features/changing_answers_spec.rb
- spec/features/levelling_up_premium_payments_content_change_logic_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
- spec/models/levelling_up_premium_payments/eligibility_spec.rb
- makes 2017 ineligible for ECP
- fixes a bug introduced my my previous PR where years 2017 and 2021 were missing for LUP claims
- removes a feature spec deprecation warning
> [CAPT-355] Allow 2017 ITT year only for LUP claims

- app/controllers/claims_controller.rb
- app/models/current_claim.rb
- app/models/early_career_payments/eligibility.rb
- app/models/levelling_up_premium_payments/eligibility.rb
- app/models/maths_and_physics/eligibility.rb
- app/models/student_loans/eligibility.rb
- spec/features/resetting_dependant_attributes_spec.rb
This PR fixes the issue of getting stuck on the ineligible page when you are submitting the same answer. It adds the form params to the list of attributes that need to be reset because the `changed` object does not contain those keys. This is not an issue when the claim is eligible.
> [CAPT-269] Reset dependant answers from params

- app/models/current_claim.rb
- spec/features/ineligible_levelling_up_premium_payments_spec.rb
- spec/models/current_claim_spec.rb
Fix that shows validation error messages for LUP claims. Eg.
> Fix current claim validation on save

- app/assets/stylesheets/components/panel.scss
- app/views/claims/existing_session.html.erb
- config/locales/en.yml
https://dfedigital.atlassian.net/browse/CAPT-396
Implements small tweaks to the restart claim prompt page:
* Change the background colour
* Change the button to a secondary type
* Change the service name
**Before**
**After**
> Tweak to restart claim page

- app/views/early_career_payments/claims/_ineligibility_reason_itt_subject_none_of_the_above.html.erb
- app/views/early_career_payments/claims/_ineligibility_reason_not_teaching_now_in_eligible_itt_subject.html.erb
- config/locales/en.yml
- spec/features/early_career_payments_trainee_teacher_spec.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/features/subject_teaching_question_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-401
Changes copy from 'Foreign languages' to 'Languages'.
Note: does not migrate the database enum key as this does not change the semantics or the relative sort order of the subject option. Data migration would introduce unnecessary complexity and risk.
> CAPT-401 - Copy change: Foreign languages > Languages

- app/models/levelling_up_premium_payments/dqt_record.rb
Update ITT code eligibility check for LUP to include both HECoS and JAC codes instead of a pre-defined list. This makes the ITT and degree checks identical.
> Make ITT and degree checks identical

- app/helpers/admin/claims_helper.rb
- app/models/claim.rb
- app/models/current_claim.rb
- app/models/early_career_payments/eligibility.rb
- app/views/admin/claims/show.html.erb
- config/locales/en.yml
- db/migrate/20220707120226_add_policy_options_provided_to_claims.rb
- db/schema.rb
- spec/factories/claims.rb
- spec/features/combined_teacher_claim_journey_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/levelling_up_premium_payments_spec.rb
- spec/helpers/admin/claims_helper_spec.rb
- spec/models/current_claim_spec.rb
For ECP/LUP claims store the claim options presented. The policy and the award amount.
This is then visible to an admin.
> Store policy_options_provided on to claim and display in admin

- app/models/admin/presenter_methods.rb
- app/models/levelling_up_premium_payments/eligibility_admin_answers_presenter.rb
- spec/models/admin/presenter_methods_spec.rb
- spec/models/levelling_up_premium_payments/eligibility_admin_answers_presenter_spec.rb
I created a presenter for Yes/No answers to display correctly unsubmitted answers, but I am not aware of other questions that can be skipped in the wizard.
> [CAPT-245] Add N/A to unsubmitted answers

- config/locales/en.yml
The emails for LUP need some work, this PR just makes it so we don't get this when testing on development:
> Add translation values for LUP emails

- spec/factories/schools.rb
- spec/fixtures/schools.yml
Fixes `db:reset` `ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_schools_on_urn"` error.
**Update:** CI runs `School.pluck(:urn)` before the database gets created. It throws: `PG::ConnectionBad: FATAL:  database "dfe-teachers-payment-service_test" does not exist`. I'll skip this approach for now and update the `urn` value to one with the same amount but closer to the end of `urn_to_award_amount_in_pounds_for_2022_to_2023`. Doing this will prevent `sequence` from getting to that number.
> Prevent the school factory to use existing URN

- app/helpers/claims/itt_subject_helper.rb
- app/models/levelling_up_premium_payments/eligibility.rb
- app/views/early_career_payments/claims/eligible_degree_subject.html.erb
- spec/helpers/claims/itt_subject_helper_spec.rb
- spec/models/levelling_up_premium_payments/eligibility_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-539
For the hint text after a teacher has selected a subject, filter out subjects from the other policy when they've chosen a subject specific to one policy.
> Change subject hint text to exclude ineligible subjects from ineligible policies

- app/helpers/early_career_payments_helper.rb
- app/models/early_career_payments/eligibility_answers_presenter.rb
- app/views/early_career_payments/claims/eligible_itt_subject.html.erb
- config/locales/en.yml
- spec/features/combined_teacher_claim_journey_spec.rb
- spec/features/early_career_payments_claim_lupp_ineligible_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/ineligibility_reason_spec.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/features/ineligible_early_career_payments_in_2022_and_future_years_spec.rb
- spec/features/ineligible_levelling_up_premium_payments_spec.rb
- spec/features/itt_subject_selection_spec.rb
- spec/features/levelling_up_premium_payments_spec.rb
- spec/features/resetting_dependant_attributes_spec.rb
- spec/helpers/claims/itt_subject_helper_spec.rb
- spec/helpers/early_career_payments_helper_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-438
Changes ITT subject question for when there's only one subject.
Also includes changes to the tense for trainee teachers which doesn't seem to have made it's way into an implementation ticket
> Update ITT subject question when there's only one choice and fix tense for trainee teachers

- app/views/static_pages/accessibility_statement.html.erb
> [CAPT-321] Amend accessibility statement to the user journey following accessibility audit

- app/jobs/application_job.rb
- azure/terraform/modules/app_service/variable.tf
- azure/terraform/modules/container/container_group.tf
- config/initializers/delayed_job.rb
- docker-compose.production.yml
https://dfedigital.atlassian.net/browse/CAPT-703
We're seeing async jobs related to dfe-analytics creating a large backlog in the delayed_job queue which is causing a delay to e-mail and SMS delivery as well as claim verification checks.
This change deprioritises the sending of these events to BigQuery relative to the message delivery and claim checks, and increases the number of workers.
> Prioritise application jobs over analytics jobs; increase worker count

- azure/delete_review_app.yml
The destroy review app workflow was getting cancelled after 60min because terraform was missing an input variable
Also, we now force checking out master on destroy to avoid the default behaviour of checking out a non existing branch
> [CAPT-702] Fix destroy review app workflow

- app/controllers/claims_controller.rb
- app/models/early_career_payments/slug_sequence.rb
- app/models/levelling_up_premium_payments/slug_sequence.rb
- config/locales/en.yml
Fixes #326 NameError: uninitialized constant LevellingUpPremiumPayments::SlugSequence
Also adds a missing translation for `app/controllers/claims_controller.rb:64`
```ruby
new_policy_description = translate("#{params[:policy].underscore}.claim_description")
```
> Fix #326 NameError: uninitialized constant

- lib/ordnance_survey/client.rb
This wasn't updated when we upgraded to Ruby 2.7. There's no need to use `send` for private methods anymore. On Ruby 2.6 this would have thrown `NoMethodError: private method params` called.
> Remove unnecessary send when using Ruby 2.7

- app/controllers/admin/tps_data_uploads_controller.rb
- app/jobs/employment_check_job.rb
- spec/requests/admin_tps_data_upload_spec.rb
This PR also adds the code that prevents tasks for claims from previous years to run on TPS upload.
> [CAPT-717] Move employment checks to job

- app/models/reminder.rb
With this change you can create a reminder without an email, but not on the `personal-details` page, similar to claims' (`on: [:"email-address", :submit]`). Behaviour tested here: https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/master/spec/models/claim_spec.rb#L21. I replicated this for reminders, meaning the error won't show up on the page, but you can create a reminder without an email anywhere else. To avoid this I'd have to have a duplicate `validates :email_address row` adding `on: [:"personal-details"]` and `if: -> { email_address.present? }`
> [CAPT-655] Fix error message for missing email

- app/views/early_career_payments/claims/qualification.html.erb
> [CAPT-583] Amend the order of 'route into teaching' options

- app/jobs/school_data_importer_job.rb
- app/models/claim.rb
- spec/factories/schools.rb
- spec/models/claim_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-730
School sync job fails most of the time when run at 6am due to 500 and 404 errors on the server side. We have been advised to run the job after 7am. I have moved the job to 12pm when we can be more sure that it will succeed.
I have also added a check when the claim is submitted to cover an edge case where the school could be updated to closed state when the claim is in progress. It will also cover other edge cases where no school is present or a closed school is somehow otherwise selected.
> CAPT-730: Fix school sync

- app/controllers/admin/tasks_controller.rb
- app/jobs/qualifications_no_match_check_job.rb
DQT API has a limit of 300 requests/minute. When that limit gets reached, the client throws a `"Net::ReadTimeout with #<TCPSocket:(closed)>` error. This was causing the job to retry and process eligibility checks on the same claims multiple times. I added a gap of 60 seconds between requests, removed retries and filtered out identical DQT check notes.
> Fix DQT API limit error

- app/models/claim/personal_data_scrubber.rb
- spec/jobs/delete_personal_data_from_old_claims_job_spec.rb
- spec/models/claim/personal_data_scrubber_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-497
Changes the timing of the job which purges personally-identifiable information.
Previously, data was purged regularly when it was 2 months old.
Now, it will be retained until the following academic year begins (on 1st September).
I had considered removing the cron job and making this run only when the next claim window was opened, but this creates a risk of PII not being scrubbed when the service is eventually retired or redundant.
> CAPT-497: Modify PII data purge timing

- app/views/claims/postcode_search.html.erb
- spec/features/auto_populating_home_address_from_postcode_search_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-713
The postcode search value would always be auto populated with the address saved to the claim, even if the user subsequently went back to change the address and did a new search.
> Fix postcode search auto populated value

- app/views/claims/_school_search_results.html.erb
- app/views/claims/current_school.html.erb
- app/views/student_loans/claims/claim_school.html.erb
- spec/features/school_search_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-678
Closed schools should not appear on the schools list on the ECP/LUPP combined journey, but should do on TSLR claims.
> CAPT-678: Fix closed schools appearing in school search on ECP/LUPP combined journey

- app/models/claim.rb
- spec/models/claim_spec.rb
- spec/requests/admin_amendments_spec.rb
We need to also be aware of the reason why this validation was added: https://github.com/DFE-Digital/claim-additional-payments-for-teaching/commit/287501d69138047cc6c5c6cc20e9275e90469bef
> [CAPT-762] Remove on amend student_loan_plan validation

- app/assets/stylesheets/components/admin_filters.scss
- app/views/admin/claims/index.html.erb
https://dfedigital.atlassian.net/browse/CAPT-738
If the users selects filters and clicks 'Apply filters', the'Clear fitlers' link will now reset the form to the default state, rather than the applied filters state.
In order to avoid a Javascript dependency the link is an anchor if filters are applied, otherwise a reset button. It could be improved by conditionally using JS if available, but it's probably overkill.
> Reset filters form if filters have been applied

- .tool-versions
- azure/terraform/main.tf
- azure/terraform/modules/app_service/app_service.tf
- azure/terraform/modules/app_service/variable.tf
- azure/terraform/variable.tf
- azure/terraform/workspace_variables/development.tfvars.json
- azure/terraform/workspace_variables/production.tfvars.json
- azure/terraform/workspace_variables/test.tfvars.json
Certificates are generated and auto renewed in Keyvault. But they are configures manually on app service. This PR brings them under terraform control.
Depends on: https://github.com/DFE-Digital/claim-additional-payments-for-teaching-infrastructure/pull/54
- Stop merging to main so the pipeline is clear
- Import certificates in test and production environments into terraform
> [CAPT-607] Manage SSL certificates via terraform

- azure/terraform/provider.tf
- azure/terraform/status_cake.tf
- azure/terraform/variable.tf
- azure/terraform/workspace_variables/production.tfvars.json
- azure/terraform/workspace_variables/test.tfvars.json
Add external monitoring via StatusCake so we are alerted via email and Slack as soon as the site goes down
See example alert: https://ukgovernmentdfe.slack.com/archives/C02TGN3B6G2/p1670322290116119
> [CAPT-790] StatusCake monitoring

- .github/dependabot.yml
Lower the limit for dependabot open Pull Requests.
From 10 to 3 for bundler and npm
The dev App Service plan is sized for around 10-12 app services running max.
Each PR creates a review app, so dependabot is causing resource issues if too many open PR's exist.  
check update logs after merge
https://github.com/DFE-Digital/claim-additional-payments-for-teaching/network/updates
> lower dependabot open PR limit

- app/controllers/admin/levelling_up_premium_payments_awards_controller.rb
- spec/features/admin_manage_lupp_school_awards_spec.rb
In addition:
- For some reason the spec file had `_spec` missing so file renamed.
> CAPT-948 flash message shows chosen AY not current AY

- app/models/levelling_up_premium_payments/dqt_record.rb
- spec/models/levelling_up_premium_payments/dqt_record_spec.rb
https://dfedigital.atlassian.net.mcas.ms/browse/CAPT-975
* Refactor LUP DQT record model for readability
* Consolidate eligible ITT years check in one method
* Add fallback check when no ITT code or degree code is returned
* Make sure the fallback check works only in the absence of ITT codes (in other words, an invalid ITT code should prevail and FAIL the check anyway)
* Add more tests around invalid ITT invalid codes/subjects/degree codes
> CAPT-975 - API logic for LUP qualifications include subject name match as well as subject code match

- app/models/early_career_payments/dqt_record.rb
- spec/models/early_career_payments/dqt_record_spec.rb
https://dfedigital.atlassian.net.mcas.ms/browse/CAPT-976
This PR will affect ECP only, as the same result is being achieved for LUP in #2397 already.
See commit message for more info; also, some credit goes to @slorek for changes to the `DqtRecord` model.
> CAPT-976 - DQT API logic for multiple subject codes/names for LUP and ECP

- app/controllers/concerns/part_of_claim_journey.rb
- app/models/current_claim.rb
- app/models/early_career_payments/slug_sequence.rb
- app/models/levelling_up_premium_payments/eligibility_answers_presenter.rb
- spec/features/levelling_up_premium_payments_spec.rb
- spec/models/current_claim_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-1040
The bug reported above affects ECP/LUP journeys where the applicant is eligible or selected to claim for LUP.
The problem is described in detail in the commit message and, in essence, is caused by how the `CurrentClaim` wrapper currently picks the "main" `Claim` and forwards validations to it. Instead of defaulting to ECP, we should make sure the LUP claim is used as "main" when it's the one selected by the user or our controller at the end of the eligibility phase.
Easier to review using https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2402/files?diff=unified&w=1
> CAPT-1040 Users need to complete all questions again if they change one part of their personal details (bugfix)

- config/initializers/omniauth.rb
This is now required due to an update to the DfE Sign-In OIDC dependency.
Fixed by other teams, see: https://github.com/DFE-Digital/access-your-teaching-qualifications/pull/232 and https://github.com/DFE-Digital/apply-for-teacher-training/pull/8385
> Add issuer value to DfE Sign-In omniauth config

- lib/dqt/matchers/levelling_up_premium_payments.rb
For simplicity, this PR addresses both https://dfedigital.atlassian.net/browse/CAPT-1059 and https://dfedigital.atlassian.net/browse/CAPT-1102
These are minor changes, and there are no associated tests that need to be amended / are worth adding.
> CAPT-1059 CAPT-1102 Review list of eligible LUP ITT subjects and codes

- app/models/early_career_payments/dqt_record.rb
- app/models/early_career_payments/induction_data.rb
- lib/dqt/objects/teacher.rb
- spec/lib/dqt/objects/teacher_spec.rb
- spec/models/early_career_payments/dqt_record_spec.rb
- spec/models/early_career_payments/induction_data_spec.rb
Broken down from: https://dfedigital.atlassian.net.mcas.ms/browse/CAPT-931
To be used by: https://dfedigital.atlassian.net.mcas.ms/browse/CAPT-1093 (PR: #2425, not ready for final review)
The wider context is that we're adding a new question to the ECP/LUP journey, which is being worked on as part of https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2420 (Prototype, not ready for review)
> CAPT-931 Consume induction data as part of DQT API return for ECP only

- app/controllers/admin/payroll_runs_controller.rb
- app/views/admin/payroll_runs/_pagination.html.erb
- app/views/admin/payroll_runs/show.html.erb
- spec/features/admin_payroll_runs_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-1163
This PR uses the [pagination component from the GOV.UK design kit](https://design-system.service.gov.uk/components/pagination/). A similar view was introduced [here](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/025df3fee764098a772cf9ef7fc2a6dcf15a5f57/app/views/admin/claims/_pagination.html.erb).
[CAPT-1163]: https://dfedigital.atlassian.net/browse/CAPT-1163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CAPT-1163 Add payroll run payments pagination

- app/views/early_career_payments/claims/_ineligibility_generic.html.erb
https://dfedigital.atlassian.net/browse/CAPT-1285
This PR reverts the changes introduced by these commits so that the generic ineligibility content for ECP/LUP is restored.
To address the specific scenario that the commits were trying to address, we'll probably have to create a new partial and amend the `IneligibilityReasonChecker` https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/5a6238588cd325af16bd8840c44d73f83a7a131b/lib/ineligibility_reason_checker.rb#L6-L10
But this is going to take a bit longer to implement and test.
> CAPT-1285 Restore generic ECP/LUP ineligibility view content

- app/helpers/claims/itt_subject_helper.rb
- spec/helpers/claims/itt_subject_helper_spec.rb
When an ECP-only school is selected and at the point in the journey where the `subjects_to_sentence_for_hint_text` helper method is used, it returns an empty list of subjects.
This commit addresses that by running a second check on the status of the ECP claim; if it's marked as "eligible_later", then:
- Use the LUP list if the LUP claim is potentially eligible too
- Use the ECP list if the LUP claim is not eligible
Follows https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2387
> CAPT-1286 Fix method returning hint text with subject list for ECP/LUP

- app/models/early_career_payments/school_eligibility.rb
Some codes have ceased to exist this year and replaced by new ones. 
See https://get-information-schools.service.gov.uk/News/Article/eeeeaa31
https://dfedigital.atlassian.net/browse/CAPT-1299
> CAPT-1299 Update list of local authority district codes for ECP

- app/controllers/admin/payroll_runs_controller.rb
- app/models/claim.rb
- app/models/payroll_run.rb
- spec/factories/payroll_runs.rb
- spec/features/admin_payroll_runs_spec.rb
- spec/models/claim_spec.rb
- spec/models/payroll_run_spec.rb
- spec/requests/admin_payroll_runs_spec.rb
Due to limitations with the current upstream payroll software we need a temporary cap on the number of claims that can enter payroll, especially since we expect a high volume of approved claims in the first few months. It's also possible we'll never really need it. The capping can be removed once it is not required anymore. Another alternative solution could be to limit the number of approved claims monthly. In one way or another, a constraint must be introduced for now.
> CAPT-1271 Payroll is limited to 3000 payments per month

- app/models/school.rb
- spec/models/school_spec.rb
- spec/spec_helper.rb
https://dfedigital.atlassian.net.mcas.ms/browse/CAPT-1331
This is one way of addressing the issue above, please refer to the commit description for the rationale; attaching some performance stats below.
```
Warming up --------------------------------------
new search: one word     7.000  i/100ms
new search: two words
6.000  i/100ms
new search: postcode (partial)
6.000  i/100ms
new search: postcode (full)
6.000  i/100ms
current search: one word
5.000  i/100ms
current search: two words
5.000  i/100ms
current search: postcode (partial)
5.000  i/100ms
current search: postcode (full)
5.000  i/100ms
Calculating -------------------------------------
new search: one word     70.287  (± 2.8%) i/s -      2.114k in  30.093702s
new search: two words
69.787  (± 2.9%) i/s -      2.094k in  30.031095s …
```
> CAPT-1331 GIAS - 'Select your school' not listing school searched for with post code only

- app/models/automated_checks/claim_verifiers/induction.rb
- app/models/early_career_payments/induction_data.rb
- spec/models/automated_checks/claim_verifiers/induction_spec.rb
- spec/models/early_career_payments/induction_data_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-1289
In some cases, the response from DQT does not contain the induction start date: this value may need to be compared with the current date when the ITT year is 2020; if it's null or missing, the check should fail with NO DATA and still record the response from DQT.
This PR's commit includes minor refactoring of the `InductionData` object to increase readability.
> Induction check failing when the induction start date is missing (ITT year 2020)

- lib/dqt/matchers/general.rb
- spec/models/early_career_payments/dqt_record_spec.rb
- spec/models/levelling_up_premium_payments/dqt_record_spec.rb
https://dfedigital.atlassian.net.mcas.ms/browse/CAPT-1031
The actual code change and description of the issue are [here](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2483/files#diff-57487b7ec5109fb49e83ddb8312be70fc97fc0f6322616574b0d38a6ec2358f7). This is for ECP/LUP and PG route only.
Tests are verbose and may seem repetitive, but it's necessary to test all the remaining ITT year/claim year combinations. Refer to the test spreadsheet on the ticket for cross-referencing. 
Please note: tests in the review app have been executed stubbing [this test data from DQT](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/commit/3f37dd9dcb9caea5de711e02315ac59fe9071d48)
> CAPT-1031 Extend ITT year eligibility by 2 weeks for PG route only

- app/controllers/claims_controller.rb
- app/views/claims/sign_in_or_continue.html.erb
- spec/features/backlink_spec.rb
- spec/features/combined_teacher_claim_journey_dependent_answers_spec.rb
- spec/features/combined_teacher_claim_journey_spec.rb
- spec/features/early_career_payments_claim_sequence_slug_spec.rb
- spec/features/early_career_payments_landing_page_spec.rb
- spec/features/early_career_payments_trainee_teacher_spec.rb
- spec/features/hmrc_bank_validation_spec.rb
- spec/features/ineligible_levelling_up_premium_payments_spec.rb
- spec/features/school_search_spec.rb
- spec/features/sign_in_or_continue_spec.rb
- spec/features/teacher_detail_page_in_user_jouney_spec.rb
- spec/features/teacher_identity_sign_in_spec.rb
- spec/features/trainee_teacher_subjourney_for_lup_schools_spec.rb
- spec/support/feature_helpers.rb
Updates the copy of the `/additional-payments/sign-in-or-continue` page to the latest prototype iteration.
> DfE Identity sign in prompt page copy updates

- app/views/claims/_confirmation_form.html.erb
- app/views/claims/_personal_details.html.erb
- app/views/claims/teacher_detail.html.erb
- config/locales/en.yml
- spec/features/teacher_identity_sign_in_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-1196
Fixes some issues on the Check and confirm personal details page:
* Incorrect alignment of columns
* Date of birth displayed in human readable format
* Copy corrected to latest version of prototype following iterations
> Check and confirm personal details page fixes

- lib/dqt/matchers/general.rb
- spec/lib/dqt/matchers/general_spec.rb
This PR reverts a change that was introduced with https://github.com/DFE-Digital/claim-additional-payments-for-teaching/commit/860ce400de7de1c3cc9b92fe7bb8a7132e6bbd46#diff-57487b7ec5109fb49e83ddb8312be70fc97fc0f6322616574b0d38a6ec2358f7 without realising the side effect of having duplicate qualification names in multiple categories.
It also adds unit tests that could have spotted the issue in the first place.
Explanation in the commit.
Please note: this PR also includes [b120fd7](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2488/commits/b120fd7fc08863704d8e1ab923ff0c71dd69d54e) which is a minor fix for #2483
> CAPT-1337 Remove duplicate QTS Award qualification from all categories except PG

- app/controllers/claims_controller.rb
- app/forms/select_email_form.rb
- app/models/claim.rb
- app/models/dfe_identity/user_info.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/claims/select_email.html.erb
- config/analytics.yml
- config/locales/en.yml
- db/migrate/20231020160015_add_email_address_check_to_claims.rb
- db/schema.rb
- spec/factories/claims.rb
- spec/features/check_email_spec.rb
- spec/features/teacher_detail_page_in_user_jouney_spec.rb
- spec/models/claim/permitted_parameters_spec.rb
- spec/models/claim_spec.rb
- spec/support/omniauth_mock_helper.rb
CAPT-1204 - Create new screen - Playback email address from Teacher ID
- Check for signed-in with teacher id and `email` from teacher id 
- If either or both are false or missing go straight to the old email verification flow 
- If both are true, show the select email page and pre-populate the `email` from teacher id
- If email is confirmed set
- the `email_address` on the claim,
- `email_verified` to true and
- `email_address_check` to true.
- go to the next question
- If email is not confirmed set
- the `email_address` on the claim to `nil`,
- `email_verified` to`nil`,
- `email_address_check` to `false` and
- go to the old email verification flow
> Capt-1204 - Create new screen - Playback email address from Teacher ID

- app/views/claims/select_email.html.erb
- spec/features/combined_teacher_claim_journey_with_teacher_id_spec.rb
- spec/features/early_career_payments_claim_sequence_slug_spec.rb
- spec/features/teacher_identity_sign_in_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-1387
While the functionality had been implemented, the existing spec was not enabled and also broken.
> Add specs for removal of TRN page

- app/models/claim.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/claims/personal_details.html.erb
- spec/features/check_email_spec.rb
- spec/features/combined_teacher_claim_journey_with_teacher_id_spec.rb
- spec/models/claim_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
- spec/support/omniauth_mock_helper.rb
* Skip page if all details are valid from TID
* Conditionally show personal details page with specific questions if anything is missing from TID
* Change first/surname valid lengh to 1..100 inline with TID validation
> CAPT-1385 - Personal details page with TID

- app/controllers/base_public_controller.rb
- app/controllers/omniauth_callbacks_controller.rb
- app/controllers/static_pages_controller.rb
- app/helpers/claims_helper.rb
- app/models/student_loans/slug_sequence.rb
- app/views/claims/_personal_details.html.erb
- app/views/claims/teacher_detail.html.erb
- app/views/static_pages/landing_page.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20231114094829_default_logged_in_with_tid_to_nil.rb
- db/schema.rb
- spec/features/backlink_spec.rb
- spec/features/check_email_spec.rb
- spec/features/claim_journey_does_not_get_cached_spec.rb
- spec/features/combined_teacher_claim_journey_with_teacher_id_spec.rb
- spec/features/correct_school_spec.rb
- spec/features/ineligible_student_loans_claims_spec.rb
- spec/features/sign_in_or_continue_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/features/teacher_detail_page_in_user_jouney_spec.rb
- spec/features/teacher_detail_page_student_loans_journey_spec.rb
- spec/requests/claims_spec.rb
- spec/requests/omniauth_callbacks_controller_spec.rb
- spec/requests/timeout_spec.rb
- spec/support/feature_helpers.rb
This pull request adds the ability for TSLR users to sign in using Teacher ID. It also includes the addition of specs and feature specs for sign-in with Teacher ID, as well as the removal of the TRN question from the user journey if the user has logged in to Teacher ID. Additionally, this PR implements the check and confirm your details page, adds the details check to the claim model, and persists teacher details from Teacher ID. Finally, it fixes failing specs and updates copy on the DfE Identity sign-in prompt page.
- [CAPT-1354](https://dfedigital.atlassian.net/browse/CAPT-1354?atlOrigin=eyJpIjoiZjc2NTk3OTY3NDQ0NGYzYjk1YjljNWY4N2VjMDgyM2MiLCJwIjoiaiJ9) Dev - TSLR ID - Use DfE Identity to sign in
- [CAPT-1355](https://dfedigital.atlassian.net/browse/CAPT-1355?atlOrigin=eyJpIjoiMDRkYjhiY2 …
> CAPT-1354 & CAPT-1355 - Implement TSLR Teacher ID sign-in and related features

- app/controllers/claims_controller.rb
- app/forms/select_mobile_number_form.rb
- app/models/claim.rb
- app/models/dfe_identity/user_info.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/claims/select_mobile.html.erb
- config/analytics.yml
- config/locales/en.yml
- db/migrate/20231031090701_add_mobile_check_to_claims.rb
- db/schema.rb
- spec/features/check_email_spec.rb
- spec/features/check_phone_number_spec.rb
- spec/features/combined_teacher_claim_journey_with_teacher_id_spec.rb
- spec/features/teacher_detail_page_in_user_jouney_spec.rb
- spec/features/teacher_detail_page_student_loans_journey_spec.rb
- spec/forms/select_mobile_number_form_spec.rb
- spec/models/claim/permitted_parameters_spec.rb
- spec/models/claim_spec.rb
- spec/support/claims_controller_helper.rb
- spec/support/omniauth_mock_helper.rb
[CAPT-1205](https://dfedigital.atlassian.net/browse/CAPT-1205?atlOrigin=eyJpIjoiMDAyMmVhNDk4Mjc2NDIxN2IyNDYwZmEzYTRjMWM4OTkiLCJwIjoiaiJ9) Create new screen - Playback mobile number from Teacher ID
- Check for signed-in with teacher id and phone number from teacher id
- If either or both are `false` or missing go straight to the old mobile verification flow
- If both are `true`, show the select mobile page and pre-populate the `phone_number` from teacher id
- If mobile is confirmed set
- the `mobile_number` on the claim,
- `provide_mobile_number` to `true` and
- `mobile_check` to "use".
- go to the next question (bank or building society)
- If mobile is not confirmed set
- the `mobile_number` on the claim to nil,
- `provide_mobile_number` to `nil`,
- `mobile_check` to "alternative" and
- …
> CAPT-1205-playback-phone-number-from-tid

- app/models/student_loans.rb
- app/models/student_loans/admin_tasks_presenter.rb
- app/models/student_loans/eligibility.rb
- app/models/student_loans/eligibility_admin_answers_presenter.rb
- app/models/student_loans/eligibility_answers_presenter.rb
- app/models/student_loans/presenter_methods.rb
- app/views/student_loans/claims/_ineligibility_reason_ineligible_qts_award_year.html.erb
- app/views/student_loans/claims/qts_year.html.erb
- config/locales/en.yml
- spec/features/backlink_spec.rb
- spec/features/changing_answers_spec.rb
- spec/features/claim_journey_does_not_get_cached_spec.rb
- spec/features/ineligible_student_loans_claims_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/helpers/claims_helper_spec.rb
- spec/models/student_loans/admin_tasks_presenter_spec.rb
- spec/models/student_loans/eligibility_admin_answers_presenter_spec.rb
- spec/models/student_loans/eligibility_answers_presenter_spec.rb
- spec/models/student_loans/eligibility_spec.rb
- spec/models/student_loans/presenter_methods_spec.rb
- spec/requests/claims_spec.rb
- spec/support/admin_checks_feature_shared_examples.rb
Content changes as per [CAPT-1341](https://dfedigital.atlassian.net/browse/CAPT-1341) and [CAPT-1396](https://dfedigital.atlassian.net/browse/CAPT-1396)
In a nutshell, the changes are in 4 parts (commits):
1. Segregation of the TSLR QTS award question view + requested content changes
2. Segregation of the TSLR QTS award ineligibility partial + requested content changes (CAPT-1396)
3. Reflecting content changes in the "check your answers page"
4. Reflecting content changes in the admin task presenter
We are still calculating the first eligible QTS award year based on the claim year for all of the above points. Still, there is no need to look at the upper limit as the last eligible QTS award year is 2020 to 2021 until the claim year 2031 to 2032 when the TSLR window will open for one last …
> CAPT-1341, CAPT-1396: TSLR QTS award year question content changes

- app/models/early_career_payments/eligibility_answers_presenter.rb
If the school playback (from TPS) was suggested and the user clicked on the suggested school the change school link goes back to the playback, all other scenarios it goes to the current-school where the user types in the school name.
> CAPT-1407 - fix change school link

- app/controllers/admin/base_admin_controller.rb
- app/controllers/application_controller.rb
- app/controllers/base_public_controller.rb
- app/controllers/school_search_controller.rb
- config/initializers/omniauth.rb
- config/initializers/session_store.rb
https://dfedigital.atlassian.net/browse/CAPT-1414
On review apps we were seeing some HTTP auth errors on the Omniauth callback controller, so I have removed it from that controller only.
I have also configured the cookie domain to match the callback URL which was suggested by various people when researching the problem. On its own it did not seem to fix the problem, but I think it is better to have it than not.
I've also removed some old/redundant Omniauth configuration which are either deprecated or the same as default..
> Fix CSRF error

- Gemfile
- Gemfile.lock
Update to latest version of dfe-analytics (v1.11.3) prior to enabling the entity table check job
> Update dfe-analytics to v1.11.3

- config/analytics.yml
Fixes a startup issue introduced in https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2539 but for some reason not picked up in that PR's review app deployment.
> Fix DfE analytics

- Gemfile
- Gemfile.lock
- config/analytics.yml
- config/analytics_blocklist.yml
Updating to the latest version of dfe-analytics (v1.11.5) prior to enabling the entity_table_check_job
> Update dfe-analytics gem

- app/models/early_career_payments/dqt_record.rb
- spec/models/early_career_payments/dqt_record_spec.rb
Similar to https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2573
Fixes a bug in the ECP DQT record matching where the ITT subject was not matched against the list of all possible strings listed in https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/master/lib/dqt/matchers/early_career_payments.rb. It would only match if it was an exact match for the key, e.g. `computing`.
This would incorrectly determine a user as ineligible in the teacher ID journey.
> Fix ECP subject matching against DQT record

- app/forms/select_mobile_number_form.rb
- app/models/claim.rb
- spec/factories/claims.rb
- spec/features/combined_teacher_claim_journey_with_teacher_id_check_mobile_spec.rb
- spec/features/tslr_claim_journey_with_teacher_id_check_mobile_spec.rb
- spec/forms/select_mobile_number_form_spec.rb
- spec/models/claim_spec.rb
- spec/support/stubbing_helpers.rb
https://dfedigital.atlassian.net.mcas.ms/browse/CAPT-1483
The best place to start is by looking at the feature specs before/after; they didn't cover the journeys end-to-end, and when rewritten, they highlighted the presence of two scenarios where the submission was being prevented, when choosing an "alternative" number or using the one that came through TID. **Requires manual testing as well**
> Fix: Unable to submit when selecting mobile number (TID)

- app/controllers/claims_controller.rb
- app/models/claim.rb
- app/models/claim_student_loan_details_updater.rb
- app/models/dqt/retrieve_claim_qualifications_data.rb
- app/models/page_sequence.rb
- app/models/student_loans/slug_sequence.rb
- spec/features/claim_with_mobile_sms_otp_spec.rb
- spec/features/ineligible_student_loans_claims_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/features/tslr_claim_journey_with_teacher_id_check_email_spec.rb
- spec/features/tslr_claim_journey_with_teacher_id_check_mobile_spec.rb
- spec/features/tslr_claim_journey_with_teacher_id_trn_spec.rb
- spec/models/page_sequence_spec.rb
- spec/requests/claims_spec.rb
https://dfedigital.atlassian.net.mcas.ms/browse/CAPT-1417
The only code change should have been in the slug sequence, but I had to make another change in the controller, and it's still quite small. This additional change was necessary because when using the TID route we start retrieving and storing personal details _before_ checking for eligibility criteria (in the non-TID route we first calculate the eligibility, then we ask and store **any** personal details).
In this particular context, retrieving and storing the Student loan details as soon as the user confirms their personal details could cause a premature exit screen when the applicant made zero repayments: in this scenario we'd still want the user to know if their qualifications etc would make them eligible. See ticket comments for …
> CAPT-1417 Change the slug sequence of the student loan playback (TSLR)

- Gemfile
- Gemfile.lock
[JIRA Issue: CAPT-1466](https://dfedigital.atlassian.net.mcas.ms/browse/CAPT-1466)
This PR adds the Rack-Mini-Profiler gem to the development group so that while working on the application we can get performance metrics back for each page so that we can detect performance issues early in development to prevent significant impact on user experience further down the line.
- Speed Badge: Visual display of each page's load time in our application.
- Detailed Metrics: Upon clicking the speed badge, reveals a breakdown of the total load time.
- SQL Queries Insight: Shows the exact part of the code running each query and its duration.
Small badge displayed in the top-left corner showing each page's load time.
Performance Breakdown View (On Badge Click)
> CAPT-1466 - Add rack-mini-profiler gem

- app/controllers/claims_controller.rb
- app/models/policies/early_career_payments/slug_sequence.rb
- spec/features/combined_teacher_claim_journey_with_teacher_id_check_mobile_spec.rb
- spec/features/combined_teacher_claim_journey_with_teacher_id_spec.rb
- spec/features/ineligible_levelling_up_premium_payments_spec.rb
- spec/features/levelling_up_premium_payments_spec.rb
- spec/features/subject_teaching_question_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
- spec/support/stubbing_helpers.rb
The way the TID route works, we retrieve the DQT record for a claim at the beginning of the journey when the applicant confirms their personal details (`teacher-detail` slug). Upon confirmation, we have access to the induction data retrieved from DQT. Before using it to determine if the claimant has induction data that does _not_ make them ineligible, we need to wait until they confirm that they are qualified teachers (`nqt-in-academic-year-after-itt` slug): we can then determine the answer to the `induction_completed` question and skip it (it's the next slug in the sequence) if we have determined a positive value for it; otherwise, the question is presented as it's currently done: if they confirmed the question with a "No", then they'd be presented an exit screen (unless the chosen …
> Determine the answer to the induction question using DQT (TID route)

- app/views/additional_payments/claims/_ineligibility_trainee_teaching_lacking_both_valid_itt_subject_and_degree.html.erb
https://dfedigital.atlassian.net/browse/CAPT-1119
This is just a content change; if you want to understand under which conditions this partial is rendered, look [here](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/master/lib/ineligibility_reason_checker.rb#L17-L18) and [here](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/master/lib/ineligibility_reason_checker.rb#L76C1-L82C6): only LUP trainees without an ECP-eligible subject and degree should be presented this exit screen.
> CAPT-1119 Amend exit screen for LUP school trainees

- app/jobs/student_loan_amount_check_job.rb
- spec/features/combined_teacher_claim_journey_with_teacher_id_spec.rb
- spec/features/tslr_claim_journey_with_teacher_id_trn_spec.rb
- spec/jobs/student_loan_amount_check_job_spec.rb
We have a similar mechanism for the student loan _plan_ [task](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2556/commits/6d46f5bf42984a2030e46eb4cfe9079829577194#diff-2c18657c671befd11628bb5625912cbca80a2cbed533959e495ef14492db720dR27)
As a summary, after deploying #2556 we'll have three potential buckets of claims:
1. Claims submitted using the student loan questions in the journey (`submitted_using_slc_data = null`)
2. Claims submitted without the student loan questions, but the student loan details were found in our SLC extract (`submitted_using_slc_data = true`)
2. Claims submitted without the student loan questions, but the student loan details were NOT found in our SLC extract (`submitted_using_slc_data = false`)
The value of `submitted_using_slc_data` …
> Skip deleting and re-running NO DATA student loan amount tasks for older TSLR claims

- app/controllers/claims_controller.rb
- app/forms/form.rb
- app/forms/journeys/additional_payments_for_teaching/nqt_in_academic_year_after_itt_form.rb
- app/models/journeys/additional_payments_for_teaching.rb
- app/models/policies/early_career_payments/eligibility.rb
- app/views/additional_payments/claims/nqt_in_academic_year_after_itt.html.erb
- spec/factories/claims.rb
- spec/forms/journeys/additional_payments_for_teaching/nqt_in_academic_year_after_itt_form_spec.rb
- spec/models/claim_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
Please feel free to nit pick as much as possible!
I'm unsure about the backlink path piece, I've kept the logic for rendering that the same as it was in the claim controller. I think it could be simplified and we could remove `return unless page_sequence.in_sequence?("correct-school")` if we can assume that `nqt-in-academic-year-after-itt` always follows the `correct-school` step - I'm not sure on that assumption though.
I hope the specs are ok! For the past year or so I've been writing specs avoiding using `let` and `before` entirely and just repeating the test setup in each `it` block, which I've found works really well, so I'm a bit rusty on `let` best practices.
---
Extracts a new form object and moves the logic associated with the
`nqt_in_academic_year_after_itt` step out of claims …
> Extract NqtInAcademicYearAfterIttForm

- app/controllers/claims_controller.rb
- app/forms/journeys/additional_payments_for_teaching/teaching_subject_now_form.rb
- app/models/journeys/additional_payments_for_teaching.rb
- app/models/journeys/additional_payments_for_teaching/answers_presenter.rb
- app/models/policies/early_career_payments/eligibility.rb
- app/views/additional_payments/claims/teaching_subject_now.html.erb
- config/locales/en.yml
- spec/features/combined_teacher_claim_journey_dependent_answers_spec.rb
- spec/features/combined_teacher_claim_journey_spec.rb
- spec/features/combined_teacher_claim_journey_with_teacher_id_check_email_spec.rb
- spec/features/combined_teacher_claim_journey_with_teacher_id_spec.rb
- spec/features/early_career_payments_claim_lupp_ineligible_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/features/itt_subject_selection_spec.rb
- spec/features/levelling_up_premium_payments_spec.rb
- spec/forms/journeys/additional_payments_for_teaching/teaching_subject_now_form_spec.rb
- spec/models/claim_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
Extract form for teaching_subject_now
Extracts a form object for the teaching subject now step.
Depending on whether or not there's an eligible subject upon reaching
the `teaching-subject-now` step, we may redirect the subject to the
`eligbible-itt-subject` step rather than render the
`teaching-subject-now` form.
`eligible-itt-subject` can be reset if the `qualification` changes, and
`eligible-itt-subject` resets the `teaching-subject-now` answer.
For now we've preserved the existing behaviour of determining whether to
render the `teaching-subject-now` in the `ClaimsController#show` action.
This feels like the wrong place for this though. It makes more sense to
handle the redirect in the `ClaimsController#update` action or better
yet in the `PageSequence#next_slug` method, something to …
> capt 1571/extract form object for teaching subject now

- app/views/additional_payments/claims/check_your_answers_part_one.html.erb
We currently refactoring all our eligibility checker pages to use form objects. We were planning to do the same to this page however i noticed a couple of things:
- even though there's a form on the page, it doesn't update anything
- even though it looks like it renders errors:
- there shouldn't be any errors at this point
- if there were errors, the standard error summary would be broken since there are no form fields to link to
Due to the above, I decided to:
- remove the html form and error summary
- **_not_** create a new form object, since there are no attributes to update nor validations to run
- stick with an `update` button so as not to break the page sequence (see below)
As the `ClaimsController` currently stands, if we link to GET `eligibility-confirmed` from this page:
1. the …
> CAPT 1575 - Remove form and errors from /check-your-answers-part-one

- app/forms/journeys/additional_payments_for_teaching/eligible_itt_subject_form.rb
- app/helpers/additional_payments_helper.rb
- app/helpers/claims/itt_subject_helper.rb
- app/models/journeys/additional_payments_for_teaching.rb
- app/models/journeys/additional_payments_for_teaching/answers_presenter.rb
- app/models/policies/early_career_payments/admin_tasks_presenter.rb
- app/models/policies/early_career_payments/eligibility.rb
- app/views/additional_payments/claims/eligible_itt_subject.html.erb
- config/locales/en.yml
- spec/features/combined_teacher_claim_journey_with_teacher_id_spec.rb
- spec/features/reminders_spec.rb
- spec/features/trainee_teacher_subjourney_for_lup_schools_spec.rb
- spec/forms/journeys/additional_payments_for_teaching/eligible_itt_subject_form_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
- spec/support/admin_tasks_presenter_shared_examples.rb
Extracts a form object for the `eligible_itt_subject` step.
I think the view could be cleaned up a bit more but it requires more 
substantial changes outside the scope of this ticket
There's a couple of existing issues with this page not addressed in this pr.
If there's no `available_subjects` present (or on master if there's no
`subject_symbols`) present, then an empty page can render. One scenario that
can cause this is the user choosing "No" on the "Do you spend at least half of
your contracted hours teaching eligible subjects?", reaches the ineligible page
then navigates back with the browser button. In this scenario the
`JourneySubjectEligibilityChecker#selectable_subject_symbols` method returns an
empty array as there are no eligible policies. Looking in the …
> CAPT 1573/form object for eligible itt subject

- app/models/student_loans_data_importer.rb
- spec/jobs/import_student_loans_data_job_spec.rb
- spec/requests/admin_student_loans_data_upload_spec.rb
https://dfedigital.atlassian.net.mcas.ms/browse/CAPT-1555
Context: We use the SLC (Student Loans Company) data to playback the student loan amount to users claiming Student Loan repayments and fetch the correct plan type before sending the payments to payroll. The data is uploaded via the admin portal and can trigger the execution of certain admin checks (each policy has different tasks and rules) for claims currently awaiting a decision. This was one of the latest automations to be introduced.
With this PR, we change the accepted valid DoB date format to be DD/MM/YYYY instead of MM/DD/YYYY (as previously assumed and coded in)
> CAPT-1555 The SLC CSV upload uses British DoB formatting

- app/controllers/claims_controller.rb
- app/forms/personal_details_form.rb
- app/models/claim.rb
- app/models/invalid_date.rb
- app/models/journeys/additional_payments_for_teaching/slug_sequence.rb
- app/models/journeys/base.rb
- app/models/journeys/teacher_student_loan_reimbursement/slug_sequence.rb
- app/views/claims/personal_details.html.erb
- spec/forms/personal_details_form_spec.rb
- spec/models/claim_spec.rb
Extracting the /personal-details into a form object.
**Personal details validations being called from slug sequences** 
Before these changes, there was a method on the `Claim` model `has_all_valid_personal_details?` which checked whether the personal details were valid, and that they matched TID:
https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2696/files#diff-177255fb498b99ec75c3866174729f24e11d030819b91655a5913b28669505c2R505-R507
This was called from the SlugSequences to determine whether to remove `/personal-details` completely.
https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/master/app/models/journeys/additional_payments_for_teaching/slug_sequence.rb#L160
Since this PR removes personal details validations from the model and shifts …
> CAPT-1563 Form object for /personal-details

- app/forms/provide_mobile_number_form.rb
- app/models/claim.rb
- app/models/journeys/base.rb
- app/views/claims/provide_mobile_number.html.erb
- spec/forms/provide_mobile_number_form_spec.rb
- spec/models/claim_spec.rb
**Changes in this PR**
- Extracted form object for `/provide-mobile-number` page.
This is a simple for saving the boolean `provide_mobile_number` onto a Claim.
- Removed validation from Claim model
**Points to note**
- I've kept the error messages out of locales for now until we decide on an approach for forms shared across all journeys
> CAPT-1588 Form object for /provide-mobile-number

- app/forms/teacher_reference_number_form.rb
- app/models/claim.rb
- app/models/journeys/base.rb
- app/views/claims/teacher_reference_number.html.erb
- config/locales/en.yml
- spec/forms/teacher_reference_number_form_spec.rb
- spec/models/claim_spec.rb
Adds a form object for teacher reference number.
When we upgrade rails and get support for Normalisation we should
replace overriding the `valid?` method with a normalisation call back.
The other thing I considered was adding ActiveModel::Callbacks to the
base form and defining a before validation callback there, might be
better not sure.
Have left some validations around trn on the claim model as it seems
like it can be set on the admin side. When we extract forms for the
admin ui we can remove these validations along with normalising the trn
from the claim model.
> Add teacher_reference_number form

- .github/workflows/ci.yaml
- bin/test_splitter
Use github actions for ci.
Runs the linters and test suite.
We run the test over multiple nodes using github actions matrices. The newly
introduced script `bin/test_splitter` handles breaking up the test suite into
sections that run on each node.
There isn't away (at least not one I know of) to cache the set up steps between
nodes, however as the bulk of CI time is spend on running the test suite this
isn't much of an issue (~1min for set up ~9mins for longest node to run).
Splitting the test suite across nodes means we can improve our test suite time
by breaking up some of the slower running feature specs into separate files so
different nodes pick them up.
> CAPT 1622/github actions for ci

- .github/workflows/ci.yaml
Cache doesn't run yarn install for us
Fixes the issues with precompiling assets on ci
> Install yarn packages

- spec/rails_helper.rb
Depending on the order specs ran
`spec/requests/omniauth_callbacks_controller_spec` would fail, the
minimal reproduction case for this failure was
```
bundle exec rspec --order defined \
spec/features/teacher_identity_sign_in_spec.rb \
spec/requests/omniauth_callbacks_controller_spec.rb
````
This was due to omniauth mocks not being reset between test runs.
Updating the suite's before hook to nil out the mock_auths fixes the
issue.
> Fixes flakey omniauth spec

- app/forms/journeys/teacher_student_loan_reimbursement/leadership_position_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/mostly_performed_leadership_duties_form.rb
- app/helpers/student_loans_helper.rb
- app/models/journeys/teacher_student_loan_reimbursement.rb
- app/models/policies/student_loans/eligibility.rb
- app/views/student_loans/claims/leadership_position.html.erb
- app/views/student_loans/claims/mostly_performed_leadership_duties.html.erb
- config/locales/en.yml
- spec/forms/journeys/teacher_student_loan_reimbursement/leadership_position_form_spec.rb
- spec/forms/journeys/teacher_student_loan_reimbursement/mostly_performed_leadership_duties_form_spec.rb
- spec/models/student_loans/eligibility_spec.rb
- spec/requests/claims_spec.rb
This pr covers both CAPT-1602 and CAPT-1603. I decided to do both together as
they're related questions. Might be easier to review each commit separately.
The only thing worth noting is that we don't call reset dependent attributes in
after changing the `had_leadership_position` question, instead we `nil`ify the
`mostly_performed_leadership_duties` question in the form update if the teacher
has changed there answer.
We may want to consider using `ActiveModel::Dirty` as this is the second form
object where we're defining a `*_changed?` method (though it's quite tricky to
get AM dirty to work with AM attributes). I think introducing
`ActiveModel::Dirty` is best done in a separate pr.
https://github.com/DFE-Digital/claim-additional-payments-for-teaching/assets/9936028/1bfb3cf5-cea2-4376-a89d- …
> CAPT 1602/leadership position

- app/controllers/claims_controller.rb
- app/forms/bank_details_form.rb
- app/forms/bank_or_building_society_form.rb
- app/models/claim.rb
- app/models/journeys/base.rb
- app/views/claims/_account_details.html.erb
- app/views/claims/bank_or_building_society.html.erb
- app/views/claims/building_society_account.html.erb
- app/views/claims/personal_bank_account.html.erb
- config/locales/en.yml
- spec/forms/bank_details_form_spec.rb
- spec/forms/bank_or_building_society_form_spec.rb
- spec/models/claim_spec.rb
- Extract form object for /bank-or-building-society
- Re-purpose existing `BankDetailsForm` to serve `/personal-bank-account` and `building-society-account` pages
- Remove page-specific logic from `ClaimsController`
- ~Switch from storing the `hmrc_validation_attempt_count` in the session to a form parameter so all logic can be encapsulated in form object~
- Move error messages to locales under shared `forms:` section
- I've kept some validations in the `Claim` model since looks as though these attributes can be updated via the admin interface and therefore should be validated still
- We could look at consolidating these into shared validators once we pull out admin form objects?
> CAPT-1592 Extract form objects for banking details

- app/controllers/claims_controller.rb
- app/controllers/concerns/journey_concern.rb
- app/models/journeys.rb
- app/models/journeys/session.rb
- config/analytics.yml
- db/migrate/20240508081918_create_journeys_sessions.rb
- db/schema.rb
- spec/factories/journeys/sessions.rb
- spec/models/journeys/session_spec.rb
As part of the efforts to simplify multi claim handling we want to move
away from creating a claim at the start of the journey and instead only
create the claim at the final step where the teacher submits their
answers.
This commit introduces a new model `Journeys::Session` which will be
used to store the answers entered by the teacher. The answers will be
stored in a json column on the new model, once validated by the form
objects.
`Journeys::Session` is currently the best name we could come up with but
we're all ears for any better suggestions.
> Introduces journey session model

- app/forms/form.rb
- spec/forms/form_spec.rb
Load values from journey session
If the journey session has a value in the answers hash prefer that when
loading the initial attribute values for a form.
Note that `Journeys::Session#answers` is intended to be a "flat" data
structure, not differentiating between claim and eligibility attributes
as it's just concerned with storing answers provided by the user, not
what they're mapped to in the data base.
> set attributes from journey session

- app/controllers/concerns/form_submittable.rb
- app/controllers/journeys/additional_payments_for_teaching/reminders_controller.rb
- app/controllers/journeys/additional_payments_for_teaching/reminders_form_callbacks.rb
- app/forms/email_verification_form.rb
- app/forms/form.rb
- app/forms/journeys/additional_payments_for_teaching/reminders/email_verification_form.rb
- app/forms/journeys/additional_payments_for_teaching/reminders/personal_details_form.rb
- app/models/journeys/additional_payments_for_teaching.rb
- app/models/journeys/base.rb
- app/models/journeys/teacher_student_loan_reimbursement.rb
- app/models/reminder.rb
- app/views/additional_payments/reminders/_one_time_password.html.erb
- app/views/additional_payments/reminders/email_verification.html.erb
- app/views/additional_payments/reminders/personal_details.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/reminders_spec.rb
- spec/features/trainee_teacher_subjourney_for_lup_schools_spec.rb
- spec/forms/email_verification_form_spec.rb
- spec/forms/form_spec.rb
- spec/forms/journeys/additional_payments_for_teaching/reminders/email_verification_form_spec.rb
- spec/forms/journeys/additional_payments_for_teaching/reminders/personal_details_form_spec.rb
- spec/models/reminder_spec.rb
- spec/requests/form_submittable_spec.rb
- spec/requests/reminders_spec.rb
This PR is the first iteration of CAPT-1634 applied to an isolated controller that handles a mini-journey for reminders (ECP/LUPP) and converts the reminders slugs to form objects as per CAPT-1633. In a follow-up PR, I will be adding the new concern to the claims controller and iterate with any improvements or changes required.
1. Review the `FormSubmittable` concern and associated request spec; I won't repeat the rationale here as it's explained extensively in various comments inside the concern; worth noting that:
- It's a first iteration, designed with speed in mind; each GET/POST/PATCH request on a `<path>/:slug` will dynamically define all the pre-post rendering/submission callback methods for that slug only. I have considered defining them as singleton methods so we could tap into …
> CAPT-1633 Form objects for reminders | CAPT-1634 Encapsulate pre/post form rendering/submission logic per-journey (Part 1)

- config/initializers/dfe_analytics.rb
- config/initializers/omniauth.rb
- config/initializers/session_store.rb
- terraform/application/application.tf
- terraform/application/config/production.tfvars.json
- terraform/application/config/test.tfvars.json
- terraform/application/variables.tf
- Add canonical_hostname variable to AKS apps
- Update where we're referencing `ENV["ENVIRONMENT_NAME"] == "review"` to reflect the fact our review app environment names are now `review-PR_NUMBER`
> Add canonical hostname variable

- spec/support/have_received_email_matcher.rb
Background:
When migrating some forms over to the journey session I noticed a bug that wasn't caught by our tests. As we're stubbing the mailers there's nothing to check that the passed in arguments implement the api the mailer methods expect.
---
Testing mailers with `allow(Mailer).to(receive(:method))` dosen't test
that the mailer actually works when passed the expected arguments.
This commit adds a test helper to check the mailer successfully sends
the expected email.
As we're using notify we want to test the personalisation is what we
expect. The notify mailer writes the personalisation to a field on the
email which we can test against.
Example useage of this matcher
```ruby
expect("test@example.com").to have_received_email(
"template-id",
email_subject: "Student loan repayment email …
```
> Add have_received_email_matcher

- app/forms/email_address_form.rb
- app/forms/email_verification_form.rb
- app/forms/journeys/additional_payments_for_teaching/reminders/email_verification_form.rb
- app/forms/select_email_form.rb
- app/models/claim_journey_session_shim.rb
- app/models/journeys/additional_payments_for_teaching/session_answers.rb
- app/models/journeys/additional_payments_for_teaching/slug_sequence.rb
- app/models/journeys/base_answers_presenter.rb
- app/models/journeys/session_answers.rb
- app/models/journeys/teacher_student_loan_reimbursement/session_answers.rb
- app/models/journeys/teacher_student_loan_reimbursement/slug_sequence.rb
- spec/factories/journeys/additional_payments_for_teaching/session_answers.rb
- spec/factories/journeys/teacher_student_loan_reimbursement/session_answers.rb
- spec/features/admin_claim_tasks_update_with_dqt_api_spec.rb
- spec/features/changing_answers_spec.rb
- spec/features/claim_journey_does_not_get_cached_spec.rb
- spec/features/combined_teacher_claim_journey_with_teacher_id_check_email_spec.rb
- spec/features/early_career_payments_eligible_now_reminder_set_spec.rb
- spec/features/one_time_password_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/features/tslr_claim_journey_with_teacher_id_check_email_spec.rb
- spec/features/validating_user_contact_details_spec.rb
- spec/forms/email_address_form_spec.rb
- spec/forms/email_verification_form_spec.rb
- spec/forms/journeys/additional_payments_for_teaching/reminders/email_verification_form_spec.rb
- spec/forms/select_email_form_spec.rb
- spec/models/journeys/page_sequence_spec.rb
- spec/requests/submissions_spec.rb
- spec/support/journey_answers_presenter_shared_examples.rb
Updates the email related forms to write their answers to the journey session.
Notes for reviewers
All should be pretty standard, most of the changes are updating the specs.
One thing that is of note is that we've copied the logic of the email verification form into the reminders email verification form that previous just inherited from the main journey form (see [this commit](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2767/commits/1679485faf89a75bbec4f0cca387762cd3561432)). We've copied the logic over as the reminders form is writing to the current claim where as the main journey form is writing to the session object. I think copying the code over is going to be less difficult to maintain than adding concerns or something as we don't know how much these …
> CAPT 1665/update email address form to write to session

- app/models/journeys/session.rb
When we load session attributes from the database and populate the
answers object's attributes that counts as a change. To avoid this false
positive we clear the changes information after initialize.
While we're only using this changes logic during the migration from
current claim to journey session, this issue highlights the trickiness
of working with a hash backed model rather than a table backed model.
Once the migration work is completed, and everything is writing to the
session object, we should consider the maintainability of this approach
and see whether a table backed approach would meet our needs better.
> Fix changes logic

- spec/jobs/employment_check_job_spec.rb
This spec was failing as, due to a call back in the factory,
`updated_at` was actually being set to the current date and the current
date is now less that 3 months from the date we travel too.
> Fix failing spec

- app/forms/claim_submission_base_form.rb
- app/forms/mobile_number_form.rb
- app/forms/mobile_verification_form.rb
- app/forms/provide_mobile_number_form.rb
- app/forms/select_mobile_form.rb
- app/models/claim_journey_session_shim.rb
- app/models/concerns/journeys/sessions/teacher_id.rb
- app/models/journeys/additional_payments_for_teaching/slug_sequence.rb
- app/models/journeys/base_answers_presenter.rb
- app/models/journeys/session_answers.rb
- app/models/journeys/teacher_student_loan_reimbursement/slug_sequence.rb
- spec/factories/journeys/additional_payments_for_teaching/session_answers.rb
- spec/factories/journeys/teacher_student_loan_reimbursement/session_answers.rb
- spec/features/admin_claim_tasks_update_with_dqt_api_spec.rb
- spec/features/changing_answers_spec.rb
- spec/features/claim_journey_does_not_get_cached_spec.rb
- spec/features/claim_with_mobile_sms_otp_spec.rb
- spec/features/early_career_payments_eligible_now_reminder_set_spec.rb
- spec/features/eligible_later_early_career_payments_claim_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/forms/mobile_number_form_spec.rb
- spec/forms/mobile_verification_form_spec.rb
- spec/forms/provide_mobile_number_form_spec.rb
- spec/forms/select_mobile_form_spec.rb
- spec/models/journeys/additional_payments_for_teaching/slug_sequence_spec.rb
- spec/models/journeys/page_sequence_spec.rb
- spec/models/journeys/teacher_student_loan_reimbursement/slug_sequence_spec.rb
- spec/requests/submissions_spec.rb
- spec/support/eligible_later_shared_examples.rb
- spec/support/journey_answers_presenter_shared_examples.rb
Updates the various mobile forms to write to the journey session and
updates the call sites to read this information from the journey
session.
We've had to change the order of things in the claim submission form
slightly as the `mobile_number_verified` validation not longer creates a
claim. When `claim_is_eligible` validation runs we need to have the
claim set up and associated with the `main_eligibility`, as this is no
longer done by the `mobile_number_verified` validation we set the claim
up in the constructor.
> Update mobile forms to write to journey session

- app/forms/journeys/teacher_student_loan_reimbursement/claim_school_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/select_claim_school_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/subjects_taught_form.rb
- app/models/journeys/teacher_student_loan_reimbursement/answers_presenter.rb
- app/models/journeys/teacher_student_loan_reimbursement/claim_journey_session_shim.rb
- app/models/journeys/teacher_student_loan_reimbursement/session_answers.rb
- spec/factories/journeys/teacher_student_loan_reimbursement/session_answers.rb
- spec/features/changing_answers_spec.rb
- spec/features/dfe_identity_sign_in_for_student_loans_journey_spec.rb
- spec/features/multiple_claim_schools_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/forms/journeys/teacher_student_loan_reimbursement/subjects_taught_form_spec.rb
- spec/models/journeys/teacher_student_loan_reimbursement/answers_presenter_spec.rb
Migrate subjects taught to session
Building off the work in the previous PR this one adds the subjects
taught to the session answers without needing to update the eligibility
> CAPT 1681/subjects taught

- app/forms/journeys/teacher_student_loan_reimbursement/claim_school_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/select_claim_school_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/still_teaching_form.rb
- app/models/journeys/teacher_student_loan_reimbursement/claim_journey_session_shim.rb
- app/models/journeys/teacher_student_loan_reimbursement/session_answers.rb
- app/models/journeys/teacher_student_loan_reimbursement/slug_sequence.rb
- spec/factories/journeys/teacher_student_loan_reimbursement/session_answers.rb
- spec/features/changing_answers_spec.rb
- spec/features/current_school_with_closed_claim_school_spec.rb
- spec/features/dfe_identity_sign_in_for_student_loans_journey_spec.rb
- spec/features/ineligible_student_loans_claims_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/features/tslr_claim_journey_with_teacher_id_still_teaching_spec.rb
- spec/forms/journeys/teacher_student_loan_reimbursement/still_teaching_form_spec.rb
- spec/models/journeys/page_sequence_spec.rb
- spec/models/journeys/teacher_student_loan_reimbursement/slug_sequence_spec.rb
- spec/requests/claims_spec.rb
Migrate still teaching form to write to answers
Migrates the still teaching form to write to the answers and updates the
call sites to read from the answers rather than from the eligibility.
> CAPT 1682/still teaching form

- app/forms/journeys/teacher_student_loan_reimbursement/qts_year_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/qualification_details_form.rb
- app/models/journeys/teacher_student_loan_reimbursement/claim_journey_session_shim.rb
- spec/factories/journeys/teacher_student_loan_reimbursement/session_answers.rb
- spec/features/changing_answers_spec.rb
- spec/features/dfe_identity_sign_in_for_student_loans_journey_spec.rb
- spec/features/ineligible_student_loans_claims_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/features/tslr_claim_journey_with_teacher_id_spec.rb
- spec/forms/journeys/teacher_student_loan_reimbursement/qts_year_form_spec.rb
- spec/forms/journeys/teacher_student_loan_reimbursement/qualification_details_form_spec.rb
- spec/models/journeys/teacher_student_loan_reimbursement/slug_sequence_spec.rb
- spec/requests/claims_spec.rb
Write qts_award_year to session answers
Updates references to qts_award_year to use the session rather than the
eligibility. Partly updates the qualification_details_form as that
writes the qts_award_year.
> CAPT 1678/qts year

- app/forms/journeys/additional_payments_for_teaching/qualification_details_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/qualification_details_form.rb
- app/models/claim_journey_session_shim.rb
- app/models/journeys/additional_payments_for_teaching/answers_presenter.rb
- app/models/journeys/additional_payments_for_teaching/slug_sequence.rb
- app/models/journeys/teacher_student_loan_reimbursement/answers_presenter.rb
- app/models/journeys/teacher_student_loan_reimbursement/slug_sequence.rb
- spec/factories/journeys/additional_payments_for_teaching/session_answers.rb
- spec/factories/journeys/teacher_student_loan_reimbursement/session_answers.rb
- spec/forms/journeys/additional_payments_for_teaching/qualification_details_form_spec.rb
- spec/forms/journeys/teacher_student_loan_reimbursement/qualification_details_form_spec.rb
- spec/models/journeys/additional_payments_for_teaching/answers_presenter_spec.rb
- spec/models/journeys/additional_payments_for_teaching/slug_sequence_spec.rb
- spec/models/journeys/teacher_student_loan_reimbursement/answers_presenter_spec.rb
- spec/models/journeys/teacher_student_loan_reimbursement/slug_sequence_spec.rb
update qualificaton details form to write to answwers
As we're still pulling the `qualification`, `eligible_itt_subject` and
`itt_academic_year` form the claim, we still need to write
`qualification_details` to the claim so that the check in reset depenent
answers is hit which removes deleting the depenencies.
Hopefully we'll soon be able to remove this reset dependent answers
stuff and just nullify the answers directly in the forms.
> CAPT 1648/qualifications details form

- app/models/payroll/payment_csv_row.rb
- app/models/payroll/payments_csv.rb
- spec/models/payroll/payment_csv_row_spec.rb
- spec/models/payroll/payments_csv_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-1712
The new payroll system is unable to ingest files with the LF character which Claim currently outputs on each line. The [RFC 4180 for CSV](https://www.ietf.org/rfc/rfc4180.txt) specifies that line endings should have a CRLF character instead. For some reason the Ruby CSV library defaults to LF.
> CAPT-1712: Use CRLF line endings on payroll CSV file

- spec/support/feature_helpers.rb
This is an attempt to fix specs which are regularly failing whenever they use the `choose_school` helper.
This type of failure can happen when the page has not yet finished loading before Capybara tries to run the next matcher. Since this page is relatively large and has Javascript instantiation on the school search field this could be the reason for the intermittent failures. The `have_text` matcher has a built in wait mechanism which usually resolves this.
> Attempt to fix flaky school search specs

- app/models/base_policy.rb
- app/models/payment.rb
- app/models/policies/levelling_up_premium_payments.rb
- app/models/policies/student_loans.rb
- spec/models/early_career_payments_spec.rb
- spec/models/levelling_up_premium_payments_spec.rb
- spec/models/payment_spec.rb
- spec/models/student_loans_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-170
Shortens the policy names output in the payroll CSV file to accommodate a new 30-character limit in the payroll system which ingests them.
The 30 characters needs to include multiple policies where a single payment covers claims from more than one policy.
> CAPT-1709: Output shortened policy names in the payroll file

- app/assets/stylesheets/components/school_search.scss
- https://dfedigital.atlassian.net/browse/CAPT-529
- Issue with font styling on school search results on iOS
- Target css to use `govuk-body` instead of fallback font which looks like times new roman
- Should probably be fixed upstream but is quickly fixed here for now
> [CAPT-529] style font for result number in search results

- app/controllers/claims_form_callbacks.rb
- app/controllers/concerns/journey_concern.rb
- app/forms/personal_details_form.rb
- app/models/claim_journey_session_shim.rb
- app/models/claim_student_loan_details_updater.rb
- app/models/journeys/additional_payments_for_teaching/answers_student_loans_details_updater.rb
- app/models/journeys/answers_student_loans_details_updater.rb
- app/models/journeys/session_answers.rb
- app/models/journeys/teacher_student_loan_reimbursement/answers_student_loans_details_updater.rb
- app/models/student_loans_data_presenter.rb
- app/views/student_loans/claims/student_loan_amount.html.erb
- spec/features/changing_answers_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/forms/personal_details_form_spec.rb
- spec/models/claim_student_loan_details_updater_spec.rb
- spec/requests/claims_spec.rb
Probably slightly easier to review both commits separately
Set student loans on session
There's a call back that sets student loans data on the claim, we need
to change this to set the student loans data on the session. The
ClaimStudentLoanDetailsUpdater is also used for setting data on
submitted claims so we've introduced an answers specific version and a
presenter class to share the data between the claim and answers
versions.
> CAPT 1697/set student loans data on answers

- app/forms/current_school_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/claim_school_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/select_claim_school_form.rb
- app/models/journeys/additional_payments_for_teaching/claim_journey_session_shim.rb
- app/models/journeys/additional_payments_for_teaching/slug_sequence.rb
- app/models/journeys/page_sequence.rb
- app/views/additional_payments/claims/_ineligibility_current_school.html.erb
- app/views/student_loans/claims/_ineligibility_reason_ineligible_current_school.html.erb
- spec/factories/journeys/additional_payments_for_teaching/session_answers.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/ineligible_levelling_up_premium_payments_spec.rb
- spec/features/reminders_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/forms/current_school_form_spec.rb
- spec/forms/journeys/additional_payments_for_teaching/eligible_itt_subject_form_spec.rb
- spec/models/journeys/additional_payments_for_teaching/slug_sequence_spec.rb
As the current school form has been migrated to write the current
school id to the session answers we want to make sure all references to
the current school use the session answers rather than the current
claim.
> Make sure references to current school use answers

- app/forms/journeys/additional_payments_for_teaching/qualification_details_form.rb
- app/forms/journeys/additional_payments_for_teaching/teaching_subject_now_form.rb
- spec/forms/journeys/additional_payments_for_teaching/qualification_details_form_spec.rb
The qualification details form should no longer need to set any
attributes on the claim or eligibility
> Clean up refernces ot current claim

- .rspec_parallel
- app/forms/journeys/additional_payments_for_teaching/poor_performance_form.rb
- app/models/journeys/additional_payments_for_teaching/answers_presenter.rb
- app/models/journeys/additional_payments_for_teaching/claim_journey_session_shim.rb
- spec/forms/journeys/additional_payments_for_teaching/poor_performance_form_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1647
- The `poor_performance` form now persists answers to journey session rather than eligibility
- Update references to these fields on answers rather than on eligbility
- Also added `.rspec_parallel` with configuration that should increase local test run times for those that run the test suite in parallel
> [CAPT-1647] Port poor performance to journey session

- app/models/concerns/journeys/sessions/teacher_id.rb
- app/models/journeys/additional_payments_for_teaching/answers_presenter.rb
- app/models/journeys/additional_payments_for_teaching/session_answers.rb
- app/models/journeys/base.rb
- app/models/journeys/base_answers_presenter.rb
- app/models/journeys/session_answers.rb
- app/models/journeys/teacher_student_loan_reimbursement/answers_presenter.rb
- app/models/policies/student_loans/admin_tasks_presenter.rb
- app/models/policies/student_loans/eligibility_admin_answers_presenter.rb
- app/models/policies/student_loans/presenter_methods.rb
- app/views/additional_payments/claims/check_your_answers.html.erb
- app/views/additional_payments/claims/check_your_answers_part_one.html.erb
- app/views/student_loans/claims/check_your_answers.html.erb
- spec/factories/journeys/teacher_student_loan_reimbursement/session_answers.rb
- spec/features/changing_answers_spec.rb
- spec/models/journeys/additional_payments_for_teaching/answers_presenter_spec.rb
- spec/models/journeys/teacher_student_loan_reimbursement/answers_presenter_spec.rb
- spec/models/student_loans/presenter_methods_spec.rb
- spec/requests/submissions_spec.rb
- spec/support/journey_answers_presenter_shared_examples.rb
Removes claim from answers presenter
Updates the answers presenters to no londer reference the claim.
Had to make a shared base branch with Ken and Phil's latest work, once that's
merged can rebase this onto master, so for the time being it's best to **review
just the[ last commit in this pr](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2841/commits/2ddcabe4a55400a83347e901c782969c82fc9488).**
> CAPT 1718/dont reference claim in answers presenter

- .github/dependabot.yml
- Partially related to https://dfedigital.atlassian.net/browse/CAPT-1456
- We want to keep container packages up-to-date
- Once we're up-to-date slowly and naturally with dependabot doing the heavy lifting we can close off that ticket  
- Also check github actions while we're at it
> [CAPT-1456] More dependabot

- app/controllers/claims_controller.rb
- app/models/journeys/additional_payments_for_teaching/slug_sequence.rb
- app/models/journeys/base.rb
- app/models/journeys/page_sequence.rb
- app/models/journeys/teacher_student_loan_reimbursement/slug_sequence.rb
- spec/features/admin_claim_tasks_update_with_dqt_api_spec.rb
- spec/features/auto_populating_home_address_from_postcode_search_spec.rb
- spec/features/changing_answers_spec.rb
- spec/features/claim_journey_does_not_get_cached_spec.rb
- spec/features/claim_with_mobile_sms_otp_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/early_career_payments_eligible_now_reminder_set_spec.rb
- spec/features/ineligible_early_career_payments_in_2022_and_future_years_spec.rb
- spec/features/levelling_up_premium_payments_content_change_logic_spec.rb
- spec/features/one_time_password_spec.rb
- spec/features/reminders_spec.rb
- spec/features/subject_teaching_question_spec.rb
- spec/features/validating_user_contact_details_spec.rb
- spec/forms/form_spec.rb
- spec/models/journeys/additional_payments_for_teaching/slug_sequence_spec.rb
- spec/models/journeys/additional_payments_for_teaching_spec.rb
- spec/models/journeys/page_sequence_spec.rb
- spec/models/journeys/teacher_student_loan_reimbursement/slug_sequence_spec.rb
- spec/models/journeys/teacher_student_loan_reimbursement_spec.rb
- spec/requests/claims_spec.rb
- spec/requests/timeout_spec.rb
- spec/support/eligible_later_shared_examples.rb
- spec/support/feature_helpers.rb
- spec/support/request_helpers.rb
Removes references to the claim from the page sequence (first commit) and slug
sequence (second commit)
> CAPT 1721/remove claim from slug sequence

- app/forms/form.rb
- app/forms/journeys/additional_payments_for_teaching/nqt_in_academic_year_after_itt_form.rb
Looks like these methods weren't cleaned up when how we handle back
links was changed
Backlinks are now set by https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/master/app/controllers/claims_form_callbacks.rb
> Remove unused methods

- app/views/layouts/application.html.erb
- My understanding is that the backlink should not be within `<main>` and should sit before it
- See https://design-system.service.gov.uk/styles/page-template/
- Incidentally this also fixes the fact that is no longer oddly located
> Move backlink out of main

- Gemfile
- Gemfile.lock
- app/views/additional_payments/landing_page.html.erb
- config/application.rb
- Introduce GOVUK components which simplifies things
- We'll soon be adding new journeys and content adding this library now should make life easier 
- Add and setup GOVUK components gem
- Change some links and a use of details component as an example
> Introduce GOVUK components

- Makefile
- global_config/production.sh
Create the base resources for the AKS prod env
https://trello.com/c/XaZrMMuy/1876-claim-create-prod-base-resources 
Validate with
make production-aks validate-arm-resources
> Create aks prod env base resources

- app/controllers/claims_controller.rb
- spec/features/backlink_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1731
- When hitting the `ClaimsController` with a form submission, if there is an error the back link is missing
- back link is generated on form `show` and `update`
> [CAPT-1731] Fix missing back link

- app/helpers/govuk_form_helper.rb
- app/views/additional_payments/reminders/_one_time_password.html.erb
- app/views/additional_payments/reminders/personal_details.html.erb
- spec/features/reminders_spec.rb
- spec/features/trainee_teacher_subjourney_for_lup_schools_spec.rb
- spec/helpers/govuk_form_helper_spec.rb
- Remove `GovukFormHelper#css_classes_for_select` which was never used anywhere
- Use `GOVUKDesignSystemFormBuilder::FormBuilder` for reminder journey forms
- Swap out any custom code to use GOVUK formbuilder
- Use GOVUK components where applicable
- Bonus: one page had multiple `h1`s, this has now been fixed
> [CAPT-1729] Form tweaks to reminders journey

- app/views/claims/sign_in_or_continue.html.erb
- app/views/shared/_backlink.html.erb
- The DfE identity sign in page is not quite right
- Use GOVUK component for back link
- Removed duplicated nested `<main>` in sign in page
- Use the back link in layout rather than in view to fix visual issues
- Removed superfluous mark up on the page if there are no errors
> Fix DfE identity sign in page

- app/views/claims/personal_details.html.erb
- spec/features/combined_teacher_claim_journey_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/hmrc_bank_validation_spec.rb
- spec/features/ineligible_student_loans_claims_spec.rb
- spec/features/levelling_up_premium_payments_spec.rb
- spec/features/student_loans_claim_spec.rb
- Use `GOVUKDesignSystemFormBuilder::FormBuilder` for personal details form
- Bonus: use smart quotes where applicable
> [CAPT-1729] Use GOVUK formbuilder for personal details form

- app/helpers/claims/show_helper.rb
- app/views/claims/address.html.erb
- spec/features/auto_populating_home_address_from_postcode_search_spec.rb
- spec/features/combined_teacher_claim_journey_spec.rb
- spec/features/combined_teacher_claim_journey_with_teacher_id_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/hmrc_bank_validation_spec.rb
- spec/features/levelling_up_premium_payments_spec.rb
- spec/helpers/claims/show_helper_spec.rb
- spec/support/feature_helpers.rb
- Use `GOVUKDesignSystemFormBuilder::FormBuilder` for address search form
- Bonus: removed helper `#heading_css_class_for_journey` as didn't seem to offer any visible difference to the page which makes one thing simpler
- Updated tests to target fields via labels rather than their `id`
> [CAPT-1729] Use GOVUK formbuilder for address form

- app/views/claims/mobile_number.html.erb
- spec/features/changing_answers_spec.rb
- spec/features/claim_with_mobile_sms_otp_spec.rb
- spec/features/combined_teacher_claim_journey_with_teacher_id_check_mobile_spec.rb
- spec/features/tslr_claim_journey_with_teacher_id_check_mobile_spec.rb
- Use `GOVUKDesignSystemFormBuilder::FormBuilder` for mobile number form
- I've made the question size `xl`, there use to be toggle depending on which journey the user was on but not sure why you would change the font size based off the question
- Updated tests to target fields via labels rather than their `id`
> [CAPT-1729] Use GOVUK formbuilder for mobile number form

- app/views/claims/_account_details.html.erb
- app/views/claims/building_society_account.html.erb
- app/views/claims/personal_bank_account.html.erb
- Use `GOVUKDesignSystemFormBuilder::FormBuilder` for payment details form
- I've made the question size `l`, there use to be toggle depending on which journey the user was on but not sure why you would change the font size based off the question
- Use GOVUK components where applicable
> [CAPT-1729] Use GOVUK formbuilder for payment details

- app/views/claims/teacher_reference_number.html.erb
- spec/features/combined_teacher_claim_journey_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/levelling_up_premium_payments_spec.rb
- spec/features/student_loans_claim_spec.rb
- Use `GOVUKDesignSystemFormBuilder::FormBuilder` for TRN form
- I've made the question size `l`, there use to be toggle depending on which journey the user was on but not sure why you would change the font size based off the question
- Use GOVUK components where applicable
> [CAPT-1729] Use GOVUK formbuilder for TRN form

- app/controllers/claims_controller.rb
- app/views/claims/existing_session.html.erb
Noticed this one while checking switching journey to / from IRP
The `current_journey_routing` name shows the name of the journey we're
switching to. We need to take a look at the journey the user came from
which will be the `first` journey session.
Due to how we clear the session when the user starts a new journey there
will only ever be two journey sessions in the `journey_sessions`
collection. In this specific case, on the existing session page, there is
only one journey session in the journey_sessions collection (as the
session for the journey we're considering switching too hasn't been
created, and as such `journey_session` is `nil`)
Looking at the git history I think this has been an issue for a while. As part
of the IRP work I'm adding some regression tests that will catch this but …
> BUGFIX Show the correct name for the previous journey

- .github/workflows/build_and_deploy.yml
- Gemfile
- Gemfile.lock
- bin/smoke
- spec/rails_helper.rb
- spec/smoke/start_a_claim_spec.rb
- spec/support/capybara.rb
We want to be able to run smoke tests on deployed environments.
- Added job to `deploy-test` which runs tests in the spec/smoke folder, tagged with :smoke
- Added basic smoke test
- Excluded smoke tests from regular test runs
In the GitHub repo:
- Added repo secrets for SMOKE_TEST_APP_HOST, BASIC_AUTH_USERNAME, BASIC_AUTH_PASSWORD
I tested the workflow by updating the branch conditions temporarily, this is the smoke test passing:
https://github.com/DFE-Digital/claim-additional-payments-for-teaching/actions/runs/9596133206/job/26462471311?pr=2875
To run the smoke test locally, add SMOKE_TEST_APP_HOST, BASIC_AUTH_USERNAME and BASIC_AUTH_PASSWORD to  your env and run `bundle exec rspec spec/smoke -t smoke:true`
> CAPT-1702 Add smoke test

- app/forms/journeys/get_a_teacher_relocation_payment/claim_submission_form.rb
- app/models/journeys.rb
- app/models/journeys/get_a_teacher_relocation_payment.rb
- app/models/journeys/get_a_teacher_relocation_payment/eligibility_checker.rb
- app/models/journeys/get_a_teacher_relocation_payment/session.rb
- app/models/journeys/get_a_teacher_relocation_payment/session_answers.rb
- app/models/journeys/get_a_teacher_relocation_payment/session_answers_type.rb
- app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
- app/models/policies/international_relocation_payments.rb
- app/models/policies/international_relocation_payments/eligibility.rb
- app/models/policies/international_relocation_payments/policy_eligibility_checker.rb
- app/views/get_a_teacher_relocation_payment/claims/check_your_answers.html.erb
- app/views/get_a_teacher_relocation_payment/landing_page.html.erb
- app/views/get_a_teacher_relocation_payment/submissions/show.html.erb
- config/analytics.yml
- config/locales/en.yml
- config/routes.rb
- db/migrate/20240618143941_create_policies_relocation_payments_eligibilities.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/journey_configurations.rb
- spec/factories/journeys/get_a_teacher_relocation_payment/get_a_teacher_relocation_payment_answers.rb
- spec/factories/policies/international_relocation_payments/eligibilities.rb
- spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
- spec/features/switching_policies_spec.rb
- spec/models/journeys_spec.rb
This commit adds the initial set up for IRP along with a some feature
tests.
So far the IRP journey lets a user click "Start now" and then
shows the check your answers page where they can submit a claim.
The feature test has some temporary hacks, where we update the database
model, this is just required to get the answers in a state that passes
the validations on the claim. We'll be removing the
`teacher_reference_number` question and (probably) the `payroll_gender`
question from the IRP journey but they're currently required to submit a claim.
[follow up PR that adds the first form to the journey](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2886)
> Initial IRP journey wire up

- app/forms/journeys/get_a_teacher_relocation_payment/application_route_form.rb
- app/models/journeys/get_a_teacher_relocation_payment.rb
- app/models/journeys/get_a_teacher_relocation_payment/answers_presenter.rb
- app/models/journeys/get_a_teacher_relocation_payment/session_answers.rb
- app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
- app/views/get_a_teacher_relocation_payment/claims/application_route.html.erb
- app/views/get_a_teacher_relocation_payment/claims/check_your_answers_part_one.html.erb
- config/analytics.yml
- config/locales/en.yml
- db/migrate/20240620084630_add_application_route_to_international_relocation_payments_eligibilities.rb
- db/schema.rb
- spec/factories/journeys/get_a_teacher_relocation_payment/get_a_teacher_relocation_payment_answers.rb
- spec/factories/journeys/get_a_teacher_relocation_payment/session.rb
- spec/features/get_a_teacher_relocation_payment/trainee_route_completing_the_form_spec.rb
- spec/features/switching_policies_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/application_route_form_spec.rb
- spec/models/journeys/get_a_teacher_relocation_payment/answers_presenter_spec.rb
- spec/support/get_a_teacher_relocation_payment/step_helpers.rb
Add application route
Adds the application route question on the irp journey and the check
your answers part one page.
We'll need to handle selecting the "other" option which makes the claim
ineligible but this will be addressed in a future commit.
https://github.com/DFE-Digital/claim-additional-payments-for-teaching/assets/9936028/acde6e57-291f-41d9-bcd0-d086e902e812
[follow up pr that adds eligibility checking](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2888)
> CAPT 1689/irp/application route

- app/forms/journeys/get_a_teacher_relocation_payment/application_route_form.rb
- app/forms/journeys/get_a_teacher_relocation_payment/state_funded_secondary_school_form.rb
- app/forms/journeys/get_a_teacher_relocation_payment/trainee_details_form.rb
- app/models/journeys/get_a_teacher_relocation_payment.rb
- app/models/journeys/get_a_teacher_relocation_payment/answers_presenter.rb
- app/models/journeys/get_a_teacher_relocation_payment/session_answers.rb
- app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
- app/models/policies/international_relocation_payments/policy_eligibility_checker.rb
- app/views/get_a_teacher_relocation_payment/claims/state_funded_secondary_school.html.erb
- app/views/get_a_teacher_relocation_payment/claims/trainee_details.html.erb
- config/analytics.yml
- config/locales/en.yml
- db/migrate/20240620085756_add_state_funded_secondary_school_to_international_relocation_payments_eligibilities.rb
- db/schema.rb
- spec/factories/journeys/get_a_teacher_relocation_payment/get_a_teacher_relocation_payment_answers.rb
- spec/features/get_a_teacher_relocation_payment/ineligible_route_completing_the_form_spec.rb
- spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
- spec/features/get_a_teacher_relocation_payment/trainee_route_completing_the_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/application_route_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/state_funded_secondary_school_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/trainee_details_form_spec.rb
- spec/models/journeys/get_a_teacher_relocation_payment/answers_presenter_spec.rb
- spec/support/get_a_teacher_relocation_payment/step_helpers.rb
Adds the next two forms in the IRP journey.
Depending on the application route the user can see two different forms, each
form writes to the same attribute as this is how it's implemented in the IRP
app.
This pr is split into 3 commits, might be easier to review each commit
separately.
https://github.com/DFE-Digital/claim-additional-payments-for-teaching/assets/9936028/3a73da0c-0973-42bb-8a39-7c84433b709f
> CAPT 1689/irp/school details

- app/forms/journeys/get_a_teacher_relocation_payment/application_route_form.rb
- app/forms/journeys/get_a_teacher_relocation_payment/contract_details_form.rb
- app/models/journeys/get_a_teacher_relocation_payment.rb
- app/models/journeys/get_a_teacher_relocation_payment/answers_presenter.rb
- app/models/journeys/get_a_teacher_relocation_payment/session_answers.rb
- app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
- app/models/policies/international_relocation_payments/policy_eligibility_checker.rb
- app/views/get_a_teacher_relocation_payment/claims/contract_details.html.erb
- config/analytics.yml
- config/locales/en.yml
- db/migrate/20240620124504_add_one_year_to_international_relocation_payments_eligibilities.rb
- db/schema.rb
- spec/factories/journeys/get_a_teacher_relocation_payment/get_a_teacher_relocation_payment_answers.rb
- spec/features/get_a_teacher_relocation_payment/ineligible_route_completing_the_form_spec.rb
- spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/application_route_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/contract_details_form_spec.rb
- spec/models/journeys/get_a_teacher_relocation_payment/answers_presenter_spec.rb
- spec/support/get_a_teacher_relocation_payment/step_helpers.rb
Adds the contract details page
The contract details page in IRP write to the `one_year` attribute, so
that's what we've done too.
https://github.com/DFE-Digital/claim-additional-payments-for-teaching/assets/9936028/2558c37a-87b4-4049-8ef6-4beb1ff14739
> CAPT 1689/irp/contract details

- app/forms/journeys/additional_payments_for_teaching/eligibility_confirmed_form.rb
- app/views/additional_payments/claims/_eligibility_confirmed_multiple.html.erb
- app/views/additional_payments/claims/eligibility_confirmed.html.erb
- Ultimate goal is to use GovukFormBuilder to simplify forms
- Use `GOVUKDesignSystemFormBuilder::FormBuilder` for multiple eligibility form
> [CAPT-1729] Use GOVUK formbuilder for multiple eligibility

- app/views/claims/_one_time_password.html.erb
- spec/features/changing_answers_spec.rb
- spec/features/claim_with_mobile_sms_otp_spec.rb
- spec/features/combined_teacher_claim_journey_spec.rb
- spec/features/combined_teacher_claim_journey_with_teacher_id_check_mobile_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/hmrc_bank_validation_spec.rb
- spec/features/levelling_up_premium_payments_spec.rb
- spec/features/one_time_password_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/features/tslr_claim_journey_with_teacher_id_check_mobile_spec.rb
- Use `GOVUKDesignSystemFormBuilder::FormBuilder` for OTP form
> [CAPT-1729] Use GOVUK formbuilder for one time password form

- .github/workflows/build_and_deploy.yml
Stop specifying the ruby version in the deploy workflow. If it conflicts, it breaks the deploy.
The workflow should pick it up from `.ruby-version` file.
This is the same as in the ci workflow: https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/master/.github/workflows/ci.yaml#L16-L19
> Fix deploy workflow

- app/forms/journeys/get_a_teacher_relocation_payment/application_route_form.rb
- app/forms/journeys/get_a_teacher_relocation_payment/start_date_form.rb
- app/models/journeys/get_a_teacher_relocation_payment.rb
- app/models/journeys/get_a_teacher_relocation_payment/answers_presenter.rb
- app/models/journeys/get_a_teacher_relocation_payment/session_answers.rb
- app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
- app/models/policies/international_relocation_payments/eligibility.rb
- app/views/get_a_teacher_relocation_payment/claims/start_date.html.erb
- config/analytics.yml
- config/locales/en.yml
- db/migrate/20240621152642_add_start_date_to_international_relocation_payments_eligibilities.rb
- db/schema.rb
- spec/factories/journeys/get_a_teacher_relocation_payment/get_a_teacher_relocation_payment_answers.rb
- spec/features/get_a_teacher_relocation_payment/ineligible_route_completing_the_form_spec.rb
- spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
- spec/features/get_a_teacher_relocation_payment/trainee_route_completing_the_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/application_route_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/start_date_form_spec.rb
- spec/models/journeys/get_a_teacher_relocation_payment/answers_presenter_spec.rb
- spec/support/get_a_teacher_relocation_payment/step_helpers.rb
Adds the form to capture the start date. Of note is the use of `_assign_attributes`. ActiveModel doesn't support multi part parameters so we need to include `ActiveRecord::AttributeAssignment` to get them. This behaviour should probably be upstreamed We may want to upstream this behaviour into the base Form class though changing the attribute assignment in the base form to support this felt out of scope of this commit.
Also this commit doesn't add the eligibility checking for invalid contract dates. We're waiting on the product team to get back to us with what this should be. When they have we'll enable the feature tests for the ineligibility.
https://github.com/DFE-Digital/claim-additional-payments-for-teaching/assets/9936028/26ac7c4f-885d-435b-b9e0-50d941d839e0
> CAPT-1689 Add start date form

- app/views/claims/existing_session.html.erb
- Refactor forms to use GOVUK formbuilder
- Update `existing sessions` page to use GOVUK form builder
> [CAPT-1729] use GOVUK formbuilder for existing session form

- app/views/claims/gender.html.erb
- Refactor forms to use GOVUK formbuilder
- Update `payroll gender` form to use GOVUK formbuilder
- Use smart quotes applicable
- Due to the divider it is not possible to pass a data structure to create radio buttons and must be crafted by hand
> [CAPT-1729] Use GOVUK formbuilder for gender form

- app/forms/journeys/get_a_teacher_relocation_payment/entry_date_form.rb
- app/models/journeys/get_a_teacher_relocation_payment.rb
- app/models/journeys/get_a_teacher_relocation_payment/answers_presenter.rb
- app/models/journeys/get_a_teacher_relocation_payment/session_answers.rb
- app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
- app/models/policies/international_relocation_payments/policy_eligibility_checker.rb
- app/views/get_a_teacher_relocation_payment/claims/entry_date.html.erb
- config/analytics.yml
- config/locales/en.yml
- db/migrate/20240621200501_add_date_of_entry_to_international_relocation_payments_eligibilities.rb
- db/schema.rb
- spec/factories/journeys/get_a_teacher_relocation_payment/get_a_teacher_relocation_payment_answers.rb
- spec/features/get_a_teacher_relocation_payment/ineligible_route_completing_the_form_spec.rb
- spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/entry_date_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/start_date_form_spec.rb
- spec/models/journeys/get_a_teacher_relocation_payment/answers_presenter_spec.rb
- spec/support/get_a_teacher_relocation_payment/step_helpers.rb
Adds the entry date form
As in claim the entry date form writes to the date_of_entry attribute.
We also reset the date of entry if the start date changes as the
eligibility calculation for date of entry depends on the start date.
Of note there doesn't seem to be a validation in claim that the date of
entry isn't _after_ the start date of the contract. I'm not sure if
that's a business rule we want to enforce or not. There is a validation
that the date of entry isn't in the future.
> CAPT 1689/irp/entry date

- app/models/concerns/eligibility_checkable.rb
- app/models/concerns/policies/early_career_payments/eligible.rb
- app/models/journeys/additional_payments_for_teaching/slug_sequence.rb
- app/models/policies/early_career_payments.rb
- app/models/policies/early_career_payments/eligibility.rb
- app/models/policies/levelling_up_premium_payments.rb
- app/models/policies/levelling_up_premium_payments/eligibility.rb
- app/views/additional_payments/claims/_ineligibility_ecp_only_induction_not_completed.html.erb
- app/views/additional_payments/claims/_ineligibility_trainee_in_last_policy_year.html.erb
- lib/ineligibility_reason_checker.rb
- spec/factories/journeys/additional_payments_for_teaching/session_answers.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/models/early_career_payments_spec.rb
- spec/models/levelling_up_premium_payments_spec.rb
- spec/models/policies/early_career_payments/policy_eligibility_checker_spec.rb
The rationale for the changes is explained in the commits; in short, we do have the concept of start/end date for ECP (and LUP), but it's used as a "combined" value in the `EligibilityCheckable` concern... this is a problem when the end year of a particular policy affects the eligibility criteria for that policy only (like with the induction question).
https://dfedigital.atlassian.net/browse/CAPT-1419
Needs manual testing
> CAPT-1419 ECP exit screen showing incorrect text for AY24-25 (when induction not completed)

- app/forms/form.rb
- app/forms/journeys/further_education_payments/subjects_taught_form.rb
- app/models/journeys/further_education_payments.rb
- app/models/journeys/further_education_payments/session_answers.rb
- app/models/journeys/further_education_payments/slug_sequence.rb
- app/views/further_education_payments/claims/subject_areas.html.erb
- app/views/further_education_payments/claims/subjects_taught.html.erb
- config/locales/en.yml
- spec/features/further_education_payments/happy_js_path_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/forms/journeys/further_education_payments/subjects_taught_form_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-551
- Add subject areas form to FE journey
- Added subject areas form to FE journey
- Added `form#t` to aid in translations on forms
- From what I can tell this is actually the first use of checkboxes in any of the existing journeys and was not supported out of the box
- The issue was around strong parameters and how permitted attributes were whitelisted. In order to `permit` a collection it must be passed `attribute_name: []` and not just `attribute_name` which was the prior implementation
- A collection is discerned with the default value of `[]` which is probably sufficient for our current needs. If this needs to be more robust we'll need to register a custom type eg:
```
ActiveModel::Type::Collection # does not exist and we'd have …
```
> [LUPEYALPHA-551] Add subject areas to FE journey

- app/controllers/claims_controller.rb
- spec/features/switching_policies_spec.rb
Previously if a claimant started a journey then visited the landing page
for that journey and choose to continue with their existing session we'd
throw an error. The `other_journey_sessions` array contains the journey
sessions for the other journeys, which if you're still on the same
journey would be empty, so we need to check the current journey session
(the session for the journey we're currently on).
How we handle managing which journey you're on is subtle and spread
across many places in the controllers / concerns, the overall approach
likely needs revisiting.
https://github.com/DFE-Digital/claim-additional-payments-for-teaching/assets/9936028/2d71a455-5f6f-4f1b-9aca-6ec26d834659
https://github.com/DFE-Digital/claim-additional-payments-for-teaching/assets/9936028/2a4fbf42-ae5d-43a4-b46 …
> Fix visiting landing page for same journey

- app/forms/journeys/get_a_teacher_relocation_payment/employment_details_form.rb
- app/models/journeys/get_a_teacher_relocation_payment.rb
- app/models/journeys/get_a_teacher_relocation_payment/answers_presenter.rb
- app/models/journeys/get_a_teacher_relocation_payment/session_answers.rb
- app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
- app/views/get_a_teacher_relocation_payment/claims/check_your_answers.html.erb
- app/views/get_a_teacher_relocation_payment/claims/employment_details.html.erb
- config/analytics_blocklist.yml
- config/locales/en.yml
- db/migrate/20240625135618_add_employment_details_to_international_relocation_payments_eligibilities.rb
- db/schema.rb
- spec/factories/journeys/get_a_teacher_relocation_payment/get_a_teacher_relocation_payment_answers.rb
- spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/employment_details_form_spec.rb
- spec/models/journeys/get_a_teacher_relocation_payment/answers_presenter_spec.rb
- spec/support/get_a_teacher_relocation_payment/step_helpers.rb
Add employment details form
Adds the employment details page as per IRP. We've named the fields the
same as in IRP. We could probably provide a school search box for this
but that's something for a future iteration.
Have also added the school details to the PII section to be on the safe
side as they might be enough to identify an claimant in combination with
some of the other non pii answers.
> CAPT 1689/irp/employment information

- spec/forms/journeys/get_a_teacher_relocation_payment/claim_submission_form_spec.rb
Add smoke test
Adds a smoke test to ensure the expect attributes for the journey are
written to the claim and eligibility.
> CAPT 1689/irp/claim submission form

- app/models/journeys/get_a_teacher_relocation_payment/answers_presenter.rb
- app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
- spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/claim_submission_form_spec.rb
- spec/support/get_a_teacher_relocation_payment/step_helpers.rb
Remove TRN step
We don't want to ask for a TRN on the IRP journey. We previously asked
for it as it was required to submit a claim. Now TRN is no longer a
required field on the claim we can drop the TRN step from the IRP
journey.
> CAPT 1740/remove trn from irp

- app/forms/journeys/get_a_teacher_relocation_payment/start_date_form.rb
- config/locales/en.yml
- spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/start_date_form_spec.rb
Don't allow future dates for start date
IRP feedback from Richard Forrest
>  I am able to enter a contract start date in the future although I can't
>  enter a travel date in the future. Can both these fields only accept
>  dates in the past?
Updates the start date form to not permit dates in the future.
> CAPT 1742/dont allow future start dates

- app/models/school_data_importer.rb
- config/analytics.yml
- db/migrate/20240627114644_add_ukprn_to_schools.rb
- db/schema.rb
- spec/models/school_data_importer_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-606
- Store `UKPRN` when doing GIAS import so we can identify which schools/colleges are eligible for FELUP downstream
- I've moved the location of the spec file to mirror the location of the actual file it tests against
- Added migration to hold `UKPRN` against `school`
- Updated `SchoolDataImporter` to now also store the UKPRN
- Update `dfe analytics` to support new db column
> [LUPEYALPHA-606] GIAS import also stores UKPRN

- app/assets/javascripts/components/college_search.js.erb
- app/controllers/school_search_controller.rb
- app/forms/journeys/further_education_payments/select_provision_form.rb
- app/models/school.rb
- app/views/further_education_payments/claims/further_education_provision_search.html.erb
- spec/factories/schools.rb
- spec/features/further_education_payments/happy_js_path_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/models/school_spec.rb
- spec/requests/school_search_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-545
- Missing part of FE journey where school search should only return FE bodies
- School search backend now capable of returning FE bodies only
- This is based of `PhaseOfEducation` is `16 plus` this is encoded as `6` 
- Wired up FE journey to this so only return FE bodies
> [LUPEYALPHA-545] FE journey school search only returns FE bodies

- app/forms/journeys/further_education_payments/contract_type_form.rb
- app/models/journeys/further_education_payments.rb
- app/models/journeys/further_education_payments/session_answers.rb
- app/views/further_education_payments/claims/contract_type.html.erb
- config/locales/en.yml
- spec/factories/journeys/further_education_payments/session_answers.rb
- spec/features/further_education_payments/happy_js_path_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/forms/journeys/further_education_payments/contract_type_form_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-546
- Add contract type to FE journey
- Added contract type form to FE journey handling happy path only
- I've tweaked the wire frames and moved some copy from radio labels to hint texts
- validation handled
- out of scope: eligibility and determine what the next page is
> [LUPEYALPHA-546] Add FE contract type

- app/models/academic_year.rb
- app/models/policies/international_relocation_payments/eligibility.rb
- app/models/policies/international_relocation_payments/policy_eligibility_checker.rb
- spec/features/get_a_teacher_relocation_payment/ineligible_route_completing_the_form_spec.rb
- spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
- spec/models/academic_year_spec.rb
- spec/models/policies/international_relocation_payments/policy_eligibility_checker_spec.rb
We want to reject claimants if their contract start date is earlier than
6 months before the autumn term. This commit updates the eligibility
checker to do so and also adds some missing tests.
https://github.com/DFE-Digital/claim-additional-payments-for-teaching/assets/9936028/2ac61505-a9a7-4d84-9990-403650dc26ec
> Add eligibility check for contract start date

- app/forms/journeys/further_education_payments/further_education_teaching_start_year_form.rb
- app/models/journeys/further_education_payments.rb
- app/models/journeys/further_education_payments/session_answers.rb
- app/models/journeys/further_education_payments/slug_sequence.rb
- app/views/further_education_payments/claims/academic_year_in_further_education.html.erb
- app/views/further_education_payments/claims/further_education_teaching_start_year.html.erb
- config/locales/en.yml
- spec/features/further_education_payments/happy_js_path_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/forms/journeys/further_education_payments/further_education_teaching_start_year_form_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-550
- Added academic start year for FE journey
- Added which academic year started teaching FE in FE journey
- I've tweaked the slug so it is more descriptive
> [LUPEYALPHA-550] Add academic start year form for FE journey

- app/jobs/purge_unsubmitted_claims_job.rb
- app/models/journeys/session.rb
- spec/jobs/purge_unsubmitted_claims_job_spec.rb
Now we only create a claim once the claimant has completed the journey
we need to update the purge job to work on journey sessions rather than
claims as all claims are submitted claims.
> Purge unsubmitted journey sessions

- app/forms/journeys/further_education_payments/teaching_qualification_form.rb
- app/models/journeys/further_education_payments.rb
- app/models/journeys/further_education_payments/session_answers.rb
- app/models/journeys/further_education_payments/slug_sequence.rb
- app/views/further_education_payments/claims/qualification.html.erb
- app/views/further_education_payments/claims/teaching_qualification.html.erb
- config/locales/en.yml
- spec/features/further_education_payments/happy_js_path_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/forms/journeys/further_education_payments/teaching_qualification_form_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-554
- Add teaching qualification form to FE journey
> [LUPEYALPHA-554] add teaching qualification form to FE journey

- app/forms/journeys/further_education_payments/ineligible_form.rb
- app/models/journeys/further_education_payments.rb
- app/models/journeys/further_education_payments/eligibility_checker.rb
- app/models/policies/further_education_payments/policy_eligibility_checker.rb
- app/views/further_education_payments/claims/_ineligible_lack_teaching_responsibilities.html.erb
- app/views/further_education_payments/claims/ineligible.html.erb
- spec/features/further_education_payments/ineligible_paths_spec.rb
- spec/models/policies/further_education_payments/policy_eligibility_checker_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-615
- For FE journey add ineligible path when user lacks teaching responsibility
- Added new ineligible page
- This is the first ineligible page for this journey so some plumbing was required to set everything up
> [LUPEYALPHA-615] FE journey handle ineligible as lack teaching

- app/forms/journeys/further_education_payments/check_your_answers_form.rb
- app/forms/journeys/further_education_payments/eligible_form.rb
- app/models/journeys/further_education_payments.rb
- app/models/journeys/further_education_payments/slug_sequence.rb
- app/views/further_education_payments/claims/check_your_answers.html.erb
- app/views/further_education_payments/claims/eligible.html.erb
- spec/features/further_education_payments/happy_js_path_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-557
- Add eligible page to FE journey
- Added eligible page to FE journey
- This page has a placeholder for the award amount which is yet to be implemented
- I had to add some placeholder code for the check your answers bit so able to get to the eligible page
> [LUPEYALPHA-557] Add eligible page to FE journey

- terraform/domains/environment_domains/config/production.tfvars.json
- terraform/domains/environment_domains/config/production_Terrafile
- terraform/domains/environment_domains/config/test.tfvars.json
- terraform/domains/environment_domains/config/test_Terrafile
- terraform/domains/environment_domains/main.tf
- terraform/domains/environment_domains/terraform.tf
- terraform/domains/environment_domains/variables.tf
Terraform code and configuration for the test and production domains
Check both domains:
- https://claim-additional-teaching-payment.service.gov.uk/
- https://test.claim-additional-teaching-payment.service.gov.uk/
Check DNS zone claim-additional-teaching-payment.service.gov.uk and front door s189p01-capt-dom-fd
Check https://claim-additional-teaching-payment.service.gov.uk/admin/ redirects to
https://www.claim-additional-teaching-payment.service.gov.uk/admin/ using front door (HTTP 308)
> [1750] DNS configuration for test and production domains

- app/models/journeys/get_a_teacher_relocation_payment/answers_presenter.rb
- app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
- app/models/policies/international_relocation_payments/policy_eligibility_checker.rb
- spec/factories/journeys/get_a_teacher_relocation_payment/get_a_teacher_relocation_payment_answers.rb
- spec/features/get_a_teacher_relocation_payment/ineligible_route_completing_the_form_spec.rb
- spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
- spec/models/journeys/get_a_teacher_relocation_payment/answers_presenter_spec.rb
- spec/models/policies/international_relocation_payments/policy_eligibility_checker_spec.rb
Only treat state funded secondary schools as eligible.
IRPs is only available for state funded secondary schools.
The first commit in this PR updates the eligibility check to look at the type
of school the claimant has selected.
The second commit moves the school select page into the eligibility section of
the journey.
> CAPT 1753/only show state secondary schools

- app/models/claim_checking_tasks.rb
- spec/factories/policies/international_relocation_payments/eligibilities.rb
We want to allow the existing payroll tasks to the IRP journeys in the
admin.
I opted to remove the early return for the IRP task list in order to
avoid duplicating logic around displaying the payroll tasks.
> Add the payroll admin tasks for IRP

- config/locales/en.yml
We were missing a translation for the matching details task
> Fix missing translation

- app/forms/journeys/further_education_payments/teaching_hours_per_week_next_term_form.rb
- app/models/journeys/further_education_payments.rb
- app/models/journeys/further_education_payments/session_answers.rb
- app/models/journeys/further_education_payments/slug_sequence.rb
- app/models/policies/further_education_payments/policy_eligibility_checker.rb
- app/views/further_education_payments/claims/_ineligible_teaching_less_than_2_5.html.erb
- app/views/further_education_payments/claims/_ineligible_teaching_less_than_2_5_next_term.html.erb
- app/views/further_education_payments/claims/teaching_hours_per_week_next_term.html.erb
- config/locales/en.yml
- spec/features/further_education_payments/happy_path_spec.rb
- spec/features/further_education_payments/ineligible_paths_spec.rb
- spec/forms/journeys/further_education_payments/teaching_hours_per_week_next_term_form_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-639
- Handle unhappy paths for teaching hour pages for FE journey
- Added new page to capture teaching hours for next term if user is not on a permanent contract
- Although technically you could store as a boolean due the way the question is structured i think storing as a string is far more flexible should they decide to change the question from a simple yes/no answer
> [LUPEYALPHA-639] Add unhappy teaching hours paths to FE journey

- .github/workflows/database_backup.yml
- Add backup database workflow via GitHub Actions
- Uses this DfE GitHub Action: https://github.com/DFE-Digital/github-actions/blob/master/backup-postgres/README.md
- Schedule to run at 3am nightly (disabled until after migration), or via manual workflow dispatch
> CAPT-1762 Add database backup workflow

- .github/workflows/database_restore.yml
By default the workflow only uses today's backup. This change allows passing another file name as input
See successful run: https://github.com/DFE-Digital/claim-additional-payments-for-teaching/actions/runs/9940315003
> [1914] Override backup file name in restore workflow

- terraform/application/config/production_app_env.yml
As part of the AKS migration, redirect production DfE Sign-in to www directly.
> Upate DfE Sign-in redirect URL

- .github/workflows/database_backup.yml
Now that we're migrated the production database, run the database backup workflow nightly at 3:00 UTC.
> Migration - Enable nightly db backups

- spec/smoke/visit_admin_spec.rb
The smoke test was failing when the service was open.
Visiting the admin should pass whether or not the service is open / closed.
> Migration - fix smoke test

- db/seeds.rb
- Originally https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2988 but made a new PR has review app failed plus changes deploy mechanism meant a different approach has been taken
- When review apps are created we currently do not import schools from GIAS
- Importing schools from GIAS aids in the review process with less managing of custom seeds especially for FE journey where specific colleges will be eligible
- When a review app spins up as part of the seeding process also enqueue `SchoolDataImporterJob` which the worker will pick up to import schools from GIAS
- Tested on the deployed review app
> Enqueue school import job when seeding

- .github/workflows/build_and_deploy.yml
Attempt smoke test fix.
Our smoke tests are failing in the test environment _we think_ because it hits a redirect and capybara is not passing through the basic auth creds.
```
SMOKE_TEST_APP_HOST="https://claim-additional-payments-for-teaching-test-web.test.teacherservices.cloud/" BASIC_AUTH_USERNAME={username} BASIC_AUTH_PASSWORD={password} bundle exec rspec spec/smoke -t smoke:true -b
..fails..
SMOKE_TEST_APP_HOST="https://test.claim-additional-teaching-payment.service.gov.uk/" BASIC_AUTH_USERNAME={username} BASIC_AUTH_PASSWORD={password} bundle exec rspec spec/smoke -t smoke:true -b
..passes..
```
In this PR we're pulling the `SMOKE_TEST_APP_HOST` from the github repo variables rather than using the output from terraform.
> Smoke tests - set smoke test host directly

- app/forms/form_helpers.rb
- app/models/journeys/further_education_payments/session_answers.rb
- app/models/policies/further_education_payments/policy_eligibility_checker.rb
- app/views/further_education_payments/claims/_ineligible_courses.html.erb
- app/views/further_education_payments/claims/_ineligible_fe_provider.html.erb
- app/views/further_education_payments/claims/_ineligible_lack_teaching_responsibilities.html.erb
- app/views/further_education_payments/claims/_ineligible_lacks_teacher_qualification_or_enrolment.html.erb
- app/views/further_education_payments/claims/_ineligible_less_than_half_hours_teaching_eligible_courses.html.erb
- app/views/further_education_payments/claims/_ineligible_must_be_recent_further_education_teacher.html.erb
- app/views/further_education_payments/claims/_ineligible_must_teach_at_least_one_term.html.erb
- app/views/further_education_payments/claims/_ineligible_subject.html.erb
- app/views/further_education_payments/claims/_ineligible_subject_to_problematic_actions.html.erb
- app/views/further_education_payments/claims/_ineligible_teaching_less_than_2_5.html.erb
- app/views/further_education_payments/claims/_ineligible_teaching_less_than_2_5_next_term.html.erb
- config/locales/en.yml
- spec/features/further_education_payments/ineligible_paths_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-778
- Add ineligible state for when teaching under half hours on eligible courses
- Tweaked `Form#t` to now accept an array as a key, this just get converted internally to `whatever.the.key.is` which makes the api a bit nicer
- Moved some code from eligibility checker to session answers, which is where i think it belongs better
- Use i18n for the ineligible screens. Could probably extract to reusable wrapper partial but not really much gain for the effort
> [LUPEYALPHA-778] FE journey: add ineligible state when under hours teaching courses

- terraform/application/config/production.tfvars.json
Non prod environment logs are already in Logit.io. They have been validated and we can now ship production logs.
> [1881] Ship production logs to Logit.io

- app/models/claim.rb
- app/views/admin/amendments/new.html.erb
- spec/features/admin_amend_claim_spec.rb
It is expected that many IRP claims will need the address changing so we
want to update the admin interface to allow admins to do this themselves.
> CAPT-1765 - Allow admins to update the address on claims

- spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
- spec/support/get_a_teacher_relocation_payment/step_helpers.rb
This test regularly fails on the select school step, getting stuck on
the school search form. We've added a check to click the continue button
if we're still on the search form and a retry to the spec in case that
goes wrong too.
> Retry flaky test

- .env.development
- .env.test
- app/controllers/omniauth_callbacks_controller.rb
- app/forms/sign_in_form.rb
- app/models/journeys/base.rb
- app/models/journeys/further_education_payments/slug_sequence.rb
- app/models/journeys/session_answers.rb
- app/views/claims/_sign_in.html.erb
- app/views/claims/sign_in.html.erb
- app/views/further_education_payments/claims/one_login_placeholder.html.erb
- app/views/get_a_teacher_relocation_payment/landing_page.html.erb
- config/initializers/omniauth.rb
- config/routes.rb
- spec/factories/journeys/further_education_payments/further_education_payments_answers.rb
- spec/features/further_education_payments/college_not_found_spec.rb
- spec/features/further_education_payments/happy_js_path_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/features/further_education_payments/ineligible_paths_spec.rb
- spec/forms/sign_in_form_spec.rb
- spec/support/feature_helpers.rb
- terraform/application/config/production_app_env.yml
- terraform/application/config/review_app_env.yml
- terraform/application/config/test_app_env.yml
The env var `BYPASS_ONELOGIN_SIGN_IN` is set to`true`,
which means the user will be logged in with email: `user@example.com` and name: `TEST USER`.
(note: the name from One Login currently comes back all capitalised).
This branch is built on top of the changes from https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/3001
> CAPT-1766 one login bypass

- app/models/journeys/session_answers_type.rb
- spec/models/journeys/session_answers_type_spec.rb
Before this change, an `UnknownAttributeError` is raised on any page in the journey, hence breaking the app totally, in the following scenarios:
* we've added an attribute to `Journeys::SessionAnswers`, deployed it, but then want to roll back that deployment
* we want to remove an attribute from `Journeys::SessionAnswers` and deploy that
* for a developer running locally, and having completed journeys locally, switching between branches that have added new attributes
There is a workaround that doesn't involve this change - and that is to purge all journey sessions.
This change would mean that is no longer necessary.
> ignore session answer attributes in the stored JSON that have not been defined on the SessionAnswers class

- app/helpers/admin/claims_helper.rb
- app/models/decision.rb
- app/models/policies/early_career_payments.rb
- app/models/policies/further_education_payments.rb
- app/models/policies/international_relocation_payments.rb
- app/models/policies/levelling_up_premium_payments.rb
- app/models/policies/student_loans.rb
- app/views/admin/decisions/_decision_form.html.erb
- config/locales/en.yml
- spec/factories/decisions.rb
- spec/features/admin_view_claim_spec.rb
- spec/helpers/claim_mailer_helper_spec.rb
- spec/mailers/claim_mailer_spec.rb
- spec/models/decision_spec.rb
Different policies have different rejection reasons. While the rejection
reasons for ECP, LUP, and TSLR are similar (ECP has an extra reason),
future policies (specifically IRP) have different rejection reasons.
This PR moves the available rejection reasons into a constant in the
policy, so new policies can just add their reasons there and update the
locales file.
**Notes for review**
This PR is split into a couple of commits, so probably best reviewed separately. First commit moves the rejection reasons into the policy, second one adds the new rejection reasons for IRP. The store accessor makes this feel a little awkward so I'm open to any different approaches for doing this (could just keep all the rejection reasons in the `Decision` class)
> CAPT-1531 Notify emails

- app/views/further_education_payments/submissions/show.html.erb
- spec/features/further_education_payments/happy_js_path_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-583
- Content for FE confirmation page as claim is submitted
- Reminder button is a placeholder and does not work as designed yet to be completed
- No email is sent yet as yet to be designed
> [LUPEYALPHA-583] FE claim confirmation page

- app/views/further_education_payments/claims/ineligible.html.erb
- spec/features/further_education_payments/ineligible_paths_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-787
- Add missing back links to ineligible screens in FE journey
> [LUPEYALPHA-787] Add back links to FE inelgible screens

- .github/workflows/delete_review_app.yml
We've noticed a lot of old review apps hanging around after PRs are closed/merged.
For all the ones I checked, it was because the 'deploy' label had been removed before closing.
This PR ensures that the review app is deleted if the label is removed.
Add and remove the 'deploy' label
> Delete review apps if PR unlabelled

- app/forms/journeys/early_years_payment/provider/claim_submission_form.rb
- app/forms/journeys/early_years_payment/provider/consent_form.rb
- app/models/journeys/early_years_payment/provider.rb
- app/models/journeys/early_years_payment/provider/session_answers.rb
- app/models/journeys/early_years_payment/provider/slug_sequence.rb
- app/views/early_years_payment/provider/claims/consent.html.erb
- app/views/early_years_payment/provider/landing_page.html.erb
- config/locales/en.yml
- spec/factories/journeys/early_years_payment/provider/session.rb
- spec/features/early_years_payment/provider/happy_path_spec.rb
- spec/forms/journeys/early_years_payment/provider/consent_form_spec.rb
- New `ConsentForm` with presence validation on `:consent_given` attribute
- Form spec and extension of happy path feature test
- Basic `ClaimSubmissionForm` which is required for the page sequence to work - it checks `claim_submittable?`
- We've skipped the email address form for now until we finish the whitelisting work
- Head to the EY landing page (link in review app comment below)
- Click 'Start now'
- Check the declaration of consent page against [the prototype](https://claim-additi-main-9yrds6vyxcsd.herokuapp.com/consent)
- Click 'Continue' with the checkbox unchecked
- Check that you get the correct error message
- Check the checkbox and press 'Continue'
- Check that you progress to the 'current-nursery' page (currently empty)
> [LUPEYALPHA-763] EY Declaration of consent page

- spec/factories/payments.rb
- we have the following deprecation warning
```
DEPRECATION WARNING: Rails 7.0 has deprecated Enumerable.sum in favor of Ruby's native implementation available since 2.4. Sum of non-numeric elements requires an initial argument. (called from block (3 levels) in <top (required)> at /Volumes/git/claim-additional-payments-for-teaching/spec/factories/payments.rb:22)
```
- this change resolves the warning
- the change can be found here https://github.com/rails/rails/pull/42080/files
> Resolve deprecation warning

- config/initializers/dfe_analytics.rb
Per @ericaporter:
> Hi Steve, would you be able to help me set a maintenance window on Claim so that we can do some CMEK encrypting of the Big Query production events table? This is part of the ongoing BQ assurance work, we were able to encrypt all other Claims tables week before last, but we want to stop events streaming to the production tables before we do those.
> Add maintenance window for DfE Analytics

- lib/one_time_password/base.rb
- lib/one_time_password/generator.rb
- lib/one_time_password/validator.rb
- spec/features/one_time_password_spec.rb
- spec/lib/one_time_password/generator_spec.rb
- spec/lib/one_time_password/validator_spec.rb
We need 2 changes to the OTP code for the EY magic link:
* allow OTP code to be validated without having a `generated_at` time.
* allow OTP codes to be generated and verified using a specified secret (because we now are verifying codes generated in a separate session)
> support validating OTP without a generated_at time and with a specified secret

- app/forms/journeys/further_education_payments/claim_submission_form.rb
- config/analytics_blocklist.yml
- db/migrate/20240812123209_add_trn_to_fe_eligibilities.rb
- db/schema.rb
- spec/features/further_education_payments/happy_path_spec.rb
- For FE journey when claim is submitted we need to store optional TRN on the `Policies::FurtherEducationPayments::Eligibility` record
> Persist TRN on eligibility for FE journey

- app/models/name_format_validator.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/claimant_name_form_spec.rb
As per this comment: https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/3092#discussion_r1716900855
We realised that the following special characters were still being allowed in name fields:
```
[]^_`|{}~
```
Update the regex to exclude these characters too.
Business review - are any of these characters supposed to be allowed for any reason?
> Bug - Improve name format regex

- app/controllers/claims_form_callbacks.rb
- app/models/journeys/early_years_payment/provider/start.rb
- app/models/journeys/page_sequence.rb
- app/views/early_years_payment/provider/start/claims/check_your_email.html.erb
- spec/features/early_years_payment/provider/start/happy_path_spec.rb
The notification banner does not show in the normal flow (enter email -> check your email page),
but if the user clicks 'send another link', then the banner shows.
> [LUPEYALPHA-842] EY send another link

- app/controllers/omniauth_callbacks_controller.rb
- We are silently catching an exception and displaying it back to the user
- This was likely debug code and don't want this to happen under normal circumstances
- We want this exception to bubble up and be caught thru usual means
> Remove debug rescue

- .env.development
- .env.test
- app/controllers/omniauth_callbacks_controller.rb
- app/models/one_login/core_identity_validator.rb
- app/models/one_login/did.rb
- app/models/one_login/did_cache.rb
- spec/models/one_login/core_identity_validator_spec.rb
- spec/models/one_login/did_cache_spec.rb
- spec/models/one_login/did_spec.rb
- terraform/application/config/production_app_env.yml
- terraform/application/config/review_app_env.yml
- terraform/application/config/test_app_env.yml
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-851
- One Login uses a public keys which we use to verify certain JWTs
- These public keys are published in a Decentralized Identifier (DID) document
- The keys in this document are prone to rotation therefore must be handled by us to ensure we have the correct keys in place
- See One Login docs for more info https://docs.sign-in.service.gov.uk/integrate-with-integration-environment/prove-users-identity/#validate-the-core-identity-claim-jwt-using-a-public-key
- Remove the hardcoded public key which was held in an environment variable `ONELOGIN_IDENTITY_JWT_PUBLIC_KEY_BASE64`
- Implement a wrapper to hold a DID document
- Implement fetching and caching of DID document, this is cached in memory
- We attempt to respect the caching time …
> [LUPEYALPHA-851] One login DID

- spec/lib/dfe_sign_in/authenticated_session_spec.rb
- spec/support/dfe_sign_in_helpers.rb
Updates the dfe sign in spec helpers to allow setting other attributes
in the auth hash and stubbing different openid connect providers
Extracted from the FE provider work
> Update spec helpers to accept attributes

- app/controllers/concerns/journey_concern.rb
- app/forms/journeys/additional_payments_for_teaching/session_form.rb
- app/forms/journeys/early_years_payment/provider/authenticated/session_form.rb
- app/forms/journeys/early_years_payment/provider/start/session_form.rb
- app/forms/journeys/further_education_payments/session_form.rb
- app/forms/journeys/get_a_teacher_relocation_payment/session_form.rb
- app/forms/journeys/session_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/session_form.rb
On some journeys we'll want to be able to set answers based on url
parameters when starting a journey. This commit adds support for setting
answers when creating a session introducing a journey session form. The
session form is passed the parameters and subclasses of the form permit
various parameters based on their attributes.
---
In the specific case of the further education payments provider journey, the provider starts the journey by following a link with the claim id in it, we need to capture this claim id in the journey session when we create it.
For reference here is the session form for the FE provider journey:
```ruby
module Journeys
module FurtherEducationPayments
module Provider
class SessionForm < Journeys::SessionForm
attribute :claim_id, :string
end
end
end
end
```
--- …
> Pass parameters to sesson creation

- app/helpers/application_helper.rb
- app/models/one_login/config.rb
- app/views/shared/_one_login_header.html.erb
- spec/helpers/application_helper_spec.rb
- For one login integration environment there is a separate `home` or account area
- The One Login home link now sends to integration environment if indeed using integration environment
> Depending on environment link to correct OL home

- app/controllers/omniauth_callbacks_controller.rb
- app/models/one_login/failure_handler.rb
- app/views/omniauth_callbacks/further_education_payments_auth_failure.html.erb
- app/views/omniauth_callbacks/further_education_payments_idv_failure.html.erb
- spec/requests/omniauth_callbacks_controller_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-869
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-870
- Handle failure from One Login auth
- When user is not logged in and there is an auth error from one login show `Sorry, there is a problem with the service` page
- When user is logged in and there is an auth error from one login show `We cannot progress your application` page
- Should be relatively trivial to adapt this to handle EY journey too
- Not all parameters passed in are used, but are available should they be needed by the next person
> [LUPEYALPHA-869] [LUPEYALPHA-870] One login FE failure

- app/forms/journeys/early_years_payment/provider/authenticated/employee_email_form.rb
- app/models/journeys/early_years_payment/provider/authenticated.rb
- app/models/journeys/early_years_payment/provider/authenticated/session_answers.rb
- app/models/journeys/early_years_payment/provider/authenticated/slug_sequence.rb
- app/views/early_years_payment/provider/authenticated/claims/employee_email.html.erb
- config/locales/en.yml
- spec/features/admin/admin_timeout_spec.rb
- spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/employee_email_form_spec.rb
The Employee Email page prompts for an email,
which gets stored as `practitioner_email_address`.
> [LUPEYALPHA-769] practitioner email address

- app/controllers/omniauth_callbacks_controller.rb
- app/models/journeys/session_answers.rb
- app/models/one_login/core_identity_validator.rb
- spec/requests/omniauth_callbacks_controller_spec.rb
- At the moment the One Login UID is not saved in against the record which makes it harder later to marry up accounts
- We also do not check if the user who auth-ed is the same user that passes IDV. This means that potentially one person could auth then use another account to pass IDV.
- After the OL auth callback also save their OL UID
- After their IDV callback ensure UID in this callback matches the UID we saved in the auth step
> One Login save UID + check it

- app/forms/journeys/early_years_payment/provider/authenticated/start_date_form.rb
- config/locales/en.yml
- spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/start_date_form_spec.rb
Validate that the start_date:
- year has four digits, otherwise if the user enters something like 13/1/90 it saves in the database as if it was 13/1/0090
- is not in the future
> Start date validations

- app/forms/journeys/further_education_payments/claim_submission_form.rb
- app/mailers/application_mailer.rb
- app/mailers/claim_mailer.rb
- app/models/journeys/further_education_payments/provider/slug_sequence.rb
- app/models/policies/further_education_payments/eligibility.rb
- spec/forms/journeys/further_education_payments/claim_submission_form_spec.rb
Email the provider
When the claimant submits their application we need to send an email out
to the provider to verify the claim.
This commit adds the mechanism to send the verification email.
Currently we've stubbed the verification deadline, to submission date +
1 week, while we wait on finding out what the actual deadline should be.
We've also set the email template for the claimant email to a,
temporary, empty template so the mailer doesn't error.
> LUPEYALPHA-838 - send verification request to provider

- config/locales/en.yml
- spec/requests/admin_tps_data_upload_spec.rb
change hint on teaching-hours-per-week page from:
> ‘Teaching’ refers to the direct contact time you spend in lessons with students of all ages.
to
> ‘Timetabled teaching hours’ refers to the time you spend teaching lessons to students of all ages.
> [LUPEYALPHA-950] teaching-hours-per-week page - content update

- app/views/further_education_payments/claims/teaching_qualification.html.erb
- config/locales/en.yml
https://dfedigital.atlassian.net.mcas.ms/browse/LUPEYALPHA-951
teaching qualification hint update - now a block of html
compared to the wireframe, the spacing below the hint is slightly different:
and when there's an error:
> [LUPEYALPHA-951] teaching qualification - hint content update

- app/controllers/omniauth_callbacks_controller.rb
- app/forms/journeys/further_education_payments/provider/omniauth_callback_form.rb
- app/views/further_education_payments/provider/claims/_dfe_sign_in_bypass_form.html.erb
- app/views/further_education_payments/provider/claims/sign_in.html.erb
- config/initializers/omniauth.rb
Add DfE sign in by pass
In review apps we can't use DfE sign in as the urls are dynamic and so
are not registered with DfE sign in. This commit provides a form to
allow testers to set the DfE sign in payload to check various sign in
scenarios.
> fe provider dsi bypass

- app/mailers/claim_mailer.rb
- app/models/policies/further_education_payments.rb
- app/models/policies/further_education_payments/eligibility.rb
- spec/forms/journeys/further_education_payments/claim_submission_form_spec.rb
We want the verification due date to be 2 weeks after the claim is
submitted.
This commit also moves the knowledge of the due date to the policy (it's
a policy concern not eligibility concern) and updates the formatting of
the dates in the emails to be consistent with our other emails.
> [LUPEALPHA-923] Update the verification due date

- app/controllers/reminders_controller.rb
- app/forms/reminders/confirmation_form.rb
- app/forms/reminders/email_verification_form.rb
- app/forms/reminders/personal_details_form.rb
- app/models/journeys/further_education_payments/session_answers.rb
- app/models/journeys/reminders/slug_sequence.rb
- app/views/further_education_payments/submissions/show.html.erb
- app/views/reminders/confirmation.html.erb
- app/views/reminders/email_verification.html.erb
- app/views/reminders/personal_details.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/further_education_payments/happy_path_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-704
- Able to set reminder as part of FE journey
- I don't think the current reminder code is the best and have written a new version of reminder journey with its own controller
- Things are a little rough round the edges but works as needed
- I've tried to keep things simple and also considered if we need to add this to the end of other journeys
- I hope later we can remove the old reminder controller and use this one instead
- I also hope we can later we can model the `ClaimsController` to be more like the controller created here
> [LUPEYALPHA-704] FE reminders

- app/forms/journeys/further_education_payments/provider/verify_claim_form.rb
- app/views/further_education_payments/provider/claims/verify_claim.html.erb
- config/locales/en.yml
- spec/features/further_education_payments/provider/provider_verifying_claims_spec.rb
- spec/forms/journeys/further_education_payments/provider/verify_claim_form_spec.rb
Updates the error messages on the verify claim form, and the nested
assertions forms, to match the copy on figma.
> Update error message copy

- app/controllers/admin/claims_controller.rb
- app/forms/admin/claims_filter_form.rb
- app/models/claim.rb
- this refactors the admin claims filter into a form object
- although called a form object its not currently wired up to the form but has the same attribute names so could be wired up to do so later
- the object of this change is to extract excess controller code into correct objects to allow separation of responsibilities allow the code to be simplified more easily
- the original reason for this change was the attempt to introduce FE claims to admin areas which were slowed by the current form filters being coupled to the controller code
> Admin claims filter refactor

- app/models/claim.rb
- app/models/payroll_run.rb
- app/models/policies.rb
- app/models/policies/further_education_payments.rb
- app/models/policies/further_education_payments/admin_tasks_presenter.rb
- app/models/policies/further_education_payments/eligibility.rb
- app/models/policies/further_education_payments/eligibility_admin_answers_presenter.rb
- config/locales/en.yml
- spec/factories/schools.rb
- spec/features/admin/admin_claim_allocation_spec.rb
- spec/models/policies_spec.rb
- spec/support/admin_view_claim_feature_shared_examples.rb
- This updates tests to including showing FE claims in back office
> FE admin claims

- app/forms/journeys/further_education_payments/provider/omniauth_callback_form.rb
- app/forms/journeys/further_education_payments/provider/verify_claim_form.rb
- app/models/automated_checks/claim_verifiers/provider_verification.rb
- app/models/base_policy.rb
- app/models/claim_checking_tasks.rb
- app/models/journeys/further_education_payments/provider/session_answers.rb
- app/models/policies/further_education_payments.rb
- app/models/policies/further_education_payments/admin_provider_verification_task_presenter.rb
- app/models/policies/further_education_payments/admin_tasks_presenter.rb
- app/models/task.rb
- app/views/admin/tasks/provider_verification.html.erb
- app/views/further_education_payments/provider/claims/_dfe_sign_in_bypass_form.html.erb
- config/locales/en.yml
- spec/factories/policies/further_education_payments/eligibilities.rb
- spec/features/admin/admin_claim_further_education_payments_spec.rb
- spec/forms/journeys/further_education_payments/provider/omniauth_callback_form_spec.rb
- spec/forms/journeys/further_education_payments/provider/verify_claim_form_spec.rb
- spec/models/automated_checks/claim_verifiers/provider_verification_spec.rb
- spec/support/admin_view_claim_feature_shared_examples.rb
Adds the admin provider verification task.
Probably best to review each commit separately, the main ones are
* [Add provider verification admin task](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/3131/commits/f9b57382ff5debfcafef00954cda7a8a7b15fe3e) - This commit adds the UI for displaying the verification in the admin area but leaves the task as a manual one for ops to complete.
* [Automate admin task](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/3131/commits/57ff76ed538ee652a8fc8d69ef6552da656b3ccd) - This commit adds the automatic task passing based on the answers given by the provider.
I've used the existing claim verifier mechanism to handle calling the provider verification task, this means the claim verifier code will be …
> admin provider verification task

- README.md
- app/jobs/heartbeat_job.rb
- terraform/application/application.tf
- terraform/application/statuscake.tf
- terraform/application/variables.tf
https://trello.com/c/PQgfB2yQ/1961-claims-worker-heartbeat-monitor
> Add heartbeat monitor for statuscake

- app/controllers/admin/further_education_payments/provider_verification_emails_controller.rb
- app/views/admin/tasks/provider_verification.html.erb
- config/routes.rb
- spec/features/admin/admin_claim_further_education_payments_spec.rb
Add button to resend provider verification email
The provider can only start the verification process via the link in the
email. If the provider has lost this email we need a mechanisim for the
ops team to resend the email.
As this admin logic is specific only to the FE policy we've opted to
move the controller into a policy specific namespace.
> [LUPALPHA-997] resend provider verification email

- terraform/application/config/production_app_env.yml
`BYPASS_ONELOGIN_SIGN_IN` does not do anything except on review apps, and is misleadingly configured.
> Fix production One Login endpoint config

- app/models/policies/further_education_payments.rb
- config/locales/en.yml
We've also updated the notify template
https://www.notifications.service.gov.uk/services/3e6d260a-4e66-4263-8ee9-87adbcabdf02/templates/a1bb5f64-585f-4b03-b9db-0b20ad801b34
> Add rejection reasons for FE claims

- Gemfile
- Gemfile.lock
- app/views/admin/decisions/_incomplete_tasks.html.erb
- app/views/admin/tasks/index.html.erb
- app/views/admin/tasks/payroll_gender.html.erb
- config/locales/en.yml
- spec/features/admin/admin_claim_payroll_details_task_spec.rb
- spec/features/admin/admin_claim_with_matching_details_spec.rb
- spec/features/admin/admin_claim_with_missing_payroll_gender_spec.rb
- spec/features/admin/admin_claim_without_verified_identity_spec.rb
- spec/support/admin_checks_feature_shared_examples.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-1012
- Update admin payroll gender hint copy depending on policy
- Added `ostruct` gem to fix deprecation warning
- Fix back link position on payroll gender admin task page
> [LUPEYALPHA-1012] Admin gender task hint

- app/views/claims/select_home_address.html.erb
- spec/features/auto_populating_home_address_from_postcode_search_spec.rb
- spec/features/combined_teacher_claim_journey_with_teacher_id_check_email_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/tslr_claim_journey_with_teacher_id_check_email_spec.rb
- spec/features/tslr_claim_journey_with_teacher_id_trn_spec.rb
- spec/support/get_a_teacher_relocation_payment/step_helpers.rb
Fix the labels on addresses
Labels on addresses were `for` `claim_some_address` but the radio button
had the `id` `some_address`. Update the radio buttons to use
govuk_radio_button helper and let that generate the label tag. Also
updates the specs to click the labels rather than find the radio buttons
by id.
https://github.com/user-attachments/assets/1f2fd2fd-d63f-443b-bed6-b0aa8fd8d0a0
> Fix the labels on addresses

- app/controllers/admin/further_education_payments/provider_verification_emails_controller.rb
- app/models/policies/further_education_payments/admin_provider_verification_task_presenter.rb
- app/models/policies/further_education_payments/admin_tasks_presenter.rb
- app/views/admin/tasks/_provider_verification_submitted.html.erb
- app/views/admin/tasks/_provider_verification_unsubmitted.html.erb
- app/views/admin/tasks/provider_verification.html.erb
- spec/features/admin/admin_claim_further_education_payments_spec.rb
The figma designs require us to display the admin who resent the provider verification email. To capture this information we use the existing note mechanism on claims. This is a bit fragile as we assume the only "provider_verification" note is for emails being sent. It seems like the label on notes maps to a task name, so we went with that for the label. If in future we can take other provider verification notes we may want to consider renaming this email specific label.
> Record who sent the email to the provider

- app/models/automated_checks/claim_verifiers/provider_verification.rb
- spec/models/automated_checks/claim_verifiers/provider_verification_spec.rb
There's a uniq index on the dfe sign in id, so we need to only find by
the dfe sign in id, not by the other attributes
> Fix find or create for provider

- app/models/policies/further_education_payments/admin_tasks_presenter.rb
- config/locales/en.yml
Fixes the missing translation for the studen loan plan task, and adds
the student loan plan to the answers presenter.
> [LUPEYALPHA-1044] Fix missing translation

- app/forms/journeys/further_education_payments/provider/verify_claim_form.rb
- app/helpers/admin/claims_helper.rb
- app/models/policies/further_education_payments/eligibility.rb
- app/models/policies/further_education_payments/eligibility_admin_answers_presenter.rb
- app/views/admin/claims/_answers.html.erb
- app/views/admin/claims/policies/early_career_payments/_claim.html.erb
- app/views/admin/claims/policies/early_years_payments/_claim.html.erb
- app/views/admin/claims/policies/further_education_payments/_claim.html.erb
- app/views/admin/claims/policies/international_relocation_payments/_claim.html.erb
- app/views/admin/claims/policies/levelling_up_premium_payments/_claim.html.erb
- app/views/admin/claims/policies/student_loans/_claim.html.erb
- app/views/admin/claims/show.html.erb
- spec/factories/policies/further_education_payments/eligibilities.rb
- spec/features/admin/admin_view_full_claim_further_education_payments_spec.rb
- spec/models/policies/further_education_payments/eligibility_admin_answers_presenter_spec.rb
Probably worth reviewing [each commit](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/3181/commits) separately.
FE claims show different information to other claims, rather than a single
"Eligibility" section the eligibility answers are split into multiple sections.
The admin claim show page now renders a policy specific partial for a given
claim so we can handle any policy specific display requirements.
> LUPEYALPHA 991/view full claim

- app/forms/journeys/further_education_payments/further_education_provision_search_form.rb
- app/forms/journeys/further_education_payments/select_provision_form.rb
- app/views/further_education_payments/claims/further_education_provision_search.html.erb
- spec/features/further_education_payments/happy_js_path_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-1020
- Show error when no search results
- There seem to be some bugs around going back changing answers and supporting both JS and non-JS seem to be quirky these should now be ironed out
> [LUPEYALPHA-1020] FE provision search errors on no results

- app/forms/journeys/further_education_payments/claim_submission_form.rb
- app/models/automated_checks/claim_verifiers/identity.rb
- app/models/base_policy.rb
- app/models/claim.rb
- app/models/policies/further_education_payments.rb
- app/views/admin/tasks/_one_login_idv.html.erb
- app/views/admin/tasks/identity_confirmation.html.erb
- config/locales/en.yml
- spec/factories/claims.rb
- spec/features/admin/tasks/identity_confirmation_spec.rb
- spec/forms/journeys/further_education_payments/claim_submission_form_spec.rb
- spec/models/automated_checks/claim_verifiers/identity_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-1036
- Admin for OL identity confirmation
- If user used OL, display their OL IDV data and opposing data from their claim in ID task
- If data matches it auto passes
- if data does not match it fails
- also on claim submission we do the same check and if it fails do not send the provider the verification email
---
> [LUPEYALPHA-1036] Admin One Login IDV

- app/models/claim/data_report_request.rb
- app/models/policies/international_relocation_payments/eligibility.rb
- spec/models/claim/data_report_request_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1536
- Add IRP specific data to admin CSV download
- This also fixes the admin download functionality as was broken as could not handle IRP data
> [CAPT-1536] Add IRP specific data to admin CSV download

- app/views/admin/tasks/_provider_verification_unsubmitted.html.erb
- app/views/admin/tasks/provider_verification.html.erb
When the provider was yet to verify the claim we weren't showing the
links to the next and previous tasks.
> Fix task links not showing

- app/models/automated_checks/claim_verifiers/student_loan_plan.rb
- app/models/claim.rb
- app/models/claim_student_loan_details_updater.rb
- app/models/journeys/answers_student_loans_details_updater.rb
- app/models/journeys/teacher_student_loan_reimbursement/answers_student_loans_details_updater.rb
- app/models/policies/student_loans/policy_eligibility_checker.rb
- app/models/student_loans_data_presenter.rb
- spec/factories/student_loans_data.rb
- spec/features/admin/upload_slc_data_spec.rb
- spec/features/ineligible_student_loans_claims_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/models/automated_checks/claim_verifiers/student_loan_plan_spec.rb
- spec/models/claim_spec.rb
- spec/models/claim_student_loan_details_updater_spec.rb
- spec/models/student_loans/eligibility_spec.rb
- spec/requests/admin/admin_student_loans_data_upload_spec.rb
- spec/requests/claims_spec.rb
https://dfedigital.atlassian.net/browse/LUPEYALPHA-1031
No need for the old claim verifier logic - was used to match student loan answers in the journey, which have since been removed.
Also, the student loan data file can now include rows with "No data" values, which indicates that the SLC does not have information for the given claimants, which confirms they do not have a student loan.
Main changes:
* on the claim and answers, `has_student_loan?` is `nil` if there's no SLC data, `true` if there is data with a plan, `false` if there is data with "No data" for the plan
* `student_loan_plan` is `nil` if there's no SLC data, and if there is data, it is either the correct plan(s) or "not_applicable" if they don't have a student loan
* eligibility for the TSLR journey copes with both having a …
> [LUPEYALPHA-1031] Cope with student loan data with "No data" rows. Remove invalid match logic

- app/forms/admin/claims_filter_form.rb
- app/helpers/admin/claims_helper.rb
- app/models/claim.rb
- app/views/admin/claims/index.html.erb
- config/locales/en.yml
- spec/features/admin/admin_claim_allocation_spec.rb
- spec/features/admin/admin_claims_filtering_spec.rb
- spec/features/admin/admin_view_full_claim_further_education_payments_spec.rb
- spec/models/claim_spec.rb
- spec/models/policies/further_education_payments/eligibility_admin_answers_presenter_spec.rb
- spec/models/policies_spec.rb
https://dfedigital.atlassian.net.mcas.ms/browse/LUPEYALPHA-1006
* removed "Qualification Status" column from admin claims page
* added filter for "Awaiting provider verification"
* refactored `spec/features/admin/admin_claims_filtering_spec.rb`
> [LUPEYALPHA-1006] Claim page updates: "Awaiting provider verification" filter, remove "Qualification status" column.

- app/controllers/claims_form_callbacks.rb
- app/jobs/student_loan_plan_check_job.rb
- app/models/automated_checks/claim_verifiers/student_loan_plan.rb
- app/models/base_policy.rb
- app/models/claim.rb
- app/models/claim/claims_awaiting_decision_finder.rb
- app/models/journeys/further_education_payments/answers_student_loans_details_updater.rb
- app/models/policies/early_career_payments.rb
- app/models/policies/further_education_payments.rb
- app/models/policies/further_education_payments/claim_checking_tasks.rb
- app/models/policies/levelling_up_premium_payments.rb
- spec/factories/claims.rb
- spec/features/admin/upload_slc_data_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/jobs/student_loan_plan_check_job_spec.rb
- spec/models/automated_checks/claim_verifiers/student_loan_plan_spec.rb
- spec/models/claim/claims_awaiting_decision_finder_spec.rb
- spec/models/claim_checking_tasks_spec.rb
- spec/models/claim_spec.rb
- spec/models/claim_student_loan_details_updater_spec.rb
- spec/requests/admin/admin_student_loans_data_upload_spec.rb
- spec/support/admin_view_claim_feature_shared_examples.rb
- spec/support/steps/student_loan_data.rb
changes in addition to LUPEYALPHA-1031 (which allows for "No data" SLC rows) https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/3183
Changes:
* student loan plan updated from student loan data if it exists
* student loan plan automated check run - currently goes to 'passed' if there is matching data, or 'failed' for everything else.
* cope with `submitted_using_slc_data` being `nil` for FE claims. With the changes in this PR, it should not be `nil` for future claims.
> [LUPEYALPHA-1010] student loan plan task for FE

- app/views/admin/amendments/index.html.erb
- app/views/admin/claims/index.html.erb
- app/views/admin/claims/search.html.erb
- app/views/admin/claims/show.html.erb
- app/views/admin/decisions/new.html.erb
- app/views/admin/notes/index.html.erb
- app/views/admin/payments/index.html.erb
- app/views/admin/tasks/arrival_date.html.erb
- app/views/admin/tasks/census_subjects_taught.html.erb
- app/views/admin/tasks/employment.html.erb
- app/views/admin/tasks/employment_contract.html.erb
- app/views/admin/tasks/employment_start.html.erb
- app/views/admin/tasks/identity_confirmation.html.erb
- app/views/admin/tasks/index.html.erb
- app/views/admin/tasks/induction_confirmation.erb
- app/views/admin/tasks/matching_details.html.erb
- app/views/admin/tasks/payroll_details.html.erb
- app/views/admin/tasks/payroll_gender.html.erb
- app/views/admin/tasks/previous_payment.html.erb
- app/views/admin/tasks/provider_verification.html.erb
- app/views/admin/tasks/qualifications.html.erb
- app/views/admin/tasks/student_loan_amount.html.erb
- app/views/admin/tasks/student_loan_plan.html.erb
- app/views/admin/tasks/subject.html.erb
- app/views/admin/tasks/teaching_hours.html.erb
- app/views/admin/tasks/visa.html.erb
- Most of the admin back link positions in the layout are incorrect
- Fixes all of them, see screen shots
- Use govuk component for back links
- Reduce verbosity of some urls
> fix admin back link positions

- app/views/static_pages/accessibility_statement.html.erb
- config/locales/en.yml
We want to be able to set these per journey as different journeys will
be audited at different times.
> Move accessibility dates to locales

- app/forms/claim_submission_base_form.rb
- app/models/claim.rb
- config/analytics.yml
- db/migrate/20240924091408_add_started_at_to_claims.rb
- db/schema.rb
- spec/forms/journeys/additional_payments_for_teaching/claim_submission_form_spec.rb
- spec/forms/journeys/further_education_payments/claim_submission_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/claim_submission_form_spec.rb
- spec/forms/journeys/teacher_student_loan_reimbursement/claim_submission_form_spec.rb
Before the introduction of the journey session claims were created at
the start of the claimant journey, however as claims are now created at
the end of the claimant journey we can no longer use the claim's created
at timestamp to infer when the journey was started.
PR 1 of 3
2 https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/3222
3 https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/3224
> Set started at on claims #1

- db/migrate/20240924095435_back_fill_claims_started_at.rb
- db/schema.rb
- spec/factories/claims.rb
- spec/forms/journeys/additional_payments_for_teaching/nqt_in_academic_year_after_itt_form_spec.rb
Back fill started at
If the claim has a journey session we try and set the `started_at` to
that, if it doesn't have a journey session we'll just use the
`created_at` timestamp, which for claims pre the introduction of journey
sessions will be the started at time.
PR 2 of 3
1 https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/3221
3 https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/3224
> LUPEYALPHA 1096/fix claim started date 2

- app/helpers/admin/claims_helper.rb
- db/migrate/20240924113642_make_claims_started_at_not_null.rb
- db/schema.rb
- spec/features/admin/admin_view_full_claim_further_education_payments_spec.rb
Show started at
Update the admin ui to show the claim started_at time rather than claim
created_at time
PR 3 of 3
1 https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/3221
2 https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/3222
> LUPEYALPHA 1096/fix claim started date 3

- spec/features/admin/admin_claims_filtering_spec.rb
Sometimes the string "FE" ends up in the generated claim reference, eg "XBCFEA", and so is visible in the table more than twice. To fix this we need to specifically look in the policy short names column.
> Fix flakey test

- app/forms/journeys/early_years_payment/practitioner/claim_submission_form.rb
- app/forms/journeys/early_years_payment/practitioner/find_reference_form.rb
- app/forms/journeys/early_years_payment/practitioner/session_form.rb
- app/models/journeys.rb
- app/models/journeys/early_years_payment/practitioner.rb
- app/models/journeys/early_years_payment/practitioner/eligibility_checker.rb
- app/models/journeys/early_years_payment/practitioner/session.rb
- app/models/journeys/early_years_payment/practitioner/session_answers.rb
- app/models/journeys/early_years_payment/practitioner/session_answers_type.rb
- app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
- app/views/early_years_payment/practitioner/landing_page.html.erb
- config/locales/en.yml
- db/seeds.rb
- spec/models/journeys_spec.rb
- Add scaffolding for EY practitioner journey
- I've added a placeholder landing page, it's possible we don't want one but the setup requires one and may need to remove later
> Add EY practitioner scaffolding

- app/helpers/admin/claims_helper.rb
- app/models/claim/matching_attribute_finder.rb
- app/views/admin/claims/_claims_with_matching_details.html.erb
- spec/features/admin/admin_claim_with_matching_details_spec.rb
- spec/helpers/admin/claims_helper_spec.rb
- spec/models/claim/matching_attribute_finder_spec.rb
Updates the logic used when showing which attributes on the claim
triggered a match to take into account the matching groups, eg if two
claims have a matching sort code but different account number we don't
want to show the sort code as the reason for the match in the ui.
> Fixes admin matching claims ui

- app/controllers/admin/payroll_runs_controller.rb
- app/models/payroll_run.rb
- app/views/admin/payroll_runs/show.html.erb
- config/routes.rb
When testing we need to spin up a new review app for each payroll run we
want to test. This commit adds a button, for review apps, staging, and development
only, to allow admins to delete a payroll run on a review app.
> Allow deleting payroll runs on review apps

- app/models/journeys/early_years_payment/practitioner.rb
- app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
- app/views/claims/_address_fields.html.erb
- app/views/claims/address.html.erb
- app/views/early_years_payment/practitioner/claims/email_address.html.erb
- app/views/early_years_payment/practitioner/claims/enter_home_address.html.erb
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
basing off `LUPEYALPHA-983-EY-practitioner-personal-details` branch
> [LUPEYALPHA-984] EY practitioner enter home address

- app/models/claim/matching_attribute_finder.rb
- spec/models/claim/matching_attribute_finder_spec.rb
- spec/models/claim_checking_tasks_spec.rb
- spec/support/admin_view_claim_feature_shared_examples.rb
A requirement is to trigger a "multiple claims with matching details"
warning if there is another claim with a matching name and date of
birth. This check is to work across all policies.
We can hold off merging this one until after Monday
> Add name and dob check to matching claims

- app/helpers/admin/claims_helper.rb
- app/views/admin/tasks/student_loan_plan.html.erb
- config/locales/en.yml
- spec/factories/policies/further_education_payments/eligibilities.rb
- spec/features/admin/admin_checks_further_education_payments_claim_spec.rb
- spec/features/admin/admin_claims_filtering_spec.rb
- spec/jobs/further_education_payments/provider_verification_chase_email_spec.rb
- spec/models/automated_checks/claim_verifiers/student_loan_plan_spec.rb
- spec/models/claim_spec.rb
- spec/support/admin_checks_feature_shared_examples.rb
student loan plan task is always automated now, no option for manual answering.
Added missing Admin Checks feature, which we had for the other journeys.
> [LUPEYALPHA-1101] remove radio buttons from Student Loan Plan task

- app/models/journeys/early_years_payment/practitioner/session_answers.rb
- app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
- app/views/additional_payments/claims/reminder_email_verification.html.erb
- app/views/additional_payments/reminders/email_verification.html.erb
- app/views/claims/_one_time_password.html.erb
- app/views/claims/email_verification.html.erb
- app/views/early_years_payment/practitioner/claims/email_address.html.erb
- app/views/early_years_payment/practitioner/claims/email_verification.html.erb
- config/locales/en.yml
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
> [LUPEYALPHA-985] EY practitioner email address

- app/models/policies/early_career_payments.rb
- app/models/policies/further_education_payments.rb
- app/models/policies/levelling_up_premium_payments.rb
- app/models/policies/student_loans.rb
- spec/models/claim/matching_attribute_finder_spec.rb
Requirement is to check for matching claims across all policies, except
for IRP, which should only flag matches with other IRP policies.
At the minute the only attribute we use on eligibility when checking for
matches is TRN, which is present in all the eligibilities we compare, if
however we start checking other attributes the db will throw an error as
the column may not be present on all eligibilities, hence having to
update the "matching_claims - blank trn" test.
> Match across all policies

- app/controllers/claims_controller.rb
- app/controllers/concerns/form_submittable.rb
- app/forms/current_school_form.rb
- app/forms/journeys/early_years_payment/practitioner/find_reference_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/claim_school_form.rb
- app/mailers/claim_mailer.rb
- app/models/journeys/early_years_payment/practitioner/session_answers.rb
- app/views/early_years_payment/practitioner/claims/find_reference.html.erb
- config/locales/en.yml
- spec/factories/journeys/early_years_payment/practitioner/session.rb
- spec/features/early_years_payment/practitioner/find_reference_spec.rb
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
- spec/forms/journeys/early_years_payment/practitioner/find_reference_form_spec.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/claim_submission_form_spec.rb
- spec/mailers/claim_mailer_spec.rb
- spec/requests/reminders_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-1045
- Adds EY practitioner find reference screen
- In order to support email in url query params and the way the current controller/journey concerns does a lot redirect, I've had to make tweaks to ensure these get passed around so they are not lost. This will affect all journeys
- I have concern where query params are stripped, thinking of mostly Safari where it can strip certain query params, may cause this feature to not work as we use it to pass state
- Updated email sent to practitioner to inject correct url to continue their journey
> [LUPEYALPHA-1045] EY practitioner find reference screen

- app/forms/journeys/early_years_payment/practitioner/find_reference_form.rb
- app/models/journeys/early_years_payment/practitioner/session_answers.rb
- app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
- app/views/early_years_payment/practitioner/claims/find_reference.html.erb
- app/views/early_years_payment/practitioner/claims/one_login_sign_in.html.erb
- spec/features/early_years_payment/practitioner/find_reference_spec.rb
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-981
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-994
- Add One Login to EY practitioner journey
- This will want to be tested after merging on TEST as review apps does not integrate with One Login
> [LUPEYALPHA-981] [LUPEYALPHA-994] Add One Login to EY practitioner journey

- app/models/claim.rb
When a new academic year has started, and we are yet to approved any claims from this academic year, all claims from the previous year are flagged for qa when approved. To avoid this we need to count the number of approved claims in the _claim's_ academic year rather than the current academic year.
> Fix claims being flagged for qa

- config/locales/en.yml
- spec/features/early_career_payments/early_career_payments_claim_spec.rb
- spec/features/early_years_payment/practitioner/find_reference_spec.rb
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
- spec/support/feature_helpers.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-1121
- Update copy on EY find reference screen
- Also fixed flakey JS test
> [LUPEYALPHA-1121] Update find ref copy

- app/controllers/admin/amendments_controller.rb
- spec/features/admin/admin_amend_claim_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1615
- Admin can view amendments on a claim even after being payrolled
- The behaviour of not being able to add new amendments remains the same, ie not possible to do so
> [CAPT-1615] Admin can view amendments after payrolled

- app/views/admin/claims/_allocations_form.html.erb
- spec/features/admin/admin_claim_allocation_spec.rb
Updates the admin UI providing a select box for allocating a specific
number of claims.
> CAPT 1834/claim allocations dropdown

- app/forms/journeys/further_education_payments/provider/verify_claim_form.rb
- app/models/policies/further_education_payments/admin_provider_verification_task_presenter.rb
- config/locales/en.yml
- spec/features/further_education_payments/provider/provider_verifying_claims_spec.rb
- spec/forms/journeys/further_education_payments/provider/verify_claim_form_spec.rb
Updates the provider verification form to ask the provider to verify
that the claimant isn't subject to any performance or disciplinary
measures.
> Add new provider verification questions

- app/controllers/admin/claims_controller.rb
- app/forms/admin/claims_filter_form.rb
- app/helpers/admin/claims_helper.rb
- app/views/admin/claims/index.html.erb
- spec/features/admin/admin_claims_filtering_spec.rb
- spec/features/admin/admin_view_claim_further_education_payments_spec.rb
- spec/helpers/admin/claims_helper_spec.rb
- spec/requests/admin/admin_claims_spec.rb
- spec/support/admin_view_claim_feature_shared_examples.rb
- https://dfedigital.atlassian.net/browse/CAPT-1297
- Admin claims filtering now stays persisted in session
- Use govuk formbuilder for filter form
- Form now has anchor so applying filter no longer bounces you to top of page
- Filters are now persisted to session therefore will always be applied unless explicitly cleared
> [CAPT-1297] Admin claims filter and session

- app/models/automated_checks/claim_verifiers/student_loan_plan.rb
- app/models/policies/further_education_payments.rb
- app/views/admin/tasks/student_loan_plan.html.erb
- spec/features/admin/upload_slc_data_spec.rb
- spec/features/further_education_payments/student_loan_spec.rb
- spec/jobs/student_loan_plan_check_job_spec.rb
- spec/models/automated_checks/claim_verifiers/student_loan_plan_spec.rb
- spec/support/steps/dqt.rb
- spec/support/steps/further_education_journey.rb
All journeys now behave the same (except TSLR which does not have a student loan plan task):
* when the claim is submitted, and there is no SLC data for the claimant, the task shows as 'Incomplete'
* when the SLC data is subsequently uploaded, the 'Incomplete' tasks will show as 'Passed' or 'Incomplete' depending if a SLC data entry has been found for that claimant
* when the claim is submitted, and there is SLC data for the claimant, the task does not show, but the plan is set correctly
For the 'Incomplete' student loan plan tasks, I've added the notes back, as that shows if the automated check was carried out (it used to show on the old 'No data' tasks).
We don't show 'No data' for student loan plan tasks any more - it's either 'Incomplete' or 'Passed'.
> [LUPEYALPHA-1112] When no entry in SLC data, do not create task (shows as incomplete on admin view)

- app/forms/admin/claims_filter_form.rb
- app/helpers/admin/claims_helper.rb
- spec/factories/claims.rb
- spec/forms/admin/claims_filter_form_spec.rb
- spec/helpers/admin/claims_helper_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1854
- Fixes issue with provider verification status in back office
- If claim is rejected, this takes precedence over provider verification
- when filtering claims for `provider verification` it only includes claims awaiting a decision
> [CAPT-1854] Provider verification status

- app/controllers/admin/payroll_runs_controller.rb
- app/forms/admin/claims_filter_form.rb
- app/models/claim.rb
- spec/forms/admin/claims_filter_form_spec.rb
The awaiting provider verification scope joins to notes, claims can have
more than one note, if they do duplicate claims are returned from the
query. To resolve this we call distinct on the claim id. Claims have a
couple of JSON columns so we can't use the `distinct` method directly,
instead we have to explicitly use distinct with the claim.id. We also
need to wrap the whole query in a where clause so when we chain on a
`count` rails generates the correct SQL rather than something like
`SELECT COUNT(count_column) FROM (SELECT DISTINCT ON (claims.id), claims.id)`
Additionally we have to make sure to include `submitted_at` in the
distinct clause as some of the scopes used to build the query include
order by submitted_at clauses.
> Fix duplciate claims in list

- app/forms/admin/claims_filter_form.rb
- spec/factories/claims.rb
- spec/forms/admin/claims_filter_form_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1402
- Back office can filter for auto approved claims
> [CAPT-1402] Back office can filter for auto approved claims

- app/controllers/admin/decisions_controller.rb
- app/models/admin/task_pagination.rb
- app/models/claim_checking_tasks.rb
- app/views/admin/_task_pagination.html.erb
- app/views/admin/claims/policies/early_career_payments/_claim.html.erb
- app/views/admin/claims/policies/early_years_payments/_claim.html.erb
- app/views/admin/claims/policies/further_education_payments/_claim.html.erb
- app/views/admin/claims/policies/international_relocation_payments/_claim.html.erb
- app/views/admin/claims/policies/levelling_up_premium_payments/_claim.html.erb
- app/views/admin/claims/policies/student_loans/_claim.html.erb
- app/views/admin/decisions/index.html.erb
- app/views/admin/tasks/index.html.erb
- config/routes.rb
- spec/features/admin/tasks/pagination_spec.rb
- spec/support/admin_checks_feature_shared_examples.rb
- https://dfedigital.atlassian.net/browse/CAPT-1614
- Improve admins paginating thru tasks, so they can now paginate thru to `Decision` or `QA decision`
- The decision page now shows previous decisions rather than show full claim
- There is a new admin `DecisonsController#index` action that displays all the previous decisions made on a claim in chronological order
- We now show this page when a decision has been made
- So when paginating thru tasks to `Decision` we now show the above page
- If QA is required we show next task as `QA decision` which displayed QA decision form
- if QA is completed we show all previous decisions
- We have both a mixture of `tasks` and `decisions` from a code perspective though from a UI perspective these are all deemed as tasks. Why we have these 2 different …
> [CAPT-1614] Admin task pagination

- app/forms/journeys/further_education_payments/provider/omniauth_callback_form.rb
- app/models/policies/further_education_payments/admin_tasks_presenter.rb
- spec/features/further_education_payments/provider/provider_verifying_claims_spec.rb
- spec/forms/journeys/further_education_payments/provider/omniauth_callback_form_spec.rb
The omniauth hash from DfE sign in is not populating the first name and
last name fields. We require these fields when displaying who verified a
claim. This commit adds a fallback to request this information from the
DSI api, if it's not present in the oauth payload.
> CAPT 1858/handle missing info

- app/forms/claim_submission_base_form.rb
- app/forms/journeys/further_education_payments/claim_submission_form.rb
- spec/forms/journeys/further_education_payments/claim_submission_form_spec.rb
If the form is invalid, say the journey session has already been
submitted and the user double clicks the submit button, we need to
return early from the child `save` method to avoid calling the mailer
with a claim that hasn't been saved (which triggeres an error as the
claim has no reference number).
> Fixes missing reference for claim

- app/views/additional_payments/claims/check_your_answers.html.erb
- app/views/early_years_payment/provider/authenticated/claims/check_your_answers.html.erb
- app/views/further_education_payments/claims/check_your_answers.html.erb
- app/views/student_loans/claims/check_your_answers.html.erb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-1158
- govuk formbuilder by default out of the box has double click prevention enabled which is desired
> [LUPEYALPHA-1158] Use govuk formbuilder for submissions

- terraform/application/config/test.tfvars.json
Create backup storage account for test environment, to allow backup workflow testing [and DR]
Set enable_postgres_backup_storage in test env tfvars
make test-aks terraform-plan-aks
https://trello.com/c/g8swAO8Q/2090-capt-enable-test-backup-storage-account
> Create backup storage account for test env

- app/forms/journeys/early_years_payment/practitioner/find_reference_form.rb
- app/models/policies/early_years_payments/eligibility.rb
- config/analytics.yml
- db/migrate/20241015093740_add_practitioner_claim_submitted_at_to_early_years_payment_eligibilities.rb
- db/schema.rb
- spec/factories/early_years_payments/eligibilities.rb
- spec/features/early_years_payment/practitioner/find_reference_spec.rb
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
- spec/forms/journeys/early_years_payment/practitioner/find_reference_form_spec.rb
- spec/support/steps/eligible_ey_journey_authenticated.rb
new field on EY eligibility: `practitioner_claim_submitted_at for EY practitioner journey` - used instead of `claim.submitted_at` to check if claim has been submitted by the practitioner.
> [LUPEYALPHA-1162] separate practitioner_claim_submitted_at for EY practitioner journey

- app/forms/mobile_number_form.rb
- spec/forms/mobile_number_form_spec.rb
Notify uses the https://pypi.org/project/phonenumbers/ library to
validate phone numbers. There's some scenarios where our regex permits a
phone number that libphonenumber doesn't allow, causing notify to return
an error when sending to that number.
We've gone for rescuing this api error and adding a validation error to
the the form. We may at some point, especially if we move message sending
into a background job, want to investigate using a gem like
https://github.com/daddyz/phonelib that will provide stricter phone
number validations.
> Rescue notify api errors

- db/migrate/20241015121145_add_not_null_reference.rb
- db/schema.rb
- spec/factories/claims.rb
- spec/forms/journeys/additional_payments_for_teaching/nqt_in_academic_year_after_itt_form_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-1163
- Migration to add not NULL constraint so `Claim#reference` cannot be NULL
- DB level constraints prevents us getting into bad data integrity situations
> [LUPEYALPHA-1163] Migration so claim#reference cannot be NULL

- lib/tasks/retrieve_notify_message_status.rake
https://dfedigital.atlassian.net/browse/CAPT-1863
A quick and dirty Rake task to automate pulling message delivery status from the Notify API. Their web site only shows the last 50 messages.
It will write them to a CSV file. You can specify the number of days to go back as a CLI argument (note the maximum retention is currently 7 days).
> CAPT-1863: Rake task to pull message delivery status from Notify API

- app/models/eligible_fe_providers_importer.rb
- lib/csv_importer/base.rb
- spec/factories/file_uploads.rb
- spec/jobs/import_census_job_spec.rb
- spec/models/claim_spec.rb
- spec/models/eligible_fe_providers_importer_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-1152
- Handle CSV uploads with empty rows by ignoring them
> [LUPEYALPHA-1152] Upload CSV with empty rows

- spec/forms/mobile_number_form_spec.rb
Cleans up the scenarios so all the failure contexts are grouped together
> Refactor the mobile form specs

- app/forms/claim_submission_base_form.rb
- app/forms/journeys/early_years_payment/practitioner/claim_submission_form.rb
- app/forms/journeys/early_years_payment/practitioner/find_reference_form.rb
- app/forms/journeys/early_years_payment/provider/authenticated/claim_submission_form.rb
- app/forms/journeys/early_years_payment/provider/start/claim_submission_form.rb
- app/forms/journeys/further_education_payments/claim_submission_form.rb
- app/forms/journeys/get_a_teacher_relocation_payment/claim_submission_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/claim_submission_form.rb
- app/jobs/claim_verifier_job.rb
- app/models/journeys/early_years_payment/practitioner/answers_presenter.rb
- app/models/policies/early_years_payments/eligibility.rb
- app/views/early_years_payment/practitioner/claims/check_your_answers.html.erb
- app/views/early_years_payment/practitioner/submissions/show.html.erb
- config/analytics.yml
- config/locales/en.yml
- db/migrate/20241017113701_add_provider_claim_submitted_at_to_early_years_payment_eligibilities.rb
- db/schema.rb
- spec/factories/claims.rb
- spec/factories/early_years_payments/eligibilities.rb
- spec/factories/journeys/early_years_payment/practitioner/answers.rb
- spec/features/early_years_payment/practitioner/find_reference_spec.rb
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
- spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
- spec/forms/journeys/early_years_payment/practitioner/claim_submission_form_spec.rb
- spec/forms/journeys/early_years_payment/practitioner/find_reference_form_spec.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/claim_submission_form_spec.rb
- spec/jobs/claim_verifier_job_spec.rb
- spec/models/journeys/early_years_payment/practitioner/answers_presenter_spec.rb
When the EY practitioner claim is submitted, it will update the existing claim (created by the EY provider) with the answers.
After discussion with @slorek, we decided that `claim.submitted_at` will only be populated when the practitioner submits the claim.
When the provider submits the claim, `claim.eligibility.provider_claim_submitted_at` will be populated.
> [LUPEYALPHA-989] EY Practitioner check-your-answers page

- app/views/admin/tasks/index.html.erb
- spec/features/admin/admin_reverse_claim_decision_spec.rb
The link to "approve/reject claim" changes depending on whether a
decision has been made. When determining if a decision has been made we
need to ignore decisions which have been undone.
If a claim is approved, then the decision is undone, and then the claim
is rejected, it should not show the "This claim has been marked for a
quality assurance review"
> Fix link to approve/reject for reversed claims

- app/forms/journeys/further_education_payments/provider/verify_claim_form.rb
- app/models/claim.rb
- config/analytics.yml
- db/migrate/20241028095040_add_verified_at_timestamp_to_claims.rb
- db/schema.rb
- spec/forms/journeys/further_education_payments/provider/verify_claim_form_spec.rb
We need to be able to access the timestamp showing when a claim was verified in big
query. The provider verification is flagged in the analytics block list
so isn't sent over to big query (it's a json structure and some of it's
fields are pii). To ensure big query has access to the verification
timestamp we have added a new column on the claim `Claim#verified_at`
which will be sent over to big query. A follow up PR will back fill this
column on already verified claims.
[Follow up pr](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/3347) to back fill the existing claims
> Set verified at on the claim

- db/migrate/20241028110426_back_fill_claims_verified_at.rb
- db/schema.rb
Back fill verified_at on verified claims
[PR](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/3346) to create the new column
> make verification timestamps available in reports part 2

- .github/workflows/delete_review_app.yml
- this allows us to specify review apps to delete on demand
- this is useful for when there are rogue review app instances
- this is untested but quickest way to test is probably to merge and give it a go
> Able to manually delete specified review app

- app/forms/journeys/early_years_payment/provider/authenticated/claimant_name_form.rb
- app/models/journeys/early_years_payment/provider/authenticated/session_answers.rb
- config/analytics_blocklist.yml
- db/migrate/20241030153139_add_claimant_details_to_ey_eligibilities.rb
- db/schema.rb
- spec/factories/journeys/early_years_payment/provider/authenticated/early_years_payment_provider_authenticated_answers.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/claim_submission_form_spec.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/claimant_name_form_spec.rb
When the provider enters the practitioner name it's stored in the
`Claim#first_name` and `Claim#surname` fields. When the practitioner
completes their portion of the journey the details they entered on the
personal details step overwrites the values entered by the provider in
the `Claim#first_name` and `Claim#surname` fields.
We have a requirement to show and compare both the provider
entered claimant name and practitioner entered claimant name in the
admin area, this commit stores the provider entered name information in
two new fields allowing us to do this.
> Capture practitioner names

- Dockerfile
Temporary fix to allow build to progress, addressing https://security.snyk.io/vuln/SNYK-ALPINE320-POSTGRESQL16-8320287
> Upgrade postgres library

- app/controllers/admin/decisions_controller.rb
- app/mailers/claim_mailer.rb
- app/models/claim.rb
- app/models/policies/early_years_payments.rb
- app/models/policies/early_years_payments/eligibility.rb
- spec/features/admin/admin_reject_claim_spec.rb
- spec/mailers/claim_mailer_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-1235
- When rejecting an EY claim, provider is also notified via email
- I'm aware that at this moment `ClaimMailer` is not in the best of shape and rather overloaded. I think at some point we need to add some kind of service class(es) to deal with business logic of when to send email leaving mail just to deal with mail
> [LUPEYALPHA-1235] Rejecting EY claim also emails provider

- app/views/admin/tasks/_form.html.erb
- config/locales/en.yml
- spec/features/admin/admin_claim_without_verified_identity_spec.rb
Don't show DQT match if DQT record not found
If we don't have a DQT record for the claimant we don't want to show the
text "The claimant’s identity matches DQT records.".
The for the identity task `claim_verifier_match` can be in one of 4
states:
`nil` - the check hasn't run or identity was verified by one login¹
`none` - no dqt record was found
`any` - a partial match against the returned dqt record
`all` - a full match against the dqt record
¹ If the claim was verified by one login then the match on the task will
be `nil`, however the way the task form is set up it only renders the
body section if the policy has a corresponding body section in the
locales file. FurtherEducationPayments does not have a body section in
the locales file so we don't show the dqt related messages for these …
> Don't show DQT match if DQT record not found

- app/controllers/admin/payroll_run_downloads_controller.rb
- app/controllers/admin/payroll_runs_controller.rb
- app/models/payroll/payment_csv_row.rb
- app/models/payroll/payments_csv.rb
- app/models/payroll_run.rb
- app/views/admin/payroll_run_downloads/show.html.erb
- spec/features/admin/admin_payroll_run_download_spec.rb
- spec/features/admin/admin_payroll_runs_spec.rb
- spec/models/payroll/payment_csv_row_spec.rb
- spec/models/payroll/payments_csv_spec.rb
- spec/models/payroll_run_spec.rb
- spec/requests/admin/admin_payroll_run_downloads_spec.rb
- spec/requests/admin/admin_payroll_runs_spec.rb
Requirement is to only produce a single payroll file with no limit on
the number of payments in the file.
This commit removes the zip file as we no longer need it and instead
serves the generated csv directly, this lets us simplify the code quite
a bit.
> Remove batching from payroll csv

- app/controllers/claims_form_callbacks.rb
- app/jobs/student_loan_plan_check_job.rb
- app/models/claim_checking_tasks.rb
- app/models/journeys/early_years_payment/practitioner/answers_student_loans_details_updater.rb
- app/models/policies/early_years_payments.rb
- app/models/policies/early_years_payments/claim_checking_tasks.rb
- spec/features/admin/upload_slc_data_spec.rb
- spec/features/early_years_payment/practitioner/email_address_spec.rb
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
- spec/features/early_years_payment/practitioner/mobile_number_spec.rb
- spec/features/early_years_payment/practitioner/student_loan_spec.rb
- spec/jobs/student_loan_plan_check_job_spec.rb
- spec/requests/admin/admin_student_loans_data_upload_spec.rb
- spec/support/admin_view_claim_feature_shared_examples.rb
- spec/support/steps/early_years_practitioner_journey.rb
- spec/support/steps/early_years_provider_journey_authenticated.rb
- spec/support/steps/eligible_ey_providers.rb
https://dfedigital.atlassian.net/browse/LUPEYALPHA-1231
> [LUPEYALPHA-1231] EY student loan plan task

- app/controllers/admin/tasks_controller.rb
- app/controllers/omniauth_callbacks_controller.rb
- app/jobs/claim_verifier_job.rb
- app/models/automated_checks/claim_verifiers/early_years_payments/identity.rb
- app/models/claim.rb
- app/models/policies/early_years_payments.rb
- app/models/policies/early_years_payments/admin_tasks_presenter.rb
- app/models/policies/early_years_payments/claim_checking_tasks.rb
- app/models/policies/early_years_payments/eligibility.rb
- app/views/admin/tasks/early_years_payments/identity_confirmation.html.erb
- config/brakeman.ignore
- config/locales/en.yml
- spec/features/admin/admin_ey_identity_task_spec.rb
- spec/jobs/claim_verifier_job_spec.rb
- spec/support/admin_view_claim_feature_shared_examples.rb
Might be easier to review each commit separately.
The main change in this pr is adding the Identity task.
The EY identity task behaves slightly differently to the other tasks.
EY practitioners don't have DQT records so we're only using the information
from one login to check identity, additionally the rules around creating the
task are slightly different to other policies.
If the one login check passes and the name returned from OL matches the name
the provider entered the task is a pass
If the one login check passes and the names are a partial match¹ then we
create task with a partial match (see Admin::ClaimsHelper#task_status_tag)
If the one login check passes and the name from OL is different to the
provider supplied name we create a failed task.
If the one login check fails we create …
> LUPEYALPHA 1171/identity task

- app/models/policies/early_years_payments.rb
- config/locales/en.yml
- spec/models/decision_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-1241
- Add extra EY rejection reason for when ID check fails
> [LUPEYALPHA-1241] Extra EY rejection reason: ID check failed

- config/locales/en.yml
- spec/features/admin/eligible_ey_providers_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1938
- Tweak EY journey name which affects the name of the service in the header
> [CAPT-1938] Tweak EY journey name

- app/helpers/admin/claims_helper.rb
- app/models/base_policy.rb
- app/models/claim.rb
- app/models/policies/early_years_payments.rb
- app/views/admin/claims/index.html.erb
- spec/factories/claims.rb
- spec/features/admin/admin_view_claim_early_years_payments_spec.rb
- spec/features/admin/admin_view_full_claim_early_years_payments_spec.rb
- spec/helpers/admin/claims_helper_spec.rb
- spec/models/base_policy_spec.rb
- spec/models/claim_spec.rb
- spec/models/policies/early_years_payments_spec.rb
- spec/support/page_matchers.rb
- https://dfedigital.atlassian.net/browse/CAPT-1921
- For back office admin viewing claims
- Tweak content for EY
- Show different decision deadline
> [CAPT-1921] EY claim index data

- app/models/policies/further_education_payments/claim_checking_tasks.rb
- app/models/policies/international_relocation_payments/claim_checking_tasks.rb
- spec/features/admin/admin_claim_with_missing_payroll_gender_spec.rb
When completing the payroll gender task we update the gender on the
claim, this removed the payroll gender task causing
`Admin::TaskPagination#current_task_index` to be `nil` ultimatly
throwing an error when we try to redirect to the
`Admin::TaskPagination#next_task_path` (which was nil).
> Keep task if claim updated with gender

- app/models/eligible_fe_providers_importer.rb
- lib/csv_importer/base.rb
- spec/fixtures/files/eligible_fe_providers_illegal_encoding.csv
- spec/models/eligible_fe_providers_importer_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1957
- Uploading eligible FE providers CSV where currency values container GBP and commas are ignored
- also upload scrub and illegally encoded characters, which get replaced with replacement character
> [CAPT-1957] Handle currency for eligble FE CSV upload

- db/migrate/20241107164046_create_ey_journey_configs.rb
- db/schema.rb
`Claim::ClaimsAwaitingDecisionFinder` assumes that the EYPayments
journeys existing on production. This class is called by the
`StudentLoanPlanCheckJob` which has been
[erroring](https://app.rollbar.com/a/dfe-digital/fix/item/dfe-claims/1411)
and thus failing to import SLC data.
> Create EY journey configs on production

- app/forms/journeys/early_years_payment/provider/authenticated/start_date_form.rb
- app/models/policies/early_years_payments.rb
- app/models/policies/early_years_payments/policy_eligibility_checker.rb
- app/views/early_years_payment/provider/authenticated/claims/_ineligibility_start_date_before_policy_start.html.erb
- app/views/early_years_payment/provider/start/landing_page.html.erb
- spec/factories/journeys/early_years_payment/provider/authenticated/early_years_payment_provider_authenticated_answers.rb
- spec/features/admin/admin_ey_identity_task_spec.rb
- spec/features/early_years_payment/provider/authenticated/ineligible_start_date_spec.rb
- spec/models/journeys/early_years_payment/provider/authenticated/answers_presenter_spec.rb
- spec/models/policies/early_years_payments/policy_eligibility_checker_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1933
- EY now has a start date for the policy
- Any start dates prior to this send the user to ineligible page
- I've had to make the constant `POLICY_START_DATE` 1 month prior to actual policy start date, otherwise we'd never be able to enter any claims for testing
- this needs to be removed for launch
> [CAPT-1933] EY start date eligibility

- app/forms/journeys/early_years_payment/practitioner/claim_submission_form.rb
- app/forms/journeys/early_years_payment/practitioner/find_reference_form.rb
- app/models/journeys/early_years_payment/practitioner/session_answers.rb
- spec/factories/journeys/early_years_payment/practitioner/answers.rb
- spec/forms/journeys/early_years_payment/practitioner/find_reference_form_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1898
- Change definition of when practitioner starts their claim
- Was when journey session was created, now after they submit a reference
> [CAPT-1898] Practitioner claim start timestamp

- app/models/eligible_fe_providers_importer.rb
- lib/csv_importer/base.rb
Calling `AnalyticsImporter` is erroring. This commit temp disables theh
`EligibleFeProvidersImporter` from calling the `AnalyticsImporter` while
we decide how best to fix that class.
> Temp disable analytics for fe provider upload

- lib/csv_importer/base.rb
- spec/lib/csv_importer/base_spec.rb
Attempting to sync analytics is erroring withh rake task not found. This
is blocking admins from uploading reports so temp disabling for now.
> Temp remove analytics syncing

- app/controllers/admin/cookies_controller.rb
- app/controllers/cookies_controller.rb
- Improves `accept_cookie` cookie with `httponly`
- Cookie is only used server side so we can prevent cookie reading or tampering client side
> Accept cookie httponly

- app/controllers/claims_form_callbacks.rb
- app/models/journeys/additional_payments_for_teaching.rb
- app/models/journeys/base.rb
- app/models/journeys/early_years_payment/practitioner.rb
- app/models/journeys/further_education_payments.rb
- app/models/journeys/get_a_teacher_relocation_payment.rb
- app/models/journeys/teacher_student_loan_reimbursement.rb
This method is a concern of the journey, not the claim callbacks.
> Move journey_requires_student_loan_details method

- app/controllers/admin/tasks_controller.rb
When the matching_details task fails to save we need to make sure we're
setting the `@matching_details` ivar otherwise the view errors.
> Handle task save failure

- app/controllers/admin/payroll_runs_controller.rb
- app/jobs/payroll_run_job.rb
- app/models/payroll_run.rb
- app/views/admin/payroll_runs/_complete.html.erb
- app/views/admin/payroll_runs/_failed.html.erb
- app/views/admin/payroll_runs/_pending.html.erb
- app/views/admin/payroll_runs/show.html.erb
- config/analytics.yml
- db/migrate/20241111114155_add_status_to_payroll_runs.rb
- db/schema.rb
- db/test_seeders/data_importer.rb
- spec/factories/payroll_runs.rb
- spec/features/admin/admin_payroll_runs_spec.rb
- spec/jobs/payroll_run_job_spec.rb
- spec/models/payroll_run_spec.rb
- spec/requests/admin/admin_payroll_runs_spec.rb
- spec/support/admin_view_claim_feature_shared_examples.rb
- spec/support/admin_view_claim_logged_in_with_tid_feature_shared_examples.rb
Creating the November payroll run timed out (October's too).
This commit moves creating the payment records into a background job.
We need to pass the claim ids and topup ids to the background job, this
is because once the admin has reviewed the claims that will be part of
this payroll run (shown in the `new` action) we can't include any claims
created in the interim. We may want to consider someother method of
indicating what claims should be part of this payroll run (create
pending payments? flag claims / topups as reviewed for payroll?) so we
don't have to pass such a large amount of information to the background
job. Have tested this with production data and it runs fine passing all the ids.
Not sure if the payroll numbers are public so have put the video walk through of testing this …
> Move payroll run to background job

- app/views/admin/tasks/payroll_details.html.erb
- spec/features/admin/admin_claim_payroll_details_task_spec.rb
When viewing the payroll details task for scrubbed claims we were
throwing an error as `hmrc_bank_validation_responses` is `nil`.
> Fix payroll details task for scrubbed claims

- app/models/eligible_fe_providers_importer.rb
- lib/analytics_importer.rb
- lib/csv_importer/base.rb
- spec/lib/analytics_importer_spec.rb
- spec/lib/csv_importer/base_spec.rb
Calling the rake task on production throws an error as the rake tasks
aren't loaded. To resolve this, rather than invoking the rake task we'll
call the code the rake task calls.
The test is probably a bit OTT but we want to make sure updates to the
gem don't break the interface we're now using.
See
https://github.com/DFE-Digital/dfe-analytics/blob/212e0a7e7d1e27ba434080387b3f7b020f082b1a/lib/dfe/analytics/tasks/import_entities.rake#L18
for implementation of the `import_entity` task.
> Replace call to rake task

- db/migrate/20241113111916_fe_providers_unique.rb
- db/migrate/20241113112028_ey_providers_unique.rb
- db/schema.rb
- Ensure we can't have duplicate data for FE + EY providers
- Need to check there is no duplicate date first before deploying
> unique indexes for FE + EY providers

- app/jobs/early_years_progress_emails_job.rb
- app/jobs/send_emails_after_three_weeks_job.rb
- app/mailers/early_years_payments_mailer.rb
- app/models/base_policy.rb
- app/models/claim.rb
- app/models/policies/early_years_payments.rb
- config/initializers/core_ext.rb
- lib/core_ext/date.rb
- spec/jobs/early_years_progress_emails_job_spec.rb
- spec/mailers/early_years_payments_mailer_spec.rb
- spec/models/claim_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1908
- EY no longer gets the every 3 week progress update emails
- This is managed with a new flag to set or unset this behaviour
- Instead it gets an different progress email sent at 2 and 5 months after submission
- Theres fair bit of additional coding to handle months not have the same number of days
- I've opted not to used arguments in mailer calls as previously done in this codebase but use `.with` and `params` instead as shown in rails guides
> [CAPT-1908] EY progress update emails

- app/mailers/claim_mailer.rb
Useful for grabbing magic links etc
> Log emails in dev

- app/controllers/concerns/form_submittable.rb
- app/forms/current_school_form.rb
- app/forms/form.rb
- app/forms/journeys/early_years_payment/provider/authenticated/current_nursery_form.rb
- app/forms/journeys/early_years_payment/provider/authenticated/returner_form.rb
- app/forms/journeys/early_years_payment/provider/authenticated/returner_worked_with_children_form.rb
- app/forms/journeys/early_years_payment/provider/authenticated/start_date_form.rb
- app/forms/journeys/get_a_teacher_relocation_payment/entry_date_form.rb
- app/forms/journeys/get_a_teacher_relocation_payment/start_date_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/claim_school_form.rb
- app/forms/personal_details_form.rb
- app/models/journeys/base.rb
- app/models/journeys/early_years_payment/provider/authenticated/answers_presenter.rb
- spec/features/early_years_payment/provider/authenticated/changing_answers_spec.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/returner_form_spec.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/returner_worked_with_children_form_spec.rb
- spec/support/steps/early_years_provider_journey_authenticated.rb
- https://dfedigital.atlassian.net/browse/CAPT-1984
- The ticket is actually for removing a change link on EY check answers page which should not be present
- For EY provider journey delete dependent answers
- Inject `session` into `Form` so it is available for reading or manipulation
- Now that `session` is available, delete from `session[:slugs]` visited slugs when clearing dependent answers for EY provider journey
- This solves the problem if:
- a user goes down the extended branch of a journey
- then changes an answer, to shorten the branch
- then changes their answer again to extend the branch
- they are now asked the missing questions rather than sent back to check answers page with incomplete questions
- This bug will likely be present for all journeys where there is possible …
> [CAPT-1984] EY clear dependent answers

- app/controllers/admin/decisions_controller.rb
- app/mailers/early_years_payments_mailer.rb
- app/models/claim_auto_approval.rb
- spec/factories/claims.rb
- spec/features/admin/approvals_spec.rb
When an EY claim is approved we want to send an email to the
practitioner and the provider.
Mailers don't let us send two email from one action, so the approve
method enqueues jobs to send each of the emails.
I think it would probably be better for policies to be told a claim has
been approved and handle policy specific actions like sending emails in
the polciy, so rather than:
`@claimpolicy.mailer.approved(@claim).deliver_later`
we'd do
`@claim.policy.claim_approved(@claim)`
and let the policy determine the action to take (sending emails).
However this is a bit different to how we do things now, so for the time
being we'll just call the mailer, even it it's a bit odd and sends two
emails.
> Send emails when claim approved

- app/controllers/admin/allocations_controller.rb
- app/views/admin/allocations/bulk_deallocate.html.erb
- spec/features/admin/admin_claim_allocation_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1915
- Fix policy name in flash message
- use govuk formbuilder for allocations form
- some simple tidying up:
- removing duplicate code
- using multi line method calls over long single line method calls
> [CAPT-1915] Improve admin allocations

- db/data/20241121115931_remove_student_loan_plan_task_from_claims_with_no_slc_plan.rb
The `ClaimStudentLoanDetailsUpdater` errored, so the `student_loan_plan`
was not set on these claims, however `ClaimStudentLoanDetailsUpdater`
swallows errors so `AutomatedChecks::ClaimVerifiers::StudentLoanPlan`
still ran. `AutomatedChecks::ClaimVerifiers::StudentLoanPlan` looks for
the presence of student loan data in the student_loans_data table but
does not check the claim has a plan when creating the passed task.
This data migration removes the tasks, allowing a future student loan
import to set the plan type on these claims (as they'll now be awaiting
the slc plan task).
See the discussion [here](https://dfedigital.atlassian.net.mcas.ms/browse/CAPT-1964) for more information.
> Remove falsely passed task

- app/models/journeys/early_years_payment/practitioner/answers_presenter.rb
- spec/models/journeys/early_years_payment/practitioner/answers_presenter_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2027
- EY practitioner is now formatted correctly rather than using the raw internal value for payroll gender
> [CAPT-2027] Fix EY practitioner answer

- app/forms/email_address_form.rb
- app/forms/reminders/personal_details_form.rb
- app/mailers/claim_mailer.rb
- app/mailers/reminder_mailer.rb
- app/models/journeys/base.rb
- app/models/journeys/session.rb
- spec/forms/email_address_form_spec.rb
- spec/mailers/claim_mailer_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2013
- For OTP email attach journey as part of the personalisation
- Notify template has yet to be updated and will have to be updated AFTER this has been merged
- We destroy the journey session at the end of the claim journey but the new reminders controller instantiates a new blank session for the correct journey to be able to fetch name
- Random thought is that maybe we want to be able to return journey instances which might present nicer apis rather than dealing with classes
- Not sure if there is a better way to hook up the journey name to the email?
> [CAPT-2013] OTP email now personalises with journey name

- app/jobs/student_loan_amount_check_job.rb
- app/jobs/student_loan_plan_check_job.rb
- app/models/claim_student_loan_details_updater.rb
- spec/jobs/student_loan_amount_check_job_spec.rb
- spec/jobs/student_loan_plan_check_job_spec.rb
- spec/models/claim_student_loan_details_updater_spec.rb
Moves the error handling out of the `ClaimStudentLoanDetailsUpdater` and
into the job that calls it.
When performing an SLC upload, if the `ClaimStudentLoanDetailsUpdater`
errors, and swallows the error, then we can get in a scenario where the
claim doesn't have student loan details set on it but the claim does
have a passing task. As the job uses the presence of the task to
determine which claims need their details updating, subsequent SLC data
uploads don't set the claim's details.
This commit moves the error handling to wrap both the
`ClaimStudentLoanDetailsUpdater` and the `AutomatedCheck`, so we still
preserve the original intention of allowing the rest of the import to go
ahead if one of the claims is throwing an error for some reason.
> Move error handling

- Gemfile
- Gemfile.lock
- package.json
- yarn.lock
- This is a prerequisite to upgrading to rails 8
> Upgrade govuk frontend 5.6.0 => 5.7.1

- .github/workflows/build_and_deploy.yml
Add manual deployment option to the build and deploy workflow
Updates to build_and_deploy.yml
check workflow still runs as expected (build/deploy review on label)
- see https://github.com/DFE-Digital/claim-additional-payments-for-teaching/actions/runs/11935131851
check code
> Add manual env deployment option

- app/forms/claim_submission_base_form.rb
- app/forms/journeys/early_years_payment/practitioner/claim_submission_form.rb
- spec/forms/journeys/early_years_payment/practitioner/claim_submission_form_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2030
- Fix EY claim started at timestamp which is being overwritten when the practitioner starts their half of the journey
- Once deployed will need to retro populate incorrect data which I'll do by hand on the box
> [CAPT-2030] Fix EY started_at timestamp

- app/controllers/admin/journey_configurations_controller.rb
- app/forms/email_address_form.rb
- app/forms/reminders/confirmation_form.rb
- app/forms/reminders/email_verification_form.rb
- app/forms/reminders/personal_details_form.rb
- app/jobs/send_reminder_email_job.rb
- app/jobs/send_reminder_emails_job.rb
- app/mailers/reminder_mailer.rb
- app/models/journeys/base.rb
- app/models/reminder.rb
- app/views/admin/journey_configurations/_ecp_reminder_warning.html.erb
- config/analytics.yml
- db/migrate/20241126105650_add_journey_class_to_reminders.rb
- db/schema.rb
- spec/factories/reminders.rb
- spec/features/admin/admin_configure_services_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/features/reminders_spec.rb
- spec/forms/email_address_form_spec.rb
- spec/jobs/send_reminder_emails_job_spec.rb
- spec/lib/tasks/fix_student_loan_repayment_amounts_spec.rb
- spec/models/reminder_spec.rb
- This PR is based on PR #3175 and has been ported to the current version which has shifted since then
- Migration adds column on reminder to store the relevant journey
- It also populates this column based off the information we have
- Opening a journey still only sends for additional payments but with a small tweak can be made to send reminders for other journeys
> Reminders store journey

- app/models/claim/data_report_request.rb
- spec/models/claim/data_report_request_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2047
- Add missing EY serializer needed to generate admin data report
> [CAPT-2047] Add EY serializer for admin data report

- app/views/further_education_payments/provider/claims/_dfe_sign_in_bypass_form.html.erb
Seems like the rails 8 upgrade broke this form used on review apps,
this commit fixes the field names so nested parameters are sent to the
controller as expected.
> Fix dfe sign in bypass form

- app/models/name_format_validator.rb
- spec/forms/personal_details_form_spec.rb
We have a claim on production with a surname of ".", we want to ensure
that the claimant's name includes at least one letter!
> Check name contains at least one letter

- app/forms/address_form.rb
- spec/forms/address_form_spec.rb
Updates the address validations to be stricter. We now require at least
a single letter in the street part of the address, only letters and
punctuation in the town / city name (no numbers)
> Add stricter address validations

- app/views/layouts/application.html.erb
The EY service hasn't been accessibility tested yet so we want to
temporarily remove the link to the accessibility statement.
> Remove accessibility statment for EY

- app/jobs/application_job.rb
When a job errors we want to be able to easily identify which claim it
was working with, if there is one.
Example [rollbar error with claim reference](https://app.rollbar.com/a/dfe-digital/fix/item/dfe-claims/1529?utm_campaign=new_item_message&utm_medium=slack&utm_source=rollbar-notification)
> Include claim reference in rollbar errors

- app/models/policies/early_career_payments/admin_tasks_presenter.rb
- spec/models/policies/early_career_payments/admin_tasks_presenter_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2090
- Add nil guard where `eligible_itt_subject` is nil in admin area otherwise throws an error
> [CAPT-2090] Add nil guard where eligible_itt_subject is nil

- .github/actions/deploy-environment/action.yml
- .github/workflows/build_and_deploy.yml
- .github/workflows/delete_review_app.yml
- config/initializers/dfe_analytics.rb
- terraform/application/application.tf
- terraform/application/config/production.tfvars.json
- terraform/application/config/review.tfvars.json
- terraform/application/config/test.tfvars.json
- terraform/application/dfe_analytics.tf
- terraform/application/variables.tf
Migrate application to use gcp wif
Adding identity federation for google cloud authentication and big query 
review changes. 
access review app 
check events flowing to GCP
[Claims: migrate to GCP WIF](https://trello.com/c/ZolMBsh6/2175-claims-migrate-to-gcp-wif)
> Migrate gcp wif

- app/views/claims/_one_time_password.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-650
- Enable iOS autocomplete for mobile OTPs
- Tested on iOS safari
- MDN for `autocomplete=one-time-code` https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#one-time-code
- Apple documentation on the feature https://developer.apple.com/news/?id=z0i801mg
> [CAPT-650] Enable OTP autocomplete

- app/models/policies/early_years_payments/admin_tasks_presenter.rb
- spec/models/policies/early_years_payments/admin_tasks_presenter_spec.rb
Displays the urn as part of the nursery name on the admin employment
task view.
> Display the urn on the employment task

- app/controllers/omniauth_callbacks_controller.rb
- app/models/claim.rb
- app/models/journeys/session_answers.rb
- app/models/one_login/core_identity_validator.rb
- config/analytics_blocklist.yml
- db/migrate/20241205121421_add_ol_full_name_to_claims.rb
- db/schema.rb
- spec/factories/claims.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/forms/journeys/further_education_payments/claim_submission_form_spec.rb
- spec/models/automated_checks/claim_verifiers/identity_spec.rb
- spec/models/claim_spec.rb
- spec/models/one_login/core_identity_validator_spec.rb
- spec/requests/omniauth_callbacks_controller_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2051
- We are only storing from OL the first and last name
-  Persist all the names that OL returns
- When checking against OL name we match entered name matches the start and end of returned OL name
- `onelogin_idv_full_name` is no longer a virtual attribute and returns the full name OL returns
- We backfill `onelogin_idv_full_name` with data we have which is concatenation of first and last name
- Once this is complete we can work to remove `onelogin_idv_first_name` and `onelogin_idv_last_name` as these will become redundant
> [CAPT-2051] Better OL name

- terraform/application/config/production.tfvars.json
- terraform/application/statuscake.tf
- terraform/application/variables.tf
The prod apex SSL cert should be monitored by statuscake, nothing else.
- Add apex_url variable
- Change statuscake.tf
make env deploy-plan
- will remove test and www ssl cert monitors, and add prod apex
https://trello.com/c/rumvvcay/2198-capt-apex-domain-not-monitored
> Fix ssl check statuscake monitoring

- app/models/claim/search.rb
- app/views/admin/claims/search.html.erb
- spec/models/claim/search_spec.rb
When reconciling payroll issues the ops team would like the ability to
search for claims by payment id, as this is what's in the payroll CSV.
> Allow searching by payment id

- app/models/claim/search.rb
- spec/models/claim/search_spec.rb
Allow searching for claims by ey details
Until the practitioner has submitted their portion of the claim EY
claims aren't easily searchable in the admin area. This commit makes
them searchable on EY provider details.
> CAPT 2143/admin search not finding ey emails

- app/jobs/file_importer_job.rb
- app/jobs/import_student_loans_data_job.rb
- app/jobs/student_loan_amount_check_job.rb
- app/jobs/student_loan_plan_check_job.rb
- app/models/claim.rb
- app/models/claim_student_loan_details_updater.rb
- app/models/policies/student_loans/eligibility.rb
- app/views/admin/amendments/index.html.erb
- spec/jobs/student_loan_amount_check_job_spec.rb
- spec/jobs/student_loan_plan_check_job_spec.rb
- spec/models/claim_student_loan_details_updater_spec-old.rb
- spec/models/claim_student_loan_details_updater_spec.rb
Create audit trail when SLC upload runs
When the SLC data upload runs we want to use the existing amendments
mechanism to record any changes to the claim. As amending a claim
requires a user to be associated with the amendment we need to pass who
triggered the SLC upload down to the `ClaimStudentLoanDetailsUpdater`.
We've had to slightly change the validation on
`StudentLoans::Eligibility` to check if the repayment amount has changed
as there's one test (`spec/features/admin/upload_slc_data_spec.rb`)
where:
* No SLC data is found for a claim
* The claim has a student_loan_repayment_amount of `0`
* The claim's plan is expected to change from `not_applicable` to `nil`
* The claim's `has_student_loan` is expected to change from `false` to
`nil`
Without changing the validation on the …
> CAPT 2083/slc upload audit

- app/controllers/application_controller.rb
- config/routes.rb
- spec/routes/routes_spec.rb
Previously we were blocking some specific head requests however rollback is triggering on head requests from email clients. We want to just return a 400 rather than generate an error.
Not sure how we want to QA this one, curl does what we'd expect
```
curl -I https://localhost:3000/additional-payments/landing-page
HTTP/1.1 400 Bad Request
```
> Block all head requests

- config/analytics.yml
- config/analytics_blocklist.yml
- config/analytics_hidden_pii.yml
- spec/lib/analytics_importer_spec.rb
Data and Insights have informed us that BigQuery is now allowed to
handle storing PII. This commit moves the requested fields from the
block list to the "clear" analytics config to allow them to be synced
over.
> Move fields to the "clear" config

- app/controllers/admin/reports_controller.rb
- app/jobs/reports_job.rb
- app/models/policies/further_education_payments/eligibility.rb
- app/models/report.rb
- app/models/reports/duplicate_claims.rb
- app/models/reports/failed_provider_check_claims.rb
- app/models/reports/failed_qualification_claims.rb
- app/views/admin/claims/index.html.erb
- app/views/admin/reports/index.html.erb
- app/views/application/_admin_menu.html.erb
- config/analytics_blocklist.yml
- config/initializers/filter_parameter_logging.rb
- config/routes.rb
- db/migrate/20241007141638_create_reports.rb
- db/schema.rb
- spec/factories/reports.rb
- spec/features/admin/reports_spec.rb
- spec/models/reports/duplicate_claims_spec.rb
- spec/models/reports/failed_provider_check_claims_spec.rb
- spec/models/reports/failed_qualification_claims_spec.rb
* new nav bar entry on the admin site: Reports
* reports page shows previously ran reports
* reports stored in database
* ReportsJob set to run on second Tuesday of each month
* Report classes based on the existing `Claim::DataReportRequest` class
> [CAPT-1797] Ops reports

- app/views/admin/support_tickets/_widget.html.erb
EY claims that are awaiting the practitioner to complete their half of
the claim don't have an email address, so we can't link to the zendesk
search by email page.
> Don't render link if no email

- app/models/reports/failed_qualification_claims.rb
- app/models/task.rb
- spec/factories/tasks.rb
- spec/models/reports/failed_qualification_claims_spec.rb
Some tweaks to the DQT qualifications report:
- **Include claims which failed dqt checks**
- **Pull dqt data from notes**
Might be easier to review each commit separately.
> CAPT 1797/qualification report tweak

- app/views/claims/information_provided.html.erb
- app/views/further_education_payments/claims/information_provided.html.erb
- spec/features/early_career_payments/early_career_payments_claim_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/features/tslr/tslr_claim_journey_with_teacher_id_check_email_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1335
- Update `information provided` pages to include SLC
> [CAPT-1335] Copy tweak: update info provided with SLC

- app/models/automated_checks/claim_verifiers/early_years_payments/identity.rb
- app/models/policies/early_years_payments/admin_tasks_presenter.rb
- app/models/policies/early_years_payments/eligibility.rb
- app/views/admin/tasks/early_years_payments/identity_confirmation.html.erb
- spec/features/admin/admin_ey_tasks_spec.rb
- spec/models/policies/early_years_payments/admin_tasks_presenter_spec.rb
In order to highlight why the IDV task might have failed we want to
display the DOB returned from one login and the DOB entered by the
claimant.
A quirk of the designs is that we show the claimant entered DOB in the
"Provider entered claimant name" row.
> Show the ol and claimant entered DOB

- app/helpers/admin/claims_helper.rb
- app/helpers/admin/timeline_helper.rb
- app/models/automated_checks/claim_verifiers/early_years_payments/identity.rb
- app/models/policies/early_years_payments/admin_claim_details_presenter.rb
- app/models/policies/early_years_payments/admin_tasks_presenter.rb
- app/views/admin/tasks/_claim_summary.html.erb
- app/views/admin/tasks/_claim_summary_early_years_payments.html.erb
- app/views/admin/tasks/_claim_summary_further_education_payments.html.erb
- app/views/admin/tasks/_claim_summary_international_relocation_payments.html.erb
- spec/features/admin/admin_amend_claim_spec.rb
- spec/features/admin/admin_ey_tasks_spec.rb
- spec/features/admin/admin_view_claim_early_years_payments_spec.rb
- spec/features/admin/admin_view_full_claim_early_years_payments_spec.rb
- spec/features/admin/admin_view_full_claim_further_education_payments_spec.rb
- spec/helpers/admin/claims_helper_spec.rb
- spec/helpers/admin/timeline_helper_spec.rb
- spec/models/policies/early_years_payments/admin_claim_details_presenter_spec.rb
- spec/models/policies/early_years_payments/admin_tasks_presenter_spec.rb
Standardise dates in the admin area
Requirement is to standardise on %d/%m/%Y when displaying dates in the
admin area. We've added a new locale format `admin_date` which we now
use throughout the admin area when displaying a date or datetime.
> CAPT 1941/admin date formats

- app/models/journeys/get_a_teacher_relocation_payment/answers_presenter.rb
- spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
- spec/models/journeys/get_a_teacher_relocation_payment/answers_presenter_spec.rb
The dates displayed on the check your answers page weren't in the
standard govuk format.
> Fix date format

- app/views/admin/notes/_note.html.erb
ITHC flagged this one. We still need to be able to render `span` and
`pre` tags as these are generated by some automated notes, we also need
to be able to set the `class` attribute as CAPT-2033 introduced some
colours to some of the automated notes.
> Don't allow admins to enter (most) html

- app/forms/email_address_form.rb
- app/forms/reminders/personal_details_form.rb
- app/forms/select_email_form.rb
- app/models/eligible_fe_provider.rb
- app/validators/email_address_format_validator.rb
- config/application.rb
- spec/validators/email_address_format_validator_spec.rb
Updates our email address validation to, mostly, match the validation
logic in notify. To avoid pulling in a gem to the project we're not
converting to puny code so some domains like `müller-büromöbel.de` won't
be permitted. If we want to support these domains we can convert them to
puny code and validate that
`https://github.com/alphagov/notifications-utils/blob/e89dcc53c7f88ef23053d1efb2c00b8ef2ea377e/notifications_utils/recipient_validation/email_address.py#L38`
The email validation code in notify seems pretty stable, having last
changed in 2022.
**Other option is to just rescue notify api errors and add a validation error** might be simpler.
> Make email address validation notify compliant

- app/forms/postcode_search_form.rb
- app/forms/select_home_address_form.rb
- app/models/journeys/further_education_payments/slug_sequence.rb
- app/views/claims/select_home_address.html.erb
- config/locales/en.yml
- spec/features/further_education_payments/jump_around_spec.rb
- As part of the navigator/state.machine work applied to FE journey there was a regression where for the FE journey searching for postcode then either choosing an address result or then opting to manually enter address was not working as desired. This PR should address these issues with extra coverage to ensure no future regressions
> FE address fix

- app/controllers/admin/base_admin_controller.rb
We already set the max-age=0, private, must-revalidate directives but we
need to add no-store so the pages don't show up in the BF cache.
ITHC picked up an issue where after logging out of the admin area
hitting the back button renders a logged in page, seems like it's BF
cache doing this.
> Don't cache admin pages

- app/controllers/admin/payments_controller.rb
- app/models/payment.rb
- app/views/admin/payments/index.html.erb
- app/views/admin/payments/show.html.erb
- app/views/admin/payroll_runs/_complete.html.erb
- config/routes.rb
- spec/features/admin/admin_views_payment_spec.rb
- spec/models/payment_spec.rb
Add payments show resource
The claim payments index shows the payments belonging to a specific
claim, however a payment can contain multiple claims and topups, this
commit adds a payment show page where admins can view all the claims and
topups belonging to a payment along with a summary of the various
payment amounts.
> Payments show

- maintenance_page/manifests/maintenance/deployment_maintenance.yml.tmpl
As per ITHC, set below for maintenance app deployment
- allowPrivilegeEscalation: false
- runAsNonRoot: true
Update to deployment file
Tested in another service which has the same config (GIT)
> Add security recommendations to maint page

- app/models/reports/failed_qualification_claims.rb
- spec/models/reports/failed_qualification_claims_spec.rb
Request from Dan to include any payment ids in the failed qualifications
report.
> Add payment_id to qualifications report

- app/jobs/qualifications_no_match_check_job.rb
- app/jobs/student_loan_amount_check_job.rb
- app/models/automated_checks/claim_verifiers/employment.rb
- app/models/base_policy.rb
- app/models/concerns/eligibility_checkable.rb
- app/models/journeys/additional_payments_for_teaching/answers_presenter.rb
- app/models/policies/targeted_retention_incentive_payments/dqt_record.rb
- app/models/policies/targeted_retention_incentive_payments/eligibility.rb
- app/models/policies/targeted_retention_incentive_payments/school_eligibility.rb
- app/models/teachers_pensions_service.rb
- db/test_seeders/claims_importer.rb
- docs/claims_with_lup_uplifts_report.md
- spec/factories/journeys/additional_payments_for_teaching/session_answers.rb
- spec/factories/policies/early_career_payments/eligibilities.rb
- spec/factories/targeted_retention_incentive_payments/awards.rb
- spec/factories/targeted_retention_incentive_payments/eligibilities.rb
- spec/features/admin/admin_claim_tasks_update_with_dqt_api_spec.rb
Add current_academic_year to policy
In quite a few places in the app we're getting the current academic year
from the policy by going through the journey. This commit adds a method
to the base policy to return the current academic year to avoid the
chained method calls, and make it easier to overwrite this method if
needs be.
Ideally we'd be able to use `AcademicYear.current` however there are
some scenarios, such as in QA,  where being able to run a journey in a
different acadmic year is useful.
> move current academic year

- app/controllers/concerns/form_submittable.rb
This method is overwritten in the claims controller by the delegation to
the PageSequence#slugs method, so it never used.
> Remove slugs method

- app/models/concerns/boolean_attributes.rb
- app/models/journeys/additional_payments_for_teaching/session_answers.rb
- app/models/journeys/further_education_payments/session_answers.rb
- app/models/journeys/session_answers.rb
- app/models/journeys/teacher_student_loan_reimbursement/session_answers.rb
Automatically define predicate methods for bools
Working on adding a new journey and remembering to add the predicate
methods for boolean attributes is a bit annoying. ActiveRecord gives us
these methods for boolean columns but ActiveModel doesn't do the same
for boolean attributes. This commit adds some functionality to define
predicate methods for boolean attributes and removes our previous manual
implementations.
> define predicate methods

- app/models/claim.rb
- app/models/policies/early_career_payments.rb
- app/models/policies/early_years_payments.rb
- app/models/policies/further_education_payments.rb
- app/models/policies/international_relocation_payments.rb
- app/models/policies/student_loans.rb
- app/models/policies/targeted_retention_incentive_payments.rb
- app/views/admin/decisions/_decision_form.html.erb
- spec/features/admin/admin_reject_claim_spec.rb
- spec/features/admin/approvals_spec.rb
- spec/models/claim_spec.rb
- spec/support/admin_checks_feature_shared_examples.rb
- spec/support/have_received_email_matcher.rb
- spec/support/stubbing_helpers.rb
Flag 10% of rejected claims for QA
The requirement for this ticket was to flag a random 10% of all rejected
claims for QA, as such we can use a simpler implementation for picking
10% of claims than we use for approval by just using `rand`.
> CAPT-2235/qa rejected claims

- app/helpers/admin/claims_helper.rb
Now the data migration has been run we don't need this special case
handling.
Don't merge until data-migration-policy-options has been run on production
> Revert bugfix

- app/forms/form.rb
- app/forms/journeys/additional_payments_for_teaching/eligibility_confirmed_form.rb
- app/forms/journeys/early_years_payment/provider/authenticated/returner_contract_type_form.rb
- app/forms/journeys/further_education_payments/building_construction_courses_form.rb
- app/forms/journeys/further_education_payments/chemistry_courses_form.rb
- app/forms/journeys/further_education_payments/computing_courses_form.rb
- app/forms/journeys/further_education_payments/contract_type_form.rb
- app/forms/journeys/further_education_payments/early_years_courses_form.rb
- app/forms/journeys/further_education_payments/engineering_manufacturing_courses_form.rb
- app/forms/journeys/further_education_payments/fixed_term_contract_form.rb
- app/forms/journeys/further_education_payments/further_education_teaching_start_year_form.rb
- app/forms/journeys/further_education_payments/half_teaching_hours_form.rb
- app/forms/journeys/further_education_payments/hours_teaching_eligible_subjects_form.rb
- app/forms/journeys/further_education_payments/maths_courses_form.rb
- app/forms/journeys/further_education_payments/physics_courses_form.rb
- app/forms/journeys/further_education_payments/provider/verify_claim_form.rb
- app/forms/journeys/further_education_payments/subjects_taught_form.rb
- app/forms/journeys/further_education_payments/taught_at_least_one_term_form.rb
- app/forms/journeys/further_education_payments/teaching_hours_per_week_form.rb
- app/forms/journeys/further_education_payments/teaching_hours_per_week_next_term_form.rb
- app/forms/journeys/further_education_payments/teaching_qualification_form.rb
- app/forms/journeys/further_education_payments/teaching_responsibilities_form.rb
- app/forms/poor_performance_form.rb
- app/forms/provide_mobile_number_form.rb
- spec/forms/journeys/further_education_payments/further_education_teaching_start_year_form_spec.rb
As part of the LUP separate journey work I've found myself introducing a
Struct to represent form options in a couple of forms. This commit adds
an Option class to the base form and replaces usage of OpenStruct with
it. We use a class rather than a Struct as we have some optional key
words.
`value` and `label` would probably make more sense as attribute names
but the existing code, and the form builder docs, use `id` and `name` so
we've stuck with them.
> Add Form::Option

- app/models/journeys/further_education_payments/provider/slug_sequence.rb
- app/views/further_education_payments/provider/claims/expired_link.html.erb
- spec/features/further_education_payments/provider/provider_verifying_claims_spec.rb
If the claim has been rejected we don't want the provider to be able to
verify the cliam.
The FormSubmittable module assumes there is a next slug or we want to
define a callback if there isn't one. In our use case we don't want to
define a callback and there is no next slug, so the simplest work around
is to just have two "expired-link" slugs.
[CAPT-2241](https://dfedigital.atlassian.net/browse/CAPT-2241)
[CAPT-2241]: https://dfedigital.atlassian.net/browse/CAPT-2241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Don't allow verifying rejected claims

- app/controllers/admin/decisions_controller.rb
- app/models/claim_auto_approval.rb
- app/models/decision.rb
- app/models/policies/claim_personal_data_scrubber.rb
- app/views/admin/decisions/_decision_form.html.erb
- app/views/admin/decisions/new.html.erb
- config/analytics.yml
- db/migrate/20250210161815_make_approved_non_null.rb
- db/schema.rb
- spec/factories/claims.rb
- spec/factories/decisions.rb
- spec/features/admin/admin_claim_check_spec.rb
- spec/features/admin/admin_fraud_prevention_spec.rb
- spec/features/admin/admin_hold_claim_spec.rb
- spec/helpers/admin/claims_helper_spec.rb
- spec/jobs/auto_approve_claim_job_spec.rb
- spec/models/claim_auto_approval_spec.rb
- spec/models/claim_spec.rb
- spec/models/decision_spec.rb
- spec/requests/admin/admin_decisions_spec.rb
Make the approved column non nullable
Now the backfill has run and we've checked the data on prod we can make
the approved column non nullable as it doesn't make sense to create a
decision without out a value for approved.
Now we've backfilled the existing records we can remove the enum
definition and reference the `approved` column.
We'll drop the `result` column in a future PR.
> CAPT 1473/convert decision enum to boolean part 2

- app/models/journeys/navigator.rb
If `action_on_unpermitted_parameters` is set to `:raise`, which is
useful in development, we can't pass all params to the form objects in
the navigator otherwise `Forms::Form#permitted_params` will error.
To avoid this we slice out the params the form object accepts.
> Handle permitted params

- app/models/decision.rb
This column has been dropped but since removing this line we're getting
errors on production.
> Ignore result column

- app/controllers/omniauth_callbacks_controller.rb
- app/models/stat.rb
- app/models/stats/one_login.rb
- config/analytics.yml
- config/initializers/omniauth.rb
- db/migrate/20250213153245_create_stats_table.rb
- db/migrate/20250214095211_add_type_to_stats.rb
- db/schema.rb
- spec/requests/omniauth_callbacks_controller_spec.rb
- ~Prior to merge MUST enable return codes in OL first + enable claim `returnCode` otherwise this feature will not work~
- This has been completed
- https://dfedigital.atlassian.net/browse/CAPT-2195
- This adds the `returnCode` claim to the OL idv check
- Create a new db backed `Stat` model to store arbitrary stat data points
- Store any OL return codes into this `Stat` model
> [CAPT-2195] OL return codes

- app/forms/admin/amendment_form.rb
- app/models/policies/further_education_payments/eligibility.rb
- spec/forms/admin/amendment_form_spec.rb
- When admin amends a claim and does not choose a student loan plan
- Browser sends this as empty string
- On the backend this is stored as nil
- So on validation of form we convert empty string to nil
- This allows the form to be saved and not raise an error
- Also fixes regression and FE award amount + TRN is now amendable again
> Fix admin amend claim

- app/controllers/concerns/part_of_claim_journey.rb
- app/controllers/journeys/early_years_payment/provider/start/static_pages_controller.rb
- app/controllers/static_pages_controller.rb
- app/controllers/submissions_controller.rb
- app/forms/claim_submission_base_form.rb
- app/forms/journeys/session_form.rb
- app/models/journeys/base.rb
- app/models/journeys/service_access_code.rb
- app/models/journeys/session.rb
- app/models/journeys/session_answers.rb
- app/views/additional_payments/landing_page.html.erb
- app/views/early_years_payment/provider/start/landing_page.html.erb
- app/views/further_education_payments/landing_page.html.erb
- app/views/get_a_teacher_relocation_payment/landing_page.html.erb
- app/views/student_loans/landing_page.html.erb
- config/analytics_blocklist.yml
- db/migrate/20250207140932_create_journeys_service_access_codes.rb
- db/migrate/20250226151104_add_used_to_journeys_service_access_codes.rb
- db/schema.rb
- spec/factories/journeys/service_access_code.rb
- spec/features/accessing_closed_service_spec.rb
- spec/models/journeys/service_access_code_spec.rb
Adds service access code
Service access codes are a mechanism for allowing claimants to access
the service outside of the claim window.
These links will be created adhoc by developers in the console
```rb
Journeys::ServiceAccessCode.create!(
journey: Journeys::FurtherEducationPayments
)
```
Some of the journeys are started via an email link
* FE provider
* EY provider authenticated
* EY practition
For these journeys we can either
* open the journey as needed (should be ok as they're not generally
accessible)
* manually construct the links to include a service access code and tell
the users to ignore links received by email
* update the code to include service access codes in any emails if the
emails were triggered by a session containing a service access code
For now we've not implemented …
> CAPT-2189/closed service access

- app/controllers/admin/amendments_controller.rb
- app/controllers/admin/auth_controller.rb
- app/forms/admin/amendment_form.rb
- app/models/dfe_sign_in/user.rb
- app/views/admin/amendments/new.html.erb
- app/views/admin/auth/sign_in.html.erb
- config/routes.rb
- spec/features/admin/admin_amend_claim_spec.rb
- spec/forms/admin/amendment_form_spec.rb
- spec/support/feature_helpers.rb
- https://dfedigital.atlassian.net/browse/CAPT-2180
- All back office users can view banking name in the amend screen if the call to HMRC failed
- If HMRC check passed back office users do not see the banking name
- If back office user has admin role that can amend the banking name
- For other back office users they will have the field disabled
- Developer auth can now login as normal or admin back office user
> [CAPT-2180] Amend banking name

- .github/workflows/build-nocache.yml
Add build-no-cache workflow, to allow rebuilding the docker image without using cached layers.
See test run https://github.com/DFE-Digital/claim-additional-payments-for-teaching/actions/runs/13787371200
> Add build-no-cache workflow

- app/controllers/omniauth_callbacks_controller.rb
- app/forms/journeys/further_education_payments/claim_submission_form.rb
- app/models/automated_checks/claim_verifiers/identity.rb
- app/models/journeys/session_answers.rb
- app/views/claims/_sign_in.html.erb
- app/views/claims/_sign_in_3_not_identified.html.erb
- config/analytics.yml
- db/migrate/20250227151439_add_ol_claim_return_codes.rb
- db/schema.rb
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
- spec/features/further_education_payments/one_login_without_idv_spec.rb
- spec/rails_helper.rb
- spec/support/feature_flags.rb
- spec/support/feature_helpers.rb
- spec/support/one_login_helper.rb
- spec/support/steps/early_years_practitioner_journey.rb
- https://dfedigital.atlassian.net/browse/CAPT-2249
- Allow users who cannot pass OL idv to continue their journey
- For review app testing this always makes the user fail OL idv
- In order to achieve this more explicit mocking of OL has had to be added to tests
- We store their OL return codes onto their session and subsequently their claim when created
> [CAPT-2249] OL without idv

- app/forms/journeys/further_education_payments/passport_form.rb
- app/models/journeys/further_education_payments.rb
- app/models/journeys/further_education_payments/answers_presenter.rb
- app/models/journeys/further_education_payments/session_answers.rb
- app/models/journeys/further_education_payments/slug_sequence.rb
- app/views/further_education_payments/claims/passport.html.erb
- config/analytics.yml
- config/analytics_blocklist.yml
- config/locales/en.yml
- db/migrate/20250310152749_add_passport_to_fe_eligibilities.rb
- db/schema.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/features/further_education_payments/one_login_without_idv_spec.rb
- spec/forms/journeys/further_education_payments/passport_form_spec.rb
- spec/models/policies/targeted_retention_incentive_payments/award_csv_importer_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2270
- Collects passport number for FE as part of alternative idv journey
- Also fixed an rspec warning
> [CAPT-2270] FE alternative idv collects passport

- app/models/automated_checks/claim_verifiers/one_login_identity.rb
- app/models/claim_checking_tasks.rb
- app/models/feature_flag.rb
- app/models/policies/early_career_payments/claim_checking_tasks.rb
- app/models/policies/early_years_payments/claim_checking_tasks.rb
- app/models/policies/further_education_payments.rb
- app/models/policies/further_education_payments/claim_checking_tasks.rb
- app/models/policies/international_relocation_payments/claim_checking_tasks.rb
- app/models/policies/student_loans/claim_checking_tasks.rb
- app/models/policies/targeted_retention_incentive_payments/claim_checking_tasks.rb
- app/models/task.rb
- app/views/admin/_task_pagination.html.erb
- app/views/admin/tasks/_one_login_idv.html.erb
- app/views/admin/tasks/index.html.erb
- app/views/admin/tasks/one_login_identity.html.erb
- config/locales/en.yml
- db/migrate/20250313111812_split_ol_identity_tasks.rb
- db/schema.rb
- spec/features/admin/admin_claim_further_education_payments_spec.rb
- spec/features/admin/tasks/identity_confirmation_spec.rb
- spec/models/automated_checks/claim_verifiers/identity_spec.rb
- spec/models/automated_checks/claim_verifiers/one_login_identity_spec.rb
- spec/models/further_education_payments_spec.rb
- spec/models/policies/further_education_payments/claim_checking_tasks_spec.rb
- spec/support/admin_checks_feature_shared_examples.rb
- spec/views/admin/tasks/index.html.erb_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2279
- FE OL task is now a separate task from identity confirmation
- This includes a data migration to acheive this
- EY should not be affected by these changes and remain the same
- We now have finer grain control of tasks name in admin area by using locales lookups rather than simply `humanize` the task name
- Finish refactoring of checking claim tasks by extracting to classes
- Rename task names on front end based on if feature flag is toggled
- The whole task thing and names is rather messy. i think this whole area needs some thinking on how we best make tasks a lot more flexible
> [CAPT-2279] Split out FE OL task

- app/helpers/admin/claims_helper.rb
- app/models/automated_checks/claim_verifiers/one_login_identity.rb
- app/models/task.rb
- app/views/admin/tasks/_task_outcome.html.erb
- app/views/admin/tasks/_task_outcome_one_login_identity.html.erb
- app/views/admin/tasks/identity_confirmation.html.erb
- app/views/admin/tasks/one_login_identity.html.erb
- config/analytics.yml
- db/migrate/20250317120537_add_reason_to_tasks.rb
- db/schema.rb
- spec/helpers/admin/claims_helper_spec.rb
- spec/models/automated_checks/claim_verifiers/one_login_identity_spec.rb
- spec/views/admin/tasks/one_login_identity.html.erb_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2281
- Able to add reason to a task which can then surfaced back to the admin
- in order to for admin task view to consider the task being viewed. this will now delegate to relevant partial if it exists
> [CAPT-2281] One login task status

- app/views/layouts/admin.html.erb
- app/views/layouts/application.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-2194
- Added titles to iframes, although, not really needed though as the iframes are hidden. don't see any harm in doing so
> [CAPT-2194] add titles to iframes

- app/forms/journeys/early_years_payment/provider/authenticated/claim_submission_form.rb
- app/mailers/early_years_payments_mailer.rb
- app/models/eligible_ey_provider.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/claim_submission_form_spec.rb
If there are two key contacts for an eligibilitie ey provider, when one
of them submits their part of the claim email both contacts.
> Send emails to both contacts

- app/helpers/admin/claims_helper.rb
- app/models/automated_checks/claim_verifiers/alternative_identity_verification.rb
- app/models/claim.rb
- app/models/journeys/further_education_payments/provider/session_answers.rb
- app/models/policies/further_education_payments.rb
- app/models/policies/further_education_payments/admin_alternative_identity_verification_task_presenter.rb
- app/models/policies/further_education_payments/admin_tasks_presenter.rb
- app/models/policies/further_education_payments/claim_checking_tasks.rb
- app/models/task.rb
- app/models/tasks.rb
- app/views/admin/tasks/_alternative_identity_verification_submitted.html.erb
- app/views/admin/tasks/alternative_identity_verification.html.erb
- app/views/admin/tasks/provider_verification.html.erb
- config/locales/en.yml
- spec/factories/policies/further_education_payments/eligibilities.rb
- spec/features/admin/admin_claim_further_education_payments_spec.rb
- spec/models/automated_checks/claim_verifiers/alternative_identity_verification_spec.rb
- spec/models/further_education_payments_spec.rb
- spec/models/policies/further_education_payments/claim_checking_tasks_spec.rb
- spec/models/tasks_spec.rb
If a claimant fails one login IDV we need to ask the provider to verify
the claimants identity. This commit adds the new task to the admin area
to track this alternative identity verification.
When a claim is considered to be a duplicate we don't automatically send
the verification email to the provider, it needs to be manually
triggered by an ops team member. The designs call for showing the resend
verification email on both the `alternative_identity_verification` and
`provider_verification` task views, both designs for this are the same,
so we've reused the parital from the `provider_verification` that
already handles this.
> CAPT 2280/alternative idv task

- app/controllers/admin/decisions_controller.rb
- app/models/base_policy.rb
- app/models/decision.rb
- app/models/policies/further_education_payments.rb
- app/views/admin/decisions/_decision_form.html.erb
- config/locales/en.yml
- spec/features/admin/admin_claim_further_education_payments_spec.rb
- spec/features/admin/admin_reject_claim_spec.rb
- spec/models/decision_spec.rb
- spec/models/policies/further_education_payments_spec.rb
Add alt idv rejection reason
We want a new rejection reason for claims that have failed alternative
identity verification. We only want this rejection reason to be
avalabile after 31st March.
The tricky bit is any rejection reasons we add to the notify template
need to be sent for all rejection emails. To handle this we only include
the rejection reason in the list of reasons admins see if the claim
requires alternative identity verification (which is feature flagged)
however the `Decision#rejected_reasons_hash` which is what is sent to
notify unconditionally includes this reason.
The `FurtherEducationPayments` policy class now has quite a few methods
that take a `Claim` as their only argument, while this works fine and is
pretty maintainable, it hints that we're missing some object.
> CAPT 2283/new rejection reason

- app/models/policies/further_education_payments.rb
- spec/features/admin/admin_claim_further_education_payments_spec.rb
Don't allow approving if alt idv failed
If the alternative identity verification failed we don't want to allow
admins to approve a claim.
> CAPT 2310/cant approve claim with failed idv

- app/controllers/omniauth_callbacks_controller.rb
- app/models/feature_flag.rb
- app/views/claims/_sign_in_2_authed.html.erb
- app/views/claims/_sign_in_2_bypass.html.erb
- spec/features/admin/admin_ey_tasks_spec.rb
Add form for test users to set return codes
In environments where we're bypassing one login we now present a form to
testers where they can enter details that would be returned from one
login, along with setting the desired one login return codes.
Now, rather than failing IDV in test based on the `alternative_idv`
feature flag we fail/pass IDV based on the presence of return codes
entered in the form.
Due to some quirks of how the form builder works, we've had to reuse the
`PersonalDetailsForm` to support this functionality. We subclass the
`PersonalDetailsForm` in the controller as `OneLoginTestUser` to make
bypassing it in tests more straightforward.
I think a slightly nicer approach would be to update the
`test_user_auth_hash` method to return a JWT with the content we want,
so we only …
> CAPT 2313/ol review app functionality

- app/models/policies/early_years_payments/eligibility.rb
We can't find the provider for EY claims in the following scenario:
* EY claim submitted for provider A
* EY provider CSV is updated to no longer include provider A
In the admin area and in reports we need to show who the provider was even
if the eligible providers list has been updated.
To resolve this we're unscoping the default scope when looking for the
provider and picking the latest one with a matching urn.
We probably want to revisit our use of default scope.
Additionally we should move `eligible_ey_provider` to a scope on the
eligibility, this will make queries easier to run, and we should look
into why we're using `find_by`, there should always be an ey provider
for a submitted claim, so we should use `find_by!` or equivalent.
> Fix missing nursery name in report

- app/assets/stylesheets/components/button_to.scss
When the sign out button is focused we want to high light it to meet
WCAG guidance.
> Highlight sign out on focus

- app/views/early_years_payment/provider/authenticated/claims/consent.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-2318
- Improve a11y by removing superfluous fieldset from EY consent checkbox
> [CAPT-2318] remove fieldset from EY consent checkbox

- .github/actions/deploy-environment/action.yml
We have noticed that when deploying changes including database migrations, dfe-analytics stops sending ActiveRecord-related events. Web request events still work. This is because dfe-analytics is [rescuing the exception and failing to initialise](https://github.com/DFE-Digital/dfe-analytics/blob/ad9e5a24296aa4bf755d04ceb96ad21f7f8c76d8/lib/dfe/analytics.rb#L134).
We are advised that moving the `prepare-database` step to before `terraform-apply` should resolve this.
> Fix pending database migrations preventing dfe-analytics initialisation

- app/models/concerns/eligibility_checkable.rb
- app/models/policies/early_career_payments/policy_eligibility_checker.rb
This method doesn't need to be shared with LUP as there will always be a
selectable LUP subject.
When calculating the subject_symbols for LUP/TRI we return an empty
array if the itt year is earlier than the previous 5 years, however we
only show the previous 5 years as options for selecting the itt year,
and if the user chooses "none of the above", they're kicked out of the
journey before this screen by the `ineligible_cohory?` check.
`Policies::TargetedRetentionIncentivePayments.subject_symbols` should
just reduce to
`Policies::TargetedRetentionIncentivePayments.fixed_subject_symbols` but
we'll refactor towards that in a separate commit.
> Move no_selectable_subjects?

- app/models/automated_checks/claim_verifiers/early_years_payments/identity.rb
- app/models/policies/early_years_payments/eligibility.rb
- spec/models/policies/early_years_payments/eligibility_spec.rb
Strip whitespace
When comparing names we don't want to fail just because the provider
added whitespace before or after the name
> CAPT 2377/ey ol partial matches

- app/views/shared/_backlink.html.erb
Feedback from WCAG audit, we need to contain the back link in a landmark
so screen readers can find it more easily.
> Add landmark for screen readers

- app/models/concerns/eligibility_checkable.rb
- app/models/policies/early_career_payments/policy_eligibility_checker.rb
- app/models/policies/targeted_retention_incentive_payments/policy_eligibility_checker.rb
- spec/models/policies/targeted_retention_incentive_payments/policy_eligibility_checker_spec.rb
Change TSLR ineligibility to use reason
Update the definition of TSLR `ineligible` to use a reason rather than
checking common / specific ineligible attributes. We'll want to use the
reason when we have the TSLR only journey to replace the usage of
`lib/ineligibility_reason_checker.rb`
> tslr ineligibility reason

- app/models/journeys.rb
- app/models/journeys/additional_payments_for_teaching.rb
- app/models/journeys/base.rb
- app/models/journeys/further_education_payments.rb
- config/routes.rb
Enable the reminders routes based on a journey level config. We're going
to have an LUP only journey soon and updating the routes with the
specific routing name will start getting cumbersome. Also adds a
convenience method for routing name so we can use symbol to proc when
mapping.
> Add uses_reminders? flag

- app/forms/postcode_search_form.rb
- config/locales/en.yml
- spec/forms/postcode_search_form_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2411
- Mark optional address fields with `optional`
- Give example of valid postcode in error message
> [CAPT-2411] Better a11y for address related forms

- app/models/payment_confirmation_upload.rb
- spec/models/payment_confirmation_upload_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2305
- Allow empty rows in payment confirmation CSV
> [CAPT-2305] Allow empty rows in payment confirmation CSV

- app/forms/claim_submission_base_form.rb
- app/models/claim.rb
- app/models/journeys.rb
- app/models/journeys/additional_payments_for_teaching.rb
- app/models/journeys/base.rb
- app/models/journeys/eligibility_checker.rb
Accessing a journeys available policies via a method rather than a
constant lets us introduce a shim we can feature flag when introducing a
new journey that may share some policies with an existing journey.
> Add Journey.policies method

- app/controllers/admin/base_admin_controller.rb
- app/controllers/admin/payroll_run_downloads_controller.rb
- app/models/dfe_sign_in/user.rb
- app/models/journeys/further_education_payments/provider/authorisation.rb
- db/test_seeders/base_importer.rb
- spec/factories/dfe_sign_in/users.rb
- spec/features/admin/admin_claim_allocation_spec.rb
- spec/features/admin/admin_claim_check_spec.rb
- spec/features/admin/admin_claims_filtering_spec.rb
- spec/features/admin/admin_payroll_run_download_spec.rb
- spec/models/dfe_sign_in/user_spec.rb
- spec/requests/admin/admin_amendments_spec.rb
- spec/requests/admin/admin_claims_spec.rb
- spec/requests/admin/admin_configure_services_spec.rb
- spec/requests/admin/admin_decisions_spec.rb
- spec/requests/admin/admin_notes_spec.rb
- spec/requests/admin/admin_page_spec.rb
- spec/requests/admin/admin_payment_confirmation_report_upload_spec.rb
- spec/requests/admin/admin_payroll_gender_tasks_spec.rb
- spec/requests/admin/admin_payroll_run_downloads_spec.rb
- spec/requests/admin/admin_payroll_runs_spec.rb
- spec/requests/admin/admin_school_workforce_data_upload_spec.rb
- spec/requests/admin/admin_student_loans_data_upload_spec.rb
- spec/requests/admin/admin_support_tickets_spec.rb
- spec/requests/admin/admin_tasks_spec.rb
- spec/requests/admin/admin_tps_data_upload_spec.rb
- spec/support/request_helpers.rb
- https://dfedigital.atlassian.net/browse/CAPT-2394
- Pre-requisite for this ticket, to remove payroll operator role which is longer used and has been the case for some time
> [CAPT-2394] Remove payroll operator role as no longer used

- terraform/application/database.tf
plpgsql extension is available by default. Azure is rejecting terraform
updates that are attempting to enable this extension as it doesn't
exist.
> Remove attempting to enable plpgsql extension

- .github/workflows/notify-schema-change.yml
We don't need to show the whole commit message in slack and `GITHUB_ENV`
evidently has trouble with multi line strings.
> Only show the commit subject

- .github/workflows/notify-schema-change.yml
Slack attempts to parse the `text` key as yaml. Potentially the keys in
the config analytics containing `:` are breaking slack's yaml parsing.
Replacing `|` with `"` to see if that fixes things!
> Escape yaml

- .github/workflows/delete_review_app.yml
We are standardizing our review app deletion process across services by migrating to a centralized GitHub Action (`DFE-Digital/github-actions/delete-review-app@master`). This reduces duplication, improves maintainability, and ensures consistent behavior across all services when cleaning up review app resources.
- Replaced our custom delete-review-app workflow with the standardized version from `DFE-Digital/github-actions`
- Configured the workflow to maintain all existing functionality including:
- PR-based and manual triggering
- Proper authentication with Azure and GCP
- Terraform state management
- PR comment notifications
- Set up appropriate parameters to ensure the action works with our current infrastructure naming conventions
The solution uses the existing make target for …
> Use delete action for delete-review-app workflow

- app/forms/journeys/additional_payments_for_teaching/correct_school_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/select_claim_school_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/still_teaching_form.rb
- app/models/journeys/additional_payments_for_teaching/session.rb
- app/models/journeys/additional_payments_for_teaching/slug_sequence.rb
- app/models/journeys/early_years_payment/practitioner/session.rb
- app/models/journeys/early_years_payment/provider/authenticated/session.rb
- app/models/journeys/early_years_payment/provider/start/session.rb
- app/models/journeys/further_education_payments/provider/session.rb
- app/models/journeys/further_education_payments/session.rb
- app/models/journeys/get_a_teacher_relocation_payment/session.rb
- app/models/journeys/session.rb
- app/models/journeys/session_answers.rb
- app/models/journeys/teacher_student_loan_reimbursement/session.rb
- app/models/journeys/teacher_student_loan_reimbursement/session_answers.rb
- app/models/journeys/teacher_student_loan_reimbursement/slug_sequence.rb
Pass reference to a session to answers
Sometimes we need a reference to the session in the answers for things
like timestamps.
Passing a reference to the session to the answers allows us to move some
attributes that are derived from the session answers off the journey session
model and onto the answers model.
Having access to the session on the answers will also allow us to implement
things like `answers.update!` and clean up the code where we have to do
`journey_session.assign_attributes(xxx); journey_session.save!`.
As we want to support subclasses of session answers for each journey we
unfortunately have to use a bit of Ruby magic to get this to work.
This code is extracted from the LUP only journey branch. If this approach is a
bit too esoteric we can leave some methods on the journey …
> pass session into answers

- app/forms/claim_submission_base_form.rb
- app/forms/journeys/early_years_payment/practitioner/claim_submission_form.rb
- app/models/claim.rb
- app/models/policies.rb
- app/models/policies/active_record_type.rb
- config/analytics.yml
- db/migrate/20250515103756_add_policy_to_claim.rb
- db/schema.rb
- spec/factories/claims.rb
- spec/factories/policies/further_education_payments/eligibilities.rb
- spec/features/admin/admin_claim_further_education_payments_spec.rb
- spec/features/admin/admin_view_full_claim_further_education_payments_spec.rb
- spec/features/further_education_payments/provider/provider_verifying_claims_spec.rb
- spec/forms/admin/claims_filter_form_spec.rb
- spec/forms/journeys/early_years_payment/practitioner/claim_submission_form_spec.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/claim_submission_form_spec.rb
- spec/forms/journeys/further_education_payments/claim_submission_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/claim_submission_form_spec.rb
- spec/forms/journeys/teacher_student_loan_reimbursement/claim_submission_form_spec.rb
- spec/models/automated_checks/claim_verifiers/alternative_identity_verification_spec.rb
- spec/models/automated_checks/claim_verifiers/provider_verification_spec.rb
- spec/models/claim_spec.rb
- spec/models/journeys/further_education_payments/provider/authorisation_spec.rb
- spec/models/policies/active_record_type_spec.rb
- Pre-requisite for https://dfedigital.atlassian.net/browse/CAPT-2177
- this change is required as concept of eligibilities are to be removed
- as policy is inferred from eligibility
- this moves policy directly onto claim as I feel we will want this as first class citizen on the claim itself
> [CAPT-2177] Move policy from eligibility to claim

- db/data/20250516122738_migrate_additional_payments_reminders_to_tslr.rb
We're removing the additional payments journey and replacing it with a
targeted retention incentive payments only journey. There are 3296
claimants who are eligibile for a TRI claim next year who set a reminder
after completing the additional payments journey. We want to ensure
these claimants still get a reminder when we open the new TRI only
journey.
> Migrate TRI reminders

- terraform/application/application.tf
- terraform/application/config/production.tfvars.json
- terraform/application/variables.tf
Increase worker and web pod memory for production.
From 1Gi to 2Gi
Review using make production terraform-plan, although already manually applied to production
> Increase worker and web pod memory

- app/models/admin/presenter_methods.rb
- app/models/policies/international_relocation_payments/admin_tasks_presenter.rb
- app/models/policies/international_relocation_payments/claim_checking_tasks.rb
- config/locales/en.yml
- spec/support/admin_view_claim_feature_shared_examples.rb
Updates to employment task
New designs consolidate the separate employment tasks into a single
task. In order to preserve the tasks completed on previous years claims
we add the other employment tasks to the tasks array only if they are
persisted. The employment task on old claims will now show some extra
information it's not worth the complexity to avoid this.
We likely want to rethink the task model.
Currently tasks are only persisted when they are completed ("passed",
"failed"), switching to an approach where when the claim is submitted we
persist the list of tasks that need completing would allow us to change
the tasks list on future claims without effecting the task list of
claims in previous years.
> CAPT 2476/employment task changes

- app/controllers/concerns/form_submittable.rb
- app/models/policies/early_years_payments/policy_eligibility_checker.rb
- spec/requests/form_submittable_spec.rb
We want to keep all navigation logic in the navigator rather than
referencing the slug sequence directly in the controller.
To support this we need to update the EY policy eligibility checker to
handle the email not yet being provided.
Have deleted the form submissable test, fixing the test would require
implementing a journey and using the real navigator (test's `next_slug`
just pulls the next slug from the array).
> Remove redirect to first slug

- app/models/journeys/teacher_student_loan_reimbursement/slug_sequence.rb
This is no longer required as navigator handles ineligible slugs
> Remove ineligible check from slug sequence

- app/forms/journeys/get_a_teacher_relocation_payment/previous_payment_received_form.rb
- app/models/journeys/get_a_teacher_relocation_payment.rb
- app/models/journeys/get_a_teacher_relocation_payment/answers_presenter.rb
- app/models/journeys/get_a_teacher_relocation_payment/session_answers.rb
- app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
- app/models/policies/international_relocation_payments/policy_eligibility_checker.rb
- app/views/get_a_teacher_relocation_payment/claims/ineligible.html.erb
- app/views/get_a_teacher_relocation_payment/claims/previous_payment_received.html.erb
- config/locales/en.yml
- spec/factories/journeys/get_a_teacher_relocation_payment/get_a_teacher_relocation_payment_answers.rb
- spec/features/get_a_teacher_relocation_payment/admin_employment_history_task_spec.rb
- spec/features/get_a_teacher_relocation_payment/admin_first_year_payment_task_spec.rb
- spec/features/get_a_teacher_relocation_payment/ineligible_route_completing_the_form_spec.rb
- spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
- spec/features/switching_policies_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/previous_payment_received_form_spec.rb
- spec/models/journeys/get_a_teacher_relocation_payment/answers_presenter_spec.rb
- spec/models/journeys/get_a_teacher_relocation_payment/slug_sequence_spec.rb
- spec/models/policies/international_relocation_payments/policy_eligibility_checker_spec.rb
- spec/support/get_a_teacher_relocation_payment/step_helpers.rb
Add new first page to IRP
Requirement is for a new first page in the IRP journey asking if the
claimant has already received an IRP payment, if they haven't they're
not eligible for this year's payment.
> CAPT 2619/previously received irp payment

- app/views/admin/claims/index.html.erb
- app/views/admin/claims/search.html.erb
- app/views/admin/reports/index.html.erb
- Remove superfluous back links on admin root pages. they don't really make sense since they are linked to a main navigation item
> Remove admin back links on root pages

- app/controllers/concerns/form_submittable.rb
- app/controllers/further_education_payments/providers/base_controller.rb
- app/controllers/further_education_payments/providers/sessions_controller.rb
- app/controllers/further_education_payments/providers/verified_claims_controller.rb
- app/controllers/static_pages_controller.rb
- app/controllers/unsubscribe_controller.rb
- app/helpers/application_helper.rb
- app/views/further_education_payments/provider/_header.html.erb
- app/views/further_education_payments/providers/verified_claims/index.html.erb
- app/views/layouts/application.html.erb
- app/views/unsubscribe/subscription_not_found.html.erb
- config/routes.rb
- spec/features/further_education_payments/providers/sessions_spec.rb
- spec/views/layouts/application.html.erb_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2662
- Add provider nav
- Switched to us newly introduced `DfeSignIn::NullUser`
- Added sign out capability
- Added new controller for verified claims, we may want to rename other controller to `UnverifiedClaims`
> [CAPT-2662] Add provider nav

- app/controllers/further_education_payments/providers/claims/verifications_controller.rb
- app/forms/further_education_payments/providers/claims/verification/check_answers_form.rb
- app/models/further_education_payments/providers/claims/verification/wizard.rb
- app/views/further_education_payments/providers/claims/verifications/check_answers.html.erb
- config/analytics.yml
- db/migrate/20250710131813_add_verification_fields_to_fe_eligibility.rb
- db/schema.rb
- spec/factories/policies/further_education_payments/eligibilities.rb
- spec/features/further_education_payments/providers/provider_verifying_claims_spec.rb
- spec/forms/further_education_payments/providers/claims/verification/check_answers_form_spec.rb
Adds the verification declaration
Upon completing the wizard we store the verifier and set the field
`provider_verification_completed_at` timestamp. We've agreed that a non
null value for `provider_verification_completed_at` represents a claim
as having been verified.
Note we use a presence validation, rather than an acceptance validation,
for the declaration checkbox as the acceptance validation doesn't run if
the attribute is `nil` so the wizard always thinks this form is
complete.
> CAPT 2637/claim summary screen

- .github/workflows/build_and_deploy.yml
- config/routes.rb
- db/seeds.rb
- spec/features/further_education_payments/providers/sessions_spec.rb
- spec/features/further_education_payments/providers/unverified_dashboard_spec.rb
- Some QOL updates around FE provider dashboard
- Update deploy comment to include link to provider dashboard (pushed after deployment which is why you don't see it below)
- change underscore URLs to hyphens, see https://insidegovuk.blog.gov.uk/url-standards-for-gov-uk/
- enable `provider_dashboard` feature flag in seeds so review apps always get this feature
> Provider dashboard QOL updates

- app/controllers/further_education_payments/providers/claims/verifications_controller.rb
- app/forms/further_education_payments/providers/claims/verification/base_form.rb
- app/forms/further_education_payments/providers/claims/verification/check_answers_form.rb
- app/forms/further_education_payments/providers/claims/verification/contract_type_form.rb
- app/forms/further_education_payments/providers/claims/verification/in_first_five_years_form.rb
- app/forms/further_education_payments/providers/claims/verification/qualification_form.rb
- app/forms/further_education_payments/providers/claims/verification/teaching_qualification_form.rb
- app/forms/further_education_payments/providers/claims/verification/teaching_responsibilities_form.rb
- app/models/further_education_payments/providers/claims/verification/wizard.rb
- app/views/further_education_payments/providers/claims/verifications/_summary.html.erb
- app/views/further_education_payments/providers/claims/verifications/contract_covers_full_academic_year.html.erb
- app/views/further_education_payments/providers/claims/verifications/contract_type.html.erb
- app/views/further_education_payments/providers/claims/verifications/contracted_hours.html.erb
- app/views/further_education_payments/providers/claims/verifications/in_first_five_years.html.erb
- app/views/further_education_payments/providers/claims/verifications/performance_and_discipline.html.erb
- app/views/further_education_payments/providers/claims/verifications/qualification.html.erb
- app/views/further_education_payments/providers/claims/verifications/taught_at_least_one_academic_term.html.erb
- app/views/further_education_payments/providers/claims/verifications/teaching_qualification.html.erb
- app/views/further_education_payments/providers/claims/verifications/teaching_responsibilities.html.erb
- config/locales/en.yml
- spec/features/further_education_payments/providers/provider_verifying_claims_spec.rb
- spec/forms/further_education_payments/providers/claims/verification/contract_type_form_spec.rb
- spec/forms/further_education_payments/providers/claims/verification/in_first_five_years_form_spec.rb
- spec/forms/further_education_payments/providers/claims/verification/qualification_form_spec.rb
- spec/forms/further_education_payments/providers/claims/verification/teaching_qualification_form_spec.rb
- spec/forms/further_education_payments/providers/claims/verification/teaching_responsibilities_form_spec.rb
Quite a few changes required in this ticket, might be easier to review each
commit separately.
At a high level we
* Switch check answers to have change links next to each answer
* Break up the role and experience form into 3 separate forms
* Add a new option for contract type
https://github.com/user-attachments/assets/9f5f7563-298c-4c4a-9ffd-eb9128c0e184
> CAPT 2701/split role and experience form

- app/forms/journeys/further_education_payments/contract_type_form.rb
- app/models/journeys/further_education_payments/answers_presenter.rb
- app/models/journeys/further_education_payments/slug_sequence.rb
- config/initializers/govuk_design_system_formbuilder.rb
- config/locales/en.yml
- spec/features/further_education_payments/ineligible_paths_spec.rb
- spec/features/further_education_payments/variable_contract_spec.rb
- spec/forms/journeys/further_education_payments/taught_at_least_one_term_form_spec.rb
- spec/forms/journeys/further_education_payments/teaching_hours_per_week_next_term_form_spec.rb
- spec/models/policies/further_education_payments/eligibility_admin_answers_presenter_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2751
- In FE claimant journey move page `taught_at_least_one_term` to earlier in the sequence
- Add missing answers to check answers page
- Answer copy has been simplified
> FE taught_at_least_one_term earlier in sequence

- app/forms/date_of_birth_form.rb
- app/forms/form.rb
- app/forms/personal_details_form.rb
- app/models/concerns/date_of_birth.rb
Extract DateOfBirth concern
We have some rules around validation errors we show to users that are
tricky to implement when we parse multipart date params using
ActiveRecord::AttributeAssignment.
We will want to share this date of birth validation handling with other
forms so we're extracting a concern.
To avoid having to overwrite the initializer in the module (other
forms may need to reopen the initializer) we've introduce active model
callbacks allowing us to define an after initializer callback the DoB
handling can hook into.
Customising the error messages is done by overwriting methods in the
including class. We've taken this approach rather than dealing with i18n
as some consumers of the module will need to pass variables to i18n (eg
`claimant_name`) which is a pain to handle in the …
> Extract DateOfBirth concern

- app/models/policies/further_education_payments.rb
- app/models/policies/international_relocation_payments.rb
- spec/models/policies/further_education_payments/claim_personal_data_scrubber_spec.rb
- spec/models/policies/international_relocation_payments/claim_personal_data_scrubber_spec.rb
- spec/support/claim_personal_data_scrubber_shared_examples.rb
Update pii scrubbing for FE and IRP
https://dfedigital.atlassian.net/browse/CAPT-1897
We want to retain attributes for matching with previous year claims for the life
of the policy.
> CAPT 1897/retain fe and irp data

- app/forms/admin/tasks/ey_alternative_verification_form.rb
- app/jobs/tasks/ey_alternative_verification_job.rb
- app/models/automated_checks/claim_verifiers/ey_alternative_verification.rb
- app/models/claim.rb
- app/models/policies/early_years_payments.rb
- app/models/tasks.rb
- app/views/admin/tasks/ey_alternative_verification.html.erb
- spec/features/admin/early_years/alternative_verification_spec.rb
- spec/models/automated_checks/claim_verifiers/ey_alternative_verification_spec.rb
Auto pass the personal details sub task
Brings back some of Phil's code for passing the ey task but modifies it
to handle passing the sub tasks.
This task is a bit weird in that there are two "sub tasks" associated.
Usually a task is considered completed when it's persisted, however the
ey_alternative_verification_form can be persisted without being
completed.
If the ey_alternative_verification verifier passes the personal details
section of the task, indidicated by the
`personal_details_were_completed_automatically` attribute, then we don't
show the personal details radio button in the form.
Similarly if the verifier passes the bank details sub task then we don't show
the bank details radio button.
Bank details matching is intentionally really strict (exact name match) most of
the time …
> CAPT 2849/ey alt idv automated task passing

- app/helpers/admin/claims_helper.rb
- app/views/admin/claims/index.html.erb
- spec/factories/policies/early_years_payments/eligibilities.rb
If we're dealing with an EY claim we can't use the `submitted_at` time
stamp as that isn't set until the provider completes their journey.
The eligibility is already eager loaded
(`app/forms/admin/claims_filter_form.rb`) so we can call attributes on
it.
> Replace decision warning with submitted date

- app/controllers/concerns/journey_concern.rb
- app/forms/form.rb
- app/forms/journeys/further_education_payments/existing_progress_form.rb
- app/jobs/expire_journey_sessions_job.rb
- app/jobs/purge_unsubmitted_claims_job.rb
- app/models/journeys/further_education_payments.rb
- app/models/journeys/further_education_payments/journey_session_migrator.rb
- app/models/journeys/further_education_payments/session.rb
- app/models/journeys/further_education_payments/slug_sequence.rb
- app/models/journeys/navigator.rb
- app/models/journeys/session.rb
- app/models/journeys/session_answers.rb
- app/models/one_login_account.rb
- app/models/policies/further_education_payments.rb
- app/views/further_education_payments/claims/existing_progress.html.erb
- config/analytics.yml
- config/locales/en.yml
- config/recurring.yml
- db/migrate/20250911092038_add_expired_to_journeys_sessions.rb
- db/schema.rb
- spec/features/further_education_payments/claimed_last_year_spec.rb
- spec/features/further_education_payments/existing_one_login_spec.rb
- spec/features/further_education_payments/one_login_contiue_spec.rb
- spec/features/further_education_payments/previously_claimed_spec.rb
- spec/features/journey_session_expiry_spec.rb
- spec/jobs/expire_journey_sessions_job_spec.rb
- spec/jobs/purge_unsubmitted_claims_job_spec.rb
- spec/models/journeys/navigator_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2743
- Allow users to resume a previous session based on their OL uid
- We ignore any previous sessions that are in ineligible state
- We now purge FE journey sessions only when the session has not been touched for a year
- Introduced concept of expiring journey sessions. this means journey sessions remain persisted but no longer available for lookup
- These journey remain persisted till they are purged at a later date. this allows users to resume a previous journey session we have persisted
- This is done via an hourly job. This means max theoretical session time is now 25 hours (24.hours - 1.second + 1.hour) down from the current time of 48 hours (24.hours - 1.second + 24.hours)
> [CAPT-2743] FE resume existing session

- app/models/journeys/further_education_payments/answers_presenter.rb
- app/models/journeys/further_education_payments/slug_sequence.rb
- app/models/policies/further_education_payments/policy_eligibility_checker.rb
- spec/features/further_education_payments/ineligible_paths_spec.rb
- spec/features/further_education_payments/variable_contract_spec.rb
If the claimant has a fixed term contract but hasn't taught for the full
term we need to ask some additional questions (the same ones as on the
variable hours journey)
> Add additional questions for fixed term

- app/helpers/admin/claims_helper.rb
- app/models/policies/early_years_payments/claim_checking_tasks.rb
- spec/helpers/admin/claims_helper_spec.rb
We need to check the `identity_confirmation` task for year 1 ey claims
> Handle year 1 ey claims

- app/models/policies/early_years_payments/claim_checking_tasks.rb
- spec/models/policies/early_years_payments/claim_checking_tasks_spec.rb
For some EY year 1 claims the practitioner journey was completed after
we removed the Identity claim verifier from EY. There for the identity
task wasn't passed, nor was `claim_verifier_match` set on the task, this
caused the identity task on these claims to be rendered in as incomplete
and the form to complete them was not shown. These claims did have the
one_login_identity (OLIdentity verifier replaced Identity verifier) so
we want to render the `one_login_identity` task rather than the
`identity_confirmation` task if it's present.
> Fix EY claim identity task

- spec/factories/claims.rb
- spec/factories/policies/further_education_payments/eligibilities.rb
- spec/features/admin/admin_claim_further_education_payments_spec.rb
- spec/features/admin/admin_claims_filtering_spec.rb
- spec/features/admin/admin_view_claim_further_education_payments_spec.rb
- spec/features/admin/tasks/identity_confirmation_spec.rb
- spec/features/admin/upload_slc_data_spec.rb
- spec/features/further_education_payments/providers/provider_verifying_with_claimant_courses_spec.rb
- spec/features/further_education_payments/viewing_year_1_claims_in_admin_area_spec.rb
- spec/models/claim_spec.rb
- spec/support/admin_checks_feature_shared_examples.rb
- spec/support/admin_view_claim_feature_shared_examples.rb
Need to split `verification` out of the `eligible` trait to make migrating specs to use year 2 verification easier.
> Refactor FE factory traits

- app/models/claim.rb
- app/models/policies/further_education_payments/eligibility.rb
- spec/features/admin/admin_checks_further_education_payments_claim_spec.rb
- spec/features/admin/admin_claims_filtering_spec.rb
- spec/features/admin/admin_view_claim_further_education_payments_spec.rb
- spec/features/admin/admin_view_claim_spec.rb
- spec/features/admin/tasks/identity_confirmation_spec.rb
- spec/features/admin/upload_slc_data_spec.rb
- spec/models/claim_spec.rb
- spec/models/policies/further_education_payments/claim_checking_tasks_spec.rb
- spec/support/admin_checks_feature_shared_examples.rb
- spec/support/admin_view_claim_feature_shared_examples.rb
Update query to work with year 2 fe claims
Year 2 claims have a different provider verification mechanisim so, in
order to get the admin filters to work as expected, we need to update
this query to work with them. We also need the filters to support year 1
claims.
> update admin filters to show y2 fe claims

- .github/workflows/ci.yaml
- app/views/early_years_payment/provider/start/consent_form.html.erb
- app/views/further_education_payments/claims/teaching_responsibilities.html.erb
- app/views/further_education_payments/providers/claims/verifications/half_timetabled_teaching_time.html.erb
[Catches invalid HTML / ERB code](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/4129)
https://herb-tools.dev
No need to switch ERB parser, though herb is a drop in replacement (and [we're now running it in dev](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/4128/files))
> CAPT 2921/add herb liniting

- config/initializers/reactionview.rb
Herb overlay changes the spacing on checkboxes.
We'll default the overlay to off for the time being.
Enable it by setting the DEBUG_VIEW variable when booting the app.
> Make herb optional in dev

- app/helpers/admin/claims_helper.rb
- app/models/claim.rb
- app/models/policies/early_years_payments/admin_claim_details_presenter.rb
- config/locales/en.yml
- spec/helpers/admin/claims_helper_spec.rb
- spec/models/claim_spec.rb
- spec/models/policies/early_years_payments/admin_claim_details_presenter_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2909
- Try to remove `govuk_verify` code
- there still remains the data and one method call which is wired
- the remainder is removal of dead code
> [CAPT-2909] Remove unused govuk verify code
