DFE-Digital/claim-additional-payments-for-teaching

- docs/architecture-decisions/0004-deployment-on-heroku.md
Architecture decision record to use Heroku for deployment.
> (ADR) 4 - Deployment on Heroku

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/govuk_frontend.js
- app/assets/stylesheets/application.css
- app/assets/stylesheets/govuk_frontend_rails.scss
- app/controllers/start_controller.rb
- app/views/layouts/application.html.erb
- app/views/start/index.html.erb
- config/routes.rb
Made a start page using GOVUK front end
> Add govuk frontend

- Gemfile
- Gemfile.lock
- docs/architecture-decisions/0005-use-brakeman-for-vulnerability-checking-on-ci.md
- lib/tasks/brakeman.rake
- lib/tasks/default.rake
Brakeman is a vulnerability scanner for Ruby-on-Rails. By adding it to our CI we can have confidence that we're not introducing known insecure code to the application.
> Add Brakeman and rake task for CI

- Gemfile
- Gemfile.lock
We are not using it so let's not load it.
> Don't use coffee script in the Rails application

- app/views/layouts/application.html.erb
- favicon
- apple-touch x 4 sizes
- mask icon
Also tidies the markup.
> Load all the favicons into the application layout

- config/routes.rb
- spec/factories/local_authorities.rb
- spec/factories/schools.rb
- spec/fixtures/local_authorities.yml
- spec/fixtures/schools.yml
- spec/requests/claims_spec.rb
- spec/routes/routes_spec.rb
- spec/services/school_data_importer_spec.rb
- spec/services/tslr/school_eligibility_spec.rb
A few minor tweaks and adjustments ahead of the work to add the ineligible page into the user flow.
> Tweaks and improvements

- .prettierignore
- .prettierrc
- README.md
- app.json
- app/assets/javascripts/govuk_frontend.js
- app/assets/javascripts/timeout_dialog.js.erb
- app/assets/stylesheets/components/a11y-dialog.scss
- docs/architecture-decisions/0003-use-rubocop-for-linting.md
- docs/architecture-decisions/0005-use-brakeman-for-vulnerability-checking-on-ci.md
- lib/tasks/default.rake
- lib/tasks/prettier.rake
- package.json
- public/404.html
- public/422.html
- public/500.html
- yarn.lock
**This is intended as a discussion point.**
This PR introduces Prettier as a code formatter. It supports many different file formats, but I have hooked it up to run on non-ERB JavaScript, CSS, Sass, HTML, Markdown, JSON, and ERB JavaScript. It's hooked up to run a checker alongside tests (like we do with `standardrb`), and there are two new rake commands to run it on the app.
Does anyone have any thoughts or feelings about introducing this to the project?
> Set up Prettier to format non-Ruby files

- docs/architecture-decisions/0011-make-payments-using-dfes-existing-finance-system-nav.md
We'll mark this as accepted and add a date once we've confirmed with the FSIP team that we're definitely doing this.
> Draft ADR for making payments using NAV

- app/views/claims/bank_details.html.erb
- config/locales/en.yml
- spec/features/tslr_claim_spec.rb
- Amend hint text to be less passive-aggressive.
- Change question to be consistent with maths an physics prototype
> Amend bank detail to be less aggressive

- app/views/claims/national_insurance_number.html.erb
- Change the question name based off maths and physics journey for
clarity.
- Change the width of the input to match the number of expected
characters
> Amend NINO page to match MPS

- app/views/claims/_check_your_answers_section.html.erb
- app/views/claims/national_insurance_number.html.erb
- app/views/claims/qts_year.html.erb
- app/views/claims/student_loan_amount.html.erb
- app/views/claims/teacher_reference_number.html.erb
- ensure all questions have labels and consistent margins
- as a bounus set relevant links to hvae govuk-link class so they are
styled correctly
> Make margins on questions consistent

- README.md
Change link on readme to include extension as it currently doesn't load
> Fix readme link to verify doc

- app/views/claims/eligibility_confirmed.html.erb
As we alternate work on TSLR and MPS the text can get updated in one
journey but not another. This will update the eligble confirmed page
in line with the latest guidence from our content designer.
> Update eligible confirmed message for consistency

- app/views/claims/eligibility_confirmed.html.erb
Rephrased text on this page based on feedback from content designer
> Amend text on eligibility confirmed page

- db/schema.rb
This got shifted in commit d7fe6325c9f9a90c76ded65162ff18121078b8d2.
> Fix schema.rb column ordering

- bin/docker-entrypoint
- db/seeds.rb
This makes the first run experience better for a developer trying to run the application (they don't need to know to run the import) and also removes the app-specific knowledge from `docker-entrypoint`.
> Run school import in seeds.rb

- azure-pipelines.yml
- bin/azure-deploy
- bin/docker-release
Most of the release configuration is specified in the web UI, as it doesn't appear to be possible to specify it in YAML, yet.
Releases are done by pushing tags to DockerHub and restarting the app service.
> Set up Azure Release to deploy the app

- azure/app/files/docker-compose.yml
I've got a new repo set up in the DfE DockerHub org. Most of the switching over takes place in the Azure DevOps config, but I've set the deployment scripts to use the new container here too.
> Use DfE Docker container when deploying

- app/views/claims/student_loan_amount.html.erb
- config/locales/en.yml
Amend question text to include the words exactly
> 375 tslr student loan amount

- docs/infrastructure-deployment.md
Some features are only available from there.
> Use the new Azure DevOps url

- azure/app/parameters/development.template.json
- azure/app/parameters/production.template.json
- azure/app/parameters/test.template.json
- azure/app/template.json
This doesn't handle generating or assigning an SSL certificate for the domain.
> Set up education.gov.uk domains

- app/assets/javascripts/components/school_search.js.erb
- app/views/claims/_school_search.html.erb
In preparation for adding support for the Maths and Physics policy, we're slowly making existing code less coupled to TSLR specifically.
> Make school search JS more generic

- bin/import-vsp-certs
- docs/govuk-verify.md
This has already been run on the certificates we just received back from Verify.
> Add a script for importing VSP certificates into the Key Vault

- azure/resource_groups/alerts/template.json
- azure/resource_groups/app/template.json
- azure/templates/app_alerts.json
- azure/templates/vsp.json
- bin/azure-deploy
This shares common commits with #226 to pull the VSP out into its own template and do the set up to support child templates.
> Set up alerts for VSP

- app/views/claims/claim_school.html.erb
- app/views/claims/current_school.html.erb
- spec/features/changing_answers_spec.rb
- spec/features/tslr_claim_spec.rb
- spec/support/feature_helpers.rb
A few changes we've made during the work to migrate the school attributes into the eligibility model.
> Some minor refactoring

- app/models/student_loans/eligibility.rb
- app/models/student_loans/permitted_parameters.rb
- app/models/tslr_claim.rb
- app/views/claims/student_loan_amount.html.erb
- db/migrate/20190808121109_add_student_loan_repayment_amount_to_student_loans_eligibilities.rb
- db/migrate/20190808121222_remove_student_loan_repayment_amount_from_tslr_claims.rb
- db/schema.rb
- spec/factories/student_loans/eligibilities.rb
- spec/factories/tslr_claims.rb
- spec/helpers/claims_helper_spec.rb
- spec/models/student_loans/eligibility_spec.rb
- spec/models/tslr_claim_spec.rb
- spec/presenters/tslr_claim_csv_row_spec.rb
This is the final attribute to go into the policy specific
StudentLoans:Eligibility model.
> Move student_loan_repayment_amount to eligibility

- app/views/claim_mailer/submitted.text.erb
- spec/mailers/claim_mailer_spec.rb
- Update the email with copy from content designer
- Inset the reference number so it will be easily visible against the
headers below
- Drop in merge fields for dynamic information
- Amend mailer spec so it now epects some of the current text
> Change the claim received email

- app/views/claim_mailer/submitted.text.erb
Minor adjustments: include whitespace between # and heading; newline at end of file.
> Adjust claim email markdown

- config/environments/production.rb
- config/initializers/rack_runtime.rb
- Enable Strict-Transport-Security on production
- Stop setting an "X-Runtime" header
> Security related tweaks

- README.md
- app/assets/javascripts/application.js
- app/assets/javascripts/google_analytics.js
- app/views/layouts/application.html.erb
- app/views/static_pages/cookies.html.erb
- azure/resource_groups/app/parameters/development.template.json
- azure/resource_groups/app/parameters/production.template.json
- azure/resource_groups/app/template.json
- config/initializers/assets.rb
Also update the cookies page with Google info
> Add google analytics to the site

- azure/resource_groups/app/template.json
This was omitted in a previous commit in error and is causing the deploy to fail.
> Fix missing parameter in template.json

- app/views/layouts/application.html.erb
- app/views/static_pages/cookies.html.erb
> Add in link to feedback form in header

- app/views/layouts/application.html.erb
- app/views/static_pages/cookies.html.erb
Fix a couple of minor errors based on a quick run through of the service
> 580 the little things snag list

- app/views/claim_mailer/submitted.text.erb
- app/views/claims/confirmation.html.erb
Update confirmation page and email sent to set expectations about when they can expect to get paid and use language to give us some wiggle room.
> 571 make clear expectations about when they will get paid

- azure/resource_groups/app/parameters/production.template.json
I have requested that the eIDAS feature be enabled for our production environment. I'm putting this PR in draft mode until we get confirmation it is enabled on production.
> Enable eIDAS feature on the production VSP

- app/views/static_pages/start_page.html.erb
> Add missing "govuk-link" class on start page links

- app/views/static_pages/privacy_policy.html.erb
DPIA have looked at the privacy policy and recommended some changes.
The 'Why our use of your personal data is lawful' section still mentions
consent which feels off. We are currently awaiting feedback on that
sentence.
> Update Privacy policy

- config/locales/en.yml
This makes it match the wording in the question a bit more closely.
> Adjust teacher training ineligibility reasons

- config/locales/en.yml
The available answers should match the phrasing of the question.
> Remove "degree" from student loan plan question

- app/views/static_pages/accessibility_statement.html.erb
Lowercase first character and no full stop.
> Standardize the grammar on list items

- app/views/static_pages/accessibility_statement.html.erb
Confirmed by Kristi as an appropriate period to respond to such a request.
> Set days-to-respond on accessibility statement

- app/views/layouts/application.html.erb
- remove the dead links to Help and Contact
- add a link to the support email
> Adjust footer links

- app/views/claim_mailer/submitted.text.erb
- spec/mailers/claim_mailer_spec.rb
- spec/requests/claims_spec.rb
> Updated content for application complete email

- CHANGELOG.md
- README.md
- docs/release-process.md
This is all up for grabs, but a first pass at how we handle deployments to production once we start private beta
> Document deployment process

- azure/resource_groups/app/parameters/development.template.json
- azure/resource_groups/app/parameters/production.template.json
- azure/resource_groups/app/template.json
- azure/templates/app.json
- azure/templates/app_service_plan.json
- azure/templates/vsp.json
They're cheaper for more resources.
This also bumps up the development environment to hopefully make the alerts a bit quieter for an extra £10 / month.
> Switch to Premium V2 app service plans

- CHANGELOG.md
- First release for student loan repayments private beta
> Release 001

- CHANGELOG.md
- app/assets/javascripts/components/school_search.js.erb
- app/assets/stylesheets/components/accessible_autocomplete_tweaks.scss
- app/assets/stylesheets/components/school_search.scss
- app/views/claims/_school_search.html.erb
Change the html elements used to display closed schools and apply
appropriate formatting.
> Improve layout of closed schools on search

- azure/templates/database.json
As per the recommendation in the Pentest report
> Set Postgres to log disconnections

- config/locales/en.yml
> Fix a typo in leadership question

- CHANGELOG.md
- Redirect requests from any domain other than the canonical one
- Fix admin IP restriction bug due to port numbers
- Fix add clear and helpful page titles
- Fix a bug displaying incorrect number of decimal places on monetary number
form fields
- Restrict access to `/admin` by IP
- Fix student_loan_start_date validation error message
- Fix OmniAuth failure path
> Release 005

- CHANGELOG.md
- azure/resource_groups/app/template.json
- azure/templates/vsp.json
- azure/templates/web_test.json
- bin/azure-deploy
- bin/import-vsp-certs
- bin/request-vsp-certs
- bin/swap-slots
Before merging:
After merging:
[the docs]: https://dfedigital.atlassian.net/wiki/spaces/TP/pages/1142423576/Alerting+Monitoring
> Set up deployment slot and availability test for VSP

- docs/release-process.md
> Update release process docs to use new names for things

- CHANGELOG.md
- Add student loan plan and amount to approver view of a claim
- Link to Get Information About Schools from the admin view of a claim
- Monitor VSP availability
- Use slots to make VSP deployment zero-downtime
- Redirect `www.` to the base URL
> Release 009

- CHANGELOG.md
- Fix deployment template conflict
- Make closed schools ineligible for current school
- Exclude closed schools from current school search
> Release 010

- CHANGELOG.md
- app/views/static_pages/accessibility_statement.html.erb
Based on the reports from DAC and our assurance testers we have
identified some issues with the service. The accessibility statement
needed to be updated to reflect the issues we cannot immediately fix.
> Update accessibility statement

- CHANGELOG.md
- Show how many claims are awaiting approval
- Show date of birth in a better place and format for claim checking
- Show DfE number against school in approver view of claim
- Drop redundant full_name column from claims table
- Updated Accessibility statement to show current issues
> Release 011

- CHANGELOG.md
- app/models/maths_and_physics/school_eligibility.rb
- app/models/student_loans/school_eligibility.rb
- spec/models/maths_and_physics/school_eligibility_spec.rb
- spec/models/student_loans/school_eligibility_spec.rb
This is following a discussion with the policy team.
> Make all-through schools eligible

- CHANGELOG.md
- app/helpers/admin/claims_helper.rb
- app/views/admin/claims/show.html.erb
- config/locales/en.yml
- spec/helpers/admin/claims_helper_spec.rb
We needed to know to support a user, which required looking in the database.
> Add the claim start and submission times to the admin view

- CHANGELOG.md
Bank account capture improvements went out in the last release but were missing from the changelog
> Add missing item to CHANGELOG.md

- app/controllers/admin/payroll_runs_controller.rb
- app/models/payroll/claims_csv.rb
- config/brakeman.ignore
- spec/models/payroll/claims_csv_spec.rb
Mostly about making it possible to extract the `PayrollRun#filename` method, but also did some refactoring of the specs for `PayrollRun`.
> Extract PayrollRun#filename method

- README.md
> Add ARM templates to our docs on reusable components

- CHANGELOG.md
- azure/resource_groups/app/parameters/production.template.json
> Enable maintenance mode on production

- bin/request-vsp-certs
- docs/govuk-verify.md
This is a rejig of the confluence doc for a developer audience, there is still page on Confluence:
https://dfedigital.atlassian.net/wiki/spaces/TP/pages/1116110992/Verify+Service+Provider
> Include Verify certificate rotation docs

- README.md
> Add full stop to example maintenance mode message

- CHANGELOG.md
- app/views/claims/student_loan_amount.html.erb
- config/locales/en.yml
The content on this page now matches the latest content in the prototype.
> Update student loan question to latest version

- README.md
- db/seeds.rb
- spec/factories/payments.rb
- spec/factories/payroll_runs.rb
Making the experience of playing with the app locally a little more pleasant.
> Add claims and payroll runs to seeds

- app/controllers/application_controller.rb
- azure/resource_groups/app/parameters/production.template.json
> Remove the basic auth from the service ready for public beta

- docs/govuk-verify.md
F had to explain this to me when I joined the project; hopefully this
will be useful for new developers.
> Explain how to complete Verify flow in local dev

- CHANGELOG.md
- db/data/20191106144218_upcase_national_insurance_numbers.rb
This is the data migration mentioned in 7e50b1e.
> Upcase existing National Insurance numbers

- CHANGELOG.md
- Make admin claim search case insensitive
- Change all of the existing claims' National Insurance numbers to upper case
- Add a link to our service's satisfaction survey to the confirmation page
- Improve journey for users that worked at more than one school during the claim
period
> Release 029

- spec/features/ineligible_tslr_claims_spec.rb
- spec/features/student_loans_claim_spec.rb
This got moved to the feature spec file for ineligible claims by mistake.
> Move different claim/current school feature spec somewhere more appropriate

- CHANGELOG.md
- Introduce the beginnings of the Maths & Physics journey, protected with basic auth
- Send statistics on submitted claims to Geckoboard
- A service operator can create and download a Database of qualified teachers (DQT) report request csv file
> Release 031

- CHANGELOG.md
- app/views/claims/student_loan.html.erb
This adds some copy to the student loan question to make it clear as to why we're asking for this information (which is more important given the Maths and Physics payment has, on the surface, no relation to student loans)
> Make it clear why we ask the student loan question

- CHANGELOG.md
- app/models/maths_and_physics/eligibility.rb
- app/models/maths_and_physics/slug_sequence.rb
- app/views/maths_and_physics/claims/_ineligibility_reason_subject_to_disciplinary_action.html.erb
- app/views/maths_and_physics/claims/_ineligibility_reason_subject_to_formal_performance_action.html.erb
- app/views/maths_and_physics/claims/disciplinary_action.html.erb
- app/views/maths_and_physics/claims/formal_performance_action.html.erb
- app/views/maths_and_physics/claims/teaching_maths_or_physics.html.erb
- config/locales/en.yml
- db/migrate/20191121122831_add_subject_to_disciplinary_action_to_maths_and_physics_eligibilities.rb
- db/migrate/20191121132035_add_subject_to_formal_performance_action_to_maths_and_physics_eligibilities.rb
- db/schema.rb
- spec/factories/maths_and_physics/eligibilities.rb
- spec/features/ineligible_maths_and_physics_claims_spec.rb
- spec/features/maths_and_physics_claim_spec.rb
- spec/models/maths_and_physics/eligibility_spec.rb
This PR completes the eligibility journey for Maths and Physics.
> Add final two Maths and Physics eligibility questions

- azure/resource_groups/app/parameters/development.template.json
- azure/resource_groups/app/parameters/production.template.json
This is what we had before, so it's what Verify expect
> Prepend verify entity IDs with https://

- app/views/static_pages/maths_and_physics.html.erb
This updates the temporary start page with new copy, as outlined in https://docs.google.com/document/d/17jGw6JSuGSadfDWfcqC27nNvR2vRWgA_hrHa30sbAco/edit#
> Update the replica start page with new copy

- db/seeds.rb
- spec/factories/payments.rb
- spec/factories/payroll_runs.rb
- spec/features/admin_payroll_runs_spec.rb
- spec/models/claim_spec.rb
- spec/models/payment_confirmation_spec.rb
- spec/models/payroll/claims_csv_spec.rb
- spec/requests/admin_payment_confirmation_report_upload_spec.rb
- spec/requests/admin_payroll_runs_spec.rb
Local development quality-of-life improvement.
> Add maths and physics seeds

- CHANGELOG.md
- app/views/static_pages/privacy_notice.html.erb
- config/locales/en.yml
This makes the privacy notice work for either (any) policy.
> Privacy notice wording works for Maths & Physics

- app/views/admin/payroll_runs/show.html.erb
After loosing my mind through rebasing #682 this got missed and we would like to demo the feature so apologies for having two PRs open but it would be great to get this merged! 😬
> Fix missing data attribute on payroll run link

- CHANGELOG.md
- Import users from DfE Signin to the local database
- Bump Rack library dependency with security update
> Release 042

- app/views/claims/_school_search.html.erb
> Fix the school search hint's markup

- CHANGELOG.md
- Feedback link tells users it will open in a new tab
- Changed existing session page to use radios and tidy up the iterruption card
- Semantic Logger has been added to make log entries more concise and useful
- Application logs can now be sent to Logstash for aggregation, analysis and monitoring
- Allow unverified addresses from GOV.UK Verify responses
- Unsubmitted claims are purged every 24 hours
- Batch Geckoboard data when submitting to the API
> Release 046

- app/assets/javascripts/components/school_search.js.erb
- app/controllers/admin/base_admin_controller.rb
- app/controllers/base_public_controller.rb
- app/controllers/concerns/admin_session_timeout.rb
- app/controllers/concerns/claim_session_timeout.rb
- app/controllers/school_search_controller.rb
- app/controllers/sessions_controller.rb
- config/initializers/session_store.rb
- spec/features/school_search_spec.rb
- spec/requests/admin_timeout_spec.rb
- spec/requests/school_search_spec.rb
- spec/requests/sessions_spec.rb
Some fixes and tweaks to deal with some of the exception noise we've been seeing the last couple of days. Full details in each commit message.
> Fix session timeout/CSRF-related issues

- app/assets/javascripts/components/school_search.js.erb
- app/controllers/base_public_controller.rb
- app/controllers/concerns/part_of_claim_journey.rb
- app/controllers/school_search_controller.rb
- spec/features/school_search_spec.rb
- spec/requests/school_search_spec.rb
A couple of changes to reduce the amount of exception noise related to expiring sessions and CSRF protection.
> School search and caching tweaks.

- CHANGELOG.md
- app/models/claim/school_check_email_data_export.rb
- spec/models/claim/school_check_email_data_export_spec.rb
Resolve some issues with `Claim::SchoolCheckEmailDataExport` which are blocking the next export.
> Fixes to school check export

- docs/geckoboard.md
Document how the Geckoboard dataset works and what data is sent.
[Read this documentation as it would appear on GitHub](https://github.com/DFE-Digital/dfe-teachers-payment-service/blob/geckoboard-documentation/docs/geckoboard.md)
> Add documentation on the Geckboard dataset

- lib/tasks/schools_data.rake
Since we last ran this task, we have introduced multiple concepts of
eligibility for Student Loans. So, handle differing method signatures.
> Fix the schools_data:export:student_loans Rake task

- CHANGELOG.md
- app/views/claims/verified.html.erb
> Update "Some of this information is wrong" content on the verified page

- CHANGELOG.md
- Update admin menu with new layout
- Update "Some of this information is wrong" content on the verified page
- A Service Operator can remove problematic payments from a payroll run
> Release 052

- CHANGELOG.md
Forgot to update the changelog!
> Update Changelog for #863

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- lib/file_download.rb
- spec/lib/file_download_spec.rb
This resolves growing memory usage during the school data import job.
> Swap Net/HTTP for HTTPClient in file_download

- README.md
- docs/school-check-data.md
Create a step-by-step guide to the developer process for generating a school check data batch.
> Document developer process for generating school check data

- app.json
- db/seeds.rb
This updates the Heroku config and seeds.rb file to get Heroku Review Apps working per-branch. This required a bunch of futzing around to get the seeds to load on first deploy mostly related to the way fixtures and factories behave in the postdeploy hook on Heroku.
> Get Heroku Review Apps working

- config/initializers/logstash.rb
- lib/environment_log_formatter.rb
- spec/lib/environment_log_formatter_spec.rb
Let's revert this. It's currently broken master and doesn't fix the problem anyway
> Revert "Simplify log formatting"

- app/views/admin/decisions/_decision_form.html.erb
- app/views/admin/decisions/new.html.erb
The layout/width should be defined by the view that the partial is rendered inside.
> Make the decision form partial layout agnostic

- CHANGELOG.md
- app/models/admin/presenter_methods.rb
- app/models/payment_confirmation_csv.rb
- app/views/admin/payroll_runs/index.html.erb
- app/views/admin/payroll_runs/show.html.erb
- app/views/admin/policy_configurations/edit.html.erb
- app/views/admin/policy_configurations/index.html.erb
- spec/models/admin/presenter_methods_spec.rb
- spec/models/payment_confirmation_csv_spec.rb
- spec/requests/admin_payment_confirmation_report_upload_spec.rb
This is the second PR for updating the admin area. It contains a series of commits mostly focused on screen reader improvements such as adding in visually hidden text within tables or links.
> Accessibility testing admin area part 2

- azure-deploy-template.yml
- azure-pipelines.yml
A couple of things went wrong when pushing to master. This should fix them.
> Fix deployment script

- CHANGELOG.md
- Links that look like buttons now work if users have JS on the claim journey
- Links styled as buttons now work as expected for keyboard users
- Manage services page validates in html checker
- Improve guidance on admin file upload when no file is selected
- Add visually hidden text to manage services
- Screen reader improvements when viewing payrun
- Add visually hidden text to payroll history table
- Add visually hidden text to GIAS school link
- Allow service operators to navigate to decision page
- Financial year for student loans claims varies based on the current academic
year
> Release 059

- CHANGELOG.md
- Add a task for confirming the student loan amount on Student Loans claims
- Student Loans claims default to new task-based claim checking interface
- Claim checking tasks have unique headings
- Show NI number in the claim summary
> Release 061

- CHANGELOG.md
- Add Yes/No option to claim checking tasks
- Update payment removal content
> Release 062

- CHANGELOG.md
- app/assets/stylesheets/components/currency_input.scss
- app/controllers/admin/amendments_controller.rb
- app/helpers/admin/timeline_helper.rb
- app/models/amendment.rb
- app/models/claim.rb
- app/models/maths_and_physics/eligibility.rb
- app/models/policies.rb
- app/models/student_loans/eligibility.rb
- app/views/admin/amendments/new.html.erb
- spec/features/admin_amend_claim_spec.rb
- spec/helpers/admin/timeline_helper_spec.rb
- spec/models/amendment_spec.rb
- spec/models/student_loans/eligibility_spec.rb
It's not a particularly elegant solution, but this change will allow service operators to amend the student loan amount. I've also added a upper limit of £5000 to the amendment.
> Support amending the student loan amount

- CHANGELOG.md
- Show the academic year when viewing a claim
- Support amending the student loan amount
> Release 065

- app/views/admin/qualification_report_uploads/new.html.erb
Muzamil no longer works for DQT
> Update DQT contact email address

- azure/resource_groups/app/parameters/development.template.json
Testing out Tekin's instructions for key rotation [1]. This is step 3.
[1] https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/998/commits/720bfcb4b82c53141e0b257e2c1bf806524492ea
> Add development VSP encryption key version 8

- azure/resource_groups/app/parameters/development.template.json
Testing out Tekin's instructions for key rotation [1]. This is step 6.
[1] https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/998/commits/720bfcb4b82c53141e0b257e2c1bf806524492ea
> Switch development VSP signing key to version 8

- azure/resource_groups/app/parameters/development.template.json
Testing out Tekin's instructions for key rotation [1]. This is step 7.
[1] https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/998/commits/720bfcb4b82c53141e0b257e2c1bf806524492ea
> Switch development VSP secondary encryption key to primary

- README.md
- docs/dfe-sign-in.md
- docs/first-line-support-developer-runbook.md
- docs/logging.md
- docs/privileged-identity-management-requests.md
This will hopefully be a useful first place for new dxw support developers to look.
> Add a runbook for first-line support developers

- CHANGELOG.md
Prettier fix within CHANGELOG.md
> Prettier fix for release 068

- README.md
This section was out of date and didn't reflect the words we now use to describe opening and closing each service.
> Adjust README bit about maintenance mode

- app/views/claims/information_provided.html.erb
> Changing Teacher Pension Service to Scheme

- README.md
> Fix capitalisation of Confluence

- app/views/payment_mailer/confirmation_for_multiple_claims.text.erb
Added information that Cantium will appear on bank statements as the sender.
> Added Cantium info

- docs/developer-onboarding.md
I’m not yet sure where we’ll link to this from, but probably either
internal dxw documentation, or the onboarding checklist that we’ll make
for the product owner.
> Add guidance on how to set up Azure 2-factor auth

- README.md
- docs/first-line-support-developer-runbook.md
- docs/govuk-verify.md
- docs/secrets.md
This explains:
- where to find the development website
- where to find the basic auth credentials
- how to get through GOV.UK Verify in development
> Document how to use the development website

- CHANGELOG.md
- Improve message shown when inconsistent payroll information is found
- Service operators can add a support ticket to claims
> Release 069

- CHANGELOG.md
- Add secondary SAML encryption key in preparation for rotating production VSP keys and certificates
> Release 070

- CHANGELOG.md
- The identity confirmation task is now present on all submitted claims
> Release 071

- CHANGELOG.md
- DQT report upload now performs automated identity confirmation checks
> Release 072

- docs/developer-onboarding.md
- docs/first-line-support-developer-runbook.md
- docs/privileged-identity-management-requests.md
I have not yet tested this end to end with a developer, so it might need more tweaks.
> Add instructions for onboarding a support developer

- CHANGELOG.md
- Display payroll status of claim within task view
- Display claim amount within task view
> Release 074

- docs/first-line-support-developer-runbook.md
Add documentation to the runbook for restarting the worker container.
> Document the process of restarting the worker

- CHANGELOG.md
> Release 076

- CHANGELOG.md
- Remove banking_name when scrubbing personal data from a claim
> Release 078

- CHANGELOG.md
- Bump rails from 6.0.3.1 to 6.0.3.2
> Release 080

- CHANGELOG.md
- app/views/claims/bank_details.html.erb
- app/views/claims/email_address.html.erb
- app/views/claims/teacher_reference_number.html.erb
- spec/features/student_loans_claim_spec.rb
> Content changes ready for opening AY20 21

- app/views/claims/information_provided.html.erb
> change the line 'we will check' to 'we may check'

- app/views/claims/teacher_reference_number.html.erb
> Update TRN phone number format

- app/views/static_pages/privacy_notice.html.erb
> update the privacy notice with changes ready for 2020-21 academic year

- CHANGELOG.md
- Changes made to content pages ready for academic year 2020-21
- Update code formatting to match latest Standard version
> Release 081

- CHANGELOG.md
- Break down number of claims and claim amount in payroll runs by policy
- Display the correct financial year for employment as part of the employment task
> Release 082

- CHANGELOG.md
- app/models/payment.rb
- app/models/payment_confirmation_csv.rb
- app/models/payroll/payments_csv.rb
- spec/features/admin_payroll_runs_spec.rb
- spec/models/payment_confirmation_csv_spec.rb
- spec/models/payment_confirmation_spec.rb
- spec/models/payment_spec.rb
- spec/models/payroll/payment_csv_row_spec.rb
- spec/models/payroll/payments_csv_spec.rb
- spec/requests/admin_payment_confirmation_report_upload_spec.rb
- Geckoboard now only includes claims from the current academic year
> Release 083

- CHANGELOG.md
- app/models/claim/data_report_request.rb
- spec/features/admin_data_report_request_spec.rb
- spec/models/claim/data_report_request_spec.rb
> Update data report request csv, corresponding tests and changelong

- CHANGELOG.md
> release 084 - adds DOB and Email to report

- CHANGELOG.md
- Update payment email copy
- Seperate policies in payment with a space
> Release 085

- CHANGELOG.md
- Fix incorrect summing for claims by policy
> Release 086

- CHANGELOG.md
- app/views/claim_mailer/approved.text.erb
- app/views/claim_mailer/submitted.text.erb
Amend email copy for "claim submitted" and "claim approved"
> (Zendesk/12094) Update claims email copy

- CHANGELOG.md
- Update the DQT automation to include HECOS codes as well as JACS codes
- Update email copy for claim submitted and claim approved
- Fix incorrect display of claims in payroll run
- Update Verify Service Provider to version 2.2.0
> Release 087

- azure/resource_groups/secrets/template.json
StorageV1 has been deprecated.
> Switch storage resource to use StorageV2

- docs/dfe-sign-in.md
[ECP-194](https://dfedigital.atlassian.net/jira/software/projects/ECP/boards/84?selectedIssue=ECP-194) As part of reviewing access via DFE Sign-in it was identified that the process on the DfE side had changed and this is the resulting update to documentation
> [ECP-194]- update documentation as the process has changed

- Dockerfile
Fixes mimemagic linux package dependency resolution
> [task/ECP-410] - add shared-mime-info package to Dockerfile

- CHANGELOG.md
> [task/ECP-414] - Retrospective updates to CHANGELOG

- docs/architecture-decisions/0008-use-govuk-verify-for-claiment-identity-assurance.md
- docs/architecture-decisions/0012-automate-dqt-integration.md
- reflects the decision to deprecate ADR-0008
- reflects new ADR 0012 to replace GOVUK Verify with DqT integration
This pull request is only to update the document so that we could record all architecture decisions that could make an impact on the service.
Co-authored-by: Muhammad Shakir <muhammad.shakir@and.digital>
> [feature/ECP-317] - Update ADR records

- Gemfile
- Gemfile.lock
- app/views/early_career_payments/claims/landing_page.html.erb
-  [ECP-508]
- Creating a new view for the ECP journey that contains the landing page to start the journey. 
- Added the form builder gem for future implementation.
[ECP-508]: https://dfedigital.atlassian.net/browse/ECP-508
> Creating the ECP landing page view for new user journey 

- CHANGELOG.md
- app/views/early_career_payments/claims/ineligible.html.erb
- config/locales/en.yml
- spec/features/early_career_payments_claim_spec.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
View build for the not eligible page
> [story/ECP-481] - User Journey Page 18 - 'You are not eligible for an early careers payment'

- CHANGELOG.md
- app/controllers/claims_controller.rb
- app/models/claim.rb
- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/eligibility_admin_answers_presenter.rb
- app/models/early_career_payments/eligibility_answers_presenter.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/early_career_payments/claims/supply_teacher.html.erb
- config/locales/en.yml
- db/migrate/20210420142343_add_employed_as_supply_teacher_to_early_career_payments_eligibilities.rb
- db/schema.rb
- spec/factories/early_career_payments/eligibilities.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/models/claim_spec.rb
- spec/models/early_career_payments/eligibility_admin_answers_presenter_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
- spec/requests/admin_claims_spec.rb
- spec/requests/admin_payroll_gender_tasks_spec.rb
- spec/requests/admin_tasks_spec.rb
Add this page for the Early Career Payments claimant journey
> [story/ECP-464] - User Journey Page 4 - 'Are you currently employed as a Supply Teacher'

- CHANGELOG.md
- app/controllers/claims_controller.rb
- app/models/claim.rb
- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/eligibility_answers_presenter.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/early_career_payments/claims/entire_term_contract.html.erb
- config/locales/en.yml
- db/migrate/20210421233832_add_has_entire_term_contract_to_early_career_payments_eligibilities.rb
- db/schema.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/models/claim_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
- spec/support/feature_helpers.rb
Add this page for the Early Career Payments claimant journey
> [story/ECP-465] - User Journey Page 5 - 'Do you have a contract to teach at the same school for an entire term or longer?'

- CHANGELOG.md
- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/eligibility_answers_presenter.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/early_career_payments/claims/employed_directly.html.erb
- config/locales/en.yml
- db/migrate/20210422193758_add_employed_directly_to_early_career_payments_eligibilities.rb
- db/schema.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/models/claim_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
View built for user journey page 6 'are you employed directly by your school'
> [story/ECP-466] - User Journey Page 6 - 'Are you employed directly by your school?'

- CHANGELOG.md
- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/eligibility_answers_presenter.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/early_career_payments/claims/disciplinary_action.html.erb
- config/locales/en.yml
- db/migrate/20210422225248_add_subject_to_disciplinary_action_to_early_career_payments_eligibilities.rb
- db/schema.rb
- spec/factories/early_career_payments/eligibilities.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
View build for the disciplinary action question.
> [story/ECP-468] - User Journey Page 8 - 'Are you currently subject to disciplinary action?'

- CHANGELOG.md
- app/models/claim.rb
- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/eligibility_answers_presenter.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/early_career_payments/claims/eligible_itt_subject.html.erb
- config/locales/en.yml
- db/migrate/20210424231757_add_eligible_itt_subject_to_early_career_payments_eligibilities.rb
- db/schema.rb
- spec/factories/early_career_payments/eligibilities.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
View build for the undergraduate ITT subject page for ECP
> [story/ECP-471] - User Journey Page 10 - 'Which subject did you do your undergraduate ITT in?'

- CHANGELOG.md
- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/eligibility_answers_presenter.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/early_career_payments/claims/teaching_subject_now.html.erb
- config/locales/en.yml
- db/migrate/20210428070526_add_teaching_subject_now_to_early_career_payments_eligibilities.rb
- db/schema.rb
- spec/factories/early_career_payments/eligibilities.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
View build for the teaching maths now page for ECP
> [story/ECP-475] - User Journey Page 12 - 'Do you teach maths now?'

- CHANGELOG.md
- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/eligibility_answers_presenter.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/early_career_payments/claims/itt_year.html.erb
- app/views/early_career_payments/claims/undergraduate_itt_academic_year.html.erb
- config/locales/en.yml
- db/migrate/20210428223553_add_itt_academic_year_to_early_career_payments_eligibilities.rb
- db/schema.rb
- spec/factories/early_career_payments/eligibilities.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
View build for the undergraduate ITT academic year page for ECP
> [story/ECP-476] - User Journey Page 13 - 'In what academic year did you complete your undergraduate ITT?'

- bin/azure-deploy
> Update azure-deploy to add a PS call 

- CHANGELOG.md
- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/eligibility_answers_presenter.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/early_career_payments/claims/masters_loan.html.erb
- config/locales/en.yml
- db/migrate/20210430184810_add_postgraduate_masters_loan_to_early_career_payments_eligibilities.rb
- db/schema.rb
- spec/factories/early_career_payments/eligibilities.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
View build for the postgraduate masters loan page for ECP
> [story/ECP-503] - User Journey Page 35 - 'Did you take out a Postgraduate Master's Loan on or after 1 August 2016?'

- app/models/claim.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/early_career_payments/claims/personal_details.html.erb
- config/locales/en.yml
- db/schema.rb
- spec/features/early_career_payments_claim_spec.rb
View build for the personal details page for ECP
> [story/ECP-490] - User Journey Page 24 - 'Personal Details'

- app/models/early_career_payments/slug_sequence.rb
- app/views/early_career_payments/claims/how_we_will_use_information_provided.html.erb
- spec/features/early_career_payments_claim_spec.rb
View build for the 'how we will use your information' page for ECP
> [story/ECP-489] - User Journey Page 23 - 'How we will use the information you provide'

- CHANGELOG.md
- app/models/claim.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/claims/gender.html.erb
- spec/features/early_career_payments_claim_spec.rb
- Dynamic title sizing added to pre existing file
- Tests added to ECP claim journey
> [story/ECP-494] - Personal Details: What gender does your school's payroll system associate with you?

- CHANGELOG.md
- app/models/claim.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/claims/address.html.erb
- spec/features/early_career_payments_claim_spec.rb
- Dynamic title sizing added to pre-existing file
- Tests added to ECP claim journey
> [story/ECP-491] - Personal Details: Personal Details: What is your address?

- CHANGELOG.md
- app/models/claim.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/claims/bank_details.html.erb
- spec/features/early_career_payments_claim_spec.rb
- Dynamic title sizing added to pre-existing file
- Tests added to ECP claim journey
> [story/ECP-494] - 'Personal Details: Enter bank account details'

- CHANGELOG.md
- app/helpers/claims_helper.rb
- app/models/early_career_payments/eligibility_answers_presenter.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/early_career_payments/claims/check_your_answers_part_one.html.erb
- config/locales/en.yml
- spec/factories/claims.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/helpers/claims_helper_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
> [story/ECP-478] - Add 'Check your answers for eligibility?'

- CHANGELOG.md
- app/helpers/claims/email_address_helper.rb
- app/models/claim.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/claims/email_address.html.erb
- config/locales/en.yml
- spec/features/early_career_payments_claim_spec.rb
- spec/helpers/claims/email_address_helper_spec.rb
> [story/ECP-492] - Add Personal Details page 'Email Address' to ECP journey

- CHANGELOG.md
- app/models/claim.rb
- app/models/early_career_payments/slug_sequence.rb
- spec/features/early_career_payments_claim_spec.rb
> [story/ECP-496] - User Journey Page 30 - 'Student Loans: Are you currently paying off your student loan?'

- CHANGELOG.md
- app/models/early_career_payments/eligibility.rb
- app/views/early_career_payments/claims/_ineligibility_reason_generic_ineligibility.html.erb
- app/views/early_career_payments/claims/_ineligibility_reason_itt_subject_none_of_the_above.html.erb
- app/views/early_career_payments/claims/_ineligibility_reason_not_teaching_now_in_eligible_itt_subject.html.erb
- app/views/early_career_payments/claims/_ineligibility_reason_subject_to_formal_performance_action.html.erb
- app/views/early_career_payments/claims/ineligible.html.erb
- config/locales/en.yml
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
- Refactor ineligible error page
- Add #ineligibility_reason for use with ineligible page using a partial based on the reason of ineligibility
> [story/ECP-581] - Add 'You are not eligible' (Subject) page

- CHANGELOG.md
- app/models/claim.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/claims/email_address.html.erb
- app/views/claims/teacher_reference_number.html.erb
- app/views/early_career_payments/claims/nqt_in_academic_year_after_itt.html.erb
- spec/features/early_career_payments_claim_spec.rb
- Added conditional rendering for hints on TRN page 
- TRN added to spec 
- _sizing for heading fixed on email address page also_
> [story/ECP-495] - Personal Details: What is your teacher reference number?

- CHANGELOG.md
- app/helpers/claims/check_your_answers_helper.rb
- app/helpers/claims/show_helper.rb
- app/views/claims/address.html.erb
- app/views/claims/bank_details.html.erb
- app/views/claims/check_your_answers.html.erb
- app/views/claims/gender.html.erb
- app/views/early_career_payments/claims/check_your_answers_part_one.html.erb
- app/views/early_career_payments/claims/disciplinary_action.html.erb
- app/views/early_career_payments/claims/eligible_itt_subject.html.erb
- config/locales/en.yml
- spec/features/early_career_payments_claim_spec.rb
- spec/helpers/claims/check_your_answers_helper_spec.rb
- spec/helpers/claims/show_helper_spec.rb
> [story/ECP-505] - Add 'Check your answers before sending your application' page to ECP journey

- CHANGELOG.md
- app/models/early_career_payments/slug_sequence.rb
- spec/features/early_career_payments_claim_spec.rb
> [story/ECP-497] - User Journey Page 31 - 'Student Loans: When you applied for your student loan where was your home address?''

- azure/resource_groups/ProjectCore/template.json
> [bug/ECP-628] - added Server farm delegation to default subnet

- azure/resource_groups/ProjectCore/template.json
> altered delegation format

- azure/resource_groups/ProjectCore/template.json
- bin/azure-deploy
> removed ProjectCore references

- CHANGELOG.md
- app/assets/javascripts/components/school_search.js.erb
- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/eligibility_answers_presenter.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/claims/_school_search.html.erb
- app/views/claims/_school_search_results.html.erb
- app/views/claims/current_school.html.erb
- config/locales/en.yml
- db/migrate/20210511105439_add_current_school_id_to_early_career_payments_eligibilities.rb
- db/schema.rb
- spec/factories/early_career_payments/eligibilities.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
- Page 2/3 school search and school search results pages completed, tested, and added to the check your answers section
- javascript updated to match new requirements
> [story/ECP-462/463] - Add 'school search pages 2/3 to ECP policy'

- azure/terraform/data.tf
- azure/terraform/env.ps1
- azure/terraform/modules/app_service/app_service_slot.tf
- azure/terraform/provider.tf
- azure/terraform/variable.tf
> Test Release testing

- azure/terraform/env.ps1
- azure/terraform/modules/app_service/app_service.tf
- azure/terraform/modules/app_service/app_service_slot.tf
- azure/terraform/modules/container/container_group.tf
> updated to point to ACR

- azure-pipelines.yml
> updated file name for tagging line 116

- azure-pipelines.yml
> added condition on the web image for master

- azure-pipelines.yml
> updated tag scripts

- azure-pipelines.yml
> updated tag in web-dependencies build

- azure-pipelines.yml
> added repository into web-dependencies build

- azure/terraform/env.ps1
- azure/terraform/modules/app_service/app_service.tf
- azure/terraform/modules/app_service/app_service_slot.tf
- azure/terraform/modules/container/container_group.tf
- azure/terraform/modules/container/data.tf
> added registry auth settings

- app/mailers/claim_mailer.rb
- app/models/automated_checks/claim_verifiers/identity.rb
- app/views/claim_mailer/identity_confirmation.text.erb
- spec/mailers/claim_mailer_spec.rb
- spec/models/automated_checks/claim_verifiers/identity_spec.rb
- spec/rails_helper.rb
- spec/support/is_expected_with_block.rb
> Add claim identity confirmation mailer for automated checks claim verifiers identity no match [ECP-342]

- CHANGELOG.md
- app/models/early_career_payments.rb
- app/models/early_career_payments/slug_sequence.rb
- config/locales/en.yml
- spec/features/early_career_payments_claim_spec.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/helpers/claims_helper_spec.rb
- spec/models/claim_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
- spec/models/early_career_payments_spec.rb
- spec/support/feature_helpers.rb
> [story/ECP-527] - Amend wording for ECP description

- app/models/early_career_payments/eligibility.rb
- app/views/early_career_payments/claims/_ineligibility_reason_itt_subject_none_of_the_above.html.erb
- app/views/early_career_payments/claims/eligible_itt_subject.html.erb
- app/views/static_pages/landing_page.html.erb
- config/locales/en.yml
- spec/factories/early_career_payments/eligibilities.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
> [story/ECP-859] - V7-V10 Update: Content change to Q 'Which subject did you do your undergraduate ITT in?'

- azure/terraform/modules/container/container_group.tf
- azure/terraform/modules/container/data.tf
> added three DQT env vars to container TF

- azure/terraform/modules/app_service/variable.tf
- azure/terraform/modules/container/container_group.tf
- azure/terraform/modules/container/variable.tf
> merge for worker start fix

- app/views/early_career_payments/claims/personal_details.html.erb
> [story/ECP-870] - V7-V10 Update: Content change to 'Personal details'

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/controllers/base_public_controller.rb
- app/controllers/claims_controller.rb
- app/mailers/claim_mailer.rb
- app/models/claim.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/claim_mailer/ecp_email_verification.text.erb
- app/views/early_career_payments/claims/_one_time_password.html.erb
- app/views/early_career_payments/claims/email_verification.html.erb
- app/views/early_career_payments/claims/reminder_email_verification.html.erb
- config/application.rb
- config/locales/en.yml
- lib/one_time_password.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/validating_user_contact_details_spec.rb
- spec/mailers/claim_mailer_spec.rb
- spec/mailers/previews/claim_mailer_preview.rb
- spec/models/claim/permitted_parameters_spec.rb
- spec/models/claim_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
> [story/ECP-274] - Implement One Time Password (OTP) Email Component in ECP User Journey

- CHANGELOG.md
- app/models/early_career_payments/school_eligibility.rb
- spec/models/early_career_payments/school_eligibility_spec.rb
> [story/ECP-625] - Creating logic for identifying uplift ECP schools

- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/eligibility_matrix_calculator.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/early_career_payments/claims/eligible_later.html.erb
- spec/factories/early_career_payments/eligibilities.rb
- spec/models/early_career_payments/eligibility_matrix_calculator_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
View build for the eligible later page for ECP
> [story/ECP-485] - User Journey Page 19 - 'You will be eligible for an early career payment in 2022'

- azure/terraform/modules/container/container_group.tf
- azure/terraform/modules/container/data.tf
> removed dqt_client_port from container build

- azure/terraform/modules/app_service/app_service_slot.tf
- azure/terraform/modules/container/container_group.tf
> added variables for env variables

- CHANGELOG.md
Created a release candidate for the PB so that the Beta team could have a stable version and could perform exploratory testing before releasing in production.
> Release 090

- app/views/submissions/_completion.html.erb
- spec/features/early_career_payments_claim_spec.rb
> [story/ECP-915] - Update 'Application complete' screen

- CHANGELOG.md
- app/models/early_career_payments/eligibility.rb
- app/views/claims/check_your_answers.html.erb
- spec/factories/early_career_payments/eligibilities.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
Co-authored-by: Mark Sutton <work.sutton.notifications@gmail.com>
> Add subject cohort ineligibility to ECP eligibility

- app/models/early_career_payments.rb
- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/early_career_payments/claims/eligibility_confirmed.html.erb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/models/claim_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
- spec/models/early_career_payments_spec.rb
> Add 'You are eligible for an early careers payment' screen to ECP journey after first 'Check your answers' screen

- app/controllers/claims_controller.rb
- app/views/early_career_payments/claims/eligibility_confirmed.html.erb
> [bug/ECP-932] - Fix No Validation on Personal Detail: Email address page

- CHANGELOG.md
- app/helpers/claims_helper.rb
- app/models/claim.rb
- app/models/early_career_payments/slug_sequence.rb
- app/models/maths_and_physics/slug_sequence.rb
- app/models/student_loans/slug_sequence.rb
- app/views/claims/bank_or_building_society.html.erb
- config/locales/en.yml
- db/migrate/20210615171328_add_bank_or_building_society_to_claim.rb
- db/schema.rb
- spec/factories/claims.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/maths_and_physics_claim_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/helpers/claims_helper_spec.rb
- spec/models/claim/permitted_parameters_spec.rb
- spec/models/claim_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
> [story/ECP-888] - Add 'What account do you want the money paid into?' screen

- app/views/static_pages/landing_page.html.erb
> [story/ECP-954] - V12 Content Change: ECP Start Page - Spell Out ITT Acronym

- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/eligibility_answers_presenter.rb
- app/views/early_career_payments/claims/eligible_itt_subject.html.erb
- app/views/early_career_payments/claims/itt_year.html.erb
- app/views/early_career_payments/claims/qualification.html.erb
- config/locales/en.yml
- spec/factories/early_career_payments/eligibilities.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
> [story/ECP-858] - Fix missing titles for postgraduate/undergraduate ITT

- CHANGELOG.md
- config/locales/en.yml
- spec/features/early_career_payments_claim_spec.rb
> [story/ECP-864] - Update 'Which subject did you do your qualification in?' screen for Assessment Only

- CHANGELOG.md
- app/models/early_career_payments/eligibility.rb
- config/locales/en.yml
- spec/models/early_career_payments/eligibility_spec.rb
> [story/ECP-865] - Update 'Which subject did you do your qualification  in?' screen for Overseas Recognition

- app/controllers/claims_controller.rb
- app/mailers/claim_mailer.rb
- app/models/claim.rb
- app/models/maths_and_physics/slug_sequence.rb
- app/models/student_loans/slug_sequence.rb
- app/views/claim_mailer/email_verification.text.erb
- app/views/claims/_one_time_password.html.erb
- app/views/claims/email_verification.html.erb
- app/views/early_career_payments/claims/email_verification.html.erb
- config/locales/en.yml
- spec/features/maths_and_physics_claim_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/mailers/claim_mailer_spec.rb
> Add email verification (OTP) to other policies

- CHANGELOG.md
- app/views/claims/address.html.erb
- spec/features/early_career_payments_claim_spec.rb
> [story/ECP-872] - Update content for 'What is your address?' screen

- CHANGELOG.md
- app/controllers/reminders_controller.rb
- app/models/reminder.rb
- app/views/early_career_payments/claims/eligible_later.html.erb
- app/views/reminders/personal_details.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20210628223812_create_reminders.rb
- db/schema.rb
- spec/factories/reminders.rb
- spec/features/reminders_spec.rb
- spec/models/reminder_spec.rb
> [story/ecp-486] - Add 'Set up a Reminder - Enter Personal Details' screen to ECP eligible later journey

- CHANGELOG.md
- lib/dqt/api/v1/qualified_teaching_status.rb
- lib/dqt/client.rb
- spec/lib/dqt/api/v1/qualified_teaching_status_spec.rb
- spec/lib/dqt/client_spec.rb
- spec/support/dqt_helpers.rb
> Update DQT client qualified teacher status to handle 404 response

- azure/terraform/modules/app_service/data.tf
- azure/terraform/modules/container/data.tf
- spec/lib/dqt/client_spec.rb
> [bug/ECP-896] - remove hard coded value

- app/controllers/claims_controller.rb
- app/models/claim.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/claim_mailer/email_verification.text.erb
- app/views/claims/_one_time_password.html.erb
- app/views/claims/_one_time_password_mobile.html.erb
- app/views/claims/email_verification.html.erb
- app/views/claims/mobile_verification.html.erb
- config/locales/en.yml
- spec/features/early_career_payments_claim_spec.rb
- spec/mailers/claim_mailer_spec.rb
- spec/models/claim_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
> [story/ECP-886] - Add 'OTP verification for mobile number' screen

- CHANGELOG.md
- app/assets/stylesheets/components/tag.scss
- app/helpers/admin/claims_helper.rb
- app/models/automated_checks/claim_verifiers/identity.rb
- app/models/automated_checks/claim_verifiers/qualifications.rb
- app/models/student_loans/dqt_record.rb
- app/models/task.rb
- db/migrate/20210701152930_add_claim_verifier_match_to_tasks.rb
- db/schema.rb
- spec/features/admin_claim_tasks_update_with_dqt_api_spec.rb
- spec/features/admin_claim_tasks_update_with_dqt_csv_spec.rb
- spec/helpers/admin/claims_helper_spec.rb
- spec/models/automated_checks/claim_verifiers/identity_spec.rb
- spec/models/automated_checks/claim_verifiers/qualifications_spec.rb
- spec/models/automated_checks/dqt_report_consumer_spec.rb
- spec/models/student_loans/dqt_record_spec.rb
- Add 'Full match' status
- Add 'Partial match' status
- Add 'No match' status
- Update to latest Design System colours
- Use multiple colours
ECP-892
> Add multiple statuses to admin task statuses

- app/models/early_career_payments/eligibility.rb
> [bug/ECP-1075] - Update validation for qualification page

- CHANGELOG.md
- app/models/early_career_payments/eligibility.rb
- config/locales/en.yml
> [bug/ECP-1099] - Update validation for eligible itt subject

- app/assets/javascripts/components/backlink.js
- app/views/claims/current_school.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_backlink.html.erb
- config/environments/development.rb
- spec/features/backlink_spec.rb
_https://dfedigital.atlassian.net/browse/ECP-611_
________
Adds backlinks to all screen on all pages, barring: claims, complete, existing-session. 
TODO
> [story/ECP-611] - Add backlinks

- CHANGELOG.md
- app/models/early_career_payments/eligibility.rb
- app/views/early_career_payments/claims/_ineligibility_reason_poor_performance.html.erb
- app/views/early_career_payments/claims/ineligible.html.erb
- config/locales/en.yml
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/helpers/early_career_payments_helper_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
_https://dfedigital.atlassian.net/browse/ECP-1071_
_____
> [story/ECP-1071] - Content Change  'You are not eligible for an early-careers payment'

- CHANGELOG.md
- app/models/maths_and_physics/slug_sequence.rb
- app/models/student_loans/slug_sequence.rb
- spec/features/maths_and_physics_claim_spec.rb
- spec/features/student_loans_claim_spec.rb
covers both:
https://dfedigital.atlassian.net/browse/ECP-976
https://dfedigital.atlassian.net/browse/ECP-974
> [story/ECP-976] - phone number screens in TSLR and M&P

- CHANGELOG.md
- app/views/admin/tasks/_claim_summary.html.erb
https://dfedigital.atlassian.net/browse/ECP-579
> [story/ECP-579] - Adds mobile to claims summary

- app/controllers/claims_controller.rb
- app/models/claim.rb
- spec/features/early_career_payments_claim_spec.rb
_https://dfedigital.atlassian.net/browse/ECP-1030_
> [bug/ECP-1030] - fixes error thrown on invalid OTP

- lib/ordnance_survey/api/v1/search_places.rb
- spec/lib/ordnance_survey/api/v1/search_places_spec.rb
- spec/support/ordnance_survey_helpers.rb
- Use BUILDING_NUMBER if supplied
- Return nil when no results returned for show endpoint - to prevent incorrect responses set a minimum threshold of 0.4 (minmatch)
Background documentation:
https://osdatahub.os.uk/docs/places/technicalSpecification
> [bug/ECP-1120] - fix issues

- CHANGELOG.md
- app/controllers/claims_controller.rb
- app/models/early_career_payments/slug_sequence.rb
- app/views/claims/address.html.erb
- app/views/claims/postcode_search.html.erb
- config/locales/en.yml
- spec/features/early_career_payments_claim_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
> [story/ECP-576] - Add home address search screen to claim journey

- app/controllers/reminders_controller.rb
- app/mailers/reminder_mailer.rb
- app/views/reminder_mailer/reminder_set.text.erb
- spec/features/reminders_spec.rb
https://dfedigital.atlassian.net/browse/ECP-882
> [story/ECP-882] - send future ECP payment reminder email

- spec/jobs/send_reminder_emails_job_spec.rb
https://dfedigital.atlassian.net/browse/ECP-1149
> [story/ECP-1149] - fixes flaky reminder email spec

- CHANGELOG.md
- README.md
- app/controllers/reminders_controller.rb
- app/controllers/submissions_controller.rb
- app/models/academic_year.rb
- app/views/reminder_mailer/reminder_set.text.erb
- app/views/reminders/set.html.erb
- app/views/submissions/_completion.html.erb
- spec/factories/claims.rb
- spec/features/ecp_eligible_now_reminder_set_spec.rb
- spec/features/reminders_spec.rb
- spec/support/capybara.rb
https://dfedigital.atlassian.net/browse/ECP-920
> [story/ECP-920] - add reminder flow to eligible now journey

- CHANGELOG.md
- app/controllers/claims_controller.rb
- app/models/claim.rb
- app/views/early_career_payments/claims/personal_details.html.erb
- spec/models/claim_spec.rb
Also closes off https://dfedigital.atlassian.net/browse/ECP-1133 for DAC Report -3. Error Skip Link - Personal Details page
> [bug/ECP-712] - Fix personal details error messages

- CHANGELOG.md
- app/controllers/reminders_controller.rb
- app/views/early_career_payments/claims/_ineligibility_reason_ineligible_nqt_in_academic_year_after_itt.html.erb
- spec/features/reminders_spec.rb
- allows a Trainee Teacher answering No to NQT question to set a reminder
> [bug/ECP-1202] - Update link_to with correct path

- CHANGELOG.md
- Site wide
- Update to Privacy Policy
- All policies
- Update to allow claimant to provide feedback via email (replaces google
forms)
- Early Career Payments
- Fix link to set reminder - I am a Trainee Teacher (NQT question)
- Remove '?' at end of some URL's (information provided / eligibility
confirmed)
- Admin
- Student Loan Plan Types
- Update the CSV Payroll file to include new plan types
> release-094

- CHANGELOG.md
- Google Analytics
- Adds CSV view for claim stats
- Early Career Payments
- Add Teacher Trainee mini journey (for 2021 ONLY)
- DAC Accessibility Report fixes
- Expanded wording of ITT when first used in ECP service
- TSLR and M&P
- Combining teacher personal details onto one page
> release-096

- lib/dqt/api/v1/qualified_teaching_status.rb
- spec/features/admin_claim_tasks_update_with_dqt_api_spec.rb
- spec/models/automated_checks/claim_verifiers/identity_spec.rb
- spec/models/automated_checks/claim_verifiers/qualifications_spec.rb
- spec/support/dqt_helpers.rb
> Fix dqt client qualified teacher status show national insurance param

- CHANGELOG.md
- All policies
- TRN hint text content change
- 'How is your gender recorded on your school’s payroll system?' page content change
- 'How we will use the information you provide' page content change
- Early Career Payments
- 'Which subject did you do your teaching qualification in?' content change
- 'Check your eligibility today' link update
- Upgrade to Ruby 2.7.3
> release-097

- CHANGELOG.md
- DAC Accessibility Report fixes
- Error skip link
> release-098

- CHANGELOG.md
- app/controllers/claims_controller.rb
- app/models/claim.rb
- spec/factories/claims.rb
- spec/features/changing_answers_spec.rb
- spec/models/claim_spec.rb
> [bug/ECP-1259] - Fix OTP not being enterable on changing contact details

- CHANGELOG.md
- app/views/early_career_payments/claims/nqt_in_academic_year_after_itt.html.erb
- for false radio button option
- on NQT (1st) question in ECP Journey
> [story/ECP-1244] - Toggle Trainee Teacher text - future years

- app/models/student_loans/eligibility.rb
- spec/features/student_loans_claim_spec.rb
- spec/models/student_loans/dqt_record_spec.rb
- spec/models/student_loans/eligibility_spec.rb
https://dfedigital.atlassian.net/browse/ECP-1252
> [story/ECP-1252] - adds specs for 2019, 2025, 2031 checks

- CHANGELOG.md
- app/models/payment_confirmation.rb
- app/models/payment_confirmation_csv.rb
- app/views/payment_mailer/confirmation_for_multiple_claims.text.erb
- app/views/payment_mailer/confirmation_for_single_claim.text.erb
- db/migrate/20211029142607_add_postgraduate_loan_repayment_to_payments.rb
- db/schema.rb
- spec/factories/claims.rb
- spec/features/admin_payroll_runs_spec.rb
- spec/mailers/payment_mailer_spec.rb
- spec/models/payment_confirmation_csv_spec.rb
- spec/models/payment_confirmation_spec.rb
- spec/requests/admin_payment_confirmation_report_upload_spec.rb
> [bug/ECP-1295] - Add Postgraduate Loan - Payment breakdown email (confirmation report upload)

- CHANGELOG.md
- app/views/claims/_school_search_results.html.erb
- app/views/school_search/create.json.jbuilder
- when school is closing in future do not show 'Closed on 'dd Month YYYY'
> [story/ECP-1319] - Update school search JS autocomplete

- db/seeds.rb
Add to local .env file
`SEED_ACADEMIC_YEAR=2021`
to seed ECP + TSLR data for the `AcademicYear` of 2021
> [story/ECP-1321] - Update seed data for ECP/TSLR in 2021

- CHANGELOG.md
- All policies
- Prevent non-selection of an address option on the home address page
- Add mobile verification with OTP to TSLR & M+P policies
- Decision deadline update
- Fix address output in csv payroll file for Cantium
> release-105

- CHANGELOG.md
- All policies
- Amend payment breakdown email
- ECP
- Amend hint text
> release-107

- spec/support/capybara.rb
- https://github.com/teamcapybara/capybara/issues/2511
> [task/ECP-1357] - Fix deprecation warning - Selenium

- app/controllers/admin/payroll_run_downloads_controller.rb
- spec/requests/admin_payroll_run_downloads_spec.rb
NB. This is to be REVERTED as soon as we can confirm if there is IP Whitelisting on Azure DEV
> wip DEV ONLY, will be REVERTED so not to go to TEST/PROD

- app/controllers/admin/payroll_run_downloads_controller.rb
- spec/requests/admin_payroll_run_downloads_spec.rb
Reverts DFE-Digital/claim-additional-payments-for-teaching#1806
Have proven that there is no IP whitelisting in at least DEV, so will revert.
> Revert "wip DEV ONLY, will be REVERTED so not to go to TEST/PROD"

- CHANGELOG.md
- Add DqT task automation notes in Admin task confirmation screens
- Align policies to transition to GOVUK Notify Mail Templates to allow business
users to modify wording
- TSLR + ECP
- Claim approved
- Update after three weeks
- Claim rejected
- ECP
- Reminder - application window open
- Reminder set up confirmation
> release-111

- db/test_seeders/base_importer.rb
- db/test_seeders/claims_importer.rb
- db/test_seeders/data_importer.rb
- db/test_seeders/eligibilities/early_career_payments_importer.rb
- lib/tasks/test_data_seeder.rake
- fixes breakages from ECP-1379 (fix forward)
> [bug/ECP-1385] - Fix broken seeding process and remove rake db:reset and associated tasks

- db/test_seeders/base_csv_import_validator.rb
- db/test_seeders/base_importer.rb
- db/test_seeders/data_importer.rb
- db/test_seeders/decisions_importer.rb
- db/test_seeders/eligibilities/early_career_payments/importer.rb
- db/test_seeders/record_builder.rb
- db/test_seeders/seeder.rb
- lib/tasks/test_data_seeder.rake
- this is to support volume testing by DfE in-house payroll
- they require 2k records. This supports any volume being generated.
- N.B for DEV/TEST only, clears down the environments existing data
> [story/ECP-1380] - Add ability to bulk load test data for Payroll Testing

- CHANGELOG.md
- Update the release process documentation
- Update cookie policy to include collection of IP addresses
- In DEV/TEST environments (NOT PROD) add data seeding/loading
capabilities
- For DfE Payroll moving in-house UAT Testing
- Add ability to generate Payroll Test data for ECP and/or TSLR
- For DqT Testing
- Add ability to upload from CSV (developer process)
data sent to the DqT for use in System/Integration Testing
for ECP & TSLR
> release-112

- CHANGELOG.md
- Admin
- Upload school workforce census data onto admin site
- Add ability to allocate claims to claims team members
> release-113

- CHANGELOG.md
- Admin
- Upload TPS data onto admin site
- Decisions stats dashboard showing incorrect data fix
> release-114

- .env.development
- .env.production
- .env.test
- .gitignore
- azure/terraform/modules/app_service/app_service.tf
- azure/terraform/modules/app_service/app_service_slot.tf
- azure/terraform/modules/app_service/data.tf
- azure/terraform/modules/container/container_group.tf
- azure/terraform/modules/container/data.tf
- lib/dqt/bearer.rb
- lib/dqt/client.rb
- lib/dqt/resource.rb
- spec/features/admin_claim_tasks_update_with_dqt_api_spec.rb
- spec/support/dqt_helpers.rb
Replaces the request to the DQT Auth server with an environment secret provided by TRA
> update DQT connection to use configured bearer token

- CHANGELOG.md
- Switch to TWD_TRA_DQT_API (V3 DqT API)
- used for identity checking
- used for qualifications checking
- Admin
- Allocate claims by policy
- Unallocate claims by policy
- Add ability to filter claims by team member
- Add automation for School Workforce Census checks - (TSLR + ECP only)
> release-115

- CHANGELOG.md
- app/models/automated_checks/claim_verifiers/census_subjects_taught.rb
- app/models/automated_checks/claim_verifiers/identity.rb
- app/models/automated_checks/claim_verifiers/qualifications.rb
- spec/models/automated_checks/claim_verifiers/census_subjects_taught_spec.rb
- spec/models/automated_checks/claim_verifiers/identity_spec.rb
- spec/models/automated_checks/claim_verifiers/qualifications_spec.rb
- so they can be easily identified by data source and automated task in the notes screen
> [story/ECP-1408] - Add labels to automated tasks

- CHANGELOG.md
- Admin
- Display stats for outcomes of School Workforce Census checks
> release-117

- Gemfile.lock
> Upgrade `sassc` to add Apple Mac M1 Silicon support

- app/views/early_career_payments/claims/_ineligibility_reason_ineligible_current_school.html.erb
> Added LUP to ineligible school text

- app/models/early_career_payments.rb
- app/models/levelling_up_premium_payments.rb
- app/models/maths_and_physics.rb
- app/models/policies.rb
- app/models/policy_configuration.rb
- app/models/student_loans.rb
- spec/features/admin_claim_allocation_and_deallocation_spec.rb
- spec/features/admin_claim_allocation_spec.rb
- spec/features/admin_claim_check_spec.rb
- spec/features/admin_search_spec.rb
- spec/features/admin_view_claim_spec.rb
- spec/models/policy_configuration_spec.rb
- spec/requests/claims_qts_year_spec.rb
- spec/requests/claims_spec.rb
- spec/support/request_helpers.rb
Refactor Policies to include LUP
> CAPT-205 Add LUP policy

- app/models/early_career_payments/slug_sequence.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-351
Added unit test for this and made minor refactoring
> Test coverage for supply teacher questions

- app/views/early_career_payments/claims/eligible_degree_subject.html.erb
> Add hint text to eligible degree subject page

- config/locales/en.yml
- spec/features/admin_configure_services_spec.rb
- spec/features/early_career_payments_claim_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-247
Renames the service in the header.
> Change service name

- README.md
- app/assets/javascripts/components/school_search.js.erb
- app/controllers/base_public_controller.rb
- app/controllers/reminders_controller.rb
- app/helpers/application_helper.rb
- app/models/policy_configuration.rb
- config/routes.rb
- lib/journey_subject_eligibility_checker.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/models/early_career_payments_spec.rb
- spec/models/levelling_up_premium_payments_spec.rb
- spec/models/policy_configuration_spec.rb
- spec/requests/claims_spec.rb
- spec/routes/routes_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-395
This changes the URL from early-career-payments to additional-payments.
Note: This PR doesn't handle the redirect part of the ticket.
> Change url path from early-career-payments to additional-payments

- app/models/levelling_up_premium_payments/dqt_record.rb
- lib/dqt/objects/teacher.rb
- spec/lib/dqt/objects/teacher_spec.rb
- spec/models/automated_checks/claim_verifiers/qualifications_spec.rb
> [CAPT-211] Add degree codes from DQT response

- lib/journey_subject_eligibility_checker.rb
- spec/lib/journey_subject_eligibility_checker_spec.rb
> Fix nil subject_symbols for claim years before 2022

- azure-pipelines.yml
- templates/build.yml
- templates/release.yml
Build and release templates created so pipeline can be used for multiple environments
> Template Deployment Pipeline

- app/models/claim.rb
- app/views/admin/amendments/new.html.erb
- spec/features/admin_amend_claim_spec.rb
- spec/requests/admin_amendments_spec.rb
> [CAPT-146] Ability to amend the national insurance number in a claim

- app/models/levelling_up_premium_payments/eligibility_admin_answers_presenter.rb
- config/locales/en.yml
- spec/models/levelling_up_premium_payments/eligibility_admin_answers_presenter_spec.rb
> [CAPT-245] Add the answer to the degree question to the full claim page

- app/models/automated_checks/claim_verifiers/census_subjects_taught.rb
- app/models/school_workforce_census.rb
- spec/factories/school_workforce_censuses.rb
- spec/models/automated_checks/claim_verifiers/census_subjects_taught_spec.rb
> [CAPT-329] Include computing in school census checks

- app/views/claims/personal_details.html.erb
- app/views/reminders/personal_details.html.erb
> Fix autocomplete values

- spec/features/school_search_spec.rb
> Trying to fix CI failure

- app/views/static_pages/landing_page.html.erb
> [CAPT-492] Amend claim process length

- spec/features/school_search_spec.rb
Should have been done in #2030
> Trying to fix CI failure v2

- app/views/early_career_payments/claims/eligible_itt_subject.html.erb
- config/locales/en.yml
- spec/helpers/early_career_payments_helper_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-517
Screenshots:
> Change text to explain why some subjects are missing

- app/views/early_career_payments/claims/_eligibility_confirmed_multiple.html.erb
- app/views/early_career_payments/claims/_eligibility_confirmed_single.html.erb
- app/views/early_career_payments/claims/_eligibility_guidance_early_career_payments.html.erb
- app/views/early_career_payments/claims/_eligibility_guidance_levelling_up_premium_payments.html.erb
- app/views/early_career_payments/claims/eligibility_confirmed.html.erb
- app/views/static_pages/landing_page.html.erb
https://dfedigital.atlassian.net/browse/CAPT-440
Eligible for both ECP and LUP:
Expanded drop down:
No selection:
ECP only:
LUP only:
> Update eligibility results page text

- app/views/early_career_payments/claims/eligible_itt_subject.html.erb
- config/locales/en.yml
- spec/helpers/early_career_payments_helper_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-532
> Change text and hide hint text for trainee teachers

- app/helpers/claims_helper.rb
- app/helpers/early_career_payments_helper.rb
- app/models/concerns/early_career_payments_helpable.rb
- app/models/current_claim.rb
- app/models/early_career_payments/eligibility.rb
- app/models/early_career_payments/eligibility_answers_presenter.rb
- app/models/levelling_up_premium_payments/eligibility.rb
- spec/features/changing_answers_spec.rb
- spec/features/combined_teacher_claim_journey_spec.rb
- spec/features/early_career_payments_claim_lupp_ineligible_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/features/ineligible_early_career_payments_in_2022_and_future_years_spec.rb
- spec/features/itt_subject_selection_spec.rb
- spec/features/levelling_up_premium_payments_spec.rb
- spec/helpers/claims_helper_spec.rb
- spec/helpers/early_career_payments_helper_spec.rb
- spec/models/early_career_payments/eligibility_answers_presenter_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
> [CAPT-518] Add degree question to check your answers page

- azure-pipelines.yml
> Reviewapps fix

- azure-pipelines.yml
- templates/release.yml
> Reviewapp fix

- app/helpers/claims/itt_subject_helper.rb
- app/views/early_career_payments/claims/teaching_subject_now.html.erb
- spec/helpers/claims/itt_subject_helper_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-522
Review app: https://s118d02-app-pr-2079-as.azurewebsites.net/additional-payments/claim
> Change hint text

- app/models/reminder.rb
- app/views/claims/_one_time_password.html.erb
- app/views/early_career_payments/claims/future_eligibility.html.erb
- app/views/reminders/_one_time_password.html.erb
- app/views/reminders/personal_details.html.erb
- config/locales/en.yml
- lib/one_time_password/validator.rb
- spec/features/changing_answers_spec.rb
- spec/features/claim_with_mobile_sms_otp_spec.rb
- spec/features/combined_teacher_claim_journey_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/levelling_up_premium_payments_spec.rb
- spec/features/maths_and_physics_claim_spec.rb
- spec/features/one_time_password_spec.rb
- spec/features/reminders_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/features/trainee_teacher_subjourney_for_lup_schools_spec.rb
- spec/features/validating_user_contact_details_spec.rb
> CAPT-506 Trainee reminder updates

- azure-pipelines.yml
- templates/release.yml
Added Test and Production Environments to deployment pipeline
> Reviewapps environments

- app/views/claims/teacher_reference_number.html.erb
https://dfedigital.atlassian.net/browse/CAPT-489
> Text changes for TRN page

- app/helpers/early_career_payments_helper.rb
- app/views/early_career_payments/claims/itt_year.html.erb
- spec/features/early_career_payments_claim_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-496
> Changes to ITT page

- azure-pipelines.yml
- azure/terraform/main.tf
- azure/terraform/modules/app_service/app_service.tf
- azure/terraform/modules/app_service/app_service_slot.tf
- azure/terraform/modules/app_service/variable.tf
- azure/terraform/variable.tf
- templates/release.yml
> Capt 615 review app amendments

- Makefile
- azure/terraform/modules/app_service/app_service.tf
- azure/terraform/modules/app_service/app_service_slot.tf
- azure/terraform/modules/app_service/data.tf
- azure/terraform/modules/app_service/variable.tf
- azure/terraform/provider.tf
Update azurerm provider to clear some tech debt and hope it will solve some small ramdom errors we've experienced
Successful run: https://dev.azure.com/dfe-ssp/S118-Teacher-Payments-Service/_build/results?buildId=286267&view=results
Review app: https://s118d02-app-pr-2095-as.azurewebsites.net/additional-payments/landing-page
As the resource is replaced, it will create a small downtime the first time it is applied to an environment
> [CAPT-604] Update azurerm terraform provider

- azure-pipelines.yml
> Remove development stage

- app/controllers/claims_controller.rb
- app/views/claims/_school_search.html.erb
- app/views/reminders/set.html.erb
- spec/features/early_career_payments_eligible_now_reminder_set_spec.rb
- spec/requests/claims_spec.rb
> Capt 512 602 620 621

- app/models/automated_checks/claim_verifiers/employment.rb
- app/models/teachers_pensions_service.rb
- spec/factories/teachers_pensions_service.rb
- spec/models/automated_checks/claim_verifiers/employment_spec.rb
- spec/requests/admin_tps_data_upload_spec.rb
> [CAPT-19] Add employment checks for TSLR claims

- Gemfile
- Gemfile.lock
- app/controllers/admin/claims_controller.rb
- app/helpers/admin/claims_helper.rb
- app/views/admin/claims/_pagination.html.erb
- app/views/admin/claims/index.html.erb
- config/initializers/pagy.rb
- package.json
- yarn.lock
Note: https://github.com/alphagov/govuk-frontend got updated so we can use the pagination feature.
> [CAPT-590] Add pagination to admin

- app/controllers/admin/tps_data_uploads_controller.rb
> [CAPT-693]  'NO DATA' claims get employment checked multiple times

- app/jobs/mail_delivery_job.rb
- config/environments/development.rb
- config/environments/production.rb
https://dfedigital.atlassian.net/browse/CAPT-703
This sets the priority of the mail delivery jobs.
> Set mail delivery job priority

- spec/features/admin_claims_pagination_spec.rb
> [CAPT-590] Add feature spec for admin pagination

- app/models/early_career_payments/eligibility.rb
> [CAPT-671] Fix typo in error message

- spec/requests/admin_tps_data_upload_spec.rb
> [CAPT-693] Add specs for NO MATCH TPS upload

- Makefile
- azure-pipelines.yml
- azure/delete_review_app.yml
- azure/terraform/main.tf
- azure/terraform/variable.tf
- templates/release.yml
Delete review apps manually as the destroy pipeline was failing
- Fix make terraform commands (missing variable)
- Refactor to remove extra variables
- Solve race condition when deleting a review app
> [CAPT-709] Fix make terraform commands

- app/models/teachers_pensions_service.rb
- app/models/teachers_pensions_service_importer.rb
- spec/models/teachers_pensions_service_importer_spec.rb
> [CAPT-714] Skip duplicate rows instead of raising error for TCP upload

- app/models/claim/data_report_request.rb
- spec/features/admin_data_report_request_spec.rb
- spec/models/claim/data_report_request_spec.rb
> [CAPT-704] Add NINO to the DQT download

- .github/workflows/ga_publish_ra_link.yml
Add Githun Action to automatically post the link to the review app when a pull request when a PR is opened.
> CAPT-690 Add Review App Link to Pull Request

- config/analytics_pii.yml
- config/initializers/semantic_logger.rb
https://dfedigital.atlassian.net/browse/CAPT-593
Configuration changes to support analytics streaming to BigQuery.
> Configuration changes for analytics

- app/models/payment_confirmation.rb
- app/views/payment_mailer/confirmation_for_multiple_claims.text.erb
- app/views/payment_mailer/confirmation_for_single_claim.text.erb
- config/initializers/date_formats.rb
- config/locales/en.yml
- spec/mailers/payment_mailer_spec.rb
- spec/mailers/previews/payment_mailer_preview.rb
- spec/models/payment_confirmation_spec.rb
> [CAPT-614] Payment breakdown email - Content changes & payment dates

- app/models/levelling_up_premium_payments.rb
- app/models/payment_confirmation.rb
- app/views/payment_mailer/confirmation_for_multiple_claims.text.erb
- app/views/payment_mailer/confirmation_for_single_claim.text.erb
- spec/models/levelling_up_premium_payments_spec.rb
- spec/models/payment_confirmation_spec.rb
* Fix payment date
* Fix blockquote formatting
* Fix reply email for LUP claims
> [CAPT-614] Payment breakdown email bugfix

- app/jobs/qualifications_no_match_check_job.rb
- spec/jobs/qualifications_no_match_check_job_spec.rb
> [CAPT-725] Add job to re-run the No Match qualifications checks

- app/models/claim/claims_preventing_payment_finder.rb
- spec/models/claim/claims_preventing_payment_finder_spec.rb
> [CAPT-728] Fix blank values preventing approval

- app/jobs/qualifications_no_match_check_job.rb
- spec/jobs/qualifications_no_match_check_job_spec.rb
> Re-run qualifications check for current year claims

- app/models/payment.rb
- spec/models/payment_spec.rb
> [CAPT-728] Fix blank values from blocking payroll runs

- app/jobs/qualifications_no_match_check_job.rb
> Add another scope to filter claims for QualificationsNoMatchCheckJob

- .github/workflows/ga_publish_ra_link.yml
Revise Permissions for posting Review APP Url
> Amend permissions for posting comment on PR

- azure/delete_review_app.yml
> Delete Terraform State File on PR Close

- app/views/claims/masters_doctoral_loan.html.erb
- app/views/claims/student_loan.html.erb
> [CAPT-679] UI change: Are you currently repaying a student loan? 

- config/locales/en.yml
> [CAPT-584] Amend the content of the question

- public/404.html
- public/422.html
- public/500.html
> [CAPT-519] Update header for error pages

- app/controllers/admin/policy_configurations_controller.rb
- app/controllers/reminders_controller.rb
- app/models/current_claim.rb
- app/models/early_career_payments/dqt_record.rb
- app/models/early_career_payments/eligibility.rb
- app/models/levelling_up_premium_payments/eligibility.rb
- app/models/policy_configuration.rb
- app/views/admin/policy_configurations/_ecp_reminder_warning.html.erb
- lib/one_time_password/validator.rb
- spec/factories/early_career_payments/eligibilities.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/models/early_career_payments/eligibility_spec.rb
- spec/models/policy_configuration_spec.rb
- spec/support/eligibility_status_shared_examples.rb
Investigated where necessary and removed redundant code and comments.
> Address TODO comments

- app/views/claims/information_provided.html.erb
> [CAPT-663] Content change: Amend Tax paragraph on 'How we will use the information you provide' page

- app/jobs/qualifications_no_match_check_job.rb
> Fix debug slice number in QualificationsNoMatchCheckJob

- app/jobs/qualifications_no_match_check_job.rb
- lib/dqt/matchers/general.rb
- spec/jobs/qualifications_no_match_check_job_spec.rb
> [CAPT-761] Add QTS Award to all qualifications and tweak job

- app/views/claims/personal_details.html.erb
- app/views/early_career_payments/claims/poor_performance.html.erb
- app/views/reminders/personal_details.html.erb
https://dfedigital.atlassian.net/browse/CAPT-652
https://dfedigital.atlassian.net/browse/CAPT-654
https://dfedigital.atlassian.net/browse/CAPT-658
Fixes error highlighting of form fields on various pages.
> Fix error highlighting

- config/initializers/pagy.rb
> Fix page overflow in admin

- app/models/early_career_payments/eligibility.rb
- app/models/levelling_up_premium_payments/eligibility.rb
- app/models/levelling_up_premium_payments/school_eligibility.rb
- app/views/early_career_payments/claims/itt_year.html.erb
- spec/support/eligible_later_shared_examples.rb
> [CAPT-751] Fix remaining hard-coded academic year

- app/controllers/admin/decisions_controller.rb
- app/controllers/admin/payroll_gender_tasks_controller.rb
- app/controllers/admin/tasks_controller.rb
- app/controllers/concerns/admin_task_pagination.rb
- app/views/admin/_task_pagination.html.erb
- app/views/admin/decisions/new.html.erb
- app/views/admin/tasks/_form.html.erb
- app/views/admin/tasks/census_subjects_taught.html.erb
- app/views/admin/tasks/employment.html.erb
- app/views/admin/tasks/identity_confirmation.html.erb
- app/views/admin/tasks/matching_details.html.erb
- app/views/admin/tasks/payroll_gender.html.erb
- app/views/admin/tasks/qualifications.html.erb
- app/views/admin/tasks/student_loan_amount.html.erb
- spec/features/admin_checks_maths_and_physics_claim_spec.rb
- spec/features/admin_checks_student_loan_claim_spec.rb
- spec/support/admin_checks_feature_shared_examples.rb
https://dfedigital.atlassian.net/browse/CAPT-743
Adds headers and next/previous task links to the admin task pages.
> Add next/previous task links and headers to admin tasks pages

- config/environments/test.rb
Fixes Spring not loading locally when running tests since the upgrade to Rails 6.1.
> Fix Spring not loading locally in test mode

- app/controllers/admin/decisions_controller.rb
- app/helpers/admin/claims_helper.rb
- app/models/decision.rb
- app/views/admin/decisions/_decision_form.html.erb
- config/analytics.yml
- config/locales/en.yml
- db/migrate/20221205175252_add_rejected_reasons_to_decisions.rb
- db/schema.rb
- spec/factories/claims.rb
- spec/factories/decisions.rb
- spec/features/admin_reject_claim_spec.rb
- spec/models/claim_spec.rb
- spec/requests/admin_decisions_spec.rb
- spec/support/admin_check_claim_feature_shared_examples.rb
- Notes now mandatory with "Other" reason
- At least one reason must be selected
- Display the Reason on the view claim page
> CAPT-17 Add rejected reasons to Reject Decision

- app/controllers/concerns/part_of_claim_journey.rb
- app/controllers/submissions_controller.rb
Addresses https://app.rollbar.com/a/dfe-digital/fix/item/dfe-claims/566
> Rails 7 redirect to gov site needs allow_other_host flag

- app/models/early_career_payments/eligibility.rb
- app/models/levelling_up_premium_payments/eligibility.rb
> CAPT-940 make eligibility itt year enum static

- app/controllers/admin/allocations_controller.rb
- app/views/admin/allocations/bulk_deallocate.html.erb
- config/locales/en.yml
- spec/features/admin_claim_allocation_spec.rb
- spec/requests/admin_allocations_spec.rb
Refer to the ticket and commit messages
> CAPT-971 - Add a confirmation button when users try to unallocate claims

- app/views/admin/payroll_runs/index.html.erb
- config/locales/en.yml
- spec/features/admin_payroll_runs_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-1053
> CAPT-1053 Amend payroll links for accessibility

- app/controllers/admin/static_pages_controller.rb
- app/views/admin/static_pages/accessibility_statement.html.erb
- app/views/layouts/admin.html.erb
- config/routes.rb
- spec/requests/admin_static_pages_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-1070
> CAPT-1070 Add accessibility statement on the Admin site

- .env.development
- .env.production
- .env.test
- app/controllers/claims_controller.rb
- app/controllers/omniauth_callbacks_controller.rb
- app/views/claims/_school_search.html.erb
- app/views/claims/current_school.html.erb
- azure/terraform/modules/app_service/data.tf
- azure/terraform/modules/app_service/variable.tf
- azure/terraform/modules/container/container_group.tf
- azure/terraform/modules/container/data.tf
- config/initializers/omniauth.rb
- config/routes.rb
- spec/features/teacher_identity_sign_in_spec.rb
- spec/requests/omniauth_callbacks_controller_spec.rb
[CAPT-1125](https://dfedigital.atlassian.net/browse/CAPT-1125)
[CAPT-1125]: https://dfedigital.atlassian.net/browse/CAPT-1125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CAPT-1125 Create client integration with Teacher Identity service

- spec/models/claim/personal_data_scrubber_spec.rb
These extra test scenarios are being added as part of the spike at https://dfedigital.atlassian.net/browse/CAPT-1055
At least one of them covers claims that are currently held in prod until the next window. Technically, these are claims without a decision, so the scrubber excludes them, and that test scenario exists already, but thought I'd make it more explicit.
> CAPT-1055 Add test scenarios to personal data scrubber spec

- app/views/early_career_payments/claims/_ineligibility_generic.html.erb
[CAPT-1121](https://dfedigital.atlassian.net.mcas.ms/browse/CAPT-1121)
[CAPT-1121]: https://dfedigital.atlassian.net/browse/CAPT-1121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CAPT-1121 Amend exit screen for users who select 'none of the above' for their ITT year - LUP schools

- app/controllers/admin/tasks_controller.rb
- app/helpers/admin/claims_helper.rb
- app/models/automated_checks/claim_verifier.rb
- app/models/automated_checks/claim_verifiers/census_subjects_taught.rb
- app/models/automated_checks/claim_verifiers/employment.rb
- app/models/automated_checks/claim_verifiers/identity.rb
- app/models/automated_checks/claim_verifiers/induction.rb
- app/models/automated_checks/claim_verifiers/qualifications.rb
- app/models/claim_checking_tasks.rb
- app/models/early_career_payments/admin_tasks_presenter.rb
- app/models/note.rb
- app/models/task.rb
- app/views/admin/tasks/induction_confirmation.erb
- config/analytics.yml
- config/locales/en.yml
- db/data/20230906111133_backfill_notes_label.rb
- db/migrate/20230906104918_add_label_to_notes.rb
- db/schema.rb
- spec/factories/notes.rb
- spec/features/admin_claim_tasks_update_with_dqt_api_spec.rb
- spec/jobs/qualifications_no_match_check_job_spec.rb
- spec/models/automated_checks/claim_verifiers/census_subjects_taught_spec.rb
- spec/models/automated_checks/claim_verifiers/employment_spec.rb
- spec/models/automated_checks/claim_verifiers/identity_spec.rb
- spec/models/automated_checks/claim_verifiers/induction_spec.rb
- spec/models/automated_checks/claim_verifiers/qualifications_spec.rb
- spec/models/claim_checking_tasks_spec.rb
- spec/models/note_spec.rb
- spec/support/admin_checks_feature_shared_examples.rb
- spec/support/admin_view_claim_feature_shared_examples.rb
https://dfedigital.atlassian.net/browse/CAPT-1093
~~Requires: #2423~~ ✅
> CAPT-1093 Add induction task to Admin site - ECP only

- app/controllers/claims_controller.rb
- app/controllers/concerns/claim_session_timeout.rb
- app/models/claim.rb
- app/models/dfe_identity/claim_user_details_check.rb
- app/models/dfe_identity/claim_user_details_reset.rb
- app/models/early_career_payments/slug_sequence.rb
- app/models/page_sequence.rb
- spec/factories/claims.rb
- spec/features/combined_teacher_claim_journey_spec.rb
- spec/features/early_career_payments_claim_lupp_ineligible_spec.rb
- spec/features/early_career_payments_claim_sequence_slug_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/ineligibility_reason_spec.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/features/itt_subject_selection_spec.rb
- spec/features/levelling_up_premium_payments_spec.rb
- spec/models/early_career_payments/slug_sequence_spec.rb
- spec/support/eligible_later_shared_examples.rb
- spec/support/feature_helpers.rb
- Pre-work before adding additional pages
> Fixes the idempotency of either tid login or skip tid

- app/models/school.rb
https://dfedigital.atlassian.net/browse/CAPT-1381
Fixes the school data importer to allow new types introduced.
> Add new Edubase school and group types

- app/models/dfe_identity/user_info.rb
- spec/models/dfe_identity/user_info_spec.rb
This removes the requirement for a NI number to be provided.
> Do not require NI number to be present or validated

- app/jobs/auto_approve_claims_job.rb
- spec/jobs/auto_approve_claims_job_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-1399
Now that we've run the first big batch of auto-approvals, we can regularly run this job at least once every weekday.
> CAPT-1399 Run auto-approval job every weekday at 8am

- app/controllers/admin/student_loans_data_uploads_controller.rb
- app/jobs/file_importer_job.rb
- app/jobs/import_census_job.rb
- app/jobs/import_student_loans_data_job.rb
- app/models/school_workforce_census_data_importer.rb
- app/models/student_loans_data.rb
- app/models/student_loans_data_importer.rb
- app/models/teachers_pensions_service_importer.rb
- app/views/admin/claims/index.html.erb
- app/views/admin/student_loans_data_uploads/new.html.erb
- config/analytics_blocklist.yml
- config/application.rb
- config/brakeman.ignore
- config/routes.rb
- db/migrate/20231121114436_create_student_loans_data.rb
- db/schema.rb
- lib/csv_importer.rb
- lib/csv_importer/base.rb
- lib/csv_importer/config.rb
- lib/csv_importer/errors.rb
- spec/jobs/file_importer_job_spec.rb
- spec/jobs/import_student_loans_data_job_spec.rb
- spec/lib/csv_importer/base_spec.rb
- spec/lib/csv_importer/config_spec.rb
- spec/requests/admin_student_loans_data_upload_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-1273
This PR creates reusable components from existing code to import CSV data with a certain degree of customisation, i.e. transformation, validation, target table, purge/append mode, etc.
Main changes:
1. [Extract CSV data importer functionality to re-usable component](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2512/commits/9a92d2d80c5b4184cac33585fe536f3aa5eea355)
2. [Create AR model to hold and query student loans data imports](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2512/commits/8e4bfc04add664ffab394463a14b9d981d483e10)
3. [Extract existing async upload import functionality to re-usable job](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2512/comm …
> CAPT-1273 Upload new SLC information to admin

- app/views/claims/sign_in_or_continue.html.erb
See https://github.com/cookpad/omniauth-rails_csrf_protection#usage
> Fix intermittent csrf_detected errors when signing in

- app/models/claim.rb
- spec/helpers/admin/claims_helper_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-1287
> CAPT-1287 Check claim SLA's to 12 weeks

- app/controllers/claims_controller.rb
- app/forms/still_teaching_form.rb
- app/models/claim.rb
- app/models/early_career_payments/slug_sequence.rb
- app/models/student_loans/eligibility.rb
- app/models/student_loans/slug_sequence.rb
- app/views/student_loans/claims/_still_teaching_with_claim_school.html.erb
- app/views/student_loans/claims/_still_teaching_with_tps_school.html.erb
- app/views/student_loans/claims/still_teaching.html.erb
- spec/features/tslr_claim_journey_with_teacher_id_still_teaching_spec.rb
- spec/forms/still_teaching_form_spec.rb
- spec/models/student_loans/eligibility_spec.rb
NOTE FOR PR REVIEW: This is based of capt-1357 which is still in Business Review, when reviewing this PR, please look at the latest commit which is specific for this PR.
> Capt 1359 current school playback

- app/models/student_loans.rb
- app/models/student_loans/dqt_record.rb
- spec/models/student_loans/dqt_record_spec.rb
- spec/models/student_loans_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-1420
> Implement policy end year for Student Loans claims

- docs/docker-hub-credentials.md
> Add documentation about Docker hub

- app/controllers/concerns/part_of_claim_journey.rb
- app/controllers/reminders_controller.rb
Optimize user journey queries
[CAPT-1433](https://dfedigital.atlassian.net.mcas.ms/browse/CAPT-1422)
[CAPT-1422]: https://dfedigital.atlassian.net/browse/CAPT-1422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CAPT-1433]: https://dfedigital.atlassian.net/browse/CAPT-1433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CAPT 1433] - Refactor/user journey db performance

- Gemfile
- Gemfile.lock
- README.md
- lefthook.yml
Setup and configure lefthook to allow precommit checks with prettier and standard 
[CAPT-1455](https://dfedigital.atlassian.net/browse/CAPT-1455)
[CAPT-1455]: https://dfedigital.atlassian.net/browse/CAPT-1455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Install lefthook

- app/models/automated_checks/claim_verifiers/student_loan_amount.rb
- spec/models/automated_checks/claim_verifiers/student_loan_amount_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-1418
> CAPT-1418 TSLR Student Loans: When SLC value is £0, mark task as NO MATCH

- app/models/base_policy.rb
- app/models/early_career_payments.rb
- app/models/levelling_up_premium_payments.rb
- app/models/maths_and_physics.rb
- app/models/student_loans.rb
- spec/models/base_policy_spec.rb
- spec/models/early_career_payments_spec.rb
- spec/models/levelling_up_premium_payments_spec.rb
- spec/models/maths_and_physics_spec.rb
- spec/models/student_loans_spec.rb
[CAPT-1465]
Refactor:
* `EarlyCareerPayments`
* `LevellingUpPremiumPayments`
* `MathsAndPhysics`
* `StudentLoans`
[CAPT-1465]: https://dfedigital.atlassian.net/browse/CAPT-1465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Move common methods to BasePolicy

- app/models/early_career_payments/induction_data.rb
- spec/models/early_career_payments/induction_data_spec.rb
[CAPT-1347](https://dfedigital.atlassian.net.mcas.ms/browse/CAPT-1347)
[CAPT-1347]: https://dfedigital.atlassian.net/browse/CAPT-1347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CAPT-1347 Induction task should be marked as 'pass' where induction status is exempt

- db/seeds.rb
[CAPT-1507](https://dfedigital.atlassian.net.mcas.ms/browse/CAPT-1507?McasTsid=20596&McasCtx=4)
Use Policies::EarlyCareerPayments
[CAPT-1507]: https://dfedigital.atlassian.net/browse/CAPT-1507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CAPT-1507] - Refactor db/seeds.rb

- db/migrate/20240315091658_change_claims_eligibility_type_to_policies_levelling_up_premium_payments.rb
- db/schema.rb
Convert `Claim#eligibility_type` from `LevellingUpPremiumPayments::Eligibility` to `Policies::LevellingUpPremiumPayments::Eligibility`
> Feature/capt 1518 namespace levelling up premium payments to policies - part 2

- app/views/additional_payments/claims/_ineligibility_teacher_with_ineligible_itt_year.html.erb
- lib/ineligibility_reason_checker.rb
- spec/features/ineligibility_reason_spec.rb
- spec/lib/ineligibility_reason_checker_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-1292. Follows #2650
> CAPT-1292 Add exit screen for LUP users who select "None of the above" ITT year

- azure/delete_review_app.yml
- templates/release.yml
https://dfedigital.atlassian.net/browse/CAPT-1606
Fixes issues with the pipelines complaining about missing tasks.
> Update Azure Terraform task names

- app/controllers/claims_form_callbacks.rb
- app/forms/form.rb
- app/forms/journeys/additional_payments_for_teaching/eligible_itt_subject_form.rb
- app/forms/personal_details_form.rb
- app/forms/select_email_form.rb
- app/forms/select_mobile_form.rb
- app/forms/sign_in_or_continue_form.rb
- app/models/claim_journey_session_shim.rb
- app/models/concerns/journeys/sessions/teacher_id.rb
- app/models/journeys/additional_payments_for_teaching/slug_sequence.rb
- app/models/journeys/base.rb
- app/models/journeys/base_answers_presenter.rb
- app/models/journeys/page_sequence.rb
- app/models/journeys/session_answers.rb
- app/models/journeys/teacher_student_loan_reimbursement/slug_sequence.rb
- spec/features/changing_answers_spec.rb
- spec/features/combined_teacher_claim_journey_with_teacher_id_spec.rb
- spec/features/dfe_identity_sign_in_for_student_loans_journey_spec.rb
- spec/features/levelling_up_premium_payments_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/forms/personal_details_form_spec.rb
- spec/forms/select_email_form_spec.rb
- spec/forms/select_mobile_form_spec.rb
- spec/models/journeys/additional_payments_for_teaching/slug_sequence_spec.rb
- spec/models/journeys/page_sequence_spec.rb
- spec/requests/claims_spec.rb
- spec/requests/submissions_spec.rb
- spec/support/journey_answers_presenter_shared_examples.rb
Migrates the personal details form over to write to the journey session, not too much to say about this one!
> Capt 1659/update personal details to write to session

- app/models/journeys/additional_payments_for_teaching/session_answers.rb
Looks like these got added twice!
> Remove duplicate attributes

- app/forms/bank_details_form.rb
- app/forms/bank_or_building_society_form.rb
- app/models/claim_journey_session_shim.rb
- app/models/journeys/additional_payments_for_teaching/slug_sequence.rb
- app/models/journeys/base_answers_presenter.rb
- app/models/journeys/session_answers.rb
- app/models/journeys/teacher_student_loan_reimbursement/slug_sequence.rb
- app/views/claims/building_society_account.html.erb
- app/views/claims/personal_bank_account.html.erb
- spec/factories/journeys/additional_payments_for_teaching/session_answers.rb
- spec/factories/journeys/teacher_student_loan_reimbursement/session_answers.rb
- spec/features/admin_claim_tasks_update_with_dqt_api_spec.rb
- spec/features/changing_answers_spec.rb
- spec/features/claim_journey_does_not_get_cached_spec.rb
- spec/features/combined_teacher_claim_journey_spec.rb
- spec/features/early_career_payments_eligible_now_reminder_set_spec.rb
- spec/features/hmrc_bank_validation_spec.rb
- spec/features/levelling_up_premium_payments_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/forms/bank_details_form_spec.rb
- spec/forms/bank_or_building_society_form_spec.rb
- spec/models/journeys/additional_payments_for_teaching/slug_sequence_spec.rb
- spec/models/journeys/page_sequence_spec.rb
- spec/models/journeys/teacher_student_loan_reimbursement/slug_sequence_spec.rb
- spec/requests/submissions_spec.rb
- spec/support/eligible_later_shared_examples.rb
- spec/support/journey_answers_presenter_shared_examples.rb
Another relatively straight forward form conversion pr.
This pr is split into two commits, though it's probably fine to review both
commits together.
Bulk of the changes are just spec updates.
> CAPT 1671/bank or building society

- app/controllers/claims_form_callbacks.rb
- app/forms/address_form.rb
- app/forms/postcode_search_form.rb
- app/forms/select_home_address_form.rb
- app/models/claim_journey_session_shim.rb
- app/models/journeys/base_answers_presenter.rb
- app/models/journeys/page_sequence.rb
- app/models/journeys/session_answers.rb
- spec/features/auto_populating_home_address_from_postcode_search_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/forms/address_form_spec.rb
- spec/forms/postcode_search_form_spec.rb
- spec/forms/select_home_address_form_spec.rb
- spec/models/journeys/page_sequence_spec.rb
- spec/support/journey_answers_presenter_shared_examples.rb
Update address forms to write to session
Updates the address related forms to write to the session, not much else
to say!
> CAPT 1663/address form

- app/forms/gender_form.rb
- app/models/claim_journey_session_shim.rb
- app/models/journeys/base_answers_presenter.rb
- app/views/claims/gender.html.erb
- spec/factories/journeys/additional_payments_for_teaching/session_answers.rb
- spec/factories/journeys/teacher_student_loan_reimbursement/session_answers.rb
- spec/features/student_loans_claim_spec.rb
- spec/forms/gender_form_spec.rb
- spec/support/journey_answers_presenter_shared_examples.rb
Migrate gender form to write to session
Another straight forward one
> CAPT 1674/update gender form

- app/forms/sign_in_or_continue_form.rb
- app/forms/teacher_reference_number_form.rb
- app/models/claim_journey_session_shim.rb
- app/models/journeys/base_answers_presenter.rb
- spec/factories/journeys/additional_payments_for_teaching/session_answers.rb
- spec/factories/journeys/teacher_student_loan_reimbursement/session_answers.rb
- spec/features/student_loans_claim_spec.rb
- spec/forms/teacher_reference_number_form_spec.rb
- spec/requests/submissions_spec.rb
Updates trn form to write to session
Another commit in the migrating the forms to write to the session saga.
> CAPT 1675/trn form

- app/forms/journeys/additional_payments_for_teaching/eligible_degree_subject_form.rb
- app/forms/journeys/additional_payments_for_teaching/qualification_details_form.rb
- app/models/journeys/additional_payments_for_teaching/answers_presenter.rb
- app/models/journeys/additional_payments_for_teaching/claim_journey_session_shim.rb
- app/models/journeys/page_sequence.rb
- spec/features/ineligible_levelling_up_premium_payments_spec.rb
- spec/forms/journeys/additional_payments_for_teaching/eligible_degree_subject_form_spec.rb
- spec/forms/journeys/additional_payments_for_teaching/qualification_details_form_spec.rb
- spec/lib/ineligibility_reason_checker_spec.rb
- spec/models/journeys/additional_payments_for_teaching/answers_presenter_spec.rb
Migrate eligibile degree subject to answers
Migrates the eligible degree subject for to write to the session
answers.
> CAPT 1652/eligible degree subject

- app/forms/journeys/additional_payments_for_teaching/qualification_form.rb
- app/forms/journeys/additional_payments_for_teaching/teaching_subject_now_form.rb
- app/models/journeys/additional_payments_for_teaching/claim_journey_session_shim.rb
- spec/factories/journeys/additional_payments_for_teaching/session_answers.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/features/ineligible_early_career_payments_claims_spec.rb
- spec/forms/journeys/additional_payments_for_teaching/qualification_form_spec.rb
- spec/forms/journeys/additional_payments_for_teaching/teaching_subject_now_form_spec.rb
Update teaching subject now to write to answers
Updates the teaching subject now form to write to the session answers
> CAPT 1653/teaching subject now

- app/models/payroll/payment_csv_row.rb
- spec/models/payroll/payment_csv_row_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-1714
> CAPT-1714: Use first and last days of the month in payroll file

- app/forms/journeys/additional_payments_for_teaching/correct_school_form.rb
- app/models/journeys/additional_payments_for_teaching/claim_journey_session_shim.rb
- app/models/journeys/additional_payments_for_teaching/session_answers.rb
- spec/features/correct_school_spec.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/forms/journeys/additional_payments_for_teaching/correct_school_form_spec.rb
Remove claim references from correct_school_form
Updates the correct school form to remove referecnes to claim /
eligibility
> CAPT 1717/correct school eligibility fixes

- README.md
- docs/connecting-to-azure.md
Add docs for accessing review apps.
[Check out the new markdown doc](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/1d77c21a646da61b107f7d535205152c55f88e36/docs/connecting-to-azure.md).
> CAPT-1707 Add documentation for review apps on AKS

- app/forms/journeys/additional_payments_for_teaching/supply_teacher_form.rb
- app/models/journeys/additional_payments_for_teaching/claim_journey_session_shim.rb
- app/models/journeys/additional_payments_for_teaching/slug_sequence.rb
- spec/features/early_career_payments_claim_spec.rb
- spec/forms/supply_teacher_form_spec.rb
- spec/models/journeys/additional_payments_for_teaching/slug_sequence_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1644
- Update supply teacher form to use journey session answers rather than eligibility
> [CAPT-1644] Port Supply teacher form

- notes
- spec/lib/hmrc/client_spec.rb
- Fix deprecation warning in tests
- Also removed someones personal note that don't belong
> Fix deprecation warning

- app/forms/provide_mobile_number_form.rb
- app/views/claims/provide_mobile_number.html.erb
- Refactor forms to use GOVUK formbuilder
- Update `provide mobile` form to use GOVUK formbuilder
> [CAPT-1729] Use GOVUK formbuilder for provide mobile form

- app/forms/journeys/further_education_payments/teaching_responsibilities_form.rb
- app/models/journeys/further_education_payments.rb
- app/models/journeys/further_education_payments/session_answers.rb
- app/views/further_education_payments/claims/teaching_responsibilities.html.erb
- config/locales/en.yml
- spec/factories/journeys/further_education_payments/session.rb
- spec/features/further_education_payments/happy_claim_spec.rb
- spec/forms/journeys/further_education_payments/teaching_responsibilities_form_spec.rb
- https://dfedigital.atlassian.net.mcas.ms/browse/LUPEYALPHA-544
- Added teaching responsibilities page to FE journey
> [LUPEYALPHA-544] Add FE teaching responsibilities page

- app/forms/journeys/get_a_teacher_relocation_payment/application_route_form.rb
- app/forms/journeys/get_a_teacher_relocation_payment/visa_form.rb
- app/models/journeys/get_a_teacher_relocation_payment.rb
- app/models/journeys/get_a_teacher_relocation_payment/answers_presenter.rb
- app/models/journeys/get_a_teacher_relocation_payment/session_answers.rb
- app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
- app/models/policies/international_relocation_payments/policy_eligibility_checker.rb
- app/views/get_a_teacher_relocation_payment/claims/visa.html.erb
- config/analytics.yml
- config/locales/en.yml
- db/migrate/20240621153517_add_visa_type_to_international_relocation_payments_eligibilities.rb
- db/schema.rb
- spec/factories/journeys/get_a_teacher_relocation_payment/get_a_teacher_relocation_payment_answers.rb
- spec/features/get_a_teacher_relocation_payment/ineligible_route_completing_the_form_spec.rb
- spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
- spec/features/get_a_teacher_relocation_payment/trainee_route_completing_the_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/application_route_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/visa_form_spec.rb
- spec/models/journeys/get_a_teacher_relocation_payment/answers_presenter_spec.rb
- spec/support/get_a_teacher_relocation_payment/step_helpers.rb
Add the visa select screen
Adds the visa select screen as per IRP
https://github.com/DFE-Digital/claim-additional-payments-for-teaching/assets/9936028/dbe9e0c4-8ff9-417c-baba-65fbd896ffcd
> CAPT 1689/irp/visa

- app/forms/bank_or_building_society_form.rb
- app/views/claims/bank_or_building_society.html.erb
- Refactor forms to use GOVUK formbuilder
- Update `bank or building society` form to use GOVUK formbuilder
> [CAPT-1729] Use GOVUK formbuilder for account choice form

- config/locales/en.yml
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-591
- Update FE journey name
> [LUPEYALPHA-591] Update FE journey name

- app/views/get_a_teacher_relocation_payment/claims/application_route.html.erb
- app/views/get_a_teacher_relocation_payment/claims/contract_details.html.erb
- app/views/get_a_teacher_relocation_payment/claims/entry_date.html.erb
- app/views/get_a_teacher_relocation_payment/claims/nationality.html.erb
- app/views/get_a_teacher_relocation_payment/claims/passport_number.html.erb
- app/views/get_a_teacher_relocation_payment/claims/start_date.html.erb
- app/views/get_a_teacher_relocation_payment/claims/state_funded_secondary_school.html.erb
- app/views/get_a_teacher_relocation_payment/claims/subject.html.erb
- app/views/get_a_teacher_relocation_payment/claims/visa.html.erb
Fix forms
Updates the forms to show large legends and set the legend to a H1 where
it is acting as the page title.
> CAPT 1736/form fixes

- app/forms/journeys/get_a_teacher_relocation_payment/personal_details_form.rb
- app/models/journeys/get_a_teacher_relocation_payment.rb
- config/locales/en.yml
- spec/forms/journeys/get_a_teacher_relocation_payment/personal_details_form_spec.rb
A business requirement is to only allow applicants between 21 and 80
years old, as per the previous IRP application.
> Ensure date of birth is suitable

- .github/workflows/build_and_deploy.yml
Noticed we didn't have a link to IRP
> Add irp link to deploy note

- config/analytics.yml
- config/analytics_blocklist.yml
> Add session answers to anayltics block list

- terraform/application/config/review_app_env.yml
- terraform/application/config/test_app_env.yml
As per this comment: https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/2887#discussion_r1660801819
Move non-secret variables into code so the deployment is faster and they can be tracked / updated more easily.
Guided by what was already disclosed here: https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/master/.env.production
> CAPT-1751 Add review and test app ENV variables

- app/forms/form.rb
- app/forms/journeys/further_education_payments/contract_type_form.rb
- app/forms/journeys/further_education_payments/fixed_term_contract_form.rb
- app/forms/journeys/further_education_payments/taught_at_least_one_term_form.rb
- app/models/journeys/further_education_payments.rb
- app/models/journeys/further_education_payments/session_answers.rb
- app/models/journeys/further_education_payments/slug_sequence.rb
- app/models/policies/further_education_payments/policy_eligibility_checker.rb
- app/views/further_education_payments/claims/_ineligible_must_teach_at_least_one_term.html.erb
- app/views/further_education_payments/claims/fixed_term_contract.html.erb
- app/views/further_education_payments/claims/taught_at_least_one_term.html.erb
- config/locales/en.yml
- spec/features/further_education_payments/happy_path_spec.rb
- spec/features/further_education_payments/ineligible_paths_spec.rb
- spec/forms/form_spec.rb
- spec/forms/journeys/further_education_payments/contract_type_form_spec.rb
- spec/forms/journeys/further_education_payments/fixed_term_contract_form_spec.rb
- spec/forms/journeys/further_education_payments/taught_at_least_one_term_form_spec.rb
- spec/models/policies/further_education_payments/policy_eligibility_checker_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-547
- Add contract type forms and associated forms with branching
- Added all pages related to contract types for FE journey
- Also includes an ineligible possibility as an outcome 
- Resetting of dependent answers as its possible to go forwards then backtrack, then forwards again and get to page that has been answered which is handle by resetting the answers on the change
> [LUPEYALPHA-547] FE contract type and branching

- app/models/policies/international_relocation_payments/eligibility_admin_answers_presenter.rb
- config/locales/en.yml
- spec/factories/policies/international_relocation_payments/eligibilities.rb
- spec/models/policies/international_relocation_payments/eligibility_admin_answers_presenter_spec.rb
Updates the admin eligibility presenter to include the rest of the
eligibility details
> Additional eligibility answers

- app/models/policies/international_relocation_payments/eligibility_admin_answers_presenter.rb
- config/locales/en.yml
- spec/factories/policies/international_relocation_payments/eligibilities.rb
- spec/models/policies/international_relocation_payments/eligibility_admin_answers_presenter_spec.rb
> IRP review app 4

- db/data/20240709134609_add_irp_journey_configuration.rb
Adds a data migration to create the GetATeacherRelocationPayment journey
configuration on produciton.
> Journey config for GetATeacherRelocationPayment

- app/models/journeys/further_education_payments/session_answers.rb
- app/models/policies/further_education_payments/policy_eligibility_checker.rb
- app/views/further_education_payments/claims/_ineligible_must_be_recent_further_education_teacher.html.erb
- spec/features/further_education_payments/ineligible_paths_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-640
- Add ineligible state for non-recent FE teachers for FE journey
> [LUPEYALPHA-640] Add ineligible state for non recent FE teacher

- app/models/journeys/further_education_payments/session_answers.rb
- app/models/policies/further_education_payments/policy_eligibility_checker.rb
- app/views/further_education_payments/claims/_ineligible_subject_to_problematic_actions.html.erb
- spec/features/further_education_payments/ineligible_paths_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-645
- Add ineligible state due to problematic actions for FE journey
> [LUPEYALPHA-645] Add FE ineligible state due to problematic actions

- README.md
- bin/azure-console
- docs/connecting-to-azure.md
- docs/first-line-support-developer-runbook.md
- docs/school-check-data.md
Update documentation to access production.
Fix `bin/azure-console` and extend so that it can be used in review apps. This is referenced in `docs/school-check-data.md`.
> CAPT-1755 Update documentation for accessing production

- app/models/journeys/further_education_payments/session_answers.rb
- app/models/policies/further_education_payments/policy_eligibility_checker.rb
- app/views/further_education_payments/claims/_ineligible_lacks_teacher_qualification_or_enrolment.html.erb
- spec/features/further_education_payments/ineligible_paths_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-649
- Add ineligible state to FE journey when teacher lacks teaching qualification or enrolment
> [LUPEYALPHA-649] Add ineligible state to FE journey

- .github/workflows/database_restore.yml
Download backup from Azure storage and restore it to the production environment
See successful run: https://github.com/DFE-Digital/claim-additional-payments-for-teaching/actions/runs/9938477627/job/27450990068
> [1914] Database restore workflow

- terraform/domains/environment_domains/config/production.tfvars.json
- terraform/domains/environment_domains/config/test.tfvars.json
Prepare for the migration. Update the test domain first.
Then keep the PR open until the migration. Apply manually then merge if the migration is successful.
> [1914] Point front door at the new environments on AKS

- app/models/journeys/further_education_payments.rb
- app/views/further_education_payments/claims/_courses.html.erb
- app/views/further_education_payments/claims/_ineligible_teaching_less_than_2_5_next_term.html.erb
- app/views/further_education_payments/claims/contract_type.html.erb
- app/views/further_education_payments/claims/eligible.html.erb
- app/views/further_education_payments/claims/fixed_term_contract.html.erb
- app/views/further_education_payments/claims/further_education_provision_search.html.erb
- app/views/further_education_payments/claims/further_education_teaching_start_year.html.erb
- app/views/further_education_payments/claims/half_teaching_hours.html.erb
- app/views/further_education_payments/claims/ineligible.html.erb
- app/views/further_education_payments/claims/poor_performance.html.erb
- app/views/further_education_payments/claims/select_provision.html.erb
- app/views/further_education_payments/claims/subjects_taught.html.erb
- app/views/further_education_payments/claims/taught_at_least_one_term.html.erb
- app/views/further_education_payments/claims/teaching_hours_per_week.html.erb
- app/views/further_education_payments/claims/teaching_hours_per_week_next_term.html.erb
- app/views/further_education_payments/claims/teaching_qualification.html.erb
- app/views/further_education_payments/claims/teaching_responsibilities.html.erb
- config/locales/en.yml
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-696
- Missing page titles in FE journey
- Added missing page titles to FE journey
- Also added missing two thirds layout on some pages
> [LUPEYALPHA-696] Add missing page titles to FE journey

- app/forms/form_helpers.rb
- app/forms/journeys/further_education_payments/building_construction_courses_form.rb
- app/forms/journeys/further_education_payments/chemistry_courses_form.rb
- app/forms/journeys/further_education_payments/computing_courses_form.rb
- app/forms/journeys/further_education_payments/early_years_courses_form.rb
- app/forms/journeys/further_education_payments/engineering_manufacturing_courses_form.rb
- app/forms/journeys/further_education_payments/hours_teaching_eligible_subjects_form.rb
- app/forms/journeys/further_education_payments/maths_courses_form.rb
- app/forms/journeys/further_education_payments/physics_courses_form.rb
- app/forms/journeys/further_education_payments/subjects_taught_form.rb
- app/models/journeys/further_education_payments.rb
- app/models/journeys/further_education_payments/courses_helper.rb
- app/models/journeys/further_education_payments/session_answers.rb
- app/models/journeys/further_education_payments/slug_sequence.rb
- app/views/further_education_payments/claims/hours_teaching_eligible_subjects.html.erb
- app/views/further_education_payments/claims/teaching_courses.html.erb
- config/locales/en.yml
- spec/features/further_education_payments/happy_js_path_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/features/further_education_payments/ineligible_paths_spec.rb
- spec/forms/form_spec.rb
- spec/forms/journeys/further_education_payments/hours_teaching_eligible_subjects_form_spec.rb
> Fe hours teaching eligible subjects

- app/forms/journeys/further_education_payments/eligible_form.rb
- app/models/journeys/further_education_payments.rb
- app/models/journeys/further_education_payments/session_answers.rb
- app/models/school.rb
- app/views/further_education_payments/claims/eligible.html.erb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/models/journeys/further_education_payments/session_answers_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-653
- Populate FE award amount placeholder with actual award amount value
- Also fixed a slug sequence issue from a previous rebasing mistake
- Also moved superfluous placeholder page to the end of journey for now
> [LUPEYALPHA-653] FE award amount

- terraform/application/config/production_app_env.yml
- terraform/application/config/test_app_env.yml
- Add missing test and prod env vars for one login
- Prod env vars are not correct and will be updated once known
- This ensures that all environments are aligned
> add one login test and prod env vars

- terraform/application/config/production_app_env.yml
- this is temporary till one login productions have been added
- and integration has been completed
> Disable one login in production for now

- app/views/get_a_teacher_relocation_payment/landing_page.html.erb
Updates the landing page copy as per the doc linked off CAPT-1748
> Update landing page copy

- app/views/claims/sign_in.html.erb
these are already populated by the controller
> remove forced one login back links

- app/views/further_education_payments/claims/information_provided.html.erb
- spec/features/further_education_payments/happy_js_path_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-593
- Update copy for information provided page on FE journey
> [LUPEYALPHA-593] Update copy for FE information provided

- app/views/further_education_payments/claims/select_provision.html.erb
- config/locales/en.yml
- spec/features/further_education_payments/happy_js_path_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/features/further_education_payments/ineligible_paths_spec.rb
- spec/forms/journeys/further_education_payments/select_provision_form_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-798
- Update copy for FE select provision page
> [LUPEYALPHA-798] Update copy for FE select provision

- app/views/further_education_payments/claims/_ineligible_courses.html.erb
- app/views/further_education_payments/claims/_ineligible_lack_teaching_responsibilities.html.erb
- app/views/further_education_payments/claims/_ineligible_lacks_teacher_qualification_or_enrolment.html.erb
- app/views/further_education_payments/claims/_ineligible_less_than_half_hours_teaching_eligible_courses.html.erb
- app/views/further_education_payments/claims/_ineligible_must_at_least_half_hours_teaching_fe.html.erb
- app/views/further_education_payments/claims/_ineligible_must_be_recent_further_education_teacher.html.erb
- app/views/further_education_payments/claims/_ineligible_must_teach_at_least_one_term.html.erb
- app/views/further_education_payments/claims/_ineligible_subject.html.erb
- app/views/further_education_payments/claims/_ineligible_subject_to_problematic_actions.html.erb
- app/views/further_education_payments/claims/_ineligible_teaching_less_than_2_5.html.erb
- app/views/further_education_payments/claims/_ineligible_teaching_less_than_2_5_next_term.html.erb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-831
- Copy changes for FE ineligible states
> [LUPEYALPHA-831] Copy update: FE ineligible pages, action links

- app/forms/journeys/further_education_payments/building_construction_courses_form.rb
- app/models/journeys/further_education_payments/courses_helper.rb
- config/locales/en.yml
- spec/forms/journeys/further_education_payments/building_construction_courses_form_spec.rb
- spec/models/journeys/further_education_payments/answers_presenter_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-816
- Copy update for FE journey, building and construction course name
> [LUPEYALPHA-816] FE copy update: tweak building course name

- app/forms/journeys/further_education_payments/physics_courses_form.rb
- config/locales/en.yml
- spec/models/journeys/further_education_payments/answers_presenter_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-830
- Update FE physics courses
> [LUPEYALPHA-830] Update FE physics courses

- terraform/application/database.tf
Need `citext` extension to fix current deployments
> add citext to azure extensions

- app/views/claims/_sign_in.html.erb
- app/views/claims/_sign_in_1_start.html.erb
- app/views/claims/_sign_in_2_authed.html.erb
- app/views/claims/_sign_in_3_identified.html.erb
- spec/support/feature_helpers.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-594
- Update One Login flow copy
- Updated copy
- Also extracted 3 view partials one for each auth state rather than having inline if statements in a single view
> [LUPEYALPHA-594] Update One Login flow copy

- app/forms/journeys/early_years_payment/provider/authenticated/paye_reference_form.rb
- app/models/journeys/early_years_payment/provider/authenticated.rb
- app/models/journeys/early_years_payment/provider/authenticated/session_answers.rb
- app/models/journeys/early_years_payment/provider/authenticated/slug_sequence.rb
- app/views/early_years_payment/provider/authenticated/claims/paye_reference.html.erb
- config/locales/en.yml
- spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/paye_reference_form_spec.rb
> [LUPEYALPHA-770] EY PAYE reference

- app/forms/journeys/early_years_payment/provider/authenticated/start_date_form.rb
- app/models/journeys/early_years_payment/provider/authenticated.rb
- app/models/journeys/early_years_payment/provider/authenticated/session_answers.rb
- app/models/journeys/early_years_payment/provider/authenticated/slug_sequence.rb
- app/views/early_years_payment/provider/authenticated/claims/start_date.html.erb
- config/locales/en.yml
- spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/start_date_form_spec.rb
Start date form page for EY journey.
Date validations other than presence - these are still being discussed.
- Navigate through the journey to the start date page
- Try to submit an empty form and check the error message
> [LUPEYALPHA-766] EY start date

- app/forms/journeys/early_years_payment/provider/authenticated/child_facing_form.rb
- app/models/journeys/early_years_payment/provider/authenticated.rb
- app/models/journeys/early_years_payment/provider/authenticated/session_answers.rb
- app/models/journeys/early_years_payment/provider/authenticated/slug_sequence.rb
- app/views/early_years_payment/provider/authenticated/claims/child_facing.html.erb
- config/locales/en.yml
- spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/child_facing_form_spec.rb
https://dfedigital.atlassian.net.mcas.ms/browse/LUPEYALPHA-767
Confirm claimant spends most of their time in their job working directly with children
> [LUPEYALPHA-767] confirm spends most of the time working with children

- terraform/application/terraform.tf
- terraform/domains/environment_domains/terraform.tf
- terraform/domains/infrastructure/terraform.tf
https://trello.com/c/moH45K2M/1839-bug-conflictingpublicnetworkaccessandvirtualnetworkconfiguration
Update terraform providers to latest versions
Review using below. Should be no changes (apart from app image)
- make production-aks terraform-plan-aks CONFIRM_PRODUCTION=yes
- make domains-infra-plan
- make production-aks domains-plan CONFIRM_PRODUCTION=yes
> Update terraform providers

- .github/workflows/build_and_deploy.yml
Our standard practice is to run SNYK scanning against build images
Add snyk to build step
Check build workflow log
https://trello.com/c/9g2RL16e/1996-add-snyk-scan-to-cicd
> Add snyk scan to build workflow

- app/mailers/application_mailer.rb
- app/views/early_years_payment/provider/authenticated/submissions/show.html.erb
- spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
- Claim submitted page with reference, first name, surname, email_address
- Notify template ID added for submitted claim email
Link to 'read more' since we don't have that page yet.
Progress a claim through to submission and check the final page contains the correct info/copy.
> LUPEYALPHA-772 EY claim submitted + email to provider

- app/forms/journeys/early_years_payment/provider/authenticated/child_facing_form.rb
- app/models/policies/early_years_payments/policy_eligibility_checker.rb
- app/views/early_years_payment/provider/authenticated/claims/_ineligibility_not_child_facing_enough.html.erb
- app/views/early_years_payment/provider/authenticated/claims/child_facing.html.erb
- config/locales/en.yml
- spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
- spec/features/early_years_payment/provider/authenticated/not_child_facing_spec.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/child_facing_form_spec.rb
- spec/support/steps/eligible_ey_journey_authenticated.rb
https://dfedigital.atlassian.net.mcas.ms/browse/LUPEYALPHA-882
checkbox is now 'yes'/'no' radio buttons - with 'no' going to the ineligible page.
> [LUPEYALPHA-882] Change checkbox to radio buttons for child-facing page

- app/views/further_education_payments/claims/further_education_provision_search.html.erb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-947
- Update copy of FE provision search page
> [LUPEYALPHA-947] Update FE provision search copy

- app/views/further_education_payments/claims/_ineligible_teaching_less_than_2_5_next_term.html.erb
> [LUPEYALPHA-948] FE ineligible less than 2.5h - content update

- app/forms/journeys/further_education_payments/contract_type_form.rb
change wording "This includes zero hours and hourly paid contract types" -> "This includes zero hours contracts"
> [LUPEYALPHA-949] content update - remove hourly paid

- app/forms/journeys/further_education_payments/contract_type_form.rb
- app/forms/journeys/further_education_payments/fixed_term_contract_form.rb
- app/forms/journeys/further_education_payments/further_education_teaching_start_year_form.rb
- app/forms/journeys/further_education_payments/teaching_hours_per_week_form.rb
- app/forms/journeys/further_education_payments/teaching_hours_per_week_next_term_form.rb
- app/views/further_education_payments/claims/fixed_term_contract.html.erb
- config/locales/en.yml
- spec/forms/journeys/further_education_payments/building_construction_courses_form_spec.rb
- spec/forms/journeys/further_education_payments/chemistry_courses_form_spec.rb
- spec/forms/journeys/further_education_payments/computing_courses_form_spec.rb
- spec/forms/journeys/further_education_payments/contract_type_form_spec.rb
- spec/forms/journeys/further_education_payments/early_years_courses_form_spec.rb
- spec/forms/journeys/further_education_payments/engineering_manufacturing_courses_form_spec.rb
- spec/forms/journeys/further_education_payments/fixed_term_contract_form_spec.rb
- spec/forms/journeys/further_education_payments/further_education_provision_search_form_spec.rb
- spec/forms/journeys/further_education_payments/further_education_teaching_start_year_form_spec.rb
- spec/forms/journeys/further_education_payments/maths_courses_form_spec.rb
- spec/forms/journeys/further_education_payments/physics_courses_form_spec.rb
- spec/forms/journeys/further_education_payments/select_provision_form_spec.rb
- spec/forms/journeys/further_education_payments/subjects_taught_form_spec.rb
- spec/forms/journeys/further_education_payments/teaching_hours_per_week_form_spec.rb
- spec/forms/journeys/further_education_payments/teaching_hours_per_week_next_term_form_spec.rb
- spec/forms/journeys/further_education_payments/teaching_qualification_form_spec.rb
https://dfedigital.atlassian.net/browse/LUPEYALPHA-935
> [LUPEYALPHA-935] Update error messages in FE claimant journey

- app/views/further_education_payments/claims/information_provided.html.erb
- app/views/further_education_payments/submissions/show.html.erb
- config/locales/en.yml
- spec/features/further_education_payments/happy_js_path_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
changes to:
* information-provided screen
* claims/confirmation screen
to match the designs: https://www.figma.com/design/jUrXRdh2tXMiqsxCRalV9v/Claims-FE-Expansion-Beta
> [LUPEYALPHA-846] content updates

- app/models/policies/further_education_payments.rb
- app/views/further_education_payments/claims/_ineligible_fe_provider.html.erb
- app/views/further_education_payments/claims/further_education_provision_search.html.erb
- app/views/further_education_payments/landing_page.html.erb
- config/locales/en.yml
- spec/features/further_education_payments/ineligible_paths_spec.rb
https://dfedigital.atlassian.net/browse/LUPEYALPHA-1001
> [LUPEYALPHA-1001] FE content updates

- app/helpers/admin/amendments_helper.rb
- spec/helpers/admin/amendments_helper_spec.rb
> [LUPEYALPHA-1009] make award amount editable for FE

- app/views/admin/tasks/provider_verification.html.erb
We want to show the ukprn rather than the claim route
> Show the FE specific claim summary

- config/locales/en.yml
- spec/features/admin/admin_claim_further_education_payments_spec.rb
The copy for this link now matches what's in figma
> Update the link copy

- app/views/further_education_payments/submissions/show.html.erb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-1024
- Add survey to FE confirmation page
> [LUPEYALPHA-1024] Add survey to FE confirmation page

- app/views/claims/gender.html.erb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-864
- Update hint copy on payroll gender question, affects all journeys
> [LUPEYALPHA-864] Update hint copy on payroll gender question

- app/views/admin/tasks/payroll_details.html.erb
- config/locales/en.yml
- spec/features/admin/admin_claim_payroll_details_task_spec.rb
We now want to include the claimant's name in the payroll details task
description, for all policies
> Update payroll details copy

- app/models/policies/international_relocation_payments.rb
- app/views/get_a_teacher_relocation_payment/landing_page.html.erb
- config/locales/en.yml
- https://dfedigital.atlassian.net/browse/CAPT-1785
- Update IRP email addresses
> [CAPT-1785] Update IRP email address

- config/locales/en.yml
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-1011
- Update copy for FE admin task questions
> [LUPEYALPHA-1011] Update copy for admin FE task questions

- app/models/claim_checking_tasks.rb
- app/models/policies/international_relocation_payments/claim_checking_tasks.rb
- app/models/task.rb
- app/views/admin/tasks/previous_payment.html.erb
- config/locales/en.yml
- spec/features/admin/admin_checks_irp_claim_spec.rb
- spec/support/admin_view_claim_feature_shared_examples.rb
- https://dfedigital.atlassian.net/browse/CAPT-1791
- Add admin task for IRP to check for previous payments
- There will be an additional rejection reason which will be added future ticket
> [CAPT-1791] admin IRP previous payment task

- app/views/get_a_teacher_relocation_payment/submissions/show.html.erb
- app/views/submissions/_confirmation.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-1782
- Update copy of IRP confirmation screen
> [CAPT-1782] Update copy for IRP confirmation screen

- app/views/admin/notes/_form.html.erb
- app/views/admin/notes/index.html.erb
> [LUPEYALPHA-1029] admin notes content update

- app/views/admin/tasks/payroll_gender.html.erb
- config/locales/en.yml
- spec/features/admin/admin_claim_with_missing_payroll_gender_spec.rb
> [LUPEYALPHA-1007] content tweak - admin task for payroll gender

- app/models/claim_checking_tasks.rb
- app/models/policies/international_relocation_payments.rb
- app/models/policies/international_relocation_payments/claim_checking_tasks.rb
- app/models/task.rb
- app/views/admin/tasks/previous_residency.html.erb
- config/locales/en.yml
- spec/mailers/claim_mailer_spec.rb
- spec/support/admin_view_claim_feature_shared_examples.rb
- https://dfedigital.atlassian.net/browse/CAPT-1823
- Add new IRP admin task for previous residency check
- Added new task for IRP
- Added extra rejection reason
- After merge and deployment, notify templates will be updated to house new rejection reason
> [CAPT-1823] IRP previous residency task

- app/views/get_a_teacher_relocation_payment/claims/ineligible.html.erb
- app/views/get_a_teacher_relocation_payment/landing_page.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-1535
> [CAPT-1535] IRP copy tweaks

- app/models/policies/international_relocation_payments/admin_tasks_presenter.rb
- config/locales/en.yml
- https://dfedigital.atlassian.net/browse/CAPT-1822
- Update IRP admin task: arrival date
> [CAPT-1822] IRP admin task, tweak arrival date

- app/views/admin/tasks/_claim_summary.html.erb
- app/views/admin/tasks/_claim_summary_further_education_payments.html.erb
- app/views/admin/tasks/_claim_summary_international_relocation_payments.html.erb
Adds a link to the task index page as per the figma designs
> Add link to view tasks

- app/views/additional_payments/landing_page.html.erb
- app/views/submissions/_confirmation.html.erb
> LUPEYALPHA-1065/amend-slas

- config/locales/en.yml
- spec/features/admin/admin_claim_further_education_payments_spec.rb
- spec/features/admin/admin_view_full_claim_further_education_payments_spec.rb
- spec/features/further_education_payments/happy_js_path_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/features/further_education_payments/ineligible_paths_spec.rb
- spec/features/further_education_payments/provider/provider_verifying_claims_spec.rb
- spec/forms/journeys/further_education_payments/provider/verify_claim_form_spec.rb
- spec/models/journeys/further_education_payments/answers_presenter_spec.rb
- spec/models/policies/further_education_payments/eligibility_admin_answers_presenter_spec.rb
Updates the teaching hours question to the new copy
> LUPEYALPHA-1059/update-teaching-hours-question

- app/forms/journeys/early_years_payment/practitioner/find_reference_form.rb
- app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
- app/views/early_years_payment/practitioner/claims/find_reference.html.erb
- app/views/early_years_payment/practitioner/claims/how_we_use_your_information.html.erb
- app/views/early_years_payment/practitioner/claims/one_login_sign_in.html.erb
- config/locales/en.yml
- spec/factories/journey_configurations.rb
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
- spec/support/steps/journey_configuration.rb
Just content.
Added happy-path feature spec.
> [LUPEYALPHA-982] EY practitioner how-we-use-your-information page

- config/locales/en.yml
https://dfedigital.atlassian.net/browse/LUPEYALPHA-1037
> Update FE eligibility guidance URL

- app/models/policies/student_loans.rb
- app/views/student_loans/claims/student_loan_amount.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-1837
- Copy tweak
> [CAPT-1837] Tweak TSLR copy

- app/views/additional_payments/landing_page.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-1829
- Landing page tweaks
> [CAPT-1829] Update landing page tweaks

- app/forms/admin/claims_filter_form.rb
- app/helpers/admin/claims_helper.rb
- app/models/claim.rb
- app/models/policies/further_education_payments/admin_provider_verification_task_presenter.rb
- app/models/policies/further_education_payments/eligibility.rb
- spec/factories/policies/further_education_payments/eligibilities.rb
- spec/features/admin/admin_claim_further_education_payments_spec.rb
- spec/features/admin/admin_claims_filtering_spec.rb
- spec/features/admin/admin_view_claim_further_education_payments_spec.rb
- spec/jobs/further_education_payments/provider_verification_chase_email_spec.rb
- spec/models/claim_spec.rb
- spec/support/admin_view_claim_feature_shared_examples.rb
https://dfedigital.atlassian.net/browse/LUPEYALPHA-1004
> [LUPEYALPHA-1004] New status for FE claims: Awaiting provider verification

- app/views/claims/information_provided.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-1836
- Copy update for info provided screen
> [CAPT-1836] Copy update: info provided screen

- app/views/admin/tasks/visa.html.erb
> fix task pagination

- app/views/further_education_payments/submissions/show.html.erb
> [CAPT-1839] content update for FE submitted page

- app/views/further_education_payments/provider/claims/complete.html.erb
Remove place holder and add in the actual time frame.
> Copy update

- app/views/additional_payments/reminders/set.html.erb
- app/views/reminders/confirmation.html.erb
Service is open for 6 months rather than 5
> Update reminder copy

- app/views/further_education_payments/landing_page.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-1841
- Update FE landing page copy
> [CAPT-1841] Update FE landing page copy

- app/models/policies/further_education_payments/admin_tasks_presenter.rb
- config/locales/en.yml
- spec/models/policies/further_education_payments/admin_tasks_presenter_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-1147
- Add missing FE employment answer to back office
> [LUPEYALPHA-1147] FE employment answer

- app/models/journeys/further_education_payments/courses_helper.rb
- config/locales/en.yml
- spec/models/journeys/further_education_payments/answers_presenter_spec.rb
- spec/models/policies/further_education_payments/eligibility_admin_answers_presenter_spec.rb
> [CAPT-1843] FE qualifications URLs update

- app/forms/admin/claims_filter_form.rb
- app/views/admin/claims/index.html.erb
- spec/factories/claims.rb
- spec/forms/admin/claims_filter_form_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1401
- Add new filters relating to QA to `status`
- Also grouped the status filters to a bit more user friendly
> [CAPT-1401] Quality assured filters

- app/controllers/claims_controller.rb
Adjusts the completed slugs method to only update the list of visited slugs if the form is valid.
There's been some rollbar errors where the user _seems_ to have skipped ahead in the journey but hasn't be redirected back by the `check_page_is_in_sequence` callback.
All the tests pass but this seems like it could be risky. I'm not 100% sure that no code is subtly relying on the visited slugs being updated on failed form verifications.
We may want to consider a different approach to wizard state management, maybe passing the session answers to a state machine to determine which slugs are accessible.
Please think of any scenarios where moving this call back to an after action might bite us!
https://github.com/user-attachments/assets/d93d680e-1b31-4888-ba12-9d087c7f7e2a …
> LUPEYALPHA-1155 / Only update visited slugs if form submission succeeded

- app/models/policies/student_loans.rb
- config/locales/en.yml
- spec/mailers/claim_mailer_spec.rb
- spec/models/decision_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1867
- Add new rejection reason for student loans
- This change MUST be merged BEFORE notify template is updated
> [CAPT-1867] Add new TSLR rejection reason

- app/models/student_loans_data.rb
- lib/tasks/fix_student_loan_repayment_amounts.rake
- spec/lib/tasks/fix_student_loan_repayment_amounts_spec.rb
- spec/models/student_loans_data_spec.rb
> [CAPT-1877] fix and rake task for duplicate SLC data entries

- app/views/early_years_payment/practitioner/submissions/show.html.erb
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
> [LUPEYALPHA-990] EY practitioner confirmation page

- app/views/further_education_payments/claims/half_teaching_hours.html.erb
- app/views/further_education_payments/claims/hours_teaching_eligible_subjects.html.erb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-1201
- Use visible legends for FE questions
> [LUPEYALPHA-1201] Use visible legends for FE questions

- app/models/policies/further_education_payments.rb
- app/models/policies/international_relocation_payments.rb
- spec/models/policies/further_education_payments_spec.rb
- spec/models/policies/international_relocation_payments_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-1221
- Implement correct policy names when generating payroll CSV
> [LUPEYALPHA-1221] Implement FE + IRP payroll csv names

- db/migrate/20241028161228_make_claim_practitioner_email_address_citext.rb
- db/schema.rb
- spec/features/early_years_payment/practitioner/find_reference_spec.rb
https://dfedigital.atlassian.net/browse/LUPEYALPHA-1230
> [LUPEYALPHA-1230] make claim practitioner_email_address case insensitive

- app/models/journeys/further_education_payments/courses_helper.rb
- config/locales/en.yml
- spec/models/journeys/further_education_payments/answers_presenter_spec.rb
https://dfedigital.atlassian.net/browse/LUPEYALPHA-1234
> [LUPEYALPHA-1234] update FE early years courses checkbox

- app/forms/admin/claims_filter_form.rb
- app/models/claim.rb
- app/models/policies/early_years_payments.rb
- app/models/policies/early_years_payments/eligibility.rb
- spec/forms/admin/claims_filter_form_spec.rb
- https://dfedigital.atlassian.net/browse/LUPEYALPHA-1175
- Admin now able to filter by EY awaiting states
> [LUPEYALPHA-1175] Can filter for EY awaiting states

- config/locales/en.yml
- https://dfedigital.atlassian.net/browse/CAPT-1904
- Update EY email addresses in content
> [CAPT-1904] Update email address for EY links

- config/locales/en.yml
> Content change

- app/views/early_years_payment/provider/authenticated/claims/_ineligibility_nursery_is_not_listed.html.erb
- app/views/early_years_payment/provider/authenticated/submissions/show.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-1971
> [CAPT-1971] Copy tweak for ineligible nursery

- app/views/early_years_payment/practitioner/submissions/show.html.erb
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1976
> [CAPT-1976] Copy tweak EY practitioner confirmation

- app/views/early_years_payment/practitioner/claims/how_we_use_your_information.html.erb
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
Commit a8a71431be80848464230bfec4af2c3e38f4e3a9  snuck in when I was rebating the changes in CAPT-1973 on to master.
This pr reverts the wip commit!
Shouldn't be an issue as it's part of the unreleased EY journey and only updates the copy
> Revert "wip"

- Dockerfile
- app/models/policies/early_years_payments.rb
- spec/features/admin/admin_ey_tasks_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1965
- Update EY policy start date ready for launch
> [CAPT-1965] Update EY policy start date => 15/11/2024

- app/views/claims/_sign_in_1_start.html.erb
- app/views/further_education_payments/landing_page.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-2017
- Add copy to FE journey to say OL is mandatory
> [CAPT-2017] Copy tweak: add OL mandatory for FE

- app/forms/journeys/additional_payments_for_teaching/eligible_itt_subject_form.rb
- spec/forms/journeys/additional_payments_for_teaching/eligible_itt_subject_form_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1631
- When only one `eligible_it_subject` show a better error message
> [CAPT-1631] If one eligible_itt_subject show better error msg

- app/views/admin/tasks/_claim_summary_international_relocation_payments.html.erb
Need to permit the html, which is safe to do as it doesn't use any user
provided values
> Fix deadline warning tag

- app/views/claims/_email_address.html.erb
- app/views/claims/_one_time_password.html.erb
- app/views/claims/personal_bank_account.html.erb
- app/views/claims/teacher_reference_number.html.erb
- app/views/further_education_payments/claims/teacher_reference_number.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-649
- Use correct field types
> [CAPT-649] Correct field types

- terraform/application/config/test.tfvars.json
Migrate application to use gcp wif - deploy to test
Adding identity federation for google cloud authentication and big query.
this will enable it for test environment 
[Claims: migrate to GCP WIF](https://trello.com/c/ZolMBsh6/2175-claims-migrate-to-gcp-wif)
> gcp wif test deployment

- app/models/policies/early_years_payments.rb
- spec/models/policies/early_years_payments_spec.rb
https://dfedigital.atlassian.net/browse/CAPT-1711
> CAPT-1711: Payroll file alias for EY policy payments

- app/controllers/claims_form_callbacks.rb
- app/forms/bank_details_form.rb
- app/forms/information_provided_form.rb
- app/forms/personal_details_form.rb
- app/models/journeys/answers_student_loans_details_updater.rb
- app/models/journeys/base.rb
- app/models/journeys/session_answers.rb
- app/views/claims/address.html.erb
- app/views/claims/current_school.html.erb
- app/views/student_loans/claims/claim_school.html.erb
- spec/features/hmrc_bank_validation_spec.rb
- spec/forms/bank_details_form_spec.rb
- spec/forms/personal_details_form_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2145
- Refactor out controller callbacks to elsewhere, typically forms
- I've not been able to remove all of them, there are 3 left which should at least be manageable
- This means the "state machine" work should be much easier with fewer random state changes
> [CAPT-2145] Refactor controller callbacks

- config/analytics_hidden_pii.yml
> Reduce hidden fields

- app/controllers/admin/reports_controller.rb
- app/views/admin/reports/index.html.erb
We update the reports in the cron job, we only create them if it's a new
report so this page is showing the wrong timestamps.
> Show correct timestamps

- config/initializers/session_store.rb
- https://dfedigital.atlassian.net/browse/CAPT-2124
- Prevent prod and test cookies from clashing
> [CAPT-2124] Change test environment cookie key

- app/views/further_education_payments/submissions/show.html.erb
> Remove survey link and copy

- db/migrate/20250210114746_create_targeted_retention_incentive_payments_eligibilities.rb
- db/migrate/20250210115829_create_targeted_retention_incentive_payments_awards.rb
this resolves a test environment in quirkly state due to rollback
> Only create tables if they exists

- app/helpers/admin/claims_helper.rb
We should probably do a migration to fix the data stored in the DB but
this should get the admin site working again.
> Quick bug fix

- db/data/20250220124403_policy_options_provided_lup_to_tri.rb
- https://dfedigital.atlassian.net/browse/CAPT-2246
- Data migration for `policy_options_provided`
> [CAPT-2246] Data migration for policy_options_provided

- app/models/decision.rb
- config/analytics.yml
- db/migrate/20250206164949_add_result_boolean_to_decisions.rb
- db/migrate/20250210155819_back_fill_decisions_approved_column.rb
- db/schema.rb
- spec/models/decision_spec.rb
First part of replacing the result enum with a boolean column.
This commit writes to the new boolean column when updating the result
enum.
> Replace enum with boolean #1

- Dockerfile
16.6-r0 is no longer available
> Bump pg version

- app/views/early_years_payment/practitioner/submissions/show.html.erb
- app/views/early_years_payment/provider/authenticated/submissions/show.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-2239
- Add beta survey links to end of EY journeys
> [CAPT-2239] Add beta survey link to EY journeys

- app/models/decision.rb
- db/migrate/20250211153629_drop_decisions_result.rb
- db/schema.rb
Replace enum with boolean #4
Now we've migrated all the data to the approved column, we no longer
need the result column.
> CAPT 1473/convert decision enum to boolean part 3

- app/models/policies/further_education_payments.rb
- config/locales/en.yml
Adds a new rejection reason for FE claims
Will update the notify templates after this is merged.
> CAPT-2240/new fe rejection reason

- .github/workflows/build_and_deploy.yml
- terraform/domains/environment_domains/output.tf
Implementing CICD for Domains infra.
Plan for production: https://github.com/DFE-Digital/claim-additional-payments-for-teaching/actions/runs/13660063325/job/38188973627
Plan for test: https://github.com/DFE-Digital/claim-additional-payments-for-teaching/actions/runs/13635725790/job/38114164949
> 1972 implement ci cd for domains on all services

- app/models/feature_flag.rb
- config/analytics_blocklist.yml
- db/migrate/20250307152200_create_feature_flags.rb
- db/schema.rb
- spec/models/feature_flag_spec.rb
- Adds a basic feature flag implementation that is database backed
> add basic feature flag implementation

- config/analytics_hidden_pii.yml
> Add TRI TRN to hidden_pii list

- app/views/admin/tasks/index.html.erb
Not sure how this snuck in there!
> Remove hardcoded false

- app/models/journeys/session_answers.rb
- https://dfedigital.atlassian.net/browse/CAPT-2284
- Scrub DOB from rollbar
> [CAPT-2284] scrub DOB from rollbar

- db/migrate/20250319095448_remove_extra_indexes.rb
- db/schema.rb
- spec/features/student_loans_claim_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2192
- Remove extra indexes that don't appear to be needed
> [CAPT-2192] Remove extra indexes

- db/migrate/20250319095448_remove_extra_indexes.rb
- db/schema.rb
- spec/features/student_loans_claim_spec.rb
Reverts DFE-Digital/claim-additional-payments-for-teaching#3654
> Revert "[CAPT-2192] Remove extra indexes"

- app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
- app/views/early_years_payment/practitioner/claims/how_we_use_your_information.html.erb
- spec/features/admin/admin_ey_tasks_spec.rb
- spec/features/early_years_payment/practitioner/find_reference_spec.rb
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
- spec/support/steps/early_years_practitioner_journey.rb
- https://dfedigital.atlassian.net/browse/CAPT-2259
- For EY practitioner journey, move OL screen to after how we use your info screen
> [CAPT-2259] Change EY practitioner journey order

- config/locales/en.yml
> CAPT 2272/content fixes

- app/views/early_years_payment/practitioner/claims/find_reference.html.erb
- config/locales/en.yml
- spec/features/admin/admin_ey_tasks_spec.rb
- spec/features/early_years_payment/practitioner/find_reference_spec.rb
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
- spec/support/steps/early_years_practitioner_journey.rb
Some tweaks to the find reference page to match designs
> Update find reference to match designs

- app/controllers/deauth_controller.rb
- app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
- spec/features/early_years_payment/practitioner/signing_out_spec.rb
- spec/requests/deauth_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2274
- Fix signing out of OL when OL bypassed
> [CAPT-2274] Fix OL sign out when OL bypassed

- .github/workflows/notify-schema-change.yml
Send a notification when analytics file changes
We want to notify the data insights team when there's changes to the dfe
analytics files so they can update big query.
> Slack analytics change notification

- app/controllers/admin/base_admin_controller.rb
- app/controllers/admin/cookies_controller.rb
- spec/features/admin/admin_sessions_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2092
- fix admin accepting cookies before auth
> [CAPT-2092] fix admin accepting cookies before auth

- app/controllers/application_controller.rb
- spec/controllers/application_controller_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-1458
- Set security headers
> [CAPT-1458] Set security headers

- app/views/early_years_payment/provider/start/claims/email_address.html.erb
- spec/features/admin/admin_ey_tasks_spec.rb
- spec/features/early_years_payment/provider/start/happy_path_spec.rb
- spec/features/early_years_payment/provider/start/ineligible_email_spec.rb
- spec/support/steps/early_years_provider_journey_start.rb
- https://dfedigital.atlassian.net/browse/CAPT-2324
- EY tweak email form for better a11y
> [CAPT-2324] EY tweak email form for better a11y

- app/forms/bank_details_form.rb
- app/forms/journeys/early_years_payment/practitioner/bank_details_form.rb
- app/models/journeys/early_years_payment/practitioner.rb
- app/views/claims/_check_your_answers_section.html.erb
- app/views/claims/_email_address.html.erb
- app/views/claims/_mobile_number.html.erb
- app/views/claims/_one_time_password.html.erb
- app/views/claims/_personal_details_page.html.erb
- app/views/claims/_provide_mobile_number.html.erb
- app/views/claims/_sign_in_2_authed.html.erb
- app/views/claims/_sign_in_3_identified.html.erb
- app/views/claims/_sign_in_3_not_identified.html.erb
- app/views/claims/gender.html.erb
- app/views/claims/mobile_number.html.erb
- app/views/claims/personal_bank_account.html.erb
- app/views/early_years_payment/practitioner/claims/_ineligibility_claim_already_submitted.html.erb
- app/views/early_years_payment/practitioner/claims/_ineligibility_reference_number_not_found.html.erb
- app/views/early_years_payment/practitioner/claims/address.html.erb
- app/views/early_years_payment/practitioner/claims/check_your_answers.html.erb
- app/views/early_years_payment/practitioner/claims/mobile_number.html.erb
- config/locales/en.yml
- spec/features/admin/admin_ey_tasks_spec.rb
- spec/features/admin/eligible_ey_providers_spec.rb
- spec/features/early_years_payment/practitioner/find_reference_spec.rb
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
- spec/features/early_years_payment/practitioner/mobile_number_spec.rb
- spec/features/further_education_payments/one_login_without_idv_spec.rb
- spec/support/feature_helpers.rb
- spec/support/steps/early_years_practitioner_journey.rb
Grab bag of copy and styling changes from user research findings.
> Copy and styling changes for EY

- app/forms/journeys/additional_payments_for_teaching/eligible_itt_subject_form.rb
- app/models/concerns/eligibility_checkable.rb
- app/models/policies/early_career_payments/policy_eligibility_checker.rb
- app/models/policies/targeted_retention_incentive_payments.rb
- spec/forms/journeys/additional_payments_for_teaching/eligible_itt_subject_form_spec.rb
Remove some special handling from the ITT subject form
> Lup only journey/clean up itt subject form

- spec/support/omniauth_mock_helper.rb
Allows passing in name and email options when using the mock helper
> Allow setting more attributes from options

- Gemfile
- Gemfile.lock
New version introduces elevated logging levels to help diagnose issues with this gem.
> Upgrade dfe-analytics

- app/forms/journeys/get_a_teacher_relocation_payment/check_your_answers_part_one_form.rb
- app/forms/journeys/get_a_teacher_relocation_payment/ineligible_form.rb
- app/models/journeys/get_a_teacher_relocation_payment.rb
- app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
- app/views/get_a_teacher_relocation_payment/claims/application_route.html.erb
- spec/support/get_a_teacher_relocation_payment/step_helpers.rb
- https://dfedigital.atlassian.net/browse/CAPT-2419
- IRP journey now uses navigator
> [CAPT-2419] IRP journey uses navigator

- app/controllers/admin/base_admin_controller.rb
- app/controllers/admin/payment_confirmation_report_uploads_controller.rb
- app/controllers/admin/payroll_run_downloads_controller.rb
- app/views/admin/auth/sign_in.html.erb
- spec/factories/dfe_sign_in/users.rb
- spec/features/admin/admin_payroll_run_download_spec.rb
- spec/features/admin/admin_payroll_runs_spec.rb
- spec/requests/admin/admin_payment_confirmation_report_upload_spec.rb
- spec/requests/admin/admin_payroll_run_downloads_spec.rb
- spec/support/feature_helpers.rb
- spec/support/request_helpers.rb
- https://dfedigital.atlassian.net/browse/CAPT-2394
- Only service admins can download and upload payroll CSVs
> [CAPT-2394] Admin for payroll download

- app/views/get_a_teacher_relocation_payment/landing_page.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-2428
- copy tweak IRP landing and closing dates
- also made IRP landing page use two thirds layout
> [CAPT-2428] Copy tweak IRP landing page and closing dates

- app/jobs/purge_old_jobs_job.rb
- config/environments/production.rb
- config/recurring.yml
- https://dfedigital.atlassian.net/browse/CAPT-2425
> [CAPT-2425] Delete finished solid queue jobs older than 5 days

- Gemfile
- Gemfile.lock
- bin/delayed_job
- config/initializers/delayed_job.rb
- db/test_seeders/base_importer.rb
- https://dfedigital.atlassian.net/browse/CAPT-2112
- Remove delayed job queue code as now using solid queue
- Does not remove database tables, these can be removed once this change is deployed
- Maybe run solid queue for a bit before we merge this one
> [CAPT-2112] Remove delayed job code

- spec/rails_helper.rb
- spec/support/is_expected_with_block.rb
This isn't used anywhere and I'm not sure what it would be used for.
> Remove a spec helper

- app/forms/sign_in_or_continue_form.rb
- app/views/claims/_confirm_detail.html.erb
- app/views/claims/_sign_in_or_continue.html.erb
- app/views/claims/_tid_bypass.html.erb
- In development env appends form to be able to enter data that would be received from TID
- See screenshot
> TID bypass

- config/analytics.yml
- config/analytics_blocklist.yml
https://dfedigital.atlassian.net/browse/CAPT-2254
> CAPT-2254: Send EY provider data to BigQuery

- app/controllers/claims_controller.rb
- app/forms/journeys/teacher_student_loan_reimbursement/eligibility_confirmed_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/ineligible_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/student_loan_amount_form.rb
- app/forms/mobile_verification_form.rb
- app/forms/personal_details_form.rb
- app/models/journeys/navigator.rb
- app/models/journeys/teacher_student_loan_reimbursement.rb
- app/models/journeys/teacher_student_loan_reimbursement/session_answers.rb
- app/models/journeys/teacher_student_loan_reimbursement/slug_sequence.rb
- app/views/student_loans/claims/claim_school.html.erb
- app/views/student_loans/claims/claim_school_results.html.erb
- app/views/student_loans/claims/eligibility_confirmed.html.erb
- app/views/student_loans/claims/leadership_position.html.erb
- app/views/student_loans/claims/mostly_performed_leadership_duties.html.erb
- app/views/student_loans/claims/qts_year.html.erb
- app/views/student_loans/claims/qualification_details.html.erb
- app/views/student_loans/claims/select_claim_school.html.erb
- app/views/student_loans/claims/still_teaching.html.erb
- app/views/student_loans/claims/student_loan_amount.html.erb
- app/views/student_loans/claims/subjects_taught.html.erb
- spec/factories/journeys/teacher_student_loan_reimbursement/session_answers.rb
- spec/features/changing_answers_spec.rb
- spec/features/claim_with_mobile_sms_otp_spec.rb
- spec/features/student_loans_claim_spec.rb
- spec/features/tslr/tslr_claim_journey_with_teacher_id_check_email_spec.rb
- spec/features/tslr/tslr_claim_journey_with_teacher_id_check_mobile_spec.rb
- spec/features/tslr/tslr_claim_journey_with_teacher_id_trn_spec.rb
- spec/requests/claims_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2417
- Migrate TSLR journey to use navigator
- Also fixes resuming of a navigator journey in session by taking them to the furthest most question not yet answered
> [CAPT-2417] Migrate TSLR journey to use navigator

- .github/workflows/notify-schema-change.yml
Rather than dealing with all the YAML quirks we'll handle generating a
JSON payload and send that to slack
> Use json for slack notifications

- app/jobs/application_job.rb
> Alert monitoring on BG job errors

- Dockerfile
Update the docker image to avoid warning on prs
> Fix docker warnings

- .github/workflows/notify-schema-change.yml
> fix slack notification 4

- .github/workflows/build_and_deploy.yml
- db/seeds.rb
Setup TRI journey for review apps
We enable the feature flag for TRI only which makes tri not avaialble
for additional payments. We'll be removing additional payments soon
(along with the feature flag).
> CAPT 2433/tri review apps

- db/migrate/20250520145836_not_null_claims_policy.rb
- db/schema.rb
- Improvement to https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/3813
> Add not null constraint on claims#policy

- .github/workflows/notify-schema-change.yml
> fix slack notification 5

- app/forms/journeys/further_education_payments/provider/sign_in_form.rb
- app/forms/sign_in_form.rb
- app/models/journeys/further_education_payments/provider.rb
- spec/features/further_education_payments/bypass_one_login_spec.rb
- spec/models/journeys/navigator_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2455
- Cannot bypass OL pages and must have session variables set as a requirement
> Cannot bypass OL pages

- app/forms/select_mobile_form.rb
- app/models/journeys/base_answers_presenter.rb
- app/models/journeys/further_education_payments/answers_presenter.rb
- app/views/claims/correct_school.html.erb
- app/views/claims/select_mobile.html.erb
- app/views/reminders/personal_details.html.erb
- config/locales/en.yml
- config/locales/targeted_retention_incentive_payments.yml
- db/seeds.rb
- spec/features/tslr/tslr_claim_journey_with_teacher_id_check_email_spec.rb
- spec/features/tslr/tslr_claim_journey_with_teacher_id_trn_spec.rb
- spec/models/policies/early_career_payments/admin_tasks_presenter_spec.rb
- spec/models/policies/targeted_retention_incentive_payments/admin_tasks_presenter_spec.rb
- spec/support/journey_answers_presenter_shared_examples.rb
* Updates the seeds now AP has been removed
* Updates the locales to remove references to additional payments
> CAPT 2055/remove additional payments part 5

- app/forms/journeys/get_a_teacher_relocation_payment/breaks_in_employment_form.rb
- app/models/journeys/get_a_teacher_relocation_payment.rb
- app/models/journeys/get_a_teacher_relocation_payment/answers_presenter.rb
- app/models/journeys/get_a_teacher_relocation_payment/session_answers.rb
- app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
- app/views/get_a_teacher_relocation_payment/claims/application_route.html.erb
- app/views/get_a_teacher_relocation_payment/claims/breaks_in_employment.html.erb
- app/views/get_a_teacher_relocation_payment/claims/changed_workplace_or_new_contract.html.erb
- app/views/get_a_teacher_relocation_payment/claims/contract_details.html.erb
- app/views/get_a_teacher_relocation_payment/claims/entry_date.html.erb
- app/views/get_a_teacher_relocation_payment/claims/headteacher_details.html.erb
- app/views/get_a_teacher_relocation_payment/claims/nationality.html.erb
- app/views/get_a_teacher_relocation_payment/claims/passport_number.html.erb
- app/views/get_a_teacher_relocation_payment/claims/start_date.html.erb
- app/views/get_a_teacher_relocation_payment/claims/state_funded_secondary_school.html.erb
- app/views/get_a_teacher_relocation_payment/claims/subject.html.erb
- app/views/get_a_teacher_relocation_payment/claims/visa.html.erb
- config/locales/en.yml
- spec/factories/journeys/get_a_teacher_relocation_payment/get_a_teacher_relocation_payment_answers.rb
- spec/features/get_a_teacher_relocation_payment/ineligible_route_completing_the_form_spec.rb
- spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
- spec/forms/journeys/get_a_teacher_relocation_payment/breaks_in_employment_form_spec.rb
- spec/models/journeys/get_a_teacher_relocation_payment/answers_presenter_spec.rb
- spec/support/get_a_teacher_relocation_payment/step_helpers.rb
- https://dfedigital.atlassian.net/browse/CAPT-2481
- Add `breaks in employment` to IRP journey
- Also fixes changing answers to redirect to `check answers` page after changing an answer
> [CAPT-2481] IRP page employment breaks

- app/views/get_a_teacher_relocation_payment/submissions/show.html.erb
- spec/support/get_a_teacher_relocation_payment/step_helpers.rb
https://dfedigital.atlassian.net/browse/CAPT-2572
> CAPT-2572 - copy change on claim submission page

- .github/workflows/build_and_deploy.yml
- README.md
- app/controllers/omniauth_callbacks_controller.rb
- app/forms/journeys/early_years_payment/practitioner/claim_submission_form.rb
- app/forms/journeys/early_years_payment/provider/start/claim_submission_form.rb
- app/forms/journeys/further_education_payments/claim_submission_form.rb
- app/forms/journeys/targeted_retention_incentive_payments/claim_submission_form.rb
- app/forms/journeys/targeted_retention_incentive_payments/itt_academic_year_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/claim_submission_form.rb
- app/mailers/payment_mailer.rb
- config/locales/targeted_retention_incentive_payments.yml
- config/routes.rb
- public/404.html
- public/422.html
- public/500.html
- spec/helpers/application_helper_spec.rb
- spec/mailers/payment_mailer_spec.rb
- spec/requests/claims_spec.rb
- terraform/application/config/production_app_env.yml
- terraform/application/config/review_app_env.yml
- terraform/application/config/test_app_env.yml
https://dfedigital.atlassian.net/browse/CAPT-2503
> Removing remaining additional payments journey references

- app/models/journeys/teacher_student_loan_reimbursement/session_answers.rb
- app/models/journeys/teacher_student_loan_reimbursement/slug_sequence.rb
- spec/models/journeys/teacher_student_loan_reimbursement/slug_sequence_spec.rb
Inverts the slug sequence for TSLR
> Invert TSLR slug sequnce

- app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
Changes the slug sequence to be addative rather than subtractive.
Probably a bit less readable than before but easier to modify and
follows the same pattern as the other slug sequences.
> Invert ey practitioner slug sequence logic

- app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
- spec/models/journeys/get_a_teacher_relocation_payment/slug_sequence_spec.rb
IMO this is a bit uglier than the deletion based approach in this case
but it will be easier to modify and follows the pattern of the other
slug sequences.
> Invert IRP slug sequence

- app/forms/journeys/teacher_student_loan_reimbursement/leadership_position_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/mostly_performed_leadership_duties_form.rb
- app/forms/journeys/teacher_student_loan_reimbursement/qts_year_form.rb
- app/views/student_loans/claims/leadership_position.html.erb
- app/views/student_loans/claims/mostly_performed_leadership_duties.html.erb
- app/views/student_loans/claims/qts_year.html.erb
- config/locales/en.yml
- spec/features/changing_answers_spec.rb
- spec/support/feature_helpers.rb
- Slowly chipping away at make govuk formbuilder the default
> Use more govuk formbuilder forms for TSLR journey

- app/models/policies/international_relocation_payments/claim_checking_tasks.rb
- spec/support/admin_view_claim_feature_shared_examples.rb
Change the order tasks are displayed to make more sense to the ops team.
> Reorder tasks

- app/forms/journeys/teacher_student_loan_reimbursement/qualification_details_form.rb
- app/views/claims/correct_school.html.erb
- app/views/claims/select_email.html.erb
- app/views/claims/select_mobile.html.erb
- app/views/student_loans/claims/qualification_details.html.erb
- app/views/student_loans/claims/select_claim_school.html.erb
- spec/features/tslr/tslr_claim_journey_with_teacher_id_check_email_spec.rb
- spec/features/tslr/tslr_claim_journey_with_teacher_id_check_mobile_spec.rb
- spec/features/tslr/tslr_claim_journey_with_teacher_id_trn_spec.rb
Migrates some more forms over to use govuk form builder
> Form builder migration

- app/forms/journeys/get_a_teacher_relocation_payment/information_provided_form.rb
- app/models/journeys/get_a_teacher_relocation_payment.rb
- app/models/journeys/get_a_teacher_relocation_payment/slug_sequence.rb
- app/views/get_a_teacher_relocation_payment/claims/information_provided.html.erb
- spec/features/get_a_teacher_relocation_payment/admin_employment_history_task_spec.rb
- spec/features/get_a_teacher_relocation_payment/admin_first_year_payment_task_spec.rb
- spec/features/get_a_teacher_relocation_payment/teacher_route_completing_the_form_spec.rb
- spec/models/journeys/get_a_teacher_relocation_payment/slug_sequence_spec.rb
- spec/support/get_a_teacher_relocation_payment/step_helpers.rb
- https://dfedigital.atlassian.net/browse/CAPT-2623
> [CAPT-2623] IRP add info provided page

- app/assets/stylesheets/components/card.scss
- app/controllers/admin/auth_controller.rb
- app/controllers/further_education_payments/providers/authorisation_failures_controller.rb
- app/controllers/further_education_payments/providers/base_controller.rb
- app/controllers/further_education_payments/providers/claims_controller.rb
- app/controllers/further_education_payments/providers/sessions_controller.rb
- app/controllers/omniauth_callbacks_controller.rb
- app/models/dfe_sign_in/user.rb
- app/views/components/_card.html.erb
- app/views/further_education_payments/providers/authorisation_failures/show.html.erb
- app/views/further_education_payments/providers/claims/index.html.erb
- app/views/further_education_payments/providers/sessions/_dfe_sign_in_by_pass.html.erb
- app/views/further_education_payments/providers/sessions/new.html.erb
- config/analytics.yml
- config/routes.rb
- db/migrate/20250627101949_add_current_organisation_ukprn_to_dfe_sign_in_users.rb
- db/schema.rb
- lib/dfe_sign_in/authenticated_session.rb
- spec/features/further_education_payments/provider/provider_verifying_claims_in_2024_ay_spec.rb
- spec/features/further_education_payments/providers/unverified_dashboard_spec.rb
- spec/models/dfe_sign_in/user_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2630
- Adds provider dashboard to see claims
- The dashboard is not perfect and not fully implemented but should act as scaffolding to hang other stuff off
> [CAPT-2630] Provider dashboard

- app/forms/further_education_payments/providers/claims/verification/check_answers_form.rb
- app/forms/further_education_payments/providers/claims/verification/performance_and_discipline_form.rb
- app/models/further_education_payments/providers/claims/verification/wizard.rb
- app/views/further_education_payments/providers/claims/verifications/check_answers.html.erb
- app/views/further_education_payments/providers/claims/verifications/performance_and_discipline.html.erb
- config/analytics.yml
- db/migrate/20250707150443_add_performance_attributes_to_fe_eligibility.rb
- db/schema.rb
- spec/features/further_education_payments/providers/provider_verifying_claims_spec.rb
> Add performance and discipline screen

- app/forms/further_education_payments/providers/claims/verification/base_form.rb
- app/forms/further_education_payments/providers/claims/verification/check_answers_form.rb
- app/forms/further_education_payments/providers/claims/verification/contract_covers_full_academic_year_form.rb
- app/forms/further_education_payments/providers/claims/verification/contracted_hours_form.rb
- app/forms/further_education_payments/providers/claims/verification/performance_and_discipline_form.rb
- app/forms/further_education_payments/providers/claims/verification/role_and_experience_form.rb
- app/models/further_education_payments/providers/claims/verification/wizard.rb
- app/views/further_education_payments/providers/claims/verifications/check_answers.html.erb
- app/views/further_education_payments/providers/claims/verifications/contracted_hours.html.erb
- config/analytics.yml
- db/migrate/20250709125318_add_contracted_hours_attribtutes_to_fe_eligibility.rb
- db/schema.rb
- spec/features/further_education_payments/providers/provider_verifying_claims_spec.rb
Introduces the contracted hours screen, not much else to say!
> Capt 2636/contracted hours screen

- app/assets/stylesheets/components/card.scss
- app/views/further_education_payments/providers/claims/index.html.erb
- Remove check required tile from provider unverified claims dashboard
> Remove check required tile

- app/controllers/further_education_payments/providers/claims_controller.rb
- app/controllers/further_education_payments/providers/verified_claims_controller.rb
- spec/features/further_education_payments/providers/unverified_dashboard_spec.rb
- spec/features/further_education_payments/providers/verified_dashboard_spec.rb
The merge was overwriting the scoping by dsi account in the base
controller.
**Before**
**After**
> Fix claim scoping

- app/views/further_education_payments/providers/claims/verifications/performance_and_discipline.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-2715
> [CAPT-2715] Add hint text to provider question

- app/controllers/further_education_payments/providers/claims/verifications_controller.rb
- app/controllers/further_education_payments/providers/verified_claims_controller.rb
- app/forms/further_education_payments/providers/claims/verification/check_answers_form.rb
- app/models/further_education_payments/providers/claims/answers_presenter.rb
- app/views/further_education_payments/providers/claims/verifications/check_answers.html.erb
- app/views/further_education_payments/providers/verified_claims/index.html.erb
- app/views/further_education_payments/providers/verified_claims/show.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/admin/admin_view_full_claim_early_years_payments_spec.rb
- spec/features/admin/admin_view_full_claim_further_education_payments_spec.rb
- spec/features/further_education_payments/providers/provider_verifying_claims_spec.rb
- spec/features/further_education_payments/providers/verified_claim_spec.rb
- spec/features/further_education_payments/providers/verified_dashboard_spec.rb
- spec/forms/further_education_payments/providers/claims/verification/check_answers_form_spec.rb
- spec/rails_helper.rb
- spec/support/govuk_summary_list_test_helper.rb
- https://dfedigital.atlassian.net/browse/CAPT-2723
- Adds readonly view for verified claims
> [CAPT-2723] Add readonly view for provider verified claim

- app/forms/journeys/further_education_payments/further_education_teaching_start_year_form.rb
- app/views/further_education_payments/claims/further_education_teaching_start_year.html.erb
- config/locales/en.yml
- spec/features/admin/admin_view_full_claim_further_education_payments_spec.rb
- spec/features/further_education_payments/bypass_one_login_spec.rb
- spec/features/further_education_payments/change_answers_spec.rb
- spec/features/further_education_payments/existing_one_login_spec.rb
- spec/features/further_education_payments/happy_js_path_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/features/further_education_payments/ineligible_paths_spec.rb
- spec/features/further_education_payments/jump_around_spec.rb
- spec/features/further_education_payments/one_login_without_idv_spec.rb
- spec/features/further_education_payments/previously_claimed_spec.rb
- spec/features/further_education_payments/variable_contract_spec.rb
- spec/forms/journeys/further_education_payments/further_education_teaching_start_year_form_spec.rb
- spec/models/journeys/further_education_payments/answers_presenter_spec.rb
- spec/models/policies/further_education_payments/eligibility_admin_answers_presenter_spec.rb
> Update teaching start year form

- app/models/journeys/further_education_payments/answers_presenter.rb
- app/models/journeys/further_education_payments/slug_sequence.rb
- app/views/further_education_payments/claims/eligible.html.erb
- app/views/further_education_payments/claims/further_education_provision_search.html.erb
- app/views/further_education_payments/claims/select_provision.html.erb
- app/views/further_education_payments/claims/teaching_qualification.html.erb
- app/views/further_education_payments/claims/teaching_responsibilities.html.erb
- config/locales/en.yml
- spec/features/accessing_closed_service_spec.rb
- spec/features/further_education_payments/bypass_one_login_spec.rb
- spec/features/further_education_payments/change_answers_spec.rb
- spec/features/further_education_payments/college_not_found_spec.rb
- spec/features/further_education_payments/existing_one_login_spec.rb
- spec/features/further_education_payments/happy_js_path_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/features/further_education_payments/ineligible_paths_spec.rb
- spec/features/further_education_payments/jump_around_spec.rb
- spec/features/further_education_payments/one_login_without_idv_spec.rb
- spec/features/further_education_payments/previously_claimed_spec.rb
- spec/features/further_education_payments/variable_contract_spec.rb
- spec/forms/journeys/further_education_payments/further_education_teaching_start_year_form_spec.rb
- spec/forms/journeys/further_education_payments/teaching_qualification_form_spec.rb
- spec/forms/journeys/further_education_payments/teaching_responsibilities_form_spec.rb
- spec/models/journeys/navigator_spec.rb
- spec/support/steps/further_education_journey.rb
- **Update teaching start year form**
- **Update start year error copy**
- **CAPT-2747 update qualification page copy**
- **CAPT-2748 teaching responsibilities copy update**
- **Update slug sequence**
- **Change check answers order**
> CAPT 2745/move ay and qualification questions

- app/views/omniauth_callbacks/dfe_identity_failure.html.erb
Resolves
https://dfe-teacher-services.sentry.io/issues/6792961218/
> Still a lingering AP reference

- app/forms/journeys/further_education_payments/fixed_term_contract_form.rb
- app/models/journeys/further_education_payments/slug_sequence.rb
- app/models/policies/further_education_payments/policy_eligibility_checker.rb
- app/views/further_education_payments/claims/_ineligible_fixed_term_must_cover_full_academic_year.html.erb
- config/locales/en.yml
- spec/features/further_education_payments/ineligible_paths_spec.rb
- spec/forms/journeys/further_education_payments/fixed_term_contract_form_spec.rb
* Add ineligible page
* Remove branch from slug sequence
* Updated content on ineligible page
> CAPT-2752 - FE fixed term contract must cover full academic year

- app/models/journeys/early_years_payment/practitioner/slug_sequence.rb
- app/views/early_years_payment/practitioner/claims/_sign_in_3_not_identified_stop.html.erb
- app/views/early_years_payment/practitioner/claims/email_address.html.erb
- app/views/early_years_payment/practitioner/claims/how_we_use_your_information.html.erb
- config/locales/en.yml
- spec/features/admin/admin_ey_tasks_spec.rb
- spec/features/early_years_payment/practitioner/fail_idv_spec.rb
- spec/features/early_years_payment/practitioner/find_reference_spec.rb
- spec/features/early_years_payment/practitioner/happy_path_spec.rb
- spec/features/early_years_payment/practitioner/signing_out_spec.rb
- spec/support/steps/early_years_practitioner_journey.rb
- https://dfedigital.atlassian.net/browse/CAPT-2777
> [CAPT-2777] EY practitioner copy tweaks

- app/mailers/early_years_payments_mailer.rb
Need to show the provider's name in the notify email
> Send provider_contact_name to notify

- app/models/policies/international_relocation_payments/policy_eligibility_checker.rb
- https://dfedigital.atlassian.net/browse/CAPT-2845
- Extend IRP window from 6 months to 18 months to handle Y2
> [CAPT-2845] Extend IRP window for Y2

- app/assets/javascripts/application.js
- app/assets/stylesheets/components/button_to.scss
- app/views/shared/_one_login_header.html.erb
- yarn.lock
> Rebranded OL header

- app/models/policies/early_years_payments/admin_claim_details_presenter.rb
- config/locales/en.yml
- spec/features/admin/admin_ey_tasks_spec.rb
- spec/features/admin/admin_view_full_claim_early_years_payments_spec.rb
- spec/features/early_years_payment/provider/authenticated/changing_answers_spec.rb
- spec/features/early_years_payment/provider/authenticated/employee_email_spec.rb
- spec/features/early_years_payment/provider/authenticated/happy_path_spec.rb
- spec/features/early_years_payment/provider/authenticated/ineligible_returner_spec.rb
- spec/models/policies/early_years_payments/admin_claim_details_presenter_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2833
- Tweak radio option copy
> [CAPT-2833] EY tweak radio option copy

- config/locales/en.yml
- https://dfedigital.atlassian.net/browse/CAPT-2828
- EY hint copy tweak
> [CAPT-2828] Copy tweak EY hint

- app/controllers/admin/tasks_controller.rb
- app/forms/admin/tasks/form_factory.rb
- app/forms/admin/tasks/generic_form.rb
- app/forms/admin/tasks/matching_details_form.rb
- app/forms/admin/tasks/payroll_details_form.rb
- app/forms/journeys/early_years_payment/provider/authenticated/child_facing_form.rb
- app/forms/journeys/early_years_payment/provider/authenticated/returner_contract_type_form.rb
- app/forms/journeys/early_years_payment/provider/authenticated/returner_form.rb
- app/forms/journeys/early_years_payment/provider/authenticated/returner_worked_with_children_form.rb
- app/forms/postcode_search_form.rb
- app/models/decision.rb
- config/locales/en.yml
- spec/features/admin/admin_claim_with_matching_details_spec.rb
- spec/features/admin/admin_reject_claim_spec.rb
- spec/features/early_years_payment/provider/authenticated/not_child_facing_spec.rb
- spec/forms/admin/tasks/matching_details_form_spec.rb
- spec/forms/admin/tasks/payroll_details_form_spec.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/child_facing_form_spec.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/returner_contract_type_form_spec.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/returner_form_spec.rb
- spec/forms/journeys/early_years_payment/provider/authenticated/returner_worked_with_children_form_spec.rb
- spec/forms/postcode_search_form_spec.rb
- spec/models/decision_spec.rb
- spec/requests/admin/admin_decisions_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2823
- Tweak error message across the site
- Also fixes bug where not selecting a radio when admin decides about matching claims would throw an error. also added coverage for this scenario
> [CAPT-2823] Global error messages tweak

- app/views/early_years_payment/practitioner/claims/confirmation.html.erb
- app/views/early_years_payment/provider/authenticated/claims/confirmation.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-2850
> [CAPT-2850] Update EY survey links

- app/views/early_years_payment/provider/authenticated/claims/returner.html.erb
We want to ask whether the claimant worked in EY in the 6 months prior
to their current job, so the end date should be the date before their
start date, not the date of.
> Use previous date in question

- app/views/further_education_payments/providers/claims/verifications/claimant_personal_details.html.erb
We no longer want this copy to be in a drop down.
> Always show dropdown text

- app/views/further_education_payments/providers/claims/verifications/half_timetabled_teaching_time.html.erb
- spec/features/further_education_payments/providers/provider_verifying_claims_spec.rb
- spec/features/further_education_payments/providers/provider_verifying_with_claimant_courses_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2862
> [CAPT-2862] Hard code spring term

- app/views/further_education_payments/landing_page.html.erb
- https://dfedigital.atlassian.net/browse/CAPT-2869
> [CAPT-2869] Copy update FE landing page

- app/views/further_education_payments/providers/claims/verifications/check_answers.html.erb
- spec/features/further_education_payments/providers/provider_verifying_claims_spec.rb
- spec/features/further_education_payments/providers/provider_verifying_with_claimant_courses_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2864
> [CAPT-2864] Copy update FE provider declaration

- app/views/further_education_payments/claims/further_education_provision_search.html.erb
- config/locales/en.yml
- spec/features/admin/admin_view_full_claim_further_education_payments_spec.rb
- spec/features/further_education_payments/bypass_one_login_spec.rb
- spec/features/further_education_payments/change_answers_spec.rb
- spec/features/further_education_payments/claimed_last_year_spec.rb
- spec/features/further_education_payments/college_not_found_spec.rb
- spec/features/further_education_payments/existing_one_login_spec.rb
- spec/features/further_education_payments/happy_js_path_spec.rb
- spec/features/further_education_payments/happy_path_spec.rb
- spec/features/further_education_payments/ineligible_paths_spec.rb
- spec/features/further_education_payments/jump_around_spec.rb
- spec/features/further_education_payments/one_login_without_idv_spec.rb
- spec/features/further_education_payments/previously_claimed_spec.rb
- spec/features/further_education_payments/variable_contract_spec.rb
- spec/features/journey_session_expiry_spec.rb
- spec/models/journeys/further_education_payments/answers_presenter_spec.rb
- spec/models/policies/further_education_payments/eligibility_admin_answers_presenter_spec.rb
- https://dfedigital.atlassian.net/browse/CAPT-2872
> [CAPT-2872] Copy update FE provision search
