app/controllers/application_controller.rb

Until we are ready for the service to be available more widely we want
to slightly restrict access to it. This is to prevent members of the
public finding the application and thinking it's currently a live
service.
We're using basic auth configured with a single set of credentials. This
makes it easy for the team to grant access to the service to anyone
working on it, any stakeholders interested in it, and any user research
participants using it.
The username and password for each environment can be configured using
environment variables set in Heroku.
Once we are confident we know the scope of our beta and how we will
introduce it to users, we will change or remove the authentication
approach.

Add basic auth

---

.rubocop.yml
app.json
lib/tasks/default.rake
lib/tasks/rubocop.rake

We can only execute one command for tests as part of CI so we need a default rake task that calls both the RuboCop and RSpec rake tasks.

Configure CI to execute default rake task

---

app/helpers/application_helper.rb
app/views/layouts/application.html.erb
config/locales/en.yml

Pages should have unique page titles and this gives us a way to set the
page title for any view by setting the value of page_title in the view
file.
If none is set we will use the service name from the locales file
which this commit also adds.
Wherever the service name appears we should us t(:service_name) so
we can change the service name at any point from a single place.

Allow dynamic page titles with a sensible default

---

app/views/layouts/application.html.erb
app/views/start/index.html.erb

- Updated the phase banner to beta as that is the phase we are in.
- Removed the navigation until we need it.
- Used the service name on the page and styled it correctly.

Couple of updates to the app layout and start page

---

spec/rails_helper.rb

When we installed RSpec yesterday I ran `rspec --init` to generate the RSpec helpers but it's framework agnostic so it didn't generate a `rails_helper.rb`.
By running the command `rails generate rspec:install` we can generate the missing rails helper file.

Add RSpec Rails helper

---

README.md

We updated to ruby 2.6.2 so the readme should reflect this change.

Update the version of ruby you need

---

Gemfile
Gemfile.lock
README.md
config/environments/test.rb
spec/rails_helper.rb
spec/support/bullet.rb

[Bullet](https://github.com/flyerhzm/bullet) is a gem that detects N+1 queries.
Bullet will raise an exception when it encounters an N+1 query causing the tests to fail. It will start before each spec. 
It is configured to only run in our test environment because running it in development would add unneeded bloat.
RSpec will now autoload all files in the `spec/support` folder. This was done to help make our RSpec configuration more manageable.

Add Bullet to RSpec to check for N+1 queries

---

README.md

So that the architecture diagram is to hand when necessary and is less likely to get lost.

Link to architecture diagram from README.md

---

app/services/school_data_importer.rb
spec/services/school_data_importer_spec.rb

Working on this. The actual memory problem is fixed with CSV::foreach, but the resulting issues around testing against a smaller data set and open-uri returning a StringIO instead of a File proved tricky.
Got a test for a method that checks we get a Tempfile and that it has a path, this will probably come out later and make the method private. Not sure about the right syntax for returning the file, think this is okay.
Planning to loose the assignment to temp_csv_file and possibly stream into the tempfile, not sure we need to.

Increase performance of school data import

---

config/environments/production.rb

DEBUG is too high a log level for production as it risks exposing/storing PII and other information that we don't want logged in log files.

Reduce log level on production

---

app/controllers/claims_controller.rb
app/helpers/claims_helper.rb
app/models/tslr_claim.rb
app/views/claims/claim_school.html.erb
app/views/claims/new.html.erb
app/views/claims/qts_year.html.erb
app/views/shared/_error_summary.html.erb
config/brakeman.ignore
config/environments/development.rb
config/environments/test.rb
config/locales/en.yml
config/routes.rb
db/migrate/20190416090236_create_tslr_claims.rb
db/schema.rb
spec/features/tslr_claim_spec.rb
spec/helpers/claims_helper_spec.rb
spec/models/tslr_claim_spec.rb
spec/requests/claims_spec.rb
spec/routes/routes_spec.rb

This is the first step in the claim process for Teacher Student Loan Reimbursements. The aim is to:
- Allow the user to consent before continuing
- Capture the answer to the first question
- Give us a foundation to build out the rest of the journey
For now there is little modelling and abstraction of the multi-page application process as this only implements the first two steps, so the specific URLs/slugs (i.e. 'qts-year' and 'claim-school') are hardcoded for now. I expect this modelling to begin emerging when the next story is worked on (specifying the school that the teacher taught at).
The foundation of this is a RESTful `ClaimsController` that behaves like a [singular resource](https://guides.rubyonrails.org/v5.2/routing.html#singular-resources) for the current in-progress claim. The …

A Teacher can start a TSLR claim

---

Gemfile
Gemfile.lock
config/initializers/rollbar.rb

This PR adds the Rollbar gem and creates the initialiser for it, I decided we don't want Rollbar in development as well as the default testing environemnts, correct me if that was a bad call.
We override the RAILS_ENV to 'staging' with ROLLBAR_ENV which allows the staging data to show up in the Rollbar project, which is the recomendation for our Heroku specific implementation, see:
https://devcenter.heroku.com/articles/rollbar#attach-rollbar-to-multiple-apps
https://devcenter.heroku.com/articles/deploying-to-a-custom-rails-environment
Once this PR is merged we can confirm the functionality in the Rollbar project dashboard for staging and then deploy to production:
https://rollbar.com/dfe-teachers-payment-prod/dfe-teachers-payment-service/
See also: Issue #17 and Trello …

(75) Add Rollbar error reporting and monitoring

---

Gemfile.lock
app/controllers/claims_controller.rb
app/models/school.rb
app/models/tslr_claim.rb
app/views/claims/claim_school.html.erb
app/views/claims/still_teaching.html.erb
config/routes.rb
db/migrate/20190502093523_add_school_ref_to_tslr_claim.rb
db/schema.rb
spec/features/school_search_spec.rb
spec/features/tslr_claim_spec.rb
spec/fixtures/schools.yml
spec/models/school_spec.rb
spec/models/tslr_claim_spec.rb
spec/rails_helper.rb
spec/requests/claims_spec.rb

So that a teacher can locate a school easily we allow them to search by school name.
We limit the search string to 4 characters on more to limit the number of returned schools.  Once a list of possible schools is displayed the teacher selects their school from the list by choosing a radio button. 
The radio buttons are displayed with the school name and the school address to allow the teacher to distinguise between schools with similar or identical names.
If the teacher is unable to locate their desired school, they can restart the search process to try again.
Our ambition is to use a Javascript autocomplete to progressively enhance this feature, this PR does not include this work.
This PR includes a version change on the `dxw_govuk_frontend_rails` gem to introduce the new secondary …

(39) Teacher specifies claim school

---

app/models/school.rb
app/services/tslr/school_eligibility.rb
spec/factories/local_authorities.rb
spec/factories/schools.rb
spec/services/tslr/school_eligibility_spec.rb

To be eligible for TSLR payments a teacher must've taught in a school that meets the following criteria:
- State funded school in England
- Local Authority maintained secondary (including middle deemed secondary)
- Local Authority maintained or non-maintained special schools
- Secondary phase academy/free school
- In one of the 25 participating local authorities
Using the data from the Get Information About Schools database and after talking with the Financial Incentives policy team we can make these assertions about school eligibility:
- State funded school means any school that isn't independent, a university, a welsh school or 'Other'
- Local Authority maintained, Colleges, Academies and Free schools are only eligible if they have a phase of secondary or middle deemed secondary
- All …

Determine if a given school meets the TSLR eligibility criteria

---

app/controllers/claims_controller.rb
app/models/tslr_claim.rb
app/views/claims/current_school.html.erb
app/views/claims/still_teaching.html.erb
app/views/claims/subject_percentage.html.erb
config/environments/test.rb
config/initializers/customise_form_errors.rb
config/routes.rb
db/migrate/20190509150211_add_employment_status_to_tslr_claim.rb
db/migrate/20190513135311_add_current_school_id_to_tslr_claims.rb
db/schema.rb
spec/features/school_search_spec.rb
spec/features/tslr_claim_spec.rb
spec/models/tslr_claim_spec.rb

So a teacher can confirm their eligibility, we need to know they are still teaching and we would like to know at which shcool.
We've added a postgres enum to the database to store the teachers 'employment status', this has meant switching schema formats to sql rather than the usual rb.
We decided to duplicate the still teaching question view for now to keep our approach as simple as possible and our views clearly named, we like the idea of one view per question.
The sequence of pages shown to a teacher is stored in the model and we've laid the groundwork to enable us to skip pages based on certain criteria.
If a teacher is still teaching at the same school as they are claiming for, we still wanted to store that school in the `current_school` association, we've done this in the model with …

A teacher can say whether they are still employed at a school

---

app/controllers/claims_controller.rb
app/helpers/claims_helper.rb
app/models/tslr_claim.rb
app/views/claims/ineligible.html.erb
config/routes.rb
spec/features/school_search_spec.rb
spec/features/tslr_claim_spec.rb
spec/models/tslr_claim_spec.rb
spec/rails_helper.rb
spec/requests/claims_spec.rb
spec/support/feature_helpers.rb

This adds a new "You’re not eligible to for this service" page to the claim process. A claimant that tries to claim against an ineligible school is shown this page. A claimant that says they are no longer teaching is shown this page. In both cases a custom reason is given for the ineligibility.
The final commit refactors the feature specs by extracting helpers for performing common steps in the claim process.
This delivers the following two stories:
- https://trello.com/c/plhfSljn/116-teachers-claiming-against-in-eligible-schools-are-told-they-are-in-eligible
- https://trello.com/c/lNrYqiYf/115-a-user-making-a-claim-and-no-longer-teaching-is-told-they-are-in-eligible

Claim ineligibility for ineligible claim school and no longer teaching

---

app/controllers/claims_controller.rb
app/models/tslr_claim.rb
app/views/claims/teacher_reference_number.html.erb
db/migrate/20190516105143_add_teacher_reference_number_to_tslr_claim.rb
db/schema.rb
spec/features/tslr_claim_spec.rb
spec/models/tslr_claim_spec.rb

So that we can pay a teacher their teacher student loan reimbursement payment we need to make sure they are really a teacher. Collecting their TRN is one of the ways we will achieve this.
At this stage we are validating the presence of the TRN and normalising it to digits only before saving it to the database.
We have contacted a subject matter expert at DfE and  now understand that TRNs are 7 digits long.
We think we may need to encrypt the value in the database at some point, but this work does not include that.
https://trello.com/c/01yTwht6

A teacher can provide their Teacher Reference Number (TRN)

---

app/views/claims/qts_year.html.erb

This is where it should be according to the GDS design system.

Move errors summary to top of page for consistency

---

app/controllers/claims_controller.rb
app/helpers/claims_helper.rb
app/views/claims/timeout.html.erb
config/routes.rb
spec/rails_helper.rb
spec/requests/claims_spec.rb
spec/requests/timeout_spec.rb

To help keep users’ information private we end the claim session after a fixed period of inactivity. We've picked 30 minutes for the time being but this may change in the future.
Note that we don't do anything with the incomplete claim data that will still be stored in the database just yet. At some point we want to ensure that this data is not retained, and perhaps deleted when the session is timed out, but until we have a way to distinguish between a fully completed claim and a partial one, we risk deleting completed claims by mistake. Capturing this elsewhere for a future story.
A JS-powered modal to warn users of the impending timeout is being worked on separately.

Time out claim session after 30 minutes

---

app/controllers/claims_controller.rb
app/models/tslr_claim.rb
app/views/claims/national_insurance_number.html.erb
db/migrate/20190520095935_add_national_insurance_number_to_tslr_claim.rb
db/schema.rb
spec/features/tslr_claim_spec.rb
spec/models/tslr_claim_spec.rb

We need to capture the teacher's National Insurance number so that we can operate PAYE on their behalf.
We are validating the NI number is present and conforms to the correct format. We are removing whitespace before saving it to the database.
We think we may need to encrypt the value in the database at some point, but this work does not include that.
https://design-system.service.gov.uk/patterns/national-insurance-numbers/
https://trello.com/c/rwg4j8qH/

A teacher can provide their National Insurance number

---

app/models/school.rb
spec/models/school_spec.rb

So that we can help avoid any smart DDoS attempts by bad actors we limit the search results to only return the first 50 results.
https://trello.com/c/KvIcPsnw

Limit the school search to 50 results

---

app/controllers/claims_controller.rb
app/models/tslr_claim.rb
app/views/claims/email_address.html.erb
db/migrate/20190521123756_add_email_address_to_tslr_claim.rb
db/schema.rb
spec/features/tslr_claim_spec.rb
spec/models/tslr_claim_spec.rb

So we can update a teacher on the progress of their claim, we need to capture their email address.
Asking users for their email address is a recognised GOVUK pattern, so we have lots to reference:
https://design-system.service.gov.uk/patterns/email-addresses/
https://trello.com/c/GWRoD6Fz

Email capture page

---

app/controllers/claims_controller.rb
app/helpers/claims_helper.rb
app/models/tslr_claim.rb
app/views/claims/subjects_taught.html.erb
db/migrate/20190521160036_add_mostly_teaching_eligible_subjects_to_tslr_claim.rb
db/schema.rb
spec/features/tslr_claim_spec.rb
spec/models/tslr_claim_spec.rb
spec/support/feature_helpers.rb

So that we can determine if a teacher is eligible for this policy or not, we need to know if they taught the eligible subjects at least 50% of their time.
The content comes from the [TSLR eligibility checker](https://github.com/DFE-Digital/tslr/blob/f01d2713eab4698e11ef55323530bd0e1ca922fa/TSLR.UI/pages/question/subjects-taught.vue) from alpha, we may want to improve it at a later date.

Claimants say if they taught 50% of their time in an eligible subject

---

app/models/tslr_claim.rb
spec/models/tslr_claim_spec.rb

We have a database length limit on the following fields but no
validation to check it when submitting:
- name (200)
- address_line_1 (100)
- address_line_2 (100)
- address_line_3 (100)
- postcode (11)
Users trying to submit values longer than this would cause an error in our app, so this adds a length validators to stop the problem.
This commit also adds some white space around the validation definitions as
they are getting large and hard to read.

Add length validation to contact fields

---

app/models/local_authority_district.rb
app/models/school.rb
app/services/maths_and_physics/school_eligibility.rb
app/services/school_data_importer.rb
db/migrate/20190528121128_create_local_authority_districts.rb
db/migrate/20190528121606_add_local_authority_disctrict_ref_to_schools.rb
db/schema.rb
spec/factories/local_authority_districts.rb
spec/factories/schools.rb
spec/fixtures/local_authority_districts.yml
spec/fixtures/schools.yml
spec/models/local_authority_district_spec.rb
spec/services/maths_and_physics/school_eligibility_spec.rb
spec/services/school_data_importer_spec.rb

This PR mostly builds on @robbiepaul work on the TSLR eligibility.
Mathematics and Physics uses the more granular 'local authority disctrict' school location from GIAS data so we needed to model that data in our sevice first.
Once we have the LAD we use the same criteria as TSLR for the rest of the checks as it is the same:
- State funded school in England
- Local Authority maintained secondary (including middle deemed
secondary)
- Local Authority maintained or non-maintained special schools
- Secondary phase academy/free school
Along with:
- In one of the 42 local authority districts listed in the policy
There were a couple of things we confrimed with the policy team:
- The policy states 'Fenland and East Cambridgeshire' which is two separate
LADs in GIAS so we end up with 43 local …

We can determine if a given school meets the mp eligibility criteria

---

app/assets/stylesheets/components/currency_input.scss
app/assets/stylesheets/govuk_frontend_rails.scss
app/controllers/claims_controller.rb
app/helpers/claims_helper.rb
app/models/tslr_claim.rb
app/views/claims/student_loan_amount.html.erb
config/locales/en.yml
db/migrate/20190531101710_add_student_loan_repayment_amount_to_tslr_claims.rb
db/schema.rb
spec/factories/tslr_claims.rb
spec/features/tslr_claim_spec.rb
spec/helpers/claims_helper_spec.rb
spec/models/tslr_claim_spec.rb

So that we know how much to pay the teacher, we need them to tell us how much student loan they paid in the last tax year.
Includes a non-standard GOV.UK pattern for capturing monetary amounts.
https://trello.com/c/3iY89vAu/

Claimants can enter the amount of student loan they repaid last tax year

---

app/controllers/claims_controller.rb
app/helpers/claims_helper.rb
app/models/tslr_claim.rb
app/views/claims/bank_details.html.erb
config/locales/en.yml
db/migrate/20190529101022_add_bank_details_to_tslr_claim.rb
db/schema.rb
spec/features/tslr_claim_spec.rb
spec/helpers/claims_helper_spec.rb
spec/models/tslr_claim_spec.rb

We are not capturing the bank 'account holder name' at this stage as we hope to get that data from elsewhere.
Followed the layout from @titlescreen (ta!),left out the optional 'SSL notice', we can always add it in later if user research shows we need it.
Trello: https://trello.com/c/ayr6F6OV
This seemed to be as DRY as I could ge the normalisation methods, I couldn't see a way to pass which attribute had changed in the `before_save` hook.
At first I set the fields to integers in the DB but this meant constantly coercing the values to strings all over the place, so in the end I changed the DB to a string, I figured the form submits a string anyway. Wonder if I could've used a `to_i` at the end of the normalisation, be interested in your thoughts on this one?

Bank account details capture page

---

app/controllers/claims_controller.rb
app/helpers/claims_helper.rb
app/models/tslr_claim.rb
app/views/claims/_check_your_answers_section.html.erb
app/views/claims/claim_school.html.erb
app/views/claims/current_school.html.erb
config/environments/test.rb
spec/factories/local_authorities.rb
spec/factories/schools.rb
spec/factories/tslr_claims.rb
spec/features/tslr_claim_spec.rb
spec/helpers/claims_helper_spec.rb

Trello card: https://trello.com/c/OhhpWDA2/175-a-user-can-change-their-answers-when-reviewing-their-claim
This adds links for a user to change their responses, as per the pattern in the [GDS design system](https://design-system.service.gov.uk/patterns/check-answers/)

A user can change their answers when reviewing their claim

---

app/models/tslr_claim.rb
spec/models/tslr_claim_spec.rb

If the user selects "still teaching at another school", we need to know which school they are teaching at. We don't add this validation to the "submit" context as it isn't always required.
https://trello.com/c/ciJxfVuu

Ensure current school is selected if needed

---

spec/features/tslr_claim_spec.rb
spec/support/capybara.rb
spec/support/feature_helpers.rb

It's possible for the redirect to take longer than a second, to fix this we can leverage Capybara's `synchronize` helper which will wait until the block has completed up until `default_max_wait_time`.
Extract the functionality out to a helper so that it reads better in the spec.
We also need to increase the `default_max_wait_time` to 5 from the default of 2.

Fix intermittent failing JavaScript redirect spec

---

.dockerignore
Dockerfile
azure/parameters/development.json
azure/template.json
bin/azure-deploy
bin/docker-entrypoint
config/database.yml
docker-compose.yml

The `Dockerfile` builds 3 images: a `dependencies` image containing the JS and Ruby dependencies and things needed to build and install them, a `web` image which contains the app (but not the specs) copying dependencies from the `dependencies` image, and a `base` image both of them depend on. `web` is the image that actually gets uploaded and run. We have opted for explicit copies over relying on the `.dockerignore`. The entries in `.dockerignore` are to speed up the build as Docker makes a copy of the build context (the target directory) before running the build, which can be quite large including the temporary files.
The app can be built in development or production mode using `--build-arg`s (defaulting to production), and there's a `docker-compose.yml` set up to build and run a …

Set up Docker and first-pass Azure web app

---

Gemfile
Gemfile.lock
app/models/tslr_claim.rb
app/services/reference.rb
db/migrate/20190606152321_add_reference_to_tslr_claim.rb
db/schema.rb
spec/models/tslr_claim_spec.rb
spec/services/reference_spec.rb

This generates a human-friendly, difficult to guess reference number for a claim, so a user can easily refer to their claim if there are any queries.

Add a reference number for a TSLR Claim

---

app/models/tslr_claim.rb

It's set by the `update_current_school` callback if the user selects same school, otherwise the user should be setting it manually.
We now run `update_current_school` on validation as well as saving. This is fine to do as the value of it is invisible to the user. The other callbacks only run on save so we show the user the values they entered if there's an error with them, not a normalized version of them.

Validate that `current_school` is set on submit

---

app/assets/stylesheets/application.css
app/assets/stylesheets/components/currency_input.scss
app/assets/stylesheets/components/flash.scss
app/controllers/claims_controller.rb
app/helpers/govuk_form_helper.rb
app/views/claims/address.html.erb
app/views/claims/bank_details.html.erb
app/views/claims/claim_school.html.erb
app/views/claims/current_school.html.erb
app/views/claims/date_of_birth.html.erb
app/views/claims/email_address.html.erb
app/views/claims/full_name.html.erb
app/views/claims/national_insurance_number.html.erb
app/views/claims/qts_year.html.erb
app/views/claims/still_teaching.html.erb
app/views/claims/student_loan_amount.html.erb
app/views/claims/subjects_taught.html.erb
app/views/claims/teacher_reference_number.html.erb
app/views/shared/_error_summary.html.erb
config/locales/en.yml
spec/features/school_search_spec.rb
spec/features/tslr_claim_spec.rb
spec/helpers/form_helper_spec.rb
spec/support/feature_helpers.rb

We needed a few things to display these errors so there is a `FormHelper` class to wrap up the methods.
Read about the errors and markup required:
https://design-system.service.gov.uk/
The FormHelper implements:
`form_group_tag` is used to render a form group for either the entire form or an individual element.
`errors_tag` is used to render error messages next to the appropriate element.
`css_classes_for_input` adds the appropriate classes to any `<input>` element.
`css_classes_for_select` adds the appropriate classes for a `<select>` element.
`form_field_id_for_errored_attribute` is used to override a error summary link
Becasue the GOVUK errors call for the red indicator bar to include the whole form group I had to change the two school search views to accomadate this. I took the …

Highlight errors in form inputs as described in the design system

---

app/assets/stylesheets/application.css
app/assets/stylesheets/govuk_frontend_custom.scss
app/assets/stylesheets/govuk_frontend_rails.scss

Restore the govuk-frontend build to a single file so that custom components
can read the settings and helpers once the Rails require tree asset helper
is turned off.

Fix sass build

---

app/views/claims/confirmation.html.erb
spec/features/tslr_claim_spec.rb

Now we have a claim reference we can play it back to the user on the confirmation page.

Play back claim reference on confirmation page

---

spec/features/tslr_claim_spec.rb
spec/support/feature_helpers.rb

Passing in an element means finding it at the time when we call `wait_until_visible`, but that might be before it exists. This way it tries to find it on every iteration of the loop, meaning it can look for elements that don't always exist.
This fixes the intermittent test failure that still occurs.

Make `wait_until_visible` take a block to yield the element

---

bin/azure-deploy

`-core` is reserved for the CIP team.

Rename the Azure resource group

---

docs/architecture-decisions/0008-use-govuk-verify-for-claiment-identity-assurance.md
docs/architecture-decisions/0009-capture-teacher-reference-number.md
docs/architecture-decisions/0010-dfe-can-download-claims-data-during-private-beta.md

- 8 Use GOVUK Verify for claimant identity assurance
- 9 Capture a Teacher Reference Number to validate a claimants qualifications
- 10 DfE can download claim data during private beta phase

Adding Architecture Decision Records

---

Gemfile
Gemfile.lock
Procfile
Procfile.dev
README.md
app/controllers/claims_controller.rb
app/mailers/claim_mailer.rb
app/views/claim_mailer/submitted.text.erb
bin/delayed_job
config/application.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
db/migrate/20190613133709_create_delayed_jobs.rb
db/schema.rb
spec/features/tslr_claim_spec.rb
spec/mailers/claim_mailer_spec.rb
spec/requests/claims_spec.rb

So that a user has confidence that they have finished a thing, and so they have a record of having completed their application, we will send the user an email confirming their claim.
We want to include a reference number so that it is easy to find their claim if they need support.
- [delayed_job](https://github.com/collectiveidea/delayed_job) to process background jobs
- [GOV.UK Notify](https://www.notifications.service.gov.uk/) for sending ActionMailer emails
The content used is just temporary and is from the confirmation page.

Notify the claimant of their application

---

app/models/tslr_claim.rb
spec/factories/tslr_claims.rb
spec/models/tslr_claim_spec.rb

The build broke because the before save callback was changed to a before
validation callback. Skipping and setting callbacks in the factories
makes the code brittle. Instead of doing that, this reworks the callback
so that it only resets the current school when the employment status
changes on a persisted record, as it's only on persisted records
(created as part of the claim journey) that we expect to automatically
set/reset the current school based on the answer to the employment
question.

Only reset inferred current school when persisted

---

app/assets/stylesheets/application.scss
config/initializers/assets.rb

Non-js assets must be explicitly declared in the precompile paths in
conifg/initializers/assets.rb
Use the source css rather than the minified version.

 Fix accessible autocomplete stylesheet import

---

Gemfile
Gemfile.lock
app/views/admin/auth/sign_in.html.erb
config/routes.rb
spec/requests/admin_spec.rb

There is a known vulnerability in OmniAuth that could potentially be used in combination with a vulnerable OAuth provider to gain a signed-in user's session. Whilst DfE Sign-in uses OpenID, not OAuth, the substance of this patch (adding CSRF protection to the "Sign in" link on the
service) is still worth doing.
For more background see:
https://github.com/DFE-Digital/dfe-teachers-payment-service/network/alert/Gemfile.lock/omniauth/open
and https://github.com/omniauth/omniauth/pull/809
which leads to https://github.com/cookpad/omniauth-rails_csrf_protection

Address CVE-2015-9284

---

app/assets/javascripts/components/timeout_dialog.js.erb
app/assets/stylesheets/components/a11y_dialog.scss
app/views/application/_timeout_dialog.html.erb

Resolves the issue of not being able to click anything if JS is disabled. Also fixes related bug of modal overlay loading in and out on page refresh.

238 bug users who have javascript disabled cant click anything

---

app/models/tslr_claim.rb
app/views/claims/student_loan_amount.html.erb
spec/models/tslr_claim_spec.rb

If a user enters an amount of £99999 for their student loan repayment, the database raises an error, as there is a hard precision of 7 and a scale of 2 set in the database (which translates to a 5 figure number with two decimal places). I've altered this so the validations take place in the model, but also limited it on the frontend too, by changing the field to an `<input type="number">` with a max value of `99999`. Not sure if this is worth doing, but is an extra belt and braces step.

Fix student loan repayment errors

---

config/locales/en.yml

After input from our content designer and some initial feedback we have a refined name for the service:
> Teachers: claim back your student loan repayments
I've serached the code base for other references to the service name and decided there are none that will not be part of a wider content audit that is to come.
https://trello.com/c/uJTE0LAP

Change the service name

---

app/models/tslr_claim.rb
app/views/claims/eligibility_confirmed.html.erb
spec/features/tslr_claim_spec.rb

Once a user has answered enough questions for the service to confirm they
are eligible to make a claim we show them them a confirmation page.
It was felt important the GOV.UK Verify content and button was included but
disabled to remain close to the real user journey. Once integrated, skipping 
GOV.UK Verify will not be possible.
Decided that `eligibility-confirmed` was a good url for this as it speaks to what
the user has achieved at this point in the journey.
Decided not to include the copy in the locales as it is not a question, rather 
a static page that, once live should not change often, appreciate any thoughts 
on when to include in the locales and when to not.
https://trello.com/c/sAMnzJ1I

Add eligibility confirmation page

---

config/locales/en.yml

Need to remove the QTS acronymn from the question as we already say the
name in full.

Change the QTS question to remove acronym

---

app/views/claims/teacher_reference_number.html.erb
config/locales/en.yml

- Amend help text to provide users a way to seek assistance if they
don't know their TRN.
- Change width of input to match number of expected characters

Change the TRN question bring it inline with MPS

---

app/views/claims/student_loan_amount.html.erb

The original hint text on this question looked like it would lead users
to get a payslip and multiply the monthly contribution by 12, which
wouldn't take into account pay rises etc. The hint has changed to
identify documents that would accurately reflect their last years
contribution or point them to the student loans company so they can
find out.

Change loan help text to encourage better response

---

app/views/claims/confirmation.html.erb

Remove the x weeks text and put in sample timescales based of the maths
and physics journey to test expecations and make the page easier to
understand

Change confirmation to use sample timescales

---

app/views/claims/new.html.erb

To provide a more consistent experience we have replicated the writing
style to reflect the maths and phys consent page. This is still subject
to change when our content designer does a formal review but its a step
forwards.

Amend consent page to reflect writing in MPS

---

app/views/claims/eligibility_confirmed.html.erb

On the eligibility confirmed screen users can now go through the verify
journey. This was added so that we can test the extended process in UR.
Test LOA2 credentials
username: verifyuser
password: verifypass

Integrate test Verify LOA2

---

Dockerfile
Gemfile
README.md
app.json
azure-pipelines.yml
docker-compose.test.yml
spec/support/capybara.rb

- Azure Pipelines doesn't have any caching so containers are built from scratch each time. The whole CI process takes ~6 minutes, which I think is fine for now.
- Removing `webdrivers` gem may impact devs slightly as they will need to ensure they have `chromedriver` installed when running feature specs.
- We will need to ensure that when we build the production container that we pass in `--target web` so that none of the test container actions are run.

Set up CI with Azure Pipelines

---

docker-compose.yml

It causes errors if it's missing, and we don't currently specify env
specific env variables.

Stop including the non-existent env file for Docker Compose

---

Procfile

This adds a `release` step to the Procfile, so the Rails migrations are run in Heroku on release. At the moment, staging is broken because of this (I'll run migrations manually to fix for now)

Run migrations in Heroku on release

---

Dockerfile

The Prettier lint steps were failing because our config from `.prettierrc` wasn't being reflected, as it hadn't been copied over to the Docker container. This fixes it. I've also copied over the `.prettierignore` and `.rspec` files too.

Copy test-related files to test Docker container

---

app/helpers/claims_helper.rb
app/views/claims/check_your_answers.html.erb
config/locales/en.yml
spec/helpers/claims_helper_spec.rb

Make sure the questions asked on page and the summary of answers use the
same questions. This should make it more consistent and easier to
understand as you will now click to change a question and see that same
question shown on the question page.

Make questions and check answers consistent

---

lib/tasks/prettier.rake

Without the quote marks around the file glob, the shell does the glob
expansion, which results in inconsistent results between local
development and the build servers. Wrapping the glob in quoutes makes
sure that prettier is left to do the expansion.

Fix issue with prettier file globbing

---

.gitignore
.prettierignore
Procfile.dev
README.md
bin/launch-vsp
docs/govuk-verify.md

This replaces a bunch of the Verify documentation with code by adding a simple script that downloads and starts the latest version of Verify Service Provider with the relevant config for development. The only prerequisite is having Java installed. I did consider downloading and installing OpenJDK11 automatically, but thought that was best left for an individual dev to do, as the VSP supports multiple versions of Java and devs may have their own preferences (or indeed, already have a version of Java installed).
For production, this can be better served by a Docker container, but this will be good enough for development purposes.

Add startup script for GOV.UK verify

---

.prettierrc
README.md
docs/architecture-decisions/0001-record-architecture-decisions.md
docs/architecture-decisions/0002-use-rspec-for-testing.md
docs/architecture-decisions/0003-use-rubocop-for-linting.md
docs/architecture-decisions/0004-deployment-on-heroku.md
docs/architecture-decisions/0007-use-dfe-sign-in-for-admin-authentication.md
docs/architecture-decisions/0008-use-govuk-verify-for-claiment-identity-assurance.md
docs/architecture-decisions/0009-capture-teacher-reference-number.md
docs/architecture-decisions/0010-dfe-can-download-claims-data-during-private-beta.md
docs/architecture-decisions/0011-make-payments-using-dfes-existing-finance-system-nav.md
docs/govuk-verify.md

By default Prettier preserves existing prose wrapping, but restricting line lengths makes it easier to read prose.

Actually wrap markdown at 80 characters

---

app/views/verify/authentications/new.html.erb

On slow connections it may flash up for the user while the JavaScript loads, so it's better not to assume that they are only seeing it because JavaScript is disabled.

Make the fallback Verify page less confusing on slow connections

---

app/models/tslr_claim.rb
app/views/claims/ineligible.html.erb
spec/features/changing_answers_spec.rb
spec/features/ineligible_tslr_claims_spec.rb
spec/requests/claims_spec.rb

Change ineligble page to say users are not eligible for this payment as
its clearer that saying service.
Rephrase the must still be teaching ineligible message to make it more
simple.
Amend CI tests to use the new text.

Update teaching ineligible message for clarity

---

app/views/claims/ineligible.html.erb
app/views/claims/mostly_teaching_eligible_subjects.html.erb
config/locales/en.yml

The second part of the 50% question was shown to be ambiguous in user
testing. Users were unsure what constituted 50% of their teaching time,
50% of hours spent teaching or 50% of contracted hours.
The question was rephrased and hint text expanded upon to make this
clearer for users.
The ineligible page header was also edited to make it clear users
were not eligible for the service.

Change half hours question

---

app/controllers/claims_controller.rb
app/models/page_sequence.rb
app/models/tslr_claim.rb
config/routes.rb
spec/models/page_sequence_spec.rb
spec/models/tslr_claim_spec.rb
spec/requests/claims_spec.rb

We had logic for determining the sequence of pages in both the model and the controller. With more sequence-related logic coming down the pipe (i.e. the multi-page student loan plan questions), moving all the sequence-related logic into a single place is going to make our lives a lot easier.

Refactor page sequence code

---

Gemfile
Gemfile.lock
README.md
app/jobs/cron_job.rb
app/jobs/school_data_importer_job.rb
bin/docker-entrypoint
config/brakeman.ignore
config/environments/test.rb
db/migrate/20190627143657_add_cron_to_delayed_jobs.rb
db/schema.rb
lib/tasks/import_schools_data.rake
lib/tasks/jobs.rake
spec/features/tslr_claim_spec.rb
spec/jobs/cron_job_spec.rb
spec/jobs/school_data_importer_job_spec.rb
spec/lib/tasks/import_schools_data_spec.rb
spec/lib/tasks/jobs_spec.rb
spec/rails_helper.rb
spec/requests/claims_spec.rb
spec/support/delayed_job.rb

Sets up [`delayed_cron_job`](https://github.com/codez/delayed_cron_job) to manage scheduled tasks through a `CronJob` superclass. The rake task that enqueues the jobs runs after each `db:migrate` and `db:schema:load`, automatically (unless running in development), meaning it runs on every deploy.

Import schools on first deploy

---

app/jobs/cron_job.rb
spec/jobs/cron_job_spec.rb

As part of the initialisation process, we were running the `rake schools_data:import` task, but running `rake jobs:schedule` immediately afterwards stomps all over our previously scheduled job. This makes sure our CronJob superclass `jobs` method only cares about jobs with a cron attached to them

Make sure cron jobs can be scheduled independently

---

config/locales/en.yml
spec/requests/claims_spec.rb

Users were struggling to answer the QTS question, they were unsure if
they answered Jun YEAR when they got QTS or Sept YEAR when they started
at the school (Newly Qualified Teacher).
We changed it to use Initial Teacher Training as there were no issues
with this in the maths and physics journey.
Amended CI to use the alias for the question so we don't have to keep
updating it.

Amend QTS question to use ITT

---

app/jobs/school_data_importer_job.rb

We had a Rollbar error this morning (https://rollbar.com/dxw/teachers-payment-service/items/8/) when importing schools because the CSV for that day didn't yet exist. I've checked with the GIAS team, and they've told us these are generated at around 3am, so this queues the job at 4am when it's more likely that the CSV will be around. If it's not yet imported, the job will retry.

Update cron job to run at 4am

---

app/views/claims/eligibility_confirmed.html.erb
config/locales/en.yml

During user testing people were getting confused with the XXXX
placeholder that would in the fullness of time dynamically pull in a
date. All instances of XXXX have been hardcoded to be the last finanical
year and a card made so we don't forget to implement the dates properly.

Change XXXX dates to be real dates

---

app/views/claims/email_address.html.erb

Looked at changing the question itself but it made the question seem
demanding and invasive. So we have ameneded the hint text instead and
we will see how this tests.

Amend text to encourage use of personal email

---

app/models/page_sequence.rb
app/models/tslr_claim.rb
spec/factories/tslr_claims.rb
spec/features/admin_csv_download_spec.rb
spec/features/changing_answers_spec.rb
spec/mailers/claim_mailer_spec.rb
spec/models/page_sequence_spec.rb
spec/models/tslr_claim_spec.rb
spec/presenters/tslr_claim_csv_row_spec.rb
spec/presenters/tslr_claims_csv_spec.rb
spec/requests/claims_spec.rb

Whilst working on the Student loan plan journey, we wanted to make the page sequence easier to manage which this refatoring enables.
After this we'll have a more robust way to mange the page sequence, which _should_ make the student loan plan journey much simpler.

Submittiable behaviour tweaks

---

lib/verify/response.rb
spec/fixtures/verify/identity-verified.json
spec/lib/verify/response_spec.rb

It is possible to have values returned from Verify that aren't verified. We don't want to capture these values as it's important that the data we have is current, correct and valid.
This PR introduces the concept of `most_recent_verfied_value` that will filter out non-verified attributes, then sort them by `to` date. This makes an assumption that this value will always be present.

Only capture the most recent verified name and address

---

azure-pipelines.yml

This only happens on `master`, so means `latest` will always be the most recent build.

Tag as `latest` when deploying a Docker image

---

azure/secrets/template.json
bin/azure-deploy
docs/infrastructure-deployment.md

Adds `--skip-login` and `--skip-confirmation` flags to `bin/azure-deploy`, to support unattended deployment.
Drop `--rollback-on-error` seeing as it doesn't seem to work anymore.
The "Deploy" release configuration will need updating once this is merged, to complete the story.

Automate deployment of Azure

---

app/views/layouts/application.html.erb

I've been meaning to fix this link for a while but haven't been able to fit it in to other work. I think we either have it link to the root path or remove the link and just have the service name as text. I think the standard thing to do is link it to the home page of the service.

Service name links to root path

---

app/controllers/admin/base_admin_controller.rb
spec/requests/admin_timeout_spec.rb

> Sessions that never expire extend the time-frame for attacks such as cross-site request forgery (CSRF), session hijacking and session fixation.
We should ensure that admin sign-in sessions do not last longer than 30 minutes of inactivity.
There's a bit of duplication of logic between the code here and the code in the claims controller. We think it's best to keep this separate and not mix admin session logic with our normal user session logic.

Admin sessions time out after inactivity

---

README.md

We normally deploy from existing development releases so we use the deployment configuration at the time of first release, so we call scripts with the appropriate arguments, for example.
We decided that we don't need to mess with Git tags or similar because Azure DevOps keeps a record of releases and supports filtering by the most current release to each stage.

Document how to release a production build

---

app/controllers/claims_controller.rb
app/helpers/claims_helper.rb
app/models/claim_update.rb
app/models/page_sequence.rb
app/models/tslr_claim.rb
spec/features/changing_answers_spec.rb
spec/helpers/claims_helper_spec.rb
spec/models/claim_update_spec.rb
spec/models/page_sequence_spec.rb
spec/models/tslr_claim_spec.rb
spec/requests/claims_spec.rb

Some refactoring work that extracts a new class for handling updates to an in-progress claim, combining logic that was previously spread across the controller, `PageSequence`, and `TslrClaim` model itself.
It does also modify the behaviour slightly for users that are changing their answers:
- if a user changes the answer to their claim school, the subsequent employment_status and current_school answers are reset as those answers are coupled to claim_school and the question has effectively changed
- a user clicking "change" on the current school answer gets sent to the "still teaching" question, as that answer is coupled to the current school and should also be updated
More details in the individual commit messages.

Extract ClaimUpdate object for managing changes to an in-progress claim

---

azure/app/parameters/development.template.json
azure/app/parameters/production.template.json
azure/app/parameters/test.template.json
azure/app/template.json
bin/azure-deploy

We'll need to work out what other metrics we want to measure, but this shows the rough skeleton of how to set alerts up. They're configured to email the alert email address stored in the KeyVault, but can also be configured to send SMS, ping webhooks, or a number of other communication methods.
I found the process of working out how to specify an alert in ARM quite challenging. I didn't find any complete documentation on how to do it in a general case, only specific examples of varying completeness which I reverse engineered. The two references that I found useful were the [(incomplete) template specification](https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/2018-03-01/metricalerts) and the [.NET Azure SDK docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure …

Set up exemplar response time and security alerts on CIP

---

app/models/school.rb
app/services/maths_and_physics/school_eligibility.rb
app/services/tslr/school_eligibility.rb
spec/factories/schools.rb
spec/services/maths_and_physics/school_eligibility_spec.rb
spec/services/tslr/school_eligibility_spec.rb

Most special schools have a "Not Applicable" education phase, so this adds support for those schools.
We use the school type, rather than the school type group for determining if a school is a special school because e.g. free special schools are grouped under free schools, and so would be left out. There maye be other examples.

Change the school eligibility checkers to allow special schools with unspecified phases

---

azure/app/template.json

Also, use resource IDs rather than names for `dependsOn`, for added clarity and reduced chance of clashes.

Set up more alerts on CIP

---

app/controllers/claims_controller.rb
app/models/claim_update.rb
app/models/page_sequence.rb
app/models/tslr_claim.rb
app/presenters/tslr_claim_csv_row.rb
app/presenters/tslr_claims_csv.rb
app/views/claims/student_loan.html.erb
app/views/claims/student_loan_country.html.erb
app/views/claims/student_loan_how_many_courses.html.erb
app/views/claims/student_loan_start_date.html.erb
config/application.rb
config/locales/en.yml
db/migrate/20190709100000_add_student_loan_to_tslr_claim.rb
db/migrate/20190709110000_add_student_loan_country_to_tslr_claim.rb
db/migrate/20190709135426_add_student_loan_courses_to_tslr_claim.rb
db/migrate/20190710103359_add_student_loan_start_date_to_tslrclaim.rb
db/migrate/20190710133334_add_student_loan_plan_to_tslr_claim.rb
db/schema.rb
lib/student_loans.rb
spec/factories/tslr_claims.rb
spec/features/tslr_claim_spec.rb
spec/lib/student_loans_spec.rb
spec/models/claim_update_spec.rb
spec/models/page_sequence_spec.rb
spec/models/tslr_claim_spec.rb
spec/presenters/tslr_claim_csv_row_spec.rb
spec/presenters/tslr_claims_csv_spec.rb

A claimant can now answer a series of questions that determines whether they are still paying a student loan, and if so, the student loan repayment plan they are on.
Things still outstanding to do:
- Play back the plan on the check-your-answers screen
- The flow that will allow a user to go back "change" their answers to the student loan question
Both those things will be tackled as a separate PR building on this work.
https://trello.com/c/ioo1e1L1/335-capture-the-student-loan-repayment-plan

Claimant answers questions to determine their student loan plan

---

app/helpers/claims_helper.rb
app/models/claim_update.rb
app/views/claims/check_your_answers.html.erb
app/views/claims/student_loan_start_date.html.erb
config/locales/en.yml
spec/features/changing_answers_spec.rb
spec/features/tslr_claim_spec.rb
spec/helpers/claims_helper_spec.rb
spec/models/claim_update_spec.rb

The answers to the student loan questions now appear on the check-your-answers page and can now be "changed". Changes to certain questions result in dependent questions being reset such that the user has to re-answer them. More details in the individual commits.

Student loan answers can be changed

---

Dockerfile
docker-compose.test.yml
docker-compose.yml

Builds of `master` are currently failing because the asset precompile is missing environment variables.
This also reduces the size of builds by skipping Alpine's caching.
I've added a card to Trello to work out why we're not getting notified of failed builds.

Fix builds

---

app/models/tslr_claim.rb
app/views/claims/ineligible.html.erb
config/locales/en.yml
spec/features/ineligible_tslr_claims_spec.rb
spec/models/tslr_claim_spec.rb

This takes a bunch of magic strings out of the model and into the locale file, simplifying the code and making the test suite less brittle. This will also help with an in-progress refactoring that is pulling eligibility criteria out to a separate model.
We do lose some specificity in the error message when the claim school is not eligible. Hopefully a price worth paying to keep the code simpler.

Move ineligibility error messages to locale file

---

azure-pipelines.yml

This will help us catch when web builds would fail when the test builds don't at the cost of slower PR builds.

Build the Docker image on all builds

---

azure/app/template.json

When using hostNameSslStates as a property of the app service it caused the app settings and some of the site config to be ignored. We're not sure why but this resolves the issue.

Move hostname settings to its own resource

---

azure/app/template.json

This should've been flagged on the build of the PR that introduced this change. We're not sure why prettier passed this on Azure pipelines. Let's fix the formatting for now so we don't block other devs.

Fix JSON formatting in the ARM template

---

bin/request-vsp-certs
docs/govuk-verify.md

We put them in the secrets key vaults. There is a manual step to do the enrollment with Verify using their web interface.
There is no "test" environment for VSP certificates here, omitted until we have a use case for Verify that wouldn't allow reusing "development" certificates.
This script was already used to generate the certificate requests that we submitted for dev and prod environments.

Create a script to create and store VSP certificate requests

---

azure/app/parameters/development.template.json
azure/app/parameters/production.template.json
azure/app/parameters/test.template.json
azure/app/template.json
azure/secrets/template.json
bin/azure-deploy

Certificates need to be added to the key vault where they will be imported and assigned to the app service. The key vault needs additional permissions to allow that process.

Set up HTTPS for custom domains on Azure

---

azure/app/parameters/development.template.json
azure/app/parameters/production.template.json
azure/app/parameters/test.template.json
azure/app/template.json
bin/azure-deploy
bin/request-vsp-certs

This PR adds the config to set up a GOV.UK Verify VSP app service on our `development` infrastructure. The VSP Docker image is built, tagged and pushed when changes are made to the master branch on its repo: https://github.com/DFE-Digital/teacher-payments-service-verify
The private keys used by the VSP need to be in PKCS8 format and base64 encoded. We add a step to the script that requests certs to also save a base64 encoded version.
We can use this VSP to test the Verify integration environment: https://www.docs.verify.service.gov.uk/test-in-integration/testing/set-up-tests

Set up a Verify Service Provider (VSP) on staging

---

lib/verify/service_provider.rb

I'm not sure how to test this, WebMock doesn't give many options for making assertions about requests.
This was causing requests to our integration VSP to be rejected as it's running on https. We still want to be able to use the development VSP so we simply check the port inferred from the URI. Any URIs with `https` will have the port 443 inferred.

Verify requests use SSL for https URLs

---

azure/app/template.json
lib/verify/service_provider.rb

If the value doesn't match the value on the hub we see a 500 error when making a POST to it.
Also changed the `uri_uses_ssl?` method to check for `default_port` instead of port.

The VSP Entity ID needs https to match the value on the Verify Hub

---

Gemfile.lock

This reverts commit a3aa62f879f17e4f3b8c0297768bd5d4c9cc0326.
The update broke our integration with DfE Signin. We've not got the time to investigate the source of the issue, but the error can be seen here: https://rollbar.com/dxw/teachers-payment-service/items/30/.

Revert "Bump omniauth_openid_connect from 0.3.1 to 0.3.2"

---

app/controllers/admin/claims_controller.rb
app/controllers/claims_controller.rb
app/helpers/claims_helper.rb
app/models/student_loans/eligibility.rb
app/models/tslr_claim.rb
app/views/claims/qts_year.html.erb
config/brakeman.ignore
db/migrate/20190725125658_create_student_loans_eligibilities.rb
db/migrate/20190725145000_add_qts_award_year_to_student_loans_eligibilities.rb
db/migrate/20190725145500_remove_qts_award_year_from_tslr_claims.rb
db/migrate/20190729143440_add_eligibility_reference_to_tslr_claims.rb
db/schema.rb
spec/factories/student_loans/eligibilities.rb
spec/factories/tslr_claims.rb
spec/features/subjects_taught_spec.rb
spec/helpers/claims_helper_spec.rb
spec/models/claim_update_spec.rb
spec/models/page_sequence_spec.rb
spec/models/student_loans/eligibility_spec.rb
spec/models/tslr_claim_spec.rb
spec/presenters/tslr_claims_csv_spec.rb
spec/requests/claims_spec.rb
spec/requests/timeout_spec.rb

This is the first in as series of changes to move the eligibility of the student loans claim into it's own class. This work will invlove a lot of big changes so we want to keep the PRs as small and concise as we can to lessen the load on the reviewer.
This first PR introduces the `StudentLoans` namespace and the `Eligibility` class.
We then move on to port the `qts_award_year` from `TslrClaim` to the new eligitibility class. We will have to used some temporary hacks to keep this work green during the move, using some delegates, which will be removed once this work completes.
Along the way there have been some tightening up of tests and fixes as we encountered them.
https://trello.com/c/yt1gsap9

Introduce student loans eligibility model and port the QTS award year attribute

---

app/controllers/static_pages_controller.rb
app/views/layouts/application.html.erb
app/views/static_pages/accessibility_statement.html.erb
app/views/static_pages/cookies.html.erb
app/views/static_pages/privacy_policy.html.erb
app/views/static_pages/terms_conditions.html.erb
config/locales/en.yml
config/routes.rb
spec/requests/static_pages_spec.rb

- Setup cookie, privacy and T&C pages based on teacher vacacnies content
- Amend layout footer to link to pages
- Setup static pages routing and controller
- Setup Accessibility statement page based on feedback from
accessibility testing
These pages all have inital text and will need updating as we progress
into private beta and beyond. Also when we resolve certain accessibility
bugs we will need to amend the accessibility statement.
We should get someone more appropriate to look at and review the legal
text on the cookie, privacy and T&C pages.

Setup T&C pages etc

---

bin/azure-deploy

Azure DevOps doesn't run the releases in a Git repository, so doesn't have access to Git operations. This allows it to use the build's source version to set an environment variable instead.

Allow overriding the Git commit hash via an environment variable

---

lib/verify/response.rb

Whilst we are debugging the Verify integration environment it would be helpful to know what the response from Verify looks like.
We should remove this logging before we integrate with the production VSP.

Temporarily log the Verify response in Rollbar

---

config/environments/test.rb

Instead we will warn and log in development mode.
This was causing us pain whilst working on the refactoring work to extract a separate model for eligibility criteria because it was raising circular warnings – if we didn't preload `eligibility: [:claim_school]`, etc when loading the claim in `current_claim`, it would complain that we
weren't eager-loading the associations, and if we did, it would complain that they were being eager-loaded but not used. This is because not all the pages where the `current_claim` is accessed also access the eligibility and/or the claim_school.
We could continue to add to the whitelist for these sorts of situations, but then bullet starts to lose its value as we'll essentially end up having to whitelist both n_plus_one_query and unused_eager_loading for …

Don't raise on bullet warnings in test suite

---

app/models/tslr_claim.rb
spec/models/tslr_claim_spec.rb

If the user submits the email field with no value both the presence and
the format validation is triggered.
Switching the format validation to allow_blank stops this behaviour and
shows the appropriate message.
https://trello.com/c/YBl0fxWQ

Fix email field validation error messages

---

Dockerfile
Gemfile
Gemfile.lock
azure/resource_groups/app/template.json
bin/azure-deploy
config/initializers/application_insights.rb

We should see request logging show up once it's deployed. This doesn't do any more than that on the AI front.
This also fixes the deployment of the tmp resource groups. You aren't allowed to have more than one app service with a given host name, so we disable deployment of the hostname parts when deploying a tmp app. The dependency graph was also missing some explicit dependencies that blocked a fresh deployment.

Set up Application Insights

---

app/controllers/admin/claims_controller.rb
app/models/claim_update.rb
app/models/student_loans/eligibility.rb
app/models/student_loans/permitted_parameters.rb
app/models/tslr_claim.rb
app/views/claims/_school_search.html.erb
app/views/claims/still_teaching.html.erb
config/brakeman.ignore
db/migrate/20190806101920_add_schools_attributes_to_student_loans_eligibilities.rb
db/migrate/20190806133855_remove_school_attributes_from_tslr_claim.rb
db/schema.rb
spec/factories/student_loans/eligibilities.rb
spec/factories/tslr_claims.rb
spec/features/changing_answers_spec.rb
spec/helpers/claims_helper_spec.rb
spec/models/claim_update_spec.rb
spec/models/page_sequence_spec.rb
spec/models/student_loans/eligibility_spec.rb
spec/models/tslr_claim_spec.rb
spec/presenters/tslr_claim_csv_row_spec.rb
spec/requests/claims_spec.rb

This continues the work to separate the common claim-related data
(identity, payment, payroll, etc) from the policy-specific fields,
making it easier to support more than one type of policy (i.e. Maths &
Physics).
This commit focuses on the two schools associations and the closely
associated employment_status field. Because all three attributes are
closely related and interdependent they've had to be migrated at the
same time.
Note that no effort has been made to migrate the data from existing
claims as we're not yet live so any existing data can simply be deleted.
The best way to do this on the Azure environments is probably going to
be to drop the database and perform a release to force the rebuilding of
the database.
- As with the preceding work that moved qts_award_year, a bunch of …

Move schools-related attributes to Eligibility

---

app/helpers/claims_helper.rb
config/locales/en.yml
spec/helpers/claims_helper_spec.rb

When shown, the payroll_gender attribute should be formatted and not an
internal representation.

Output formatted payroll_gender

---

lib/verify/response.rb
spec/fixtures/verify/identity-verified-minimum.json
spec/fixtures/verify/identity-verified.json
spec/lib/verify/response_spec.rb

We now know more about the data attributes that are returned from Verify. This PR should allow us to have a "minimum viable Verify user" complete the journey with us.
- If the user's details haven't changed then we don't get any `to` or `from` dates
- If the user's details have changed they get a `to` and `from` date except the current value which doesn't have a `to` date
- If a user has no middle name it will be returned as an empty array

 Allow the minimum set of verified data from Verify

---

app/presenters/tslr_claim_csv_row.rb
spec/presenters/tslr_claim_csv_row_spec.rb
spec/presenters/tslr_claims_csv_spec.rb

"-", "+", "=", and "@" all have special meaning in Excel. Wrapping strings that contain them in `="<field>"` tells Excel to treat the field as a string, and to not execute any formulae.
When exported to a CSV, we end up with field that look like: `"=""=SUM(A1, A2)"""`, which works as expected.

Sanitize dangerous fields in CSV output

---

azure/resource_groups/app/parameters/production.template.json

So that we can get the production VSP up-and-running we need to configure several parameters used in the ARM templates.
We don't want to enable the feature flag just yet until we have a production VSP running and we can access the Verify production environment.

Add production VSP configuration parameters

---

app/assets/javascripts/components/subjects_taught.js
app/models/page_sequence.rb
app/models/student_loans/eligibility.rb
app/models/student_loans/permitted_parameters.rb
app/models/tslr_claim.rb
app/views/claims/ineligible.html.erb
app/views/claims/mostly_teaching_eligible_subjects.html.erb
app/views/claims/subjects_taught.html.erb
db/migrate/20190807103322_add_subjects_taught_attributes_to_student_loans_eligibilities.rb
db/migrate/20190807110948_remove_subjects_taught_attributes_from_tslr_claims.rb
db/schema.rb
spec/factories/student_loans/eligibilities.rb
spec/factories/tslr_claims.rb
spec/features/changing_answers_spec.rb
spec/features/ineligible_tslr_claims_spec.rb
spec/features/subjects_taught_spec.rb
spec/features/tslr_claim_spec.rb
spec/helpers/claims_helper_spec.rb
spec/models/student_loans/eligibility_spec.rb
spec/models/tslr_claim_spec.rb
spec/presenters/tslr_claim_csv_row_spec.rb
spec/presenters/tslr_claims_csv_spec.rb
spec/requests/claims_spec.rb

This moves the attributes related to subjects and teaching time to the Eligibility model. These were the last attributes that determine eligibility, which means we can also now stop delegating the eligibility-related methods. There are still accessor methods being delegated that we'll want to remove, but that can be done as a separate step later.
Part of https://trello.com/c/9gpS69mI/536-separate-eligibility-data-modelling-from-claims-in-prep-for-mp

Migrate subjects and teaching time-related attributes to the Eligibility model

---

app/models/tslr_claim.rb
spec/factories/tslr_claims.rb
spec/models/tslr_claim_spec.rb

We can't expect Verify to always return three lines of address.

Don't validate address line 3 presence

---

app/views/claims/qts_year.html.erb

Originally this was a select with only eligible options so we needed
the hint to explain why their options were limited. Now that it has been
amended to radios and a path to fail has been added this hint text has
become very leading and it is no longer required.

Remove hint on ITT/QTS year

---

config/locales/en.yml

We ask this question to determine whether we need to know the student
loan repayment plan the claimant is on so we can cover the recoveries
due for their claim. It makes no sense to ask them if they have ever
taken out a student loan at this stage, as if they hadn't they
wouldn't be eligible to actually claim back student loan repayments!
Separate work might follow to add an additional "Have you ever taken
out a student?" question earlier in the journey to tell those that might
be claiming even though they've never had one that they aren't eligible.

Simplify student loan plan gate question

---

lib/verify/response.rb

Now that we have Verify running in production we do not want to log the responses in Rollbar anymore.

Do not log Verify responses in production

---

app/presenters/tslr_claim_csv_row.rb
lib/excel_utils.rb
spec/lib/excel_utils_spec.rb
spec/presenters/tslr_claim_csv_row_spec.rb
spec/presenters/tslr_claims_csv_spec.rb
test.csv

Just wrapping the entire value in ="STRING_HERE" is not going to prevent
a formula triggering, for example a value of test"+SUM(A1- A2)+" would
get escaped to ="test"+SUM(A1- A2)+"", which would still attempt to
evaluate the entered info as a formula.
Instead we escape the first character if it is one of the known
formula-triggering characters. This may result in operability issues
further down the line, but these will be easy to deal with by the human
operator that will be working with the files. The excess of backslashes
in the gsub is the only way to add the '\\' escape character and match
substitution character '\0'.
See http://georgemauer.net/2017/10/07/csv-injection.html for more
details of how opening CSV files with Excel can result in formula
injection.

Adjust escaping of formula-triggering characters

---

app/assets/javascripts/application.js
app/assets/javascripts/js_check.js
app/views/layouts/application.html.erb
config/initializers/assets.rb
config/initializers/content_security_policy.rb

We only allow scripts, images and styles served over https and from our own domain. This will need updating as and when we add third-party scripts, for example Google Analytics.

Enable strict content security policy

---

azure/resource_groups/app/parameters/development.template.json
azure/resource_groups/app/parameters/production.template.json
azure/resource_groups/app/template.json
azure/templates/vsp.json

This allows us to explicitly set the number of instances we're running in a service plan. There is the option to do autoscaling, but this gives us redundancy if one instance was to fall over.

Set up redundancy and resource levels on infrastructure

---

app/controllers/admin/auth_controller.rb
app/controllers/admin/base_admin_controller.rb
app/controllers/application_controller.rb
app/controllers/claims_controller.rb
app/helpers/claims_helper.rb
app/views/layouts/application.html.erb
app/views/static_pages/cookies.html.erb
spec/requests/admin_spec.rb
spec/requests/admin_timeout_spec.rb
spec/requests/claims_spec.rb
spec/requests/timeout_spec.rb

This fixes a bug where a admin users session wouldn't be correctly timed out, even after the timeout period had elapsed.
If a previously signed-in admin user visited a page outside of /admin after the timeout period had elapsed, their admin session wouldn't be cleared because that was only happening in controllers inheriting from `Admin::BaseAdminController`, but the `last_seen_at` timestamp would get updated, as that happens in `ApplicationController`. When they then visit /admin, their session will no longer be timed out because of the updated `last_seen_at`.
The fix is to check and reset the admin session on all controller actions, not just the admin ones.
This also does the same thing for the claims session so that a user's claim session will be reset regardless of whether they are …

Admin session timeout bug

---

app/views/static_pages/privacy_policy.html.erb

As we are accessing the Database of Qualified Teachers and the Teacher
Pension Service, need need to explain to users how this information will
be used and who will access it.

Add in text about how we use data with DQT and TPS

---

app/views/claim_mailer/submitted.text.erb

The linebreaks get rendered as HTML `<br>` tags in the email body, which results in weird flow of text. Removing the linebreaks lets the text flow more naturally with the viewport of the mail client the email is being viewed in.

Remove linebreaks from email template

---

config/routes.rb

This adds a simple endpoint that returns 200 and a JSON response, so we can quickly check the service is up

Add a healthcheck endpoint

---

azure/resource_groups/alerts/template.json
bin/azure-deploy

These are proving too noisy, we get several every time someone deploys something. We can always reinstate these later when the service is more stable.

Remove the KeyVault activity alerts

---

azure/resource_groups/app/template.json

It seems that even though the deployment doesn't get run if `useAppServiceHostName` is false, Azure still attemptes to parse the template, and `appServiceCertificateDeploymentName` doesn't exist, so the deploy fails

Conditionally get the thumbprint from deployment

---

app/views/static_pages/accessibility_statement.html.erb
app/views/static_pages/terms_conditions.html.erb
config/locales/en.yml

We use the service-wide support email address on these pages as we can't know which particular policy the user will be interested in when viewing these pages.

Update accessiblity and T&Cs with support email

---

config/initializers/content_security_policy.rb

Only allow whitelisted JavaScript and CSS, which at the moment means anything from our domain, plus JavaScript from the Google Analytics and Tag Manager domains.

Tighten Content-Security-Policy

---

azure/resource_groups/app/template.json
azure/templates/vsp.json

They just made their first backwards incompatible change (changing the way database firewall rules are named), and we want to explicitly update rather than grabbing `master` every time.
This also makes rolling back more reliable, as we will roll back our dependency versions, too.

Pin the platform building blocks to a specific commit

---

azure/resource_groups/app/template.json
azure/templates/web_test.json

This GETs /healthcheck from 6 regions and fails if at least 3 of those regions return anything other than a 200 response within 30 seconds.
It lives in `app`, despite being an alert, because it needs to be in the same resource group as the Application Insights resource, and the web app service depends on that.
Inline XML is less than ideal, but we need to modify it at runtime making it difficult to pull out into a file.

Set up healthcheck alerts

---

azure/resource_groups/app/parameters/development.template.json
azure/resource_groups/app/parameters/production.template.json
azure/resource_groups/app/template.json
azure/templates/vsp.json
lib/verify/response.rb
spec/features/govuk_verify_spec.rb
spec/features/missing_verify_information_spec.rb
spec/features/student_loans_claim_spec.rb
spec/fixtures/verify/identity-verified-no-address.json
spec/fixtures/verify/identity-verified.json
spec/lib/verify/response_spec.rb
spec/requests/verify_authentications_spec.rb

GOV.UK Verify returns a different set of data for EU citizens, which is missing their address. Therefor, for EU citizens to be able to use the service, we need to ask them to provide their address explicitly.
We also need to enable the eIDAS feature on our VSP.
See https://www.docs.verify.service.gov.uk/using-verify-data/data-from-verify/#european-identities-and-eidas
I also took the opportunity to add a feature spec for users being able to provide a payroll gender that got lost as part of some other refactoring work.

GOV.UK Verify support for EU citizens

---

app/assets/javascripts/google_analytics.js
app/models/claim.rb
config/initializers/filter_parameter_logging.rb
config/initializers/rollbar.rb
spec/models/claim_spec.rb

The disadvantage of maintaining a separate list of these fields in `filter_parameter_logging.rb` means we'll have to be vigilant with updating this list when new sensitive parameters get added. I considered extracting them out to a separate constant so they'd be more visible in our codebase but we'd have a similar problem of keeping it up-to-date.

Filter out or anonymise personally identifiable information

---

app/views/claims/student_loan_amount.html.erb

Change hint to reference P60, annual statement then student loans
company so users will look for info in the way we want them to and not
guess last payslip contribution * 12

Change loan amount hint

---

config/initializers/application_insights.rb

This should give us more information about exceptions that occur. There is possibly some overlap here with Rollbar.

 Set up the more advanced unhandled exception handler on Application Insights

---

config/initializers/application_insights.rb

#293 has introduced an error in dev, because the `instrumentation_key` was incorrectly named (my bad, should've spotted that) and the container can't start correctly.

Fix incorrectly named variable

---

app/helpers/claims_helper.rb
config/locales/en.yml
spec/features/ineligible_tslr_claims_spec.rb
spec/helpers/claims_helper_spec.rb
spec/support/feature_helpers.rb

Because screen readers don't read out "-" as a word we should say
e.g. September 1 2013 to August 31 2014

Change how we show academic years

---

app/controllers/static_pages_controller.rb
app/views/static_pages/start_page.html.erb
config/routes.rb
spec/support/feature_helpers.rb

This replicates the start page on https://dfe-tslr-start-page.herokuapp.com/, and changes the root path to direct users to there by default. I'm not sure this is what we'll want to do long term (especially when we move to support Maths and Physics claims too), but it's enough for private beta.

Recreate the Heroku start page within our app

---

app/controllers/verify/authentications_controller.rb
app/models/claim.rb
db/migrate/20190815151449_add_verify_response_to_claim.rb
db/schema.rb
lib/verify/response.rb
spec/features/govuk_verify_spec.rb
spec/lib/verify/response_spec.rb
spec/models/claim_spec.rb
spec/support/verify_helpers.rb

This adds an additional JSON column to the Claims table where the entirity of the Verify response is called, regardless of if it's a succcessful verification or not. How we actually access this data (given we don't have SSH access) is a different matter

Store the entire GOV.UK Verify response to aid debugging during early beta

---

app/helpers/claims_helper.rb
app/views/claims/_check_your_answers_section.html.erb
app/views/claims/check_your_answers.html.erb
spec/helpers/claims_helper_spec.rb

They need to see what data we're using before they can make an informed decision about whether or not they submit the claim.

Play GOV.UK Verify response data back to the user

---

app/views/static_pages/privacy_policy.html.erb

We don't store any IP addresses at all, currently.

Remove reference to storing partial IP addresses

---

README.md
app/assets/javascripts/application.js
app/assets/javascripts/components/cookie_banner.js
app/assets/javascripts/cookie_functions.js
app/assets/javascripts/google_analytics.js
app/assets/stylesheets/components/cookie_banner.scss
app/views/layouts/application.html.erb
app/views/static_pages/cookies.html.erb

The styles are mostly copied from the "govuk_publishing_components" which GOV.UK uses as there's no official pattern in the Design System for it.
It will always show until the user clicks 'accept cookies'. No non-essential cookies should be loaded unless the user has clicked accept.
Google Analytics is considered non-essential so it won't start tracking until the page after they click "Accept cookies" on, this might skew our analytics slightly and we might want to tweak this/add events at a later date.
By default the cookie banner will always show to users without JavaScript, but won't have the accept button.
https://ico.org.uk/about-the-ico/news-and-events/news-and-blogs/2019/07/blog-cookies-what-does-good-look-like/

Add a basic cookie banner

---

app/views/claims/_school_search.html.erb

With the parameter on it appeared that the logic on the form group was
never getting triggered as it had returned a school and did not have an
error on that part. The error was because a user had not selected a
school from the radio.
Was
Now

Remove parameter on error check

---

app/controllers/admin/auth_controller.rb
app/controllers/admin/base_admin_controller.rb
app/controllers/admin/claims_controller.rb
app/controllers/application_controller.rb
app/models/admin_session.rb
app/views/admin/page/index.html.erb
spec/features/admin_csv_download_spec.rb
spec/models/admin_session_spec.rb
spec/requests/admin_spec.rb
spec/requests/admin_timeout_spec.rb

This builds on #307 and adds a support for a 'support' role in the app. If a user logs in to the admin section with a role of `teacher_payments_support`, then they are logged in, but cannot download the full CSV of claims

Have a support role within the app

---

README.md

The link in the Readme doesn't work

Fix busted link to release process

---

Dockerfile
azure-pipelines.yml
docker-compose.test.yml

This involves pushing up 3 new Docker images with `master` builds:
- `cache-web-dependencies`: the `dependencies` image that's dropped from the final image
- `cache-test`: the `test` image built for running tests
- `cache-test-dependencies`: the `dependencies` image for those tests (with `RAILS_ENV=test`)
This is so we can use them as cache sources for builds. This change means all non-`master` builds should now reuse the Docker cache from the latest `master` build. `master` builds build from scratch to ensure we're running fresh images (probably not necessary, but it depends on how much you trust Docker and our use of it).
In order to get this to work locally, I needed to drop the `--no-cache` flag on the package installations. This results in slightly larger Docker images, which I think …

Cache Docker on CI

---

config/environments/test.rb

Now that we're using translations a lot and we've previously seen one go missing we should raise an exception so we know before it makes it in to production.

Raise exception on missing translations in test environment

---

bin/slack-alert

This adds a quick Bash script that we can use in Azure DevOps at the end of a pipeline to alert the `#twd_payments_devs` channel that a deploy has happened. 
Once this has merged, we'll need to add the following command to a bash script at the end of both pipelines:
```bash
$(System.DefaultWorkingDirectory)/Build/repository/bin/slack-alert
```
And the following arguments
```bash
$(Environment.Name) $(Release.Artifacts.Build.BuildNumber) $(Build.BuildId) {SLACK_WEBHOOK_URL)
```

Add a Slack alert script to be run in Azure DevOps

---

CHANGELOG.md
app/controllers/verify/authentications_controller.rb
lib/verify.rb
lib/verify/redacted_response.rb
spec/lib/verify/redacted_response_spec.rb

This will aid in debugging situations where there is a problem handling the response from GOV.UK Verify.

Report redacted GOV.UK Verify responses using Rollbar

---

CHANGELOG.md
lib/verify/response.rb
spec/fixtures/verify/identity-verified-unverified-lastname.json
spec/fixtures/verify/identity-verified-unverified-middlename.json
spec/lib/verify/response_spec.rb

We saw an error on production where a user returned from Verify with an unverified middle name causing an application error and they couldn't complete their journey.
Middle names are not essential to payroll so we can mark them as optional, if a non-verified value comes back we can ignore it.
https://rollbar.com/dxw/teachers-payment-service/items/69/

Un-verified middle names are now ignored

---

CHANGELOG.md
app/models/claim.rb
app/views/claims/_ineligibility_reason_employed_at_no_school.html.erb
app/views/claims/_ineligibility_reason_ineligible_claim_school.html.erb
app/views/claims/_ineligibility_reason_ineligible_qts_award_year.html.erb
app/views/claims/_ineligibility_reason_not_taught_eligible_subjects.html.erb
app/views/claims/_ineligibility_reason_not_taught_enough.html.erb
app/views/claims/ineligible.html.erb
config/locales/en.yml
spec/features/changing_answers_spec.rb
spec/features/ineligible_tslr_claims_spec.rb
spec/features/subjects_taught_spec.rb
spec/lib/student_loans_spec.rb
spec/models/claim_spec.rb
spec/models/student_loans/eligibility_spec.rb
spec/requests/claims_spec.rb

They are now consitently worded and include the date range where appropriate. The subjects taught ineligibility is now more explicit about what the requirements are.

Adjust ineligible screens

---

CHANGELOG.md

- Record Google Analytics page views immediately after the user accepts
- Update ineligibility page content for clarity
- Ignore unverified middle names from Verify response
- Report redacted GOV.UK Verify responses to help debug issues with our response
handling
- Add static error pages for 400, 500 and 422 errors

Release 002

---

docs/release-process.md

We're already using the ref `release-xxx` for the branch name so doing a push will result in an error `src refspec matches more than one`.

Be explicit about pushing the release tag

---

azure/resource_groups/secrets/template.json

This adds a diagnostic setting to our Keyvault, as well as a storage account where we can keep the logs (retained for a year by default)

Add diagnostic logs to key vault

---

CHANGELOG.md
app/presenters/tslr_claim_csv_row.rb
spec/presenters/tslr_claim_csv_row_spec.rb

The `Current School` CSV field was erroneously displaying the Claim School

Fix display of current school in CSV

---

CHANGELOG.md
app/views/claims/_school_search.html.erb

The radio's label was not the next element so it made the radio
unselectable. Moved the label to the correct postition and split the
label to wrap the school contents.

Fixed bug with non JS search

---

azure-pipelines.yml

We're using Docker for building and running CI so we don't need Ruby any more. We were seeing an error with the version of Ruby we requested not being available on the agent. This should fix that.

Remove the 'Use Ruby' step from the build pipeline

---

CHANGELOG.md
config/initializers/rollbar.rb
lib/verify/redacted_response.rb
spec/lib/verify/redacted_response_spec.rb

There are two goals here:
1. Redact the from date in the Verify response
2. Ensure the users IP Address is not passed from Rails to Rollbar
Redacting the entire from date was the simplest option at this point, we will continue to monitor the service and if we need to redact only part of the date we can come back to this.
Rails sends a couple of headers and we have expicitly set the Rollbar gem not to send the client IP.
You can test this in Rollbar by removing `|| Rails.env.development?` from the rollbar config and adding the `ROLLBAR_ACCESS_TOKEN` to your `env.development` –  you can get the token from Rollbar, after which there should be no evidence of the IP in Rollbar occurances.
Once this change is deployed to production we must delete all prioir occorances in Rollbar where the from …

Stop leaking dates of birth in govuk verify responses inferrable from from fields

---

CHANGELOG.md
azure/templates/app.json
bin/swap-slots

The runtime stack is still declared for the "production" slot so an incomplete deployment followed by a service restart doesn't take the service down. If not specified, the fact that we do a `Complete` deployment would mean that the configuration would be cleared when deploying, making the app fragile to a restart.
The app service doesn't change which version it's running unless it's restarted.
This situation might be improved by setting the main slot to use the currently live version explicitly, so configuration would match what's already live, though this wouldn't stop environment variable changes getting deployed. We could do this by querying the Azure API. I don't believe this is a good idea, however. It's better to deploy a complete configuration of the newest version accidentally …

Create a staging slot to deploy to for zero-downtime

---

CHANGELOG.md

- Fixed a bug where missing "from" dates on Verify attributes caused a crash
- Stop user IP address appearing in Rollbar
- Redact all from dates in Verify response
- Fixed a bug where the no JS school contact was not selectable
- Fixed a bug in the GOVUK logotype svg src url
- Improve layout of closed schools in search results
- Add contact us page
- Fix an error in the claim CSV where the current school was displaying
incorrectly
- Switch to using deployment slots for "zero-downtime" deployment

🚢 Release 003 

---

app/controllers/application_controller.rb
app/controllers/verify/authentications_controller.rb
app/helpers/claims_helper.rb
spec/features/govuk_verify_spec.rb
spec/features/timeout_spec.rb

As a user can potentially take a long time to authenticate with Verify, we've seen users sessions getting timed out when they return to the app. This extends the timeout period to 90 minutes on Verify-related pages, giving the user a bit more time to complete their actions.

Extend timeout length when coming back from Verify

---

bin/slack-alert

This adds another option to add to the Slack script that sends an error if the build fails. The release pipeline will need to be changed before this is merged.

Update Slack script to send error if build fails

---

CHANGELOG.md
app/presenters/tslr_claims_csv.rb

Active Record's find_each cannot be ordered and the claims export must
be ordered.
The claim export is a temporary measure for private beta only so we
are not worried about the load on the service that switching to each
will incur as the number of cliams is limited.
Details about find_each in the Rails docs:
https://edgeguides.rubyonrails.org/active_record_querying.html#retrieving-multiple-objects-in-batches
I decided not to add a test as I wasn't sure creating a whole bunch of claims 
in the DB and slowing the test suite outweighed knowing that this tiny change is right.
Could I have done something smarter for a test? Thoughts/suggestions please?

Use each instead of find_each in claims export

---

CHANGELOG.md

- Fix claims export ordering
- Store claimants' names as separate fields
- Add ability to run data migrations
- Add data migration to back fill claimant's full name, middle name and surname
- Introduced rake tasks to export eligible schools to csv

🚢 Release 004

---

docs/release-process.md

*.visualstudio.com is deprecated, and some features only work from dev.azure.com URLs.

Prefer dev.azure.com URLs

---

app/views/static_pages/accessibility_statement.html.erb

Currently on an older version of JAWS and Windows 7 if you use a JAWS
shortcut it thinks you are in the school search input but you are not.
The text added is to explain to users how to sidestep this issue.

Add in text to assist JAWS users

---

azure-pipelines.yml

We already build all branches, so building PRs means double building.

Disable PR builds on Azure DevOps

---

CHANGELOG.md
app/models/claim.rb
config/locales/en.yml
spec/models/claim_spec.rb

The student_load_start_date is used in two contexts, when a user has
completed one course or has completed two or more courses. This should
be taken into account in the validation error message.
Used the locales file to provide two different validation errors.
Introduced question and validation_error keys to the
student_loan_start_date locale values which meant adjusting a few other
places those string are used.
The current value of student_loan_courses is used switch between them.
Updated an incorrect it block in claim_spec.rb.

Pluralize student_loan_start_date validation error

---

CHANGELOG.md
app/helpers/application_helper.rb
app/views/claims/student_loan_amount.html.erb
spec/features/changing_answers_spec.rb
spec/helpers/application_helper_spec.rb

Introduce a new `currency_value_for_number_field` helper that will take a number, convert it in to a currency value (with two decimal places) but not include a pound sign or commas, suitable for a number_field.

Format student loan amount to two decimal places

---

app/mailers/claim_mailer.rb
app/views/claim_mailer/approved.text.erb
app/views/claim_mailer/submitted.text.erb
spec/mailers/claim_mailer_spec.rb

Once a users claim is approved we need to be notify them via email.
There is additional work to actually approve a claim happening
elsewhere this commit adds the email and method to send it:
```ruby
ClaimMailer.approved(claim).delviver_later
```
## Mockup
https://miro.com/app/board/o9J_kxelVYI=/?moveToWidget=3074457346829288666

A user receives a notification when their claim is approved

---

app/views/static_pages/start_page.html.erb

The GOV.UK v3.0.0 start button requires an in-line svg to render the
chevron icon.

Add the icon to the start button

---

CHANGELOG.md
config/initializers/omniauth.rb
spec/support/omniauth.rb

Passing `path_prefix` as an option doesn't set it correctly, causing the failure path to have the "/admin" part missing. This means users who fail to authenticate themselves on DfE Sign In return to a 404 page.
By configuring OmniAuth's `path_prefix` we can ensure the correct failure path will be generated. We were (incorrectly) overriding this value in our spec helper, setting it globally means we don't have to do that any more.

Configure OmniAuth path_prefix so that failure path works

---

CHANGELOG.md
lib/restrict_admin_by_ip_middleware.rb
spec/lib/restrict_admin_by_ip_middleware_spec.rb

Currently the admin IP restriction middleware is broken on Azure because the requests arrive with a port number in tow, which results in `IPAddr::InvalidAddressError` being raised
(see https://rollbar.com/dxw/teachers-payment-service/items/84/occurrences/95116428392/).

Fix admin IP restriction bug caused by port numbers

---

CHANGELOG.md
azure/resource_groups/app/template.json
config/routes.rb
spec/requests/canonical_domain_redirect_spec.rb

This creates a new environment variable, called `CANONICAL_URL`, which is only set if we're using a hostname for that environment. If that variable is set in the app, then we have a rule in the routes that redirects us to the correct hostname, keeping the path and query string intact.
This should also help with #395

Stop old Azure URLs serving the site

---

CHANGELOG.md
app/views/claims/address.html.erb
app/views/claims/qts_year.html.erb
app/views/static_pages/accessibility_statement.html.erb

For 'Which academic year did you complete your initial teacher training?'
This question originally used a select field that was later replaced with a
set of radio buttons. Radio buttons should be marked-up with `<fieldset>`
and `<legend>` rather than a `<label>` so the html parser error is resolved.
For the address question:
- 'region' is not valid `autocomplete` value, use 'address-level-1' 
see below
- Town or city is the second most specific after County so is
'address-level-2'
See guidance:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#Values

Parsing no major html markup code errors

---

CHANGELOG.md
app/helpers/application_helper.rb
app/views/claims/address.html.erb
app/views/claims/bank_details.html.erb
app/views/claims/check_your_answers.html.erb
app/views/claims/claim_school.html.erb
app/views/claims/confirmation.html.erb
app/views/claims/current_school.html.erb
app/views/claims/eligibility_confirmed.html.erb
app/views/claims/email_address.html.erb
app/views/claims/gender.html.erb
app/views/claims/ineligible.html.erb
app/views/claims/information_provided.html.erb
app/views/claims/leadership_position.html.erb
app/views/claims/mostly_performed_leadership_duties.html.erb
app/views/claims/national_insurance_number.html.erb
app/views/claims/qts_year.html.erb
app/views/claims/still_teaching.html.erb
app/views/claims/student_loan.html.erb
app/views/claims/student_loan_amount.html.erb
app/views/claims/student_loan_country.html.erb
app/views/claims/student_loan_how_many_courses.html.erb
app/views/claims/student_loan_start_date.html.erb
app/views/claims/subjects_taught.html.erb
app/views/claims/teacher_reference_number.html.erb
spec/helpers/application_helper_spec.rb

This means a user using a screen reader will be immediately notified that an error is present

Prefix titles with an error when error present

---

CHANGELOG.md
app/views/claims/bank_details.html.erb
app/views/claims/national_insurance_number.html.erb

It is something that is unique to each person and is often used in identity theft. It looks like people can unknowingly submit 'autocompleted' data on malicious websites/websites that accidentally
use malicious npm packages: https://medium.com/@bramus/stealing-usernames-passwords-and-other-personal-data-via-browsers-and-npm-packages-30938725ebc8
However by turning it off, we'll be breaking this WCAG 2.1 criteria: https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html
Some more detail: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
Also: https://www.owasp.org/index.php/Top_10_2013-A6-Sensitive_Data_Exposure

Turn off autocomplete on sensitive inputs

---

CHANGELOG.md
app/controllers/admin/base_admin_controller.rb
app/controllers/admin/claim_approvals_controller.rb
app/controllers/admin/claims_controller.rb
app/helpers/admin/claims_helper.rb
app/models/claim.rb
app/views/admin/claims/_answer_section.html.erb
app/views/admin/claims/index.html.erb
app/views/admin/claims/show.html.erb
app/views/admin/page/index.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20190905140712_add_approved_at_to_claim.rb
db/migrate/20190906082123_add_approved_by_to_claim.rb
db/schema.rb
spec/factories/claims.rb
spec/features/admin_claim_approve_spec.rb
spec/helpers/admin/claims_helper_spec.rb
spec/models/claim_spec.rb
spec/requests/admin_claim_approvals_spec.rb
spec/requests/admin_claims_spec.rb

This is an MVP to allow logged in service operator can mark a claim as 'approved'. Users can view all claims awaiting approval, click a link to view the relevant information to allow a claim to be reviewed, and then click a button to approve.

A service operator is able to mark a claim as approved

---

CHANGELOG.md
app/assets/stylesheets/components/gds_kit_tweaks.scss

Dyslexic user couldn't see the hint text. I've changed the colour to be
AAA accessible for the font size.

Increase contrast on hint text

---

CHANGELOG.md
lib/restrict_admin_by_ip_middleware.rb
spec/lib/restrict_admin_by_ip_middleware_spec.rb

I noticed this when testing `/admin` locally, my IP address is `::1` which is the IPv6 equivalent for local host.
I'm not sure if IPv6 addresses can come through with ports attached, but this should fix it for the majority of cases anyway.

Fix RestrictAdminByIpMiddleware allowing IPv6 addresses

---

bin/swap-slots

This fixes tmp resource group slot swapping.

Derive app service names after modifying the resource group name when swapping slots

---

azure/resource_groups/app/parameters/development.template.json
azure/resource_groups/app/parameters/production.template.json
azure/resource_groups/app/template.json

During key rotation on the VSP the secondary key is the new,
incoming key and once the old cert is removed at the GOV.UK Verify hub
the new key becomes the primary.
Have a empty string as the secondary key in the template files to make
this explicit.

Add empty secondary VSP encryption key parameter

---

config/initializers/application_insights.rb
lib/application_insights/enhance_request_data_with_client_ip.rb
lib/application_insights/enhance_track_request_with_client_ip.rb
spec/requests/application_insights_spec.rb

The request IP gets sent to Application Insights, but not stored. This monkey patches the [Application Insights gem](https://github.com/microsoft/ApplicationInsights-Ruby) to add the request IP to the payload inside a custom properties hash, which allows us to store and query against IP addresses.

Log IP addresses in Application Insights

---

CHANGELOG.md
app/helpers/admin/claims_helper.rb
spec/helpers/admin/claims_helper_spec.rb

If there is any doubt about where a teacher says they have worked and the data Hartlink has about them, this will help approvers quickly check GIAS to see if (for example) the school they work at is part of a Multi-Academy Trust and payroll is handled by a different school within the trust.

Link schools to Get Information About Schools

---

CHANGELOG.md
app/helpers/admin/claims_helper.rb
app/views/admin/claims/show.html.erb
spec/helpers/admin/claims_helper_spec.rb

This should make it easier for an approver to see all the information they need to approve a claim without having to download the CSV

Add student loan plan and amount to approver view

---

CHANGELOG.md
app/assets/javascripts/components/school_search.js.erb
app/controllers/claims_controller.rb
app/controllers/school_search_controller.rb
app/models/school.rb
app/models/student_loans/eligibility.rb
app/views/claims/_ineligibility_reason_current_school_closed.html.erb
app/views/claims/_school_search.html.erb
app/views/claims/claim_school.html.erb
app/views/claims/current_school.html.erb
app/views/claims/still_teaching.html.erb
app/views/school_search/create.json.jbuilder
spec/features/current_school_with_closed_claim_school_spec.rb
spec/features/ineligible_tslr_claims_spec.rb
spec/features/school_search_spec.rb
spec/fixtures/local_authorities.yml
spec/fixtures/schools.yml
spec/models/student_loans/eligibility_spec.rb
spec/requests/school_search_spec.rb
spec/support/feature_helpers.rb

This does 3 things:
- Excludes closed schools from the current school search
- Removes the option to pick the claim school as the current school if it's closed
- Adds an ineligibility screen for if a user somehow selects a closed school as their current school (e.g. by manually setting query parameters)

Make it so current school doesn't support closed schools

---

CHANGELOG.md
azure/templates/app.json

There's a conflict in our deploy resulting from a "copy loop that is set to parallel". Changing it to 'Serial' should resolve it.
Thread: https://ukgovernmentdfe.slack.com/archives/CKYNU0VG9/p1568723738001400

Fix parallel copy loops

---

CHANGELOG.md
app/models/claim.rb
db/data/20190829135327_backfill_first_middle_surnames.rb
db/migrate/20190918142241_drop_redundant_full_name_column_from_claims.rb
db/schema.rb
spec/models/claim_spec.rb

We split the claimants' names out to separate fields in Release 004,
making this field now redundant.
This also updates the data migration that performed the backfill so that
it won't error if it is run in future by a new developer joining the
team. There is probably an argument for simply deleting the data
migration, but given it's the only one we have it at the moment it might
be useful to keep it around to serve as a reference for future adding
future data migrations.

Drop redundant full_names column from claims

---

CHANGELOG.md
app/helpers/admin/claims_helper.rb
app/models/school.rb
app/models/school_data_importer.rb
db/migrate/20190917100131_add_establishment_number_to_schools.rb
db/schema.rb
spec/helpers/admin/claims_helper_spec.rb
spec/models/school_spec.rb
spec/services/school_data_importer_spec.rb

This adds a new column to schools to store the DfE number in the database (which is fetched when the nightly import runs), and show the DfE number in brackets against both the claim and the current school, to make it easier when checking a school against a record in Hartlink.

A service operator can easily check employment details in Hartlink

---

CHANGELOG.md
app/helpers/admin/claims_helper.rb
config/locales/en.yml
spec/helpers/admin/claims_helper_spec.rb

During a claim checking session we noticed that we were checking date of birth before national insurance number so it made sense to show that first. We also noticed that the date format in DQT and TPS is DD/MM/YYYY and claim checking could be eased by displaying the DOB in the same format.

Changes to the claim data shown to service operators

---

CHANGELOG.md
app/models/claim.rb
app/views/admin/claims/index.html.erb
app/views/admin/page/index.html.erb
spec/features/admin_claim_approve_spec.rb

This shows a service operator at a glance how many claims are awaiting approval, meaning they don't have to download a CSV and count rows in order to keep tabs on how many people have applied

Show how many claims are awaiting approval

---

lib/tasks/default.rake

When installed, Rspec removes the 'test' task from the default rake task
and replaces it with it's own 'spec' task.
Clear default task prerequisites ('spec') and then specify our own tasks
to get the expected order instead of the spec task always first.
Run the style checks first so we do not have to wait for the specs to
run only to find a small style error.

Run default rake task in the order specified

---

spec/features/timeout_spec.rb
spec/rails_helper.rb
spec/spec_helper.rb

We've been running tests in the order they're defined in. This could potentially cause some issues where tests defined further down could rely invisibly on some state that gets defined before that test gets run. This sets the order to random, so every time the test suite gets run, the tests are run in a different order each time.

Order tests randomly

---

.gitignore
spec/spec_helper.rb

During the refactor work I found myself reaching for this command several times. It's useful when working through a number of failures in batches.
The command is `rspec --only-failures` and can be re-ran several times while fixing specs until there aren't from the original failures left.

Allow retrying RSpec failures

---

CHANGELOG.md
app/views/static_pages/privacy_notice.html.erb

We are now sending the client IP address to Application Insights so we state that in the notice.

Update privacy notice to include IP address

---

README.md
spec/factories/schools.rb

There was a [failed build](https://dfe-ssp.visualstudio.com/S118-Teacher-Payments-Service/_build/results?buildId=22918) where a factory tried to create a local authority district with a "code" that was already in the database. Instead of sampling from the list of eligible codes, we can use the fixtures that we create specifically for eligible and ineligible local authorities and districts.

Fix spec flakiness related to clashing identifiers

---

azure/resource_groups/ProjectCore/parameters/development.json
azure/resource_groups/ProjectCore/parameters/production.json
azure/resource_groups/ProjectCore/template.json
bin/azure-deploy

At the moment we're not using the virtual network for anything, however we intend to use it for either protecting resources with a firewall or splitting out worker processes (both require our own virtual network)
Virtual networks are [free of charge](https://azure.microsoft.com/en-us/pricing/details/virtual-network/).
We add the virtual network first as we expect to rely on these in the later resource group deployments.

Add Virtual Network to ProjectCore resource group

---

CHANGELOG.md

Coming back on the project, I thought it'd be a good idea to review the changelog to see what's happened, but the last two links to compare the released tags were broken due to a lack of leading zeroes. This fixes it.

Fix changelog references

---

CHANGELOG.md
config/locales/en.yml

We only care about the courses they took a loan out for, and we use it calculate the plan they're on, and we have seen that users are confused by this question.

Reword the how many courses question

---

CHANGELOG.md
app/views/static_pages/accessibility_statement.html.erb

As we have upgraded accessible autocomplete, it now appears to be AA
compliant on latest OS / IE / JAWS versions. Added in text saying we
think we are AA compliant and we haven't been externally tested to
confirm this.

Changes to accessibility statement

---

CHANGELOG.md
app/assets/javascripts/components/timeout_dialog.js.erb
config/initializers/assets.rb
config/routes.rb
spec/routes/routes_spec.rb

In preparation for adding another policy (Maths & Physics) we need to have different URLs for each one. 
- Include the policy name as a parameter available the controller
- Only allow valid policies in the URL
- Include URL helpers in the asset pipeline as calling them statically from assets doesn't set the correct defaults

Rework URL structure in preparation for Maths & Physics policy

---

CHANGELOG.md
app/controllers/application_controller.rb
app/controllers/claims_controller.rb
app/views/claims/qts_year.html.erb
app/views/static_pages/start_page.html.erb
config/routes.rb
spec/features/changing_answers_spec.rb
spec/features/current_school_with_closed_claim_school_spec.rb
spec/features/govuk_verify_spec.rb
spec/features/ineligible_tslr_claims_spec.rb
spec/features/missing_verify_information_spec.rb
spec/features/school_search_spec.rb
spec/features/student_loans_claim_spec.rb
spec/rails_helper.rb
spec/requests/claims_spec.rb
spec/requests/timeout_spec.rb
spec/requests/verify_authentications_spec.rb
spec/support/feature_helpers.rb
spec/support/request_helpers.rb

This updates the first page of the claim to be a `new` action, rather than a `create` action, which then starts the claim process. This means that the start of the journey will be able to be linked to from a GOV.UK start page. 
The bulk of the lines of code in this PR are test changes, I've endeavoured to tidy up the tests a bit by adding a Request helper that means we're not always repeating ourselves when we're POSTing to create a Claim. This will also make things easier to change if / when we change the journey in any way.

Prepare for an external start page

---

CHANGELOG.md

- Update the first page of the claim to initialise, rather than create a claim
- Rework URL structure in preparation for Maths & Physics policy
- Changes to accessibility statement as we think we now meet AA standard

Release 015

---

CHANGELOG.md
app/models/student_loans/eligibility.rb
app/views/claims/student_loan_amount.html.erb
spec/models/student_loans/eligibility_spec.rb

This makes sure a claimant can't submit £0 for their student loan payment by updating the validations, and also changing to minimum amount that can be entered in the number field to `1`. Again, £1 might not be a realistic amount, but it's easier to deal with than £0!

Make sure claimants cannot make a claim for £0

---

bin/launch-vsp

Sometimes when spinning up the VSP locally, I get an error because a previous VSP process hasn't exited properly, which means I have to search around to find what port it's running on, then Google the incantation to find out the PID number using a specific port, which eats up a bunch of time. This does the checking for me before spinning up the VSP, and then kills the process if it's found, before spinning up the VSP

Cleanup any stale VSP processes when starting the service in dev

---

app/controllers/claims_controller.rb
app/models/page_sequence.rb
config/routes.rb
spec/models/page_sequence_spec.rb
spec/requests/claims_spec.rb

This does a couple of things.
Firstly it reworks the URLS to be a bit friendlier to the user:
- `#new` becomes `/student-loans/claim` instead of `/student-loans/new?slug=qts-year`
- `#create` becomes `/student-loans/claim` instead of `/student-loans?slug=qts-year`
Secondly it adds some code to handle the scenario where a user visits `#new` with an already in-progress claim. This was resulting in exceptions being raised.

Tweak URL paths for new/create and refine handling of return visitors

---

CHANGELOG.md
app/controllers/admin/claim_checks_controller.rb
app/controllers/admin/claims_controller.rb
app/mailers/claim_mailer.rb
app/models/check.rb
app/models/claim.rb
app/views/admin/claims/index.html.erb
app/views/admin/claims/show.html.erb
app/views/admin/page/index.html.erb
app/views/claim_mailer/rejected.text.erb
spec/features/admin_claim_approve_spec.rb
spec/features/admin_claim_reject_spec.rb
spec/mailers/claim_mailer_spec.rb
spec/models/claim_spec.rb
spec/requests/admin_claim_checks_spec.rb

This PR introduces the concept of _rejecting_ a claim. The goal was to do the smallest possible work to achieve that without trying to guess at what the process around claim rejection will look like.
We know claims will have to be rejected so we are confident of that, we do not know what the claims checking process looks like around rejections so want to keep the code as flexible as possible.
There were three steps:
1. change the words on the UI so it is clear we are not just approving claims, rather checking them
2. allow a `Check` to have a result of `rejected`
3. send a notification to the user
Some obvious omissions we know about are:
- the UI has had no thought as this is a seperate piece of work – I wonder if we should show the reject button at all?
- no record of why a claim is …

A service operator can reject a claim

---

app/controllers/claims_controller.rb
app/views/claims/eligibility_confirmed.html.erb

This is a slight enhancement that has been included in a couple of recently closed PRs, it would be good to get it in.
To make the journey more robust and open to changes we can make `next_slug` a helper method and use it in any directly linked paths.

Use next_slug on eligibility confirmed screen

---

CHANGELOG.md

- A service operator can reject a claim and an email is sent to the
claimant
- Make sure claimants cannot make a claim of £0

Release 016

---

CHANGELOG.md
app/assets/stylesheets/components/flash.scss
app/controllers/admin/claim_checks_controller.rb
app/models/claim.rb
app/views/admin/claims/show.html.erb
config/locales/en.yml
spec/features/admin_claim_approve_spec.rb
spec/models/claim_spec.rb
spec/requests/admin_claim_checks_spec.rb

Claims that don't have a payroll gender cannot be approved because our payroll provider (and HMRC) have gender as a required field. It is possible for users to submit a claim and answer "I don't know" to the question we ask about payroll gender.
We need to prevent admins from being able to approve these claims and flag it to them as something to investigate.
There's no official pattern for [alerts in the Design System yet](https://github.com/alphagov/govuk-design-system-backlog/issues/2), so I decided to reuse the informative banner style we use for flash messages for now. @titlescreen may have opinions on it?
I've also included some warning text next to the disabled button to remind the user why they can't approve it.
Also includes a fix for the time formatting

A service operator can see if a claim is missing a payroll gender

---

app/controllers/application_controller.rb
app/controllers/claims_controller.rb
app/controllers/concerns/part_of_claim_journey.rb
app/controllers/verify/authentications_controller.rb

Rather than defining claim-specific methods in the base controller and having them present in all controllers of the application, we only include them in the places where a current claim is expected and being worked with.
This is part of the work to prepare us for introducing Maths & Physics by reducing the places in the codebase where a specific policy is referenced, i.e. in this case the `StudentoLoans::Eligibility`. In the context of `ClaimsController` we will know the policy because of the `:policy` param we get as part of the routing, which means we'll be able to modify the method to set an appropriate eligibility based on the param.
The only other place where the `current_claim` is checked and modified is the `Verify::AuthenticationsController`. This doesn't have routing scoped by a …

Scope current claim methods to specific controllers

---

CHANGELOG.md
app/assets/stylesheets/components/navigation.scss
app/controllers/admin/auth_controller.rb
app/controllers/admin/base_admin_controller.rb
app/views/admin/claims/index.html.erb
app/views/layouts/admin.html.erb
config/routes.rb
spec/features/admin_access_spec.rb
spec/features/admin_claim_approve_spec.rb
spec/features/admin_claim_reject_spec.rb
spec/features/admin_csv_download_spec.rb
spec/features/admin_sessions_spec.rb
spec/requests/admin_spec.rb

This set the foundation for navigation within the /admin side of the
service. Admin views will now use a bespoke admin layout which keeps
the familiar look and feel of the user facing side with some tweaks
- admin side now has its own layout
- beta banner is removed as its not really relevant header
- parent service name has been used as the admin side will support more
than student student
- Existing links have been refactored to use the new navigation bar
- claims page has a back link

Admin uses its own layout with with updated navigation

---

app/controllers/admin/auth_controller.rb
app/views/admin/claims/show.html.erb
app/views/admin/page/index.html.erb
app/views/layouts/admin.html.erb
spec/features/admin_claim_approve_spec.rb
spec/features/admin_claim_reject_spec.rb
spec/features/admin_sessions_spec.rb
spec/requests/admin_spec.rb

Some tidying up in admin:
- add "Payroll" as a top-level navigation link
- remove redundant/duplicate navigation links from the root page
- add a "Back" link on `admin/claims#show`
No need for additional Changelog items as the most of this could fall under existing unreleased Changelog items.
The admin root now looks like this:

Admin navigation tweaks

---

CHANGELOG.md
README.md
app/controllers/static_pages_controller.rb
app/views/static_pages/maintenance.html.erb
azure/resource_groups/app/parameters/development.template.json
azure/resource_groups/app/parameters/production.template.json
azure/resource_groups/app/template.json
bin/set-maintenance-mode
config/initializers/maintenance_mode.rb
config/routes.rb
spec/requests/maintenance_mode_spec.rb
spec/routes/routes_spec.rb

This allows the service to be put into maintenance mode by setting an environment variable. Based on [prior art from the Schools Experience team](https://github.com/DFE-Digital/schools-experience/pull/987)

Allow service to be put into maintenance mode

---

CHANGELOG.md
config/routes.rb
spec/requests/maintenance_mode_spec.rb

Whilst we want to be able to put the service into maintenance mode and prevent users from making claims during scheduled maintenance, or when the service is taken offline outside of the claim window, we still need service operators to be able to access the back-office for the service so they can continue to check claims and provide support to existing claimants.

Exclude /admin from maintenance mode

---

CHANGELOG.md
bin/docker-entrypoint

We've been noticing some ConcurrentMigration errors in our logs since our first deploy that included some proper data migrations. We think this may be because we're running data and schema migrations separately and they're taking a while to complete.

Use db:migrate:with_data to run schema and data migrations

---

bin/request-vsp-certs

The script we use to generate the VSP certificate signing request should
include the group email address.
It would also be helpful if they were put in a directory that is git ignored so 
developers like myself do not accidentally commit them!

Add email address to request certs script

---

azure/resource_groups/app/parameters/development.template.json

This is the first PR to update the intergrtaion (development) certificates for Verify.
We update the signing key and we run two versions of the encryption key until verify have removed the old one. At that point there will be another PR to make the new key into the primary key and remove the old one.
#469 can also be merged once we have confirmed that these new keys are working correctly in the development environment.
v3 was the key that we were never notified of due to a typo in the email address used.
v4-5 were not used as I was updating the script (#469) to include the email address and needed a way to test the generation of the CSRs.

Bump Verify signing and encryption keys to 6

---

CHANGELOG.md

- Run schema and data migrations at the same time
- Exclude /admin from maintenance mode
- Allow service to be put into maintenance mode

Release 018

---

CHANGELOG.md
app/models/payroll/claim_csv_row.rb
spec/models/payroll/claim_csv_row_spec.rb

The start and end dates in the payroll export is the fictional period a
claimant was employed in order for DfE to pay them.
We did not want the start date to be before the 6th of a given month as
the tax year runs from the 6 April until the 5 May the following year.
By setting the start date to the second Monday in the month and the end
date to the following Sunday, we avoid this issue.
I debated with myself about the spec for this for ages and ended up deciding 
I wanted a context to show what is being tested is the day of the 1st of the 
current month as that has the most impact on the code working correctly 
and wasn't really shown without consulting a calendar – appreciate thoughts 
on that.

Change the payroll start and end dates

---

CHANGELOG.md
app/assets/stylesheets/components/tag.scss
app/controllers/admin/claims_controller.rb
app/helpers/admin/claims_helper.rb
app/models/claim.rb
app/views/admin/claims/index.html.erb
app/views/admin/page/index.html.erb
config/locales/en.yml
spec/features/admin_stats_spec.rb
spec/helpers/admin/claims_helper_spec.rb

We tell users they will hear back on the outcome of their claim "within 6 weeks". To help Service Operators ensure they check claims within the 6 weeks, they should be able to easily see when a claim is nearing the end of this period, and when it has passed it.

Service operators can easily identify claims that are close to their deadline

---

azure/resource_groups/app/parameters/development.template.json

We have let Verify know that we are running both old and new encryption keys and they have confirmed so the this step is to remove the reference to the old one and set the new one as the primary.

Remove old VSP encryption key

---

azure/resource_groups/app/parameters/development.template.json

We've had confirmation from the Verify team that the old encryption key has been removed so we can safely remove it from the configuration now.
This completes the VSP key rotation.
Once this PR is merge we _must_ confrim the development enviroment is able to comple the Verify step.

Remove VSP encryption cert v2

---

config/application.rb

I noticed when testing adding notes to claim checking that we're displaying times using the Rails default time zone (UTC).
By setting the time zone to "London" all times will be shown in local time but still stored in UTC.

Set application time zone to London

---

app/assets/stylesheets/components/navigation.scss

The padding and hover styles were on `li` element causing incorrect user feedback when a user hovered over the `li`.
Combining both these styles on to the anchor tag makes the hover style appear in the correct way.

Small fix for admin navigation padding

---

CHANGELOG.md
app/controllers/admin/claims_controller.rb
app/views/admin/claims/search.html.erb
app/views/layouts/admin.html.erb
config/routes.rb
spec/features/admin_search_spec.rb
spec/requests/admin_claims_spec.rb

This allows a service operator to search for a claim by its reference. If a claim is found, it redirects to the relevant claim, otherwise the user gets an error. UI is very basic, so may need some @titlescreen ❤️

Allow users to search for a claim by reference

---

CHANGELOG.md

- The Payment Confirmation Report for a payroll run can be uploaded and
processed
- Update student loan question to latest version
- Allow service operators to search for a claim
- No longer ask for specific year for QTS award year
(In e0172ee I accidentally added the Payment Confirmation Report to the
Release 021 section of the CHANGELOG. That was a lie which I fix here.)

Release 022

---

app/controllers/claims_controller.rb
app/models/page_sequence.rb
app/models/student_loans/slug_sequence.rb
config/routes.rb
spec/models/page_sequence_spec.rb
spec/models/student_loans/slug_sequence_spec.rb
spec/requests/claims_spec.rb

This work makes `PageSequence` policy-agnostic by allowing the policy-specific slug sequence to be passed in, paving the way for the introduction of the Maths & Physics policy.

Prepare PageSequence for Maths & Physics

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/a11y_dialog.scss
app/assets/stylesheets/components/accessible_autocomplete_tweaks.scss
app/assets/stylesheets/components/cookie_banner.scss
app/assets/stylesheets/components/currency_input.scss
app/assets/stylesheets/components/flash.scss
app/assets/stylesheets/components/tag.scss
config/initializers/assets.rb
package.json
yarn.lock

Loading the GOVUK Frontend styles, js and assets from a gem worked great until
it didn't when an update to sprockets broke it.
Althought the gem is fixed, as the GOVUK Frontend is distrubuted as a npm
package it makes more sense to load it from there and keep the dependency
tighter.
This commit removes the gem and makes the changes to load the assets from the
npm package in node_modules.
I propose this as a replacement to #549 which I've closed.

Load GOVUK Frontend from npm package

---

CHANGELOG.md
app/models/school.rb
app/models/student_loans/eligibility.rb
app/models/student_loans/school_eligibility.rb
app/views/claims/_ineligibility_reason_current_school_closed.html.erb
app/views/claims/_ineligibility_reason_ineligible_current_school.html.erb
app/views/claims/ineligible.html.erb
spec/features/ineligible_tslr_claims_spec.rb
spec/fixtures/schools.yml
spec/models/student_loans/eligibility_spec.rb
spec/models/student_loans/school_eligibility_spec.rb

Inform the user that their claim is ineligible, if the school that they are currently employed at is not eligible.
This is the message informing the user that their claim is ineligible:

Claim is ineligible if current school is ineligible

---

app/views/claim_mailer/payment_confirmation.text.erb
spec/mailers/claim_mailer_spec.rb

These are the final payment confirmation email tweaks from Faye, as well as adding a link to a feedback survey (to be removed once we start making public beta payments)

Payment email tweaks

---

CHANGELOG.md
app/helpers/application_helper.rb
app/mailers/claim_mailer.rb
app/views/claim_mailer/approved.text.erb
app/views/claim_mailer/payment_confirmation.text.erb
app/views/claim_mailer/rejected.text.erb
app/views/claim_mailer/submitted.text.erb
app/views/claims/verified.html.erb
app/views/layouts/application.html.erb
app/views/static_pages/accessibility_statement.html.erb
app/views/static_pages/contact_us.html.erb
app/views/static_pages/cookies.html.erb
app/views/static_pages/maintenance.html.erb
app/views/static_pages/privacy_notice.html.erb
app/views/static_pages/start_page.html.erb
app/views/static_pages/terms_conditions.html.erb
config/locales/en.yml
config/routes.rb
spec/helpers/application_helper_spec.rb

This moves the static pages found in the footer (e.g. "Contact us", "Privacy notice", etc) from the root of the domain to be namespaced under a policy. So `/contact-us` now lives at `/student-loans/contact-us`. This means that these pages can now be made policy-aware, and display appropriate titles and support email addresses, based on the routing.
This continues the work to prepare the way for introducing the Maths & Physics policy to the service.

Make static content policy aware

---

Gemfile
Gemfile.lock
azure/resource_groups/app/parameters/development.template.json
azure/resource_groups/app/parameters/production.template.json
azure/resource_groups/app/template.json
db/data/20191029113201_backfill_note_on_already_checked_claims.rb
spec/db/data/backfill_note_on_already_checked_claims_spec.rb

This adds a data migration to backfill notes on claims that have already been checked. To get around the possibility of adding personal/sensitive data to the repo, the notes are stored as an envrionment variable in CSV format in the Azure keyvault. 
**This variable will have to be set before the development/production deploy happens**
Once the data migration has happened, we can remove the environment variable.

Backfill note on claims that have already been checked

---

CHANGELOG.md

- Updated feedback URL ready for public beta
- Service updated to be linked to from external start page
- Update the Verify Service Provider to version 2.1.0
- Make static pages such as "Cookies", and "Contact us" policy aware

Release 024

---

azure/resource_groups/app/parameters/production.template.json

I've turned maintenance mode off in production temporarily, but this makes the change permanent (or at least until we decide to enable it agai). This will take effect on the next production deploy.

Unset maintenance mode in production

---

CHANGELOG.md
app/controllers/claims_controller.rb
spec/features/ineligible_tslr_claims_spec.rb
spec/requests/claims_spec.rb

If the user submits answers that make their claim ineligible, we want
them to still be able to start a new claim.
This is fixing a regression, that was introduced when we removed our
temporary start page, which performed a POST to the first question.
As a future piece of work, we should also consider allowing the user to go
back to the answer that caused their claim to become ineligible, instead
of having to restart their claim.

Allow user to restart claim by visiting start page

---

app/views/claims/_ineligibility_reason_employed_at_no_school.html.erb
app/views/claims/_ineligibility_reason_ineligible_claim_school.html.erb
app/views/claims/_ineligibility_reason_ineligible_current_school.html.erb
app/views/claims/_ineligibility_reason_ineligible_qts_award_year.html.erb
app/views/claims/_ineligibility_reason_not_taught_eligible_subjects.html.erb
app/views/claims/_ineligibility_reason_not_taught_enough.html.erb
app/views/claims/_school_search.html.erb
app/views/claims/ineligible.html.erb
spec/features/ineligible_tslr_claims_spec.rb
spec/features/subjects_taught_spec.rb

This adds the copy added by Faye to the school search page and the relevant ineligibility pages. Here's how they look:

Adjust content on the school claim screen to help users who worked in multiple schools

---

CHANGELOG.md
app/assets/stylesheets/components/flash.scss
app/controllers/admin/claim_checks_controller.rb
app/controllers/admin/claims_controller.rb
app/helpers/admin/claims_helper.rb
app/models/claim/matching_attribute_finder.rb
app/views/admin/claims/show.html.erb
spec/features/admin_duplicate_claims_spec.rb
spec/helpers/admin/claims_helper_spec.rb
spec/models/claim/matching_attribute_finder_spec.rb
spec/requests/admin_claims_spec.rb

This is the first step for the work to prevent people being paid more than once. 
We think that checking for matching details in claims and what to do about it falls to the the service operators, therefore we want to get claims with matching attributes in-front of them as soon as we can.
This first step simply checks all other submitted claims for matching details and flags the claims up to the service operator.
It lets them see the other claims and links to them for comparison. We want to do more work around the UI for comparing claims later, with help from the service operators.
We also want to check for matches across combination of details, but this will also come later.
As the service does not distiguish between tax years, nor do the checks.
We know this operation is quite expensive …

Service operators can see when details in a claim have been used before

---

README.md

The root redirects to the GOV.UK start page, which isn't too helpful for
a new dev who wants to play around.

Update README to give to a more useful first page

---

docs/release-process.md

When I first followed the release instructions, it wasn't obvious that I
wanted the master commit; I thought there would be a build for the tag.

Clarify instructions re selecting build to release

---

app/assets/javascripts/components/timeout_dialog.js.erb
app/controllers/application_controller.rb
app/controllers/claims_controller.rb
app/controllers/concerns/part_of_claim_journey.rb
app/controllers/sessions_controller.rb
app/models/claim.rb
app/models/payroll/claim_csv_row.rb
app/models/student_loans.rb
app/views/application/_timeout_dialog.html.erb
app/views/claims/ineligible.html.erb
app/views/claims/verified.html.erb
app/views/layouts/admin.html.erb
app/views/layouts/application.html.erb
app/views/static_pages/accessibility_statement.html.erb
app/views/static_pages/contact_us.html.erb
app/views/static_pages/cookies.html.erb
app/views/static_pages/maintenance.html.erb
app/views/static_pages/privacy_notice.html.erb
app/views/static_pages/terms_conditions.html.erb
config/routes.rb
spec/features/admin_timeout_spec.rb
spec/features/timeout_spec.rb
spec/models/claim_spec.rb
spec/requests/claims_spec.rb
spec/requests/sessions_spec.rb

This PR is part of the work to prepare for introducing the Maths & Physics policy. It focuses on updating the timeout-related code such that it isn't coupled to the routing for the Student Loans policy.
There were two routes that were hardcoded in the timeout JavaScript:
- `claim_refresh_session_path`, which translated to `"/student-loans/refresh-session"`
- `timeout_claim_path`, which translated to `"/student-loans/timeout"`
The session refresh routing is dealt with by moving the action so it no longer sits under the policy namespace. This makes sense, as refreshing the session will be the same regardless of the policy, and is also used for admin sessions.
The timeout redirection path is dealt with by making the path for redirection configurable by setting it in the DOM, rather than …

Make timeout code policy-agnostic

---

CHANGELOG.md
app/views/layouts/admin.html.erb
app/views/layouts/application.html.erb

Following the guidance onthe service-manual[1], we tell search engines
not to index pages on the service so that users will always start their
journey on our start pages.
https://www.gov.uk/service-manual/technology/get-a-domain-name#ensure-users-start-their-journey-on-govuk

Prevent search engines from indexing the service

---

CHANGELOG.md
app/controllers/admin/base_admin_controller.rb
app/controllers/application_controller.rb
app/views/layouts/application.html.erb
spec/features/admin_timeout_spec.rb
spec/requests/admin_timeout_spec.rb

This mostly organises the code for admin sessions and public-facing user sessions such that they are entirely separate, the exception being the update_last_seen_at method, which updates the timestamp for the user regardless of the type of user they are.
A test was deleted as part of this mostly because it was a mostly false requirement - we do not expect admin users to be visiting the public-facing site, and if they do, it's not a major issue that their sign-in session will get extended because of it.

Re-organise session handling code to separate claim session code from admin session code

---

CHANGELOG.md
app/models/claim/matching_attribute_finder.rb
spec/models/claim/matching_attribute_finder_spec.rb

It might be that we have stored building_society_roll_numbers that are blank strings. Those should not be flagged as matches.

Don't match blank building society roll numbers

---

CHANGELOG.md

- Fixed bug in claim matcher code that would match blank building society roll numbers
- Admin users are sent to the sign in page when their session times out
- Add noindex and nofollow directives to prevent search engines indexing pages

Release 027

---

app/controllers/application_controller.rb
app/controllers/base_public_controller.rb
app/controllers/claims_controller.rb
app/controllers/school_search_controller.rb
app/controllers/static_pages_controller.rb
app/controllers/submissions_controller.rb
app/controllers/verify/authentications_controller.rb
spec/features/timeout_spec.rb
spec/requests/timeout_spec.rb

This creates a clearer separation between the controller code for the public-facing part of the application and the admin part, as requested in https://github.com/DFE-Digital/dfe-teachers-payment-service/pull/579.

Extract a BasePublicController to mirror admin

---

CHANGELOG.md
app/models/claim/matching_attribute_finder.rb
spec/models/claim/matching_attribute_finder_spec.rb

For example, a claim with a National Insurance number that differs only
in capitalisation should be considered a match.

Ignore case when checking for matching attributes

---

CHANGELOG.md
app/models/claim.rb
spec/models/claim_spec.rb

Now that we're performing case-insensitive comparisons when detecting
matching claims, this is no longer strictly necessary. It does however
seem like good data hygiene, and something that we should have done when
we first wrote the normalisation.
There will also be a data migration to upcase the existing NI numbers,
but this will be deployed in a subsequent release, to ensure that,
before we run the data migration, all of the running web servers are
already using this new normalisation. Since we have zero-downtime
deploys, we cannot make this guarantee if we deploy the new code and the
data migration simultaneously.

Upcase when normalising National Insurance number

---

CHANGELOG.md

- Always save claimant's National Insurance number in upper case
- When checking whether a claim's details have been used in other claims, ignore
the case (i.e. capitalisation) of the claims' details

Release 028

---

app/views/claims/_school_search.html.erb
app/views/claims/_school_search_results.html.erb
app/views/claims/claim_school.html.erb
app/views/claims/current_school.html.erb

The diff for this PR isn't very helpful as we included a small refactor to untangle things slightly.
The diff for the fix can be seen in 93578335ef27fc2cbe86d659dcc1350fc17a7528
We're not sure what's causing the error to happen, some combination of headless chrome not liking the `<p class="govuk-body">` tag wrapping the hint. Changing the paragraph's class to anything else fixes the error. Adding a sleep before the failing expectation also fixes the error.
We felt that this solution was smallest change that we could get to pass consistently.
We had concerns about the way that screen readers might read the two span tags that are back to back, but we checked it in VoiceOver and it made sense.

Fix flakey current school search spec

---

CHANGELOG.md
app/views/submissions/show.html.erb

Follows the confirmation page pattern on the Design System. Faye has approved the text.
https://design-system.service.gov.uk/patterns/confirmation-pages

Add a link to our service's Done page in Whitehall

---

CHANGELOG.md
app/controllers/admin/claims_controller.rb

We exploit the fact that all claim references are upper case, by
searching for the upcased search text. This lets us continue using the
existing database index.

Make admin claim search case insensitive

---

CHANGELOG.md
app/helpers/claims_helper.rb
app/models/student_loans/eligibility.rb
app/models/student_loans/slug_sequence.rb
app/views/claims/_ineligibility_reason_generic.erb
app/views/claims/_ineligibility_reason_ineligible_claim_school.html.erb
app/views/claims/_ineligibility_reason_no_more_schools.erb
app/views/claims/_ineligibility_reason_not_taught_eligible_subjects.html.erb
app/views/claims/_school_search.html.erb
app/views/claims/claim_school.html.erb
app/views/claims/ineligible.html.erb
app/views/claims/subjects_taught.html.erb
config/locales/en.yml
spec/features/changing_answers_spec.rb
spec/features/current_school_with_closed_claim_school_spec.rb
spec/features/govuk_verify_spec.rb
spec/features/ineligible_tslr_claims_spec.rb
spec/features/missing_verify_information_spec.rb
spec/features/multiple_claim_schools_spec.rb
spec/features/school_search_spec.rb
spec/features/student_loans_claim_spec.rb
spec/features/subjects_taught_spec.rb
spec/helpers/claims_helper_spec.rb
spec/models/student_loans/eligibility_spec.rb
spec/support/feature_helpers.rb

This implements the new multiple schools journey. Now if a teacher did not teach at an eligible school, they are given the opportunity to try again with another school that they may have taught at in the same period. We also change the flow so they are asked if they taught eligibile subjects relative to the school they taught in, if they didn't they are given the opportunity to choose another school where they may have taught eligible subjects.

Implement the new multiple schools journey

---

README.md
app/models/student_loans.rb

At the moment, in development, when a dev goes to `http://localhost:3000`, or a claim times out, they're redirected to the GOV.UK start page, which is disorienting. This redirects the user to the start of the claim journey if we're in development.

Redirect to start of claim journey in development

---

CHANGELOG.md
app/mailers/claim_mailer.rb
app/models/student_loans.rb
spec/mailers/claim_mailer_spec.rb

We're about to add the Maths and Physics policy to the service and will need to set a different reply-to address for each policy.
GOV.UK Notify allows us to create a whitelist of "Reply-to" addresses under `Settings > Reply-to email addresses`.

Set appropriate reply to address when sending notify emails

---

spec/features/changing_answers_spec.rb
spec/support/feature_helpers.rb

Before, we were completing the student flow completely before each scenario. I've tweaked this now, so we create a submittable claim, and then visit the check-your-answers page. I've also cut down on the amount of nested scenarios, which speeds things up further.
This cuts down the amount of time the spec takes to run from ~20 seconds to ~5 seconds, and takes our total test suite run time down from ~1 minute 20s seconds, to ~57 seconds (so under 1 minute! 🙌 )

Speed up the changing answers spec

---

app/views/claims/ineligible.html.erb
app/views/student_loans/claims/_ineligibility_reason_ineligible_claim_school.html.erb
app/views/student_loans/claims/_ineligibility_reason_ineligible_current_school.html.erb
app/views/student_loans/claims/_ineligibility_reason_not_taught_eligible_subjects.html.erb

Passing in the school names as locals couples the view to the Student
Loans policy. Instead, leave the partials to figure out what they need
to show themselves, based on the current_claim.
Also there's no need to check the claim for errors for the page title as
the ineligible screen is not shown for an errored claim.

Ineligibility page becomes policy-independent

---

app/controllers/application_controller.rb

We don't ever expect to use basic auth to disable the entire application so this no longer makes sense here. The config for the environment variables is hanging around though as we can still use those for adding basic auth for individual policies, i.e. the upcoming Maths & Physics private beta.

Remove global basic auth check

---

CHANGELOG.md

- Add policy specific "Reply-to" address for claim emails
- Upgrade to Rails 6.0.1
(I've added the Rails upgrade to the Changelog, it isn't a user-facing change, but I think it's important to keep track of)

Release 030

---

CHANGELOG.md
app/controllers/base_public_controller.rb
app/controllers/concerns/part_of_claim_journey.rb
app/controllers/static_pages_controller.rb
app/models/claim.rb
app/models/maths_and_physics.rb
app/models/maths_and_physics/eligibility.rb
app/models/maths_and_physics/slug_sequence.rb
app/models/policies.rb
app/views/maths_and_physics/claims/_ineligibility_reason_not_teaching_maths_or_physics.html.erb
app/views/maths_and_physics/claims/eligibility_confirmed.html.erb
app/views/maths_and_physics/claims/teaching_maths_or_physics.html.erb
app/views/static_pages/maths_and_physics.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20191106160514_create_maths_and_physics_eligibilities.rb
db/schema.rb
spec/factories/maths_and_physics/eligibilities.rb
spec/features/maths_and_physics_claim_spec.rb
spec/models/claim_spec.rb
spec/models/maths_and_physics/eligibility_spec.rb
spec/requests/basic_auth_protects_maths_and_physics_spec.rb
spec/routes/routes_spec.rb

Finally, after the many preparatory PRs, here is the beginnings of the Maths & Physics journey.
It introduces the beginnings of the `Eligibility` model and`SlugSequence` as well as a temporary start page that can be used during private beta. Only the first question is implemented in the PR, the rest of the journey can be implemented iteratively from this base.
The Maths & Physics journey will be protected using basic auth; all that needs to happen is to set the appropriate environment variables.

Introduce the Maths & Physics journey

---

Dockerfile

We had some issues in staging that meant the Docker image fell over during boot. The solution outlined in https://github.com/sass/sassc-ruby/issues/146#issuecomment-534197168 should fix it so we're not relying on the underlying system that built the image

Add config to Dockerfile to make sassc portable

---

CHANGELOG.md
app/controllers/admin/claims_controller.rb
app/models/claim/database_of_qualified_teachers_report_request.rb
app/views/admin/claims/index.html.erb
spec/features/admin_dqt_report_request_spec.rb
spec/models/claim/database_of_qualified_teachers_report_request_spec.rb
spec/requests/admin_claims_spec.rb

This PR adds a simple way for service operators to download a csv file that contains the `reference` and `teacher_reference_number` for claims that are `awaiting checking`.
The file is sent securely to the DQT team who return a report file with all the relevent details for claims checking, this saves a service operator from having to sign in to DQT and check each record manually as they can just reference the report.
There is the opportunity to extend this feature to ingest the report, but this is not part of this PR and would need to be scoped and prioritised.
I wanted this to be as simple as possible so I just used a new `format` on the admin#index action of the controller as this already loads the correct claims.
From there I introduced a new …

A service operator can download a csv file to generate a report from DQT

---

azure/resource_groups/app/parameters/production.template.json

These were hardcoded to blank values to disable basic auth when we went into public beta. Instead of doing that in the template we should load the value from the key vault, that way we can enable/disable basic auth without having to do a full release.
We're currently making use of basic auth to protect the new Maths & Physics journey. Re-instating these environment variables will mean basic auth will be active when we ship the beginning of the Maths & Physics journey.

Reinstate production basic auth env vars

---

CHANGELOG.md
app/views/claims/_school_search.html.erb
app/views/student_loans/claims/_ineligibility_reason_employed_at_no_school.html.erb
app/views/student_loans/claims/_ineligibility_reason_ineligible_claim_school.html.erb
app/views/student_loans/claims/_ineligibility_reason_ineligible_current_school.html.erb
app/views/student_loans/claims/_ineligibility_reason_no_more_schools.erb
config/locales/en.yml
spec/features/changing_answers_spec.rb
spec/features/ineligible_tslr_claims_spec.rb
spec/features/multiple_claim_schools_spec.rb
spec/requests/claims_spec.rb

The intent of the policy is to consider the location of the school where
the claimant _taught_, not the location of their employer (these may be
different in the case of, e.g. a multi-academy trust).
I've checked these changes with Faye, our content designer.

Update employment-related copy to clarify policy

---

CHANGELOG.md
app/helpers/admin/payroll_run_helper.rb
app/models/payroll_run.rb
app/views/admin/payroll_runs/index.html.erb
spec/features/admin_payroll_runs_spec.rb
spec/helpers/admin/payroll_run_helper_spec.rb
spec/models/payroll_run_spec.rb

- Service operators are shown when the next payroll run file is expected to be uploaded by
- Only allow payroll runs to be created if none exist already for the current month

Improvements to the generate payroll interface

---

app/jobs/record_payment_job.rb
app/models/payment_confirmation.rb
spec/features/admin_payroll_runs_spec.rb
spec/features/missing_verify_information_spec.rb
spec/features/student_loans_claim_spec.rb
spec/jobs/record_payment_job_spec.rb
spec/jobs/record_submitted_claim_job_spec.rb
spec/models/claim/geckoboard_event_spec.rb
spec/models/payment_confirmation_spec.rb
spec/requests/admin_payment_confirmation_report_upload_spec.rb
spec/requests/submissions_spec.rb
spec/support/geckoboard_helpers.rb

This is a follow-up PR to send data about claims that have been paid to Geckoboard. It uses the same class introduced in #617 to give us a record of all the claims that have been paid, which will allow us to get a count of claims that have been paid during a particular time period, as well as track activity over time. This is updated every time a claim is paid.

Send payment stats to Geckoboard

---

CHANGELOG.md

- Update employment-related copy to clarify that the policy cares about the
location that the teacher _taught_ at, not where their employer is based.
- A service operator can open or close an individual service from the admin
interface. Closing the service prevents users from making claims. As part of
this, we remove the global maintenance mode, and the default maintenance mode
availability message.
- Service operators are shown when the next payroll run file is due to be sent
to Cantium
- Only allow payroll runs to be created if none exist already for the current
month

Release 032

---

CHANGELOG.md
app/models/maths_and_physics/slug_sequence.rb
app/views/maths_and_physics/claims/check_your_answers.html.erb
app/views/maths_and_physics/claims/eligibility_confirmed.html.erb
spec/features/maths_and_physics_claim_spec.rb
spec/models/maths_and_physics/slug_sequence_spec.rb

This will get the user as far as the check-your-answers page. For now,
the check-your-answers page is just a holding page as the real thing
is planned to be implemented as a separate story.
This commit adds a temporary check-your-answers template as the existing
one will break if given a Maths & Physics claim. A separate story is
planned that will make check-your-answers work with any type of claim.
Note that there is now a fair amount of commonality/duplication between
the two SlugSequence classes but it feels too early to try and extract
any kind of abstraction.

Wire in the post-eligiblity Qs for Maths & Physics

---

spec/fixtures/local_authority_districts.yml

"bradford" is referred to but there isn't actually a fixture for it.
Noticed this whilst trying to test Meyric's maths and physics school
question PR in local development.

Add missing local authority district to fixtures

---

CHANGELOG.md
app/mailers/claim_mailer.rb
app/views/claim_mailer/approved.text.erb
app/views/claim_mailer/payment_confirmation.text.erb
app/views/claim_mailer/rejected.text.erb
app/views/claim_mailer/submitted.text.erb
spec/features/admin_claim_check_spec.rb
spec/mailers/claim_mailer_spec.rb
spec/requests/submissions_spec.rb

Updated based on feedback from Faye. As well as updating the content to be more helpful to the user, we're also now using a consistent sentence when referring to the claim, which will make it easier to adjust these emails based on the policy. We've also removed mention of the claim school from the emails as this is not really necessary, and also confusing for users that may have worked at multiple schools.

Update approved/rejected email content

---

CHANGELOG.md
app/models/maths_and_physics/eligibility.rb
app/models/maths_and_physics/slug_sequence.rb
app/views/maths_and_physics/claims/_ineligibility_reason_ineligible_current_school.html.erb
db/migrate/20191114141607_add_current_school_to_maths_and_physics_eligibilities.rb
db/schema.rb
spec/factories/maths_and_physics/eligibilities.rb
spec/features/changing_answers_spec.rb
spec/features/current_school_with_closed_claim_school_spec.rb
spec/features/govuk_verify_spec.rb
spec/features/ineligible_maths_and_physics_claims_spec.rb
spec/features/ineligible_student_loans_claims_spec.rb
spec/features/maths_and_physics_claim_spec.rb
spec/features/missing_verify_information_spec.rb
spec/features/multiple_claim_schools_spec.rb
spec/features/school_search_spec.rb
spec/features/student_loans_claim_spec.rb
spec/features/subjects_taught_spec.rb
spec/features/timeout_spec.rb
spec/models/maths_and_physics/eligibility_spec.rb
spec/requests/claims_spec.rb
spec/requests/submissions_spec.rb
spec/requests/timeout_spec.rb
spec/requests/verify_authentications_spec.rb
spec/support/feature_helpers.rb
spec/support/request_helpers.rb

This is the first PR in a series for maths and physics eligibility.
Obtains the `current_school` using the existing school search. Although I looked at the specs around the school search, I decided not to add additional tests for maths and physics as the school search is independant of which journey, but let me know if that was a bad call. 
Most of this is taken straight from student loans.

Add current school question to maths and physics

---

app/models/student_loans/eligibility.rb
app/views/student_loans/claims/_ineligibility_reason_not_taught_eligible_subjects.html.erb
config/locales/en.yml
db/migrate/20191120081451_change_computer_science_taught_to_computing_taught.rb
db/schema.rb
spec/models/claim/permitted_parameters_spec.rb
spec/models/student_loans/eligibility_spec.rb

This changes all references of "Computer Science" to "Computing". I've also changed the name of the column to `computing_taught`. I considered not doing this to save added complication, but given that `change_column` is a non-destructive action, it makes sense to do this, so we don't have legacy naming flying around.

Change computer science to computing

---

app/models/maths_and_physics/eligibility.rb
app/models/maths_and_physics/slug_sequence.rb
app/views/maths_and_physics/claims/initial_teacher_training_specialised_in_maths_or_physics.html.erb
config/locales/en.yml
db/migrate/20191118161602_add_initial_teacher_training_specialised_in_maths_or_physics_to_maths_and_physics_eligibilities.rb
db/schema.rb
spec/factories/maths_and_physics/eligibilities.rb
spec/features/maths_and_physics_claim_spec.rb
spec/models/maths_and_physics/eligibility_spec.rb

We did not want an abbreviation in the attribute, which made it very
long, but we felt the price was worth paying to be clear what the
attribute represents.
The question template is a copy-and-paste of an existing one.

Add ITT specialisation question

---

app/models/maths_and_physics/eligibility.rb
app/models/maths_and_physics/slug_sequence.rb
app/views/maths_and_physics/claims/_ineligibility_reason_no_maths_or_physics_qualification.html.erb
app/views/maths_and_physics/claims/has_uk_maths_or_physics_degree.html.erb
config/locales/en.yml
db/migrate/20191119115400_add_has_uk_maths_or_physics_degree_to_maths_and_physics_eligibilities.rb
db/schema.rb
spec/features/ineligible_maths_and_physics_claims_spec.rb
spec/features/maths_and_physics_claim_spec.rb
spec/models/maths_and_physics/eligibility_spec.rb
spec/models/maths_and_physics/slug_sequence_spec.rb
spec/support/feature_helpers.rb

This is the first maths and physics question with a question which is
displayed conditionally.
MathsAndPhysics::Eligibility#reset_dependent_answers is a copy-and-paste
of the same method from StudentLoans::Eligibility.

Add question about maths or physics degree

---

CHANGELOG.md
app/controllers/claims_controller.rb
spec/features/switching_policies_spec.rb

Currently, if a user starts a claim session for one policy, and then attempts to switch policies, they're confronted with a Template error. This is because `prepend_view_path_for_policy` runs before the claim session is cleared, so the view path is set for the old policy. This tweak changes this behaviour so `clear_claim_session` runs before the view path is set.

Clear claim session before prepending view path

---

CHANGELOG.md
app/mailers/claim_mailer.rb
app/models/maths_and_physics.rb
app/models/student_loans.rb
app/views/claim_mailer/approved.text.erb
app/views/claim_mailer/payment_confirmation.text.erb
app/views/claim_mailer/rejected.text.erb
app/views/claim_mailer/submitted.text.erb
config/locales/en.yml
spec/factories/claims.rb
spec/factories/payments.rb
spec/mailers/claim_mailer_spec.rb

This updates the transactional claim emails so that they will work with any policy. There are a lot of commits here, but it's not as bad as it looks:
- The first half dozen update the mailer and the views such that they will handle either type of claim
- The rest are small iterative steps that rework the mailer specs until the point where they can all be run with a claim for either policy
**NOTE: the rejection reasons for Maths & Physics are currently being reviewed and I'll be fixing them up in the translation file once the final content has been agreed**

Make transactional emails work with any policy

---

app/helpers/claims_helper.rb
app/models/maths_and_physics/eligibility.rb
app/models/maths_and_physics/slug_sequence.rb
app/views/claims/qts_year.html.erb
app/views/maths_and_physics/claims/_ineligibility_reason_ineligible_qts_award_year.html.erb
app/views/student_loans/claims/qts_year.html.erb
config/locales/en.yml
db/migrate/20191120120237_add_qts_award_year_to_maths_and_physics_eligibilities.rb
db/schema.rb
spec/factories/maths_and_physics/eligibilities.rb
spec/features/ineligible_maths_and_physics_claims_spec.rb
spec/features/maths_and_physics_claim_spec.rb
spec/features/student_loans_claim_spec.rb
spec/features/switching_policies_spec.rb
spec/helpers/claims_helper_spec.rb
spec/models/maths_and_physics/eligibility_spec.rb
spec/requests/claims_spec.rb
spec/routes/routes_spec.rb

This adds the question and the eligibility logic. It's a couple of small refactors, to be able to reuse a question template, and then pretty much a copy and paste from Student Loans (which seems like the right thing to do, at the moment).
It's worth noting that the relevant date for Maths and Physics is 1 September _2014_, in contrast to Student Loans which is 2013.

Add qts-year question to Maths and Physics

---

CHANGELOG.md

- Display the gross pay instead of the gross value in the payment confirmation email
- Update transational emails with improved content
- Clear claim session before view path gets calculated
- Add some copy to make it clear why we ask about a user's student loan
- Update transactional emails to support the two different policy types
- Change "computer science" to "computing" on student loans questions

Release 033

---

app/controllers/concerns/part_of_claim_journey.rb
spec/features/claim_journey_does_not_get_cached_spec.rb
spec/requests/verify_authentications_spec.rb

This fixes two issues - the first being an issue where a user who has finished, or was part way through their claim and has navigated away, can have their personal data surfaced by someone using the back button, even after the session has expired.
The second issue is if a user starts the Verify journey and then uses the back button, clicking continues results in an error, because the browser sends the same authentication request, rather than a newly minted one. This is slightly harder to test, because we stub out a lot of the Verify stuff in feature tests (and we  don't even see the error in the development version of the VSP), so the only thing we can test is that the cache headers get successfully set in the part of the journey where the authentication request is made.

Set cache headers so pages are refreshed each time

---

app/models/maths_and_physics/eligibility.rb
app/models/maths_and_physics/slug_sequence.rb
app/views/maths_and_physics/claims/_ineligibility_reason_no_entire_term_contract.html.erb
app/views/maths_and_physics/claims/_ineligibility_reason_not_employed_directly.html.erb
app/views/maths_and_physics/claims/employed_directly.html.erb
app/views/maths_and_physics/claims/entire_term_contract.html.erb
app/views/maths_and_physics/claims/supply_teacher.html.erb
config/locales/en.yml
db/migrate/20191120161044_add_employed_as_supply_teacher_to_maths_and_physics_eligibilities.rb
db/migrate/20191120171540_add_has_entire_term_contract_to_maths_and_physics_eligibilities.rb
db/migrate/20191121081842_add_employed_directly_to_maths_and_physics_eligibilities.rb
db/schema.rb
spec/factories/maths_and_physics/eligibilities.rb
spec/features/ineligible_maths_and_physics_claims_spec.rb
spec/features/maths_and_physics_claim_spec.rb
spec/models/maths_and_physics/eligibility_spec.rb
spec/models/maths_and_physics/slug_sequence_spec.rb

This adds the "Are you currently employed as a supply teacher?" question, which acts as a branching point in the Maths and Physics eligibility journey. It then adds all the questions for this branch of the journey. (After these questions, the main journey will resume.)

Add supply teacher questions to Maths and Physics journey

---

CHANGELOG.md
app/helpers/application_helper.rb
app/models/maths_and_physics.rb
app/models/student_loans.rb
spec/features/maths_and_physics_claim_spec.rb
spec/features/student_loans_claim_spec.rb

This adds a helper method to get the feedback link for each policy. I've also refactored the `ApplicationHelper` to get the current policy based on the routing name given that we're using it in two places now. 
I've also updated the StudentLoans and Maths and Physics modules to extend from themselves, to avoid the repetition of typing `self` at the beginning of every method name, and given that we're unlikely to be including these modules in any other classes.
I've also added a simple test in the Student Loan and Maths and Physics happy paths to give us the confidence that the correct feedback URLs are being returned for each journey.

Change feedback link depending on policy

---

app/models/maths_and_physics.rb
app/models/student_loans.rb
app/views/submissions/show.html.erb
spec/requests/submissions_spec.rb
spec/support/request_helpers.rb

This does two things:
* Moves the done page URL to a method in each policy (Maths and Physics currently has none, so returns `nil`)
* Only link to a done page on the confirmation page if it exists for that particular policy

The "claim submitted" page should not link to the done page for Maths and Physics

---

CHANGELOG.md
app/models/maths_and_physics/eligibility.rb
app/models/payroll/claim_csv_row.rb
app/models/payroll/claims_csv.rb
spec/features/admin_payroll_runs_spec.rb
spec/models/maths_and_physics/eligibility_spec.rb
spec/models/payroll/claim_csv_row_spec.rb
spec/models/payroll_run_spec.rb

Prior to this things would have blown up if a payroll run was attempted with an approved Maths & Physics claim.
This doesn't deal with the bigger issue of when there is a claim for each policy from the same person in the same payroll run, but that is being tackled elsewhere in another story. This at least means we can approve and pay Maths & Physics claims, as long as the person doesn't have an approved Student Loans claim in the same run.

Make sure payroll process works with a Maths & Physics claim

---

app/helpers/claims_helper.rb
app/views/student_loans/claims/student_loan_amount.html.erb
spec/features/changing_answers_spec.rb
spec/features/missing_verify_information_spec.rb
spec/features/student_loans_claim_spec.rb
spec/helpers/claims_helper_spec.rb

The student_loans.questions.student_loan_amount question no longer
refers to the claim school, as of d2afc57.

Drop unused claim school name param in I18n calls

---

CHANGELOG.md
azure/resource_groups/app/parameters/production.template.json

This adds the GOV.UK service domains (with the canonical one first), as well as the certificate names and mapings to the template. With these in place we will be able to start serving requests from the service domain, and any requests to the old domain will be redirected to the new one.

Add new domains and certificates to template

---

azure/resource_groups/app/parameters/production.template.json

Rather than going big bang and making the service domain canonical, we're going to play it safe and keep the education.gov.uk as the canonical domain for now, until we've verified that the certificate for the service domain is in place and working as expected.

Make education.gov.uk domain canonical for now

---

spec/support/capybara.rb

We're having some issues with tests failing on Headless Chrome occasionally when forms have hints that make the screen size a specific height. Working theory is that Chromedriver isn't taking account of the margin/padding of the span element and causing it to click in the wrong place. An easy fix for this is to increase the screen size to make sure Chromedriver doesn't have to scroll for most cases.

Make headless Chrome screen size bigger

---

CHANGELOG.md
azure/resource_groups/app/parameters/production.template.json

Now the certificate is set up an confirmed working, we can now redirect all requests to the service domain.
**NOTE** Before this goes to production, we'll need to put the app into maintenance mode, as the sessions are stored by domain, so any in-progress claims will break.

Make service.gov.uk domain canonical

---

CHANGELOG.md
app/controllers/admin/auth_controller.rb
app/controllers/admin/base_admin_controller.rb
spec/features/admin_sessions_spec.rb
spec/support/feature_helpers.rb

Not only is this a better user experience in general, Cantium users will only be
given a single endpoint to download the payroll run file. By redirecting them
after sign in we save them from having to navigate to the right place.

Signed-out admin users redirected to orginal request url after signing in

---

CHANGELOG.md

- Make www.claim-additional-teaching-payment.service.gov.uk the
canonical domain
- Admin users are redirected to their original request path after sign
in

Release 035

---

app/models/admin_session.rb
spec/models/admin_session_spec.rb

We'll use this to grant restricted access to Cantium employees so that they can sign-in and download the monthly payroll file.
This new role has been set up on pre-production and is scoped to a new "Cantium Business Solutions" organisation. That way, the approver for this organisation will be able to grant and revoke access to users themselves without the need for intervention from us. For now, I have been set up as the approver on pre-production so that we can test the behaviour whilst we build out the new functionality.

Introduce DfE Sign-in role for payroll operators

---

azure/resource_groups/app/parameters/development.template.json
azure/resource_groups/app/parameters/production.template.json
azure/resource_groups/app/template.json

Since we switched to the service domain, we accidentally switched the VSP entity ID too, as it's tied to the canonical domain. This hardcodes the ID, so it's no longer tied to the domain, as Verify don't really care if it's related to the domain (it's a abitary string)

Hardcode the VSP entity ID

---

CHANGELOG.md

- Hardcode VSP entity ID to fix our GOV.UK Verify journey
- Temporarily whitelist new DfE Manchester office IP so that service operators
can continue to access admin interface

Release 036

---

CHANGELOG.md
app/controllers/admin/claims_controller.rb
app/helpers/admin/claims_helper.rb
app/models/claim.rb
app/models/maths_and_physics.rb
app/models/policies.rb
app/models/student_loans.rb
app/views/admin/claims/index.html.erb
app/views/admin/claims/show.html.erb
config/locales/en.yml
spec/features/admin_claim_check_spec.rb
spec/requests/admin_claims_spec.rb

This shows the policy in the admin view against each claim, and also allows users to filter by policy.
There will be some further work needed on this story, once the Check Your Answers work is done.

Allow admin to filter by policy

---

azure/resource_groups/app/parameters/development.template.json
azure/resource_groups/app/parameters/production.template.json
azure/resource_groups/app/template.json

This will always be whatever hostname is the canonical one, so, in case we move domain again, this will ensure the redirect URL is set correctly. We'll still need to get DfE Signin to whitelist the URL, but it's one less thing for us to think about

Use Canonical Hostname for DfE Signin base URL

---

app/helpers/admin/claims_helper.rb
app/helpers/claims_helper.rb
app/presenters/maths_and_physics/eligibility_answers_presenter.rb
app/presenters/student_loans/eligibility_answers_presenter.rb
app/presenters/student_loans/presenter_methods.rb
app/views/claims/check_your_answers.html.erb
app/views/maths_and_physics/claims/employed_directly.html.erb
app/views/maths_and_physics/claims/has_uk_maths_or_physics_degree.html.erb
config/locales/en.yml
spec/helpers/claims_helper_spec.rb
spec/presenters/maths_and_physics/eligibility_answers_presenter_spec.rb
spec/presenters/student_loans/eligibility_answers_presenter_spec.rb

This PR is the first step in building the `check-your-answers` page for Maths and Physics. There's a first refactor which lets us provide a per-policy class to format the answers for playback to the claimant. After that, I create this class for M&P.
I'm submitting this PR now, before building the whole `check-your-answers` feature, because:
1. I would like feedback on the approach (@tekin and I did talk about it a bit already though);
2. We will probably want to use a similar approach when [adapting the admin claims interface for M&P](https://trello.com/c/hgPHPmX4/991-admin-is-updated-to-accommodate-maths-physics-claims), so getting this in early means we can be consistent in our approach.

Refactor check-your-answers helper for multiple policies and add answer formatting for Maths and Physics

---

app/views/student_loans/claims/subjects_taught.html.erb

(I noticed that the page title was showing a %{school} placeholder.)

Add school name to subjects-taught page title

---

spec/mailers/previews/claim_mailer_preview.rb

This makes the development and demoing experience a little nicer. I've also added an extra commit which locks the claim ordering so that we know which claim will be used for the preview.

Parameterise claim mailer previews by policy

---

CHANGELOG.md
README.md
bin/azure-console

This gives us bash console access to the worker container, which, in turn will allow us to access the Rails console, with appropriate warnings as to the severity and last-resort nature of running this command. I did consider dropping the user straight into the Rails console for this, but `az container exec` doesn't support this (https://docs.microsoft.com/en-us/azure/container-instances/container-instances-exec#restrictions)

Add a script to allow access to the container

---

CHANGELOG.md
app/views/maths_and_physics/claims/_ineligibility_reason_subject_to_disciplinary_action.html.erb
app/views/maths_and_physics/claims/_ineligibility_reason_subject_to_formal_performance_action.html.erb
app/views/static_pages/accessibility_statement.html.erb
app/views/static_pages/maths_and_physics.html.erb
config/locales/en.yml

Just the simple stuff for now:
- Adjust Maths & Physics private beta start page content
- Correct wording in Maths & Physics claim emails
- Remove explicit mention of Student Loans policy on accessibility statement
- Update re-apply date on performance/disciplinary ineligibility pages

Maths & Physics content snags

---

app/models/maths_and_physics/slug_sequence.rb
app/models/student_loans/slug_sequence.rb
spec/models/maths_and_physics/slug_sequence_spec.rb
spec/models/student_loans/slug_sequence_spec.rb

Instead of a raising a 500 error if a user visits the ineligible screen
with an claim that isn't actually ineligible we raise a 404.
We had an exception raised for the ineligible screen because a partial
for the ineligibility reason couldn't be found: `"...Missing partial
claims/_ineligibility_reason_"`. Based on the code in the partial this
is likely to have happened because the claim eligibility didn't report
an `ineligibility_reason`. which would only happen if the claim wasn't
actually ineligible. This is probably a weird edge case and caused by
the user navigating outside of the normal UI interface, but in any case
Returning a 404 feels more appropriate and will reduce the rollbar
noise.
If we find more users ending up on the ineligible screen
unexpectedly we might want to consider …

Don't include ineligible slug when not appropriate

---

spec/features/changing_answers_spec.rb

This does three things:
- Slims down the check-your-answers specs, reducing it to a
representative set of scenarios instead of a separate scenario for
changing each answer from each policy, which would not be a sustainable
approach as we add new policies.
- Introduces some maths and physics questions into the
check-your-answers specs (as part of the aforementioned set of
scenarios).
- Rearranges the file so that it's clear which specs are related to
eligibility (and hence are only representative of a broader set of
policy-specific questions), and which specs represent questions that are
present across all policies.

Update check-your-answers feature specs for M&P

---

CHANGELOG.md
app/assets/javascripts/components/timeout_dialog.js.erb

This fixes a bug where a user that has dismissed the timeout dialog to
continue their session still gets redirected after the timeout dialog
warning period has expired. This was happening because the JS timeout
that gets initially set to redirect the user after the timeout period
has expired wasn't being cleared.
It's unlikely many users will have experienced this because the timeout
is naturally cleared when a new page is loaded.

Clear JS timeout redirect when session refreshed

---

app/models/application_record.rb
db/migrate/20191203103255_add_created_at_indexes_for_implicit_ordering.rb
db/schema.rb

One of the downsides to using UUIDs for primary keys is that we lose the
implicit ordering behaviour of the `first` and `last` finder methods,
which by default return the first and last records based on the primary
key as a proxy for creation date. When that is an incrementing integer,
things work as expected, but with UUIDs we end up with entirely
random records based on the string ordering of the UUIDs. Rails 6
introduced the ability to [override this implicit order column](https://github.com/rails/rails/pull/34480), which
means we can set it to created_at and get back the natural and less
surprising behaviour of `first` and `last` when an explicit `order` hasn't
been used.

Configure implicit ordering based on created_at

---

CHANGELOG.md
README.md
config/application.rb
config/routes.rb

Now Maths and Physics is in private beta, it no longer makes sense to redirect requests to the root url to the Maths and Physics start page. There is now a [generic page on GOV.UK](https://www.gov.uk/government/publications/additional-payments-for-teaching-eligibility-and-payment-details) about teacher payments, so we're now redirecting to that. I've stored it as a config var in the Rails application.rb, rather than exposing it in the routes file, as it a) may be useful in other places and b) I'm not a huge fan of having a big URL like that in the routes.rb file itself.

Redirect root url to an all-encompassing page

---

db/migrate/20191203103255_add_created_at_indexes_for_implicit_ordering.rb
db/schema.rb

Turns out our schema.rb file was not an accurate reflection of the
actual database schema: it was missing indexes for created_at and
updated_at on the payroll_runs table. This corrects the schema.rb file
and also updates the most recent migration, which is currently failing
to run because it tries to add an index that already exists.
The problem stems from this commit: https://github.com/DFE-Digital/dfe-teachers-payment-service/commit/39ca7bfa30144ff3c2a0671de42b984ad55d322b
It added the payroll_runs table with `t.timestamps index: true`, which
would have added indexes for `created_at` and `updated_at`, but for whatever
reason those indexes were not reflected in the schema.rb changes. The
result of this was our local versions of the database were likely to get
out of sync after running …

Correct schema.rb and currently failing migration

---

CHANGELOG.md

- Service operators can see Maths and Physics claim eligibility
- Fix a bug that would occassionally redirect users even after they'd continued their session
- Redirect requests to the root URL to a GOV.UK page about teacher payments

Release 038

---

CHANGELOG.md
app/assets/javascripts/components/auto_click_link.js
app/assets/javascripts/components/copy_to_clipboard.js
app/controllers/admin/base_admin_controller.rb
app/controllers/admin/page_controller.rb
app/controllers/admin/payroll_run_downloads_controller.rb
app/controllers/admin/payroll_runs_controller.rb
app/models/payroll_run.rb
app/views/admin/payroll_run_downloads/new.html.erb
app/views/admin/payroll_run_downloads/show.html.erb
app/views/admin/payroll_runs/index.html.erb
app/views/admin/payroll_runs/new.html.erb
app/views/admin/payroll_runs/show.html.erb
config/brakeman.ignore
config/routes.rb
db/migrate/20191126083258_add_downloaded_at_and_by_to_payroll_runs.rb
db/schema.rb
spec/features/admin_claim_check_spec.rb
spec/features/admin_payroll_run_download_spec.rb
spec/features/admin_payroll_runs_spec.rb
spec/models/payroll_run_spec.rb
spec/requests/admin_claim_checks_spec.rb
spec/requests/admin_configure_services_spec.rb
spec/requests/admin_page_spec.rb
spec/requests/admin_payment_confirmation_report_upload_spec.rb
spec/requests/admin_payroll_run_downloads_spec.rb
spec/requests/admin_payroll_runs_spec.rb
spec/requests/admin_spec.rb

This PR allows Payroll operators (Cantium users) to sign in to the admin area of the service and download the payroll run file.
Serivce operators (DfE users) can no longer donwload a payroll run file but they must still create the payroll run at which point they are provided with a link to the file to send to Cantium, they cannot download the file from the link.  The link is not shown once the file has been downloaded.
This manual process will be replaced with a more automated one at a later date.
Because the payroll run file contains personally identifiable information, we want to limit the number of times it can be downloaded. To achieve this we chose to limit the time a Payroll user can download the file, currently set to 30 seconds. Once the timeout is reached the file cannot be …

Cantium can download the payroll file themselves

---

app/controllers/admin/payroll_runs_controller.rb
app/models/claim.rb
app/models/payment.rb
app/models/payroll_run.rb
app/views/admin/payroll_runs/new.html.erb
db/data/20191203100302_populate_payment_id_for_claims.rb
db/data_schema.rb
db/migrate/20191203095639_add_payment_id_to_claims.rb
db/schema.rb
spec/factories/payments.rb
spec/models/payroll/claim_csv_row_spec.rb
spec/models/payroll_run_spec.rb

This is technical groundwork for some feature work that will come later. The main change also allows us to optimise the `PayrollRun#total_award_amount` method, which comes in its own commit.

Change payment <-> claim associations to enable multiple payments per claim

---

CHANGELOG.md

- Service operators can create and view a payroll run and provide a link to
payroll operators (Cantium users) to download a file
- Payroll operators can download the payroll run file using a link
- Security: Bump puma from 4.3.0 to 4.3.1 to resolve Keepalive thread
overload/DoS vulnerability

Release 039

---

CHANGELOG.md
azure/resource_groups/app/parameters/development.template.json
azure/resource_groups/app/parameters/production.template.json

Makes it possible to change the whitelist without a full release/deploy cycle, which is way faster.
I've added `AdminAllowedIPs` secrets to both Key vaults.

Configure admin IP whitelist using Key vault

---

app/controllers/admin/payroll_run_downloads_controller.rb
app/models/payment.rb
app/models/payroll/payment_csv_row.rb
app/models/payroll/payments_csv.rb
config/brakeman.ignore
spec/models/payroll/payment_csv_row_spec.rb
spec/models/payroll/payments_csv_spec.rb

This is prep work for updating the CSV to work with multiple claims,
where each line of the CSV will correspond to a single _payment_, not
necessarily a single claim. We modify and rename the CSV classes to
reflect this.
When we move to multiple claims, there will be some data fields which
are duplicated across a payment's claims, for example address, payroll
gender, etc. We add these fields as methods on the Payment class. At the
moment, they just delegate to the payment's claim. Once we move to
multiple claims, they will probably delegate to the first claim of the
payment. This allows us to keep the CSV generation code the same, and
abstract away the process of getting e.g. an address for a payment.

Make payments CSV classes use payments, not claims

---

config/routes.rb

**This must be merged before #692**
This ensures that we can access the staging application on its own domain, rather than redirecting to the canonical hostname, this allows us to check the health of slots before swapping them

Move the healthcheck URL to before the constraints

---

bin/swap-slots

This changes the `swap-slots` script to check the staging slot has come up cleanly before swapping it over to production. Most of the work I've done on this has been on a train with poor connectivity, so I've not had chance to check it actually works, so would be good to test this out as part of the review process.

Check staging slot responds before swapping

---

db/schema.rb

I introduced this incorrectly to schema.rb:
https://github.com/DFE-Digital/dfe-teachers-payment-service/blob/eeab5b33685ef9360a112dec0e4bb59f11f12d61/db/schema.rb#L172
Removing it here will mean the migration can run when it is introduced along
with the code that uses it.

Remove statutory_high_age from schema

---

README.md

Developers will want to run this locally when setting up their database
to prime the data schema migrations table with the existing (and hence
outdated) ones so that they aren't run the next time data migrations are
executed.

Mention data:schema:load task in README.md

---

.gitignore

Adds a `.gitkeep` file to the `bin/vsp` directory so that download/unzip/copy of VSP doesn't fail.

Add a .gitkeep to the bin/vsp directory

---

CHANGELOG.md
azure/resource_groups/app/template.json
azure/templates/availability_tests.json

This restores the webtest functionality, which was originally deleted due to the template using 'classic' alerts. The template has now been altered to use Azure Metric Alerts.
The deployment deploys alerts for the VSP and the app at the same time, and the template utlises ARM `copy` functionality to deploy multiple webtests and alerts for each endpoint.

Add webtests/alerts for the app and VSP

---

spec/features/admin_payroll_runs_spec.rb

This test seems to ocassionally fail because claims aren't always in the order we expect them. I've got around this by mapping the subjects and addressee emails to an array and then matching the array, so we don't worry about the order.

Fix test flicker on payroll run spec

---

CHANGELOG.md
app/helpers/admin/claims_helper.rb
app/models/claim/matching_attribute_finder.rb
spec/models/claim/matching_attribute_finder_spec.rb

This changes the `ATTRIBUTES_TO_MATCH` array to be an array of groups to match against in the database. If there is more than one attribute in the group, we concatenate the subjects and  predicates together, so we can make sure both things match. At the moment, we only need this for bank details, but we may need this for other things (such as maybe firstname / lastname / DOB etc)

Don't match bank account sort code when identifying potentially similar claims

---

CHANGELOG.md
app/models/maths_and_physics/school_eligibility.rb
app/models/school.rb
app/models/school_data_importer.rb
app/models/student_loans/school_eligibility.rb
db/migrate/20191202123242_add_statutory_high_age_to_schools.rb
db/schema.rb
spec/factories/schools.rb
spec/models/maths_and_physics/school_eligibility_spec.rb
spec/models/school_spec.rb
spec/models/student_loans/school_eligibility_spec.rb
spec/services/school_data_importer_spec.rb

Special schools with a `phase` of `not_applicable` are still eligble when they teach students over the age of 11. We use the `statututoryHighAge` column in the Get information about schools data to test the elgiblity of this type of school.
Alternative provision schools that teach students over the age of 11 are also eligible. Alternative provision schools are those of the `school_type`:
- pupil_referral_unit
- secure_unit
- free_school_alternative_provider
- academy_alternative_provision_converter
- academy_alternative_provision_sponsor_led
The same `statututoryHighAge` can be used along with the school type to determine eligibility.
Secue units do not have a recognised state funded `school_type_group` so I had to add an exception for it in the `state_funded?` method as the group they …

Bug: fix special school age range and add Alternative provision schools

---

Dockerfile

Bundler 2.1.0 has been released and the switch to that version coincided with deployments breaking on development. To narrow down the issue we are locking to the previous version to see if that resolves things before we figure out what the problem is with 2.1.0.

Lock to bundler 2.0.2 in docker file

---

Dockerfile
Gemfile.lock
bin/docker-entrypoint

We locked the version of Bundler to 2.0.2 in the Dockerfile because with
the latest version (2.1.0) the app was failing to start – the calls to
the `rails` command in docker-entrypoint were resulting in "command not
found" errors. We traced the issue to the fact that bundler 2.1.0 when
installed in the Docker container doesn't appear to be creating any
binstubs for commands like `rake` or `rails`. Instead of relying on the
presence of binstubs we call the commands with `bundle exec` instead.
The second commit gets rid of the deprecation warnings introduced by bundler 2.1.0.

Unpin Bundler version in Dockerfile

---

config/brakeman.ignore
lib/tasks/brakeman.rake

Brakeman currently does not exit with a non-zero exit code, so if we get any warnings, the test suite continues and we don't see any issues (unless we scroll back an read the output). This updates the Rake task to exit appropriately if there are any warnings. 
We also previously had a warning, which we're safe to ignore.

Fix Brakeman

---

azure/templates/worker.json

As we discovered in #717 - Bundler 2.1.0 no longer appears to be generating binstubs for common commands like `rake` or `rails`. We fixed this for the web container, but didn't do this for the worker, so the worker still wasn't coming up cleanly.

Append `bundle exec` to the worker startup script

---

CHANGELOG.md
app/views/claims/ineligible.html.erb
app/views/maths_and_physics/claims/_ineligibility_reason_ineligible_current_school.html.erb
app/views/maths_and_physics/claims/_ineligibility_reason_ineligible_qts_award_year.html.erb
app/views/maths_and_physics/claims/_ineligibility_reason_no_entire_term_contract.html.erb
app/views/maths_and_physics/claims/_ineligibility_reason_no_maths_or_physics_qualification.html.erb
app/views/maths_and_physics/claims/_ineligibility_reason_not_employed_directly.html.erb
app/views/maths_and_physics/claims/_ineligibility_reason_not_teaching_maths_or_physics.html.erb
app/views/maths_and_physics/claims/_ineligibility_reason_subject_to_disciplinary_action.html.erb
app/views/maths_and_physics/claims/_ineligibility_reason_subject_to_formal_performance_action.html.erb
app/views/student_loans/claims/_ineligibility_reason_employed_at_no_school.html.erb
app/views/student_loans/claims/_ineligibility_reason_ineligible_claim_school.html.erb
app/views/student_loans/claims/_ineligibility_reason_ineligible_current_school.html.erb
app/views/student_loans/claims/_ineligibility_reason_ineligible_qts_award_year.html.erb
app/views/student_loans/claims/_ineligibility_reason_no_more_schools.erb
app/views/student_loans/claims/_ineligibility_reason_not_taught_eligible_subjects.html.erb
app/views/student_loans/claims/_ineligibility_reason_not_taught_enough.html.erb
spec/features/ineligible_student_loans_claims_spec.rb
spec/requests/claims_spec.rb

We found claimants were contacting support to confirm eligibility criteria which was over burdening support staff. By updating all the ineligibility content we hope to make it simpler for claimants to understand why they may not be eligible.
Two specs needed updated to reflect the new content.
I decided not to extract the new 'for more information' content to a partial as the url varies and I didn't not want to introduce more nested partials.
All the content are in thsese Google Docs, note that some dates in the docs are out-of-date.
https://docs.google.com/document/d/1pxrOk4sCMesk3IhZLTgn6jcT0dVCvheSqbLwqP_4Jg0/edit?folder=1WU_WvNrG7HEEtAHXmE9ZZO_8NbRdgH96#heading=h.w78bjvgufkjb
https://docs.google.com/document/d/1bnVttY_jN_faNyc0JlR3RPBo7yOFWRGfyiHiyAQC6ro/edit?folder=1rGeTXKllSUHmOw8pC3 …

A user should know why their answer has made them ineligible

---

CHANGELOG.md
config/locales/en.yml

Users found the previous wording for this question confusing and we saw
support tickets about it. This change aims to make it clearer what the
question is asking.

Update student loan question

---

CHANGELOG.md

- Restore uptime alerting to alert when the App / VSP are down
- Don't match bank account sort code when identifying potentially
similar claims
- Alternative provisions schools and special schools that teach students
who are over 11 are eligible
- Update content for both maths and physics and student loans ineligible
screens
- Update student loan question wording to make the intention clearer

Release 041

---

lib/tasks/jobs.rake

The Rake task was mistakenly calling to the method `#run`, which doesn't exist. The actual method name is `#schedule`

Fix call to `CronJobScheduler`

---

CHANGELOG.md
app/views/claims/address.html.erb

This maps to what Google recommends for the autocomplete attribute for
the various address fields. Prior to this, my browser (Safari on Mac)
was autocompleting my street address in the City field. Now it maps all
address fields, including County, correctly.

Update address autocomplete attributes

---

azure/resource_groups/app/template.json
bin/azure-deploy

Currently the workers aren't getting the up to date code when we do a production / development deploy. After a lot of chat with other ops people we've realised that this is because we always the the `development` Docker tag, so the container doesn't know that anything has changed, so doesn't pull down the latest image.
This adds a new environment variable to the web and worker containers, set by setting the `AZURE_BUILD_NUMBER` in the build environment when deploying. This means that the worker container knows something has changed and restarts itself, pulling down the latest version of the `development` or `production` image from DockerHub.
Once this is merged, we'll also need to set an `AZURE_BUILD_NUMBER` environment variable in the Azure DevOps config to the value of the build we're …

Add BUILD_NUMBER env var to containers

---

CHANGELOG.md
app/controllers/verify/authentications_controller.rb
app/views/claim_mailer/submitted.text.erb
app/views/submissions/show.html.erb
config/routes.rb
docs/govuk-verify.md
spec/mailers/claim_mailer_spec.rb
spec/requests/submissions_spec.rb
spec/requests/verify_authentications_spec.rb

Users that do not complete GOV.UK Verify see different content explaining how their claim will be handled.
This PR also introduces the endpoint that we will link back to from GOV.UK Verify's failure screen so that users can pick up where they left off.

Adjust content when GOV.UK Verify hasn't been completed

---

app/controllers/claims_controller.rb
app/models/claim.rb
app/models/maths_and_physics/eligibility.rb
app/models/student_loans/eligibility.rb
app/views/claims/bank_details.html.erb
spec/models/claim_spec.rb
spec/models/student_loans/eligibility_spec.rb
spec/requests/claims_spec.rb

Updated error messages to make them consistent and provide some more guidance to users. To be clear these are the messages shown when you don't select an option/input any text and try to continue. 
Messages have been changed to follow the pattern e.g. `select yes if you teach any maths or physics` rather than telling the user to select an option. Messages should now also be consistent in their use of case and punctuation.
Miro board of new error messages can be found here https://miro.com/app/board/o9J_kvlNgOg=/

1116 inconsistent error messages

---

app/views/admin/claims/show.html.erb
app/views/admin/policy_configurations/edit.html.erb
app/views/claims/_school_search.html.erb
app/views/claims/bank_details.html.erb
app/views/claims/email_address.html.erb
app/views/claims/gender.html.erb
app/views/claims/national_insurance_number.html.erb
app/views/claims/student_loan.html.erb
app/views/claims/student_loan_how_many_courses.html.erb
app/views/claims/teacher_reference_number.html.erb
app/views/maths_and_physics/claims/disciplinary_action.html.erb
app/views/maths_and_physics/claims/formal_performance_action.html.erb
app/views/maths_and_physics/claims/has_uk_maths_or_physics_degree.html.erb
app/views/maths_and_physics/claims/initial_teacher_training_subject_specialism.html.erb
app/views/maths_and_physics/claims/teaching_maths_or_physics.html.erb
app/views/student_loans/claims/leadership_position.html.erb
app/views/student_loans/claims/mostly_performed_leadership_duties.html.erb
app/views/student_loans/claims/student_loan_amount.html.erb

This adds an `aria-describedby` to elements that have hints. In some cases the hints describe a group of elements (such as, for example a bunch of radio buttons), in this case, the `aria-describedby` element is added to the enclosing `fieldset`, which will also have a `role` of `group` (which is a pattern I've seen elsewhere, but hasn't until now, been consistent)

Add aria-describedby to elements with hints

---

CHANGELOG.md
app/views/static_pages/privacy_notice.html.erb

DfE's Legal Advisers Office came back with some tweaks to the privacy
policy regarding bank details and how users can get data amended

Updates to privacy policy

---

CHANGELOG.md
app/controllers/admin/payroll_runs_controller.rb
app/helpers/admin/claims_helper.rb
app/helpers/dfe_sign_in/user_helper.rb
app/models/payroll_run.rb
app/views/admin/payroll_runs/show.html.erb
db/data/20200102151230_update_payroll_run_created_by_to_created_by_id.rb
db/data_schema.rb
db/migrate/20200102142041_add_created_by_to_payroll_runs.rb
db/migrate/20200102144145_remove_null_constraint_from_created_by.rb
db/schema.rb
spec/factories/payroll_runs.rb
spec/features/admin_payroll_runs_spec.rb
spec/helpers/dfe_sign_in/user_helper_spec.rb
spec/models/payroll_run_spec.rb
spec/requests/admin_payroll_runs_spec.rb

This updates the PayrollRun model to refer to a user in the database, rather than a simple Dfe Sign-In user ID. This also allows the name of a user to be shown like so:

Display the name of a user who created a payroll run

---

CHANGELOG.md
app/controllers/admin/payroll_run_downloads_controller.rb
app/helpers/dfe_sign_in/user_helper.rb
app/models/payroll_run.rb
app/views/admin/payroll_run_downloads/show.html.erb
app/views/admin/payroll_runs/show.html.erb
db/data/20200106141251_update_payroll_run_downloaded_by_to_downloaded_by_id.rb
db/data_schema.rb
db/migrate/20200106120123_add_downloaded_by_to_payroll_runs.rb
db/schema.rb
spec/factories/dfe_sign_in/users.rb
spec/factories/payroll_runs.rb
spec/helpers/admin/claims_helper_spec.rb
spec/helpers/dfe_sign_in/user_helper_spec.rb
spec/models/payroll_run_spec.rb
spec/requests/admin_payroll_run_downloads_spec.rb
spec/requests/admin_payroll_runs_spec.rb

This is the final part of https://trello.com/c/fr9sNCXk/877-display-the-name-of-the-service-operator-who-took-an-action, and this displays the name of a user who has downloaded a Payroll Report. As with #731 and #744, if a user's details have been imported, it shows their full name, but if we haven't yet hit the API to import some user data, it shows the user's DfE Sign-In ID:
There is also a data migration to import any existing user IDs that are set on the `downloaded_by` column and convert them into a proper reference to a user object.

Display the name of the user who downloaded a payroll report

---

CHANGELOG.md

- Update to privacy policy to explain how data can be amended and add bullet point about collecting bank details
- Users can complete and submit a claim without completing GOV.UK Verify
- Update autocomplete attributes for the address capture page
- Application complete page and claim submitted email updated to include content for claimants that do not complete GOV.UK Verify
- Service operators can see who approved a claim
- Service operators can see who created a payroll run
- Fix a bug where users who spent more than 90 minutes in Verify would trigger a routing exception and not receive the session timeout message.
- Service operators can see who downloaded a payroll run

Release 043 🚢

---

CHANGELOG.md
app/models/maths_and_physics/school_eligibility.rb
spec/models/maths_and_physics/school_eligibility_spec.rb

The policy document says that schools in the West Somerset opportunity
area are eligible, but this is defined as contiguous with the (now
defunct) West Somerset local authority district. When the local
authority districts of West Somerset and Taunton were merged this local
authority district ceased to exist, and the new local authority district
which schools were moved to is not eligible.
Schools in the `EXPLICITLY_ELIGIBLE_SCHOOL_URNS` list are now treated as
being in an eligible local authority district. This is a list of schools
which are in the West Somerset opportunity area and which are eligible.

Eligible schools in the West Somerset opportunity area should be able to apply

---

spec/factories/claims.rb
spec/rails_helper.rb
spec/requests/admin_claims_spec.rb
spec/requests/admin_payment_confirmation_report_upload_spec.rb

We use the factories to seed our local development databases so we want to make sure they don't create claims that look the same and get flagged by our duplicate claim matching code. Reseting the sequences between each spec ensures they don't get so large that we end up generating
invalid TRNs or NI numbers.

Claims factory doesn't create potential duplicates

---

db/migrate/20200109115709_remove_claim_id_from_payments.rb
db/schema.rb

In 7092dbc we used this column to populate the newly-introduced payment_id
column on claims. Now that this commit has been released and the data
migrated, the claim_id column is no longer needed.

Remove claim_id from payments

---

bin/docker-entrypoint

Because of a recent Bundler update we need to make sure all our rake commands are prefixed with `bundle exec`.

Fix Docker entrypoint migration status check

---

CHANGELOG.md
app/assets/stylesheets/components/banner.scss
app/helpers/admin/claims_helper.rb
app/models/claim.rb
app/models/school_data_importer.rb
app/views/admin/claims/_info_panel_identity_unconfirmed.html.erb
app/views/admin/claims/index.html.erb
app/views/admin/claims/show.html.erb
db/migrate/20200108133802_add_phone_number_to_schools.rb
db/schema.rb
spec/factories/claims.rb
spec/factories/schools.rb
spec/features/admin_claim_check_spec.rb
spec/helpers/admin/claims_helper_spec.rb
spec/models/check_spec.rb
spec/models/claim_spec.rb
spec/services/school_data_importer_spec.rb

This re-enables the ability to approve claims that did not complete the GOV.UK Verify process.
This is different to how the story was initially outlined. For now we are keeping this super simple and expecting the identity check process to be carried out and managed as part of the existing spreadsheet-based claim checking. Unverified claims can be approved or rejected as before, but we now provide additional information to service operators for these claims:
**Highlight unverified claims on the claim list**
**Unverified claims include an info panel relating to the manual identity check**
**An additional warning is shown in the claim approve/reject form for unverified claims**
This also updates the `School` model and the import code to save school phone numbers so that we can show that to …

Service operators can approve GOV.UK Verify-skipped claims

---

bin/docker-entrypoint

When setting up a new environment we run "db:setup" which loads the db schema and seeds the database. The next time the container starts it attempts to run the data migrations, many of which fail to run.
Instead we should explicitly load the db and data schema files so no needless migrations are ran on subsequent deploys.

Fix database setup to load db and data schema files

---

CHANGELOG.md
app/models/claim.rb
app/views/claims/bank_details.html.erb
spec/models/claim_spec.rb

Cantium cannot process 6- and 7-digit bank account numbers (although these are technically valid).
This updates bank account validation to only accept exactly 8 digit numbers, as well as provide a more useful error message to the user.
Also updates the example bank account number to be more in line with the [design pattern](https://design-system.service.gov.uk/patterns/bank-details/).

Only accept 8 digit bank account numbers

---

Dockerfile
azure/templates/worker.json
bin/report-ip
bin/update-db-firewall-rules

Because we're having trouble with the preview ACI feature which allows us to deploy container groups into VNETs, we're trying another approach where we grab the IP address of the container group post-deploy and use this to manually update the firewall rules in Postgres. Hopefully this will be a better way to work with containers and mean we don't have to use poorly-supported preview features.

Manually set firewall rules for worker

---

bin/update-db-firewall-rules

When we were testing this on test we manually created the script in the `/bin` folder, that won't work with our script as it is stored in our project directory.

Use the relative script path for reporting the IP of the container

---

CHANGELOG.md
app/controllers/admin/payroll_runs_controller.rb
app/models/payment.rb
app/models/payroll_run.rb
spec/factories/payments.rb
spec/mailers/payment_mailer_spec.rb
spec/models/payment_spec.rb
spec/models/payroll/payment_csv_row_spec.rb
spec/models/payroll_run_spec.rb
spec/requests/admin_payroll_runs_spec.rb

This currently uses National Insurance number to identify a claimant.
Claims from the same claimant are grouped in to one payment in the payroll run. If any of the personal details on the claim don't match the payroll run will fail and will need some intervention from a developer. In the future we plan to catch these discrepancies earlier in the process so the user should never see the error when creating payroll run. The error message doesn't give much detail as to what claims don't match, however as it is just a stop-gap solution it should be ok.
**Open for discussion: We need to decide which of the personal details we care about not matching, currently we check them all but there may be some that legitimately differ like address.**

Group multiple claims from the same person into single payment

---

bin/report-ip
bin/update-db-firewall-rules

It's possible that the container instance could be in a "Waiting" state if it ran in to an error. This would break our script to fetch the IP address as you can only execute commands on a running container instance.
By restarting the container instance we can ensure that it will be "Running" when we execute our command to fetch the IP address.

Ensure container instance has restarted before fetching the IP

---

CHANGELOG.md
app/assets/javascripts/components/govuk_verify_auth_request_auto_submit.js
app/views/verify/authentications/new.html.erb

As we have observed in the past (e.g. commit 0f225f8), submitting the
same SAML request to Verify twice causes Verify to show a "Sorry,
something went wrong" error screen.
It was possible to submit the request twice by clicking the "Continue"
button on the `/verify/authentications/new` page after the JavaScript
auto-submit had been triggered. (I was able to reproduce this in a
browser, in our development environment, although not consistently.)
To prevent this, we take advantage of Rails' built-in prevention of
double-clicks (the `data-disable-with` attribute, which is set by
default), which disables the submit button once it is clicked. We change
the JavaScript so that it clicks the submit button instead of submitting
the form element.
We also change the page message so that once button …

Reduce the chance of user submitting Verify SAML form twice

---

CHANGELOG.md
app/assets/stylesheets/components/panel.scss
app/controllers/claims_controller.rb
app/controllers/concerns/part_of_claim_journey.rb
app/controllers/sessions_controller.rb
app/controllers/static_pages_controller.rb
app/helpers/application_helper.rb
app/mailers/claim_mailer.rb
app/mailers/payment_mailer.rb
app/views/claim_mailer/approved.text.erb
app/views/claim_mailer/rejected.text.erb
app/views/claim_mailer/submitted.text.erb
app/views/claims/existing_session.html.erb
app/views/payment_mailer/confirmation_for_multiple_claims.text.erb
app/views/payment_mailer/confirmation_for_single_claim.text.erb
config/locales/en.yml
config/routes.rb
spec/features/ineligible_student_loans_claims_spec.rb
spec/features/switching_policies_spec.rb
spec/requests/claims_spec.rb

When a user is in the middle of a claim, and tries to access the initial page of a new claim, they're now confronted with a warning telling them that they are in the middle of an application, and giving them the opportunity to start a new claim, or continue the claim they are currently making:
We've used the interruption card pattern, as outlined in the [Home Office Design System](https://home-office-digital-patterns.herokuapp.com/patterns/interruption-card), so this may need some looking over by @titlescreen before merge too.

Handling the situation where a user tries to claim for both policies at once

---

spec/features/admin_payroll_runs_spec.rb

Fix sporadically failing payroll runs feature spec
There is no connection between the ordering of PayrollRun#claims and
PayrollRun#payments, so if we wish to refer to the same payment multiple times
inside a spec then we need to consistently refer to only one of these
relations.
I ran the test suite ten times in a row without any failures, so
hopefully this is fixed.

Fix sporadically failing payroll runs feature spec

---

CHANGELOG.md
app/views/layouts/admin.html.erb
app/views/layouts/application.html.erb
public/404.html
public/422.html
public/500.html

As part of the internal accessibility audit, the website was run through a html validator and identified some places where we had set aria roles that were implicit due to the html elements we had already used.  
This PR just removes those un-needed roles that ARIA recommend we do not use.

1109 411 parsing no major code errors

---

azure/resource_groups/ProjectCore/template.json
azure/templates/worker.json

Now the issues with Azure's virtual networks and containers have been solved, we can now put the container back in the VN. We've had to rename the VN too, as the original network had some issues. This new name seems more descriptive now though.

Return worker container to virtual network

---

CHANGELOG.md
app/mailers/payment_mailer.rb
app/models/claim.rb
app/models/payment.rb
app/models/payment_confirmation.rb
db/data/20200114160644_add_payment_dates_to_payroll_runs.rb
db/data_schema.rb
db/migrate/20200114151353_add_scheduled_payment_date_to_payroll_runs.rb
db/schema.rb
spec/factories/payments.rb
spec/factories/payroll_runs.rb
spec/mailers/payment_mailer_spec.rb
spec/models/claim_spec.rb
spec/models/payment_confirmation_spec.rb

As discussed in #629, we thought it best to add a reliable way to see when a claim has / will be paid. Rather than gunk up the other PR, I've opened a new PR to do this, as there's extra work to be done with a data migration and refactoring the mailers.

Add a payment date to payroll runs

---

app/models/payment.rb

This was an accidental inclusion (in 2d7bf9b). It makes no behavioural
difference but it's confusing.

Remove NI number from attributes which we allow to be inconsistent

---

CHANGELOG.md
app/views/claims/_check_your_answers_section.html.erb
app/views/layouts/application.html.erb

This PR will amend the change links on the check your answers page so they will have an ARIA label to provide context for the link.
E.g. `Change which subject did you complete your initial teacher training in?`
This is important as the links will now provide context and let accessibility users know what question they are changing the answer to. We did consider adding some words before the question to help explain the possible janky-ness of the sentence being read out, but when testing with voice over, it was just adding extra words that didn't have much value and made it harder to focus on which question we are changing.

1108 2.4.4 link purpose in context every links purpose is clear from its context

---

CHANGELOG.md
app/views/claims/information_provided.html.erb
app/views/maths_and_physics/claims/eligibility_confirmed.html.erb
app/views/student_loans/claims/eligibility_confirmed.html.erb

We have a couple of links that are styled to look like buttons and have
the appropriate aria role so that screen readers will put them up
however, they do not function as a keyboard only user wold expect them
to. Users were unable to give the buttons focus and press space to
trigger them.
This PR swaps the links to be actual buttons so they will function as
expected.

Change links that look like buttons to be buttons

---

CHANGELOG.md

- Changed buttons on information-provided and eligibility confirmed pages to be actual buttons
- Check your answers page now has ARIA labels on the change buttons so screen readers will now tell users what they will change by visiting the link
- Removed unnecessary tags on main and footer elements that were causing warnings on validators
- A Payment date is set when a payroll run is ingested
- Backfill data about historic claims in Geckoboard

Release 045

---

CHANGELOG.md
Gemfile
Gemfile.lock
azure/resource_groups/app/parameters/development.template.json
azure/resource_groups/app/parameters/production.template.json
azure/resource_groups/app/parameters/test.template.json
azure/resource_groups/app/template.json
config/application.rb
config/puma.rb

Send _application_ logs to a Logstash instance hosted on LogIt.io, so that aggregated logs are searchable and more easily monitored.
This uses the [Rails Semantic Logger](http://rocketjob.github.io/semantic_logger/rails) gem to make the information which is pushed up to Logstash more structured and useful, as well as reducing log noise by turning a request from many log entries into one.
@lawrence-dxw  and I spent a good couple of hours dredging through Azure documentation and blog posts from across the web. Getting Docker logs into LogIt.io is a massive pain - the best we could come up with involves configuring Azure logging to write to a Storage Account, and then having a new worker with the Storage Account mounted and running FileBeat to pipe them into Logstash.
Find Teacher Training …

Add log aggregation to the service

---

bin/docker-entrypoint
lib/tasks/default.rake

When a new database is set up we want to make sure all existing data migrations are listed in the data_migrations table, otherwise they will be treated as having not been run and will be executed the next time `db:migrate:with_data` is called. This causes issues as some of the older data migrations will no longer execute because the schema has moved on since then.
By overriding the `db:setup` we make sure that a developer that runs that (as well as `db:reset`) will end up with a clean database where all migrations and data migrations are marked as having been executed.
Longer term I think we should look to remove the `data_migration` as a dependency altogether, as it is quite intrusive into Rails and has proved one of the more unreliable dependencies we use. Now we have console access we …

Override db:setup to play nicer with data migrations

---

CHANGELOG.md
app/jobs/purge_unsubmitted_claims_job.rb
app/models/claim.rb
spec/jobs/purge_unsubmitted_claims_job_spec.rb

This will run every day at midnight and remove any unsubmitted claims
that are more than 24 hours old so we don't hang on to user data that we
don't need and can't use.
Because this inheritts from `CronJob` it will automatically get picked
up and scheduled by `CronJobScheduler` when the `jobs:schedule` rake
task is run.
**Note: this PR delivers one part of the larger story around data purging and anonymising.**

Purge unsubmitted claims nightly.

---

CHANGELOG.md
app/models/claim/geckoboard_event.rb
spec/models/claim/geckoboard_event_spec.rb

After deploying #629, we got an error because there are now more than 500 sumbitted claims, causing Geckoboard to hit us with an error, as we can only submit 500 datapoints at a time. This adds batching functionality to the `GeckoboardEvent` class, so claims are batched into groups of 500.

Batch Geckoboard requests

---

CHANGELOG.md
app/assets/stylesheets/components/panel.scss
app/controllers/claims_controller.rb
app/controllers/sessions_controller.rb
app/views/claims/existing_session.html.erb
config/routes.rb
spec/features/switching_policies_spec.rb

This PR builds upon the existing interruption card that was used with
some usability improvements. We now ask the user if they want to abandon
their current claim and use radio buttons for them to select their
response.
We have also tided up some of the CSS that is no longer needed.

Change existing session to use radios

---

app/views/claim_mailer/submitted.text.erb

This better reflects the next steps that actually get taken when a user can't Verify using GOV.UK Verify.

Update next steps when not using Verify

---

azure/resource_groups/ProjectCore/parameters/development.json
azure/resource_groups/ProjectCore/parameters/production.json
azure/resource_groups/ProjectCore/parameters/test.json
azure/resource_groups/ProjectCore/template.json
azure/resource_groups/app/template.json
azure/resource_groups/secrets/template.json
azure/templates/database.json
bin/azure-deploy
docs/govuk-verify.md

To harden up our infrastructure a firewall has been added to our storage account and KeyVault.
This will affect developers viewing secrets in our KeyVault. It will require an extra step of adding your IP to the allow list on the firewall. For production this will require a PIM request. I've added some documentation to [confluence].(https://dfedigital.atlassian.net/wiki/spaces/TP/pages/1264418844/Secrets)
The storage account used by Postgres' security alerts is no longer needed so I've removed it.

Enable the firewall on our KeyVaults and storage accounts

---

azure/resource_groups/alerts/parameters/test.template.json
azure/resource_groups/alerts/template.json
azure/resource_groups/app/parameters/test.template.json
azure/resource_groups/app/template.json
azure/templates/app_alerts.json
azure/templates/availability_tests.json
azure/templates/database_alerts.json

Most of the alerts are intended to let us know that the application isn't working as expected. For the test environment we mainly care about if the infrastructure has deployed or not. eg. Alerts letting us
know that the CPU usage is high during a deployment are just noise.
I've left the service health alerts in there as they only happen when there's a problem with the infrastructure.

Disable application alerts in the test environment

---

CHANGELOG.md
app/views/layouts/application.html.erb

As the link opens in a new window or tab, we should tell the user this
so that they are not sent off somewhere unexpected.

Feedback link says it opens in new tab

---

app/views/claim_mailer/approved.text.erb
app/views/claims/information_provided.html.erb
app/views/static_pages/maths_and_physics.html.erb

This adds the copy set out in [this Miro board](https://miro.com/app/board/o9J_kvoqa7E=/?moveToWidget=3074457347131294063) to try and make it clearer about how we make and pay deductions when a teacher receives their money.
The pages now look like this:

Update the copy about deductions to make it clearer

---

azure/resource_groups/secrets/template.json
bin/azure-deploy

We considered making this automatic with another step of the script that checks to see if a soft-deleted KeyVault exists and change the `createMode` depending on the result.
However we decided against it. Deleting a KeyVault is quite a purposeful action, the expected result from the next deployment should error loudly to the user to let them know they need to either delete the KeyVault permanently or recover it explicitly.
The KeyVault can be recovered using the `--recover-keyvault` flag when calling the azure-deploy script.

Allow soft-deleted KeyVaults to be recovered with a flag

---

.env.development
CHANGELOG.md
Dockerfile
config/application.rb
config/initializers/logstash.rb

This allows for aggregated logs from different deployments to be distinguished in Logstash.

Add environment name tags to Logstash entries

---

app/jobs/school_data_importer_job.rb

We have been getting sporadic 500 responses from GIAS when we've been running this job at 4am. Having asked GIAS about it they have suggested we shift the job to 6am to minimise the chance that our request will clash with them refreshing the file.

Adjust schools import timing to 6am

---

CHANGELOG.md
app/assets/stylesheets/components/panel.scss
app/controllers/claims_controller.rb
app/views/claims/existing_session.html.erb
spec/features/switching_policies_spec.rb

This PR fixes some issues we found with existing session page.  
- If a user selects no option, they are not routed to complete their existing application.
- When no option is selected a user is shown a flash alert with guidance
- Radio options were reordered to be more logical and follow GDS guidance
- Buttons on interrupt cards will no longer turn green when they have been clicked on and are disabled whilst the next page loads
- Interrupt cards have a darker background colour to provide AAA contrast
- After some discussion, the test was kept in the feature spec

1211 setup error messages on claim in progress interruption page

---

README.md
app/jobs/geckoboard/update_unchecked_claims_job.rb
app/jobs/record_or_update_geckoboard_dataset_job.rb
app/models/check.rb
app/models/claim/geckoboard_dataset.rb
lib/tasks/geckoboard.rake
spec/models/check_spec.rb
spec/models/claim/geckoboard_dataset_spec.rb
spec/support/geckoboard_helpers.rb

This updates the Geckoboard dataset to add a `number_of_days_to_check` value, which gets updated when a claim is approved. This will then allow us to show the average number of days it takes a claim to be approved / rejected on our dashboard(s)

Record the mean time to reach a decision on a claim

---

CHANGELOG.md

- Fix existing session page so if no option is selected a user doesn't continue their claim
- Update Geckoboard with how many claims are passed their check deadline
- Log entries are now tagged with their deployed environment
- Record the the time in days between submitting and approving a claim
- Add a Rake task to update a Geckoboard dataset when a new field has been added

Release 047

---

Rakefile

We use the default Rake task as our standard invocation for running the
test suite and other code quality checks. We noticed that running
`bundle exec rake` was causing dotenv to use the ENVIRONMENT_NAME
variable from the .env.development file, and not .env.test as expected.
A recent change in 1d57789 to the values of ENVIRONMENT_NAME in
.env.development hence caused the tests to start failing when run
locally.
We found out that other people have also been experiencing this issue
[1]. The linked comment explains in detail what causes this to happen:
> Actually, I found that it will load `.env.test`, but because `.env.development` was already loaded before `.env.test`, and since `Dotenv.load` won't override the env var if it exist, it will use var defined in `.env.development` not …

Ensure that the default Rake task uses the `test` environment by default

---

config/application.rb
config/environments/production.rb

We've added the environment to our logs, but this was getting overridden by a config variable in production.rb which was appending the request ID to all logs. We can fix this by setting all the log tag in application.rb.

Fix environment not appearing in logs

---

CHANGELOG.md
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/gds_kit_tweaks.scss
app/assets/stylesheets/components/panel.scss
app/assets/stylesheets/components/school_search.scss
app/views/static_pages/accessibility_statement.html.erb
app/views/static_pages/maths_and_physics.html.erb

The GDS design system targets AA status due to the complexities and practicalities of what some services are. This PR tweaks parts of the design system and some of the custom components that we have added to provide the necessary contrast for us to achieve AAA status. 🤞
The main focus is the contrast on small text (anything under 24px) and mainly involves selecting darker colours for button and links etc to provide that contrast. Whilst the hover state of the govuk-buttons has been changed there is no contrast requirement between normal, hover and disabled states.

Changes to achieve AAA status

---

CHANGELOG.md

- QLS questions now refer to academic year, instead of "1 September"
- Styling tweaks to make the service AAA accessible. Accessiblity updated to  reflect AAA status
- Remove basic authentication on the Maths and Physics journey
- Update the "Claim submitted" page so all journeys link to the done page on GOV.UK
- Remove the temporary Maths and Physics start page and redirect to the one on GOV.UK
- New Maths and Physics feedback form link

Release 048

---

CHANGELOG.md
app/controllers/admin/claim_checks_controller.rb
app/controllers/admin/claims_controller.rb
app/models/claim.rb
app/models/claim/claims_preventing_payment_finder.rb
app/views/admin/claims/show.html.erb
config/locales/en.yml
spec/features/admin_claim_check_spec.rb
spec/models/claim/claims_preventing_payment_finder_spec.rb
spec/models/claim_spec.rb
spec/requests/admin_claim_checks_spec.rb

This implements the work hinted at in 2d7bf9b. If a service operator
views a claim for which there is a claim from the same claimant which
has been approved but not yet payrolled, and which has inconsistent
personal details which would prevent the two claims from being combined
into a single payment, then inform the service operator that this has
happened and prevent them from approving the claim.
This means that it is now unlikely that we will ever violate the
validations introduced on Payment in 2d7bf9b, but we keep them as an
additional safety net.
We still need to decide how a service operator can resolve this situation
of an inconsistent claim. For example, one option would be to contact
the claimant and ask them whether they are happy to be paid in two
different months or to ask …

Prevent service operator from approving an inconsistent claim

---

CHANGELOG.md
app/jobs/send_emails_after_three_weeks_job.rb
app/mailers/claim_mailer.rb
app/views/claim_mailer/update_after_three_weeks.text.erb
spec/jobs/send_emails_after_three_weeks_job_spec.rb
spec/mailers/claim_mailer_spec.rb
spec/mailers/previews/claim_mailer_preview.rb

Send emails every morning for claims which have been submitted three weeks ago (to the day).
This does not include any logic for retrying emails should a job fail, on the grounds that the emails themselves are purely advisory and don't form an integral part of the claim flow.

Auto email teachers 3 weeks after a claim is submitted

---

app/models/claim/school_check_email_data_export.rb
app/models/maths_and_physics/school_check_email_data_export_presenter.rb
app/models/student_loans/school_check_email_data_export_presenter.rb
lib/tasks/export.rake
spec/models/claim/school_check_email_data_export_spec.rb

Each month, a service operator sends a verification email to claimants'
schools, asking them to confirm some details of the claim.
In order to do the mail merge for this email, the service operator needs
a developer to provide them with an export of some of the data from the
submitted claims for which the email has not yet been sent. Until now,
we have been doing this as an ad-hoc process where Tekin would run
something in the Rails console.
Since our future plans are to either continue running this monthly
export, or to automate the subject check email, it makes sense to move
some of this ad-hoc process into the codebase.
This commit adds a Rake task that we can run to do the export. It takes
a list of claim references for which the email has already been sent
(this will be provided by …

Add Rake task to export data needed for school subject check email

---

CHANGELOG.md

- Prevent service operator from approving a claim if we would not be able to pay
it in the current payroll month because we are already paying the same
claimant for another claim with different payment details [1]
- Emails are sent for unchecked claims three weeks after they are submitted,
advising users that their claim is still in progress
- Developers can export data needed for school check mail merge
[1] I've moved this to the current release in the CHANGELOG; it was
originally accidentally added in the Release 047 section.

Release 049

---

CHANGELOG.md
app/models/claim/claims_preventing_payment_finder.rb
app/models/payment.rb
app/models/payroll_run.rb
spec/models/claim/claims_preventing_payment_finder_spec.rb
spec/models/claim_spec.rb
spec/models/payment_spec.rb
spec/models/payroll_run_spec.rb
spec/requests/admin_payroll_runs_spec.rb

Because of the restrictions of payroll, we can only make one payment to
an individual in a given month. Therefor if a user claims for more than
one policy, we need a way to combine their claims into a single payment.
Previously this was done by matching claims with the same
National Insurance number (NiNo), this commit switches that matching to
be based on the claimant's teacher reference number (TRN):
- Historically, users enter their TRN more reliably than NiNo so there
are few with errors, meaning fewer claims to have to correct
- There is no technically reason for us to be check the NiNo on claims
during claim checking except because of this matching. If we switch to
use the TRN instead, claim checkers can ignore the NiNo during claim
checking, giving them one less thing to worry …

Identify claimants by teacher reference instead of NI number

---

CHANGELOG.md
app/views/claim_mailer/update_after_three_weeks.text.erb
spec/mailers/previews/claim_mailer_preview.rb

I clocked that we were sending bare datetime strings to users when sending the three week emails:
I've fixed this, using the [I18n `l`](https://guides.rubyonrails.org/i18n.html#the-public-i18n-api) helper. The emails now look like this:

Fix reminder email date sent to user

---

CHANGELOG.md

- Claim award amount is now sent to the Geckoboard dataset
- Identify claimants by teacher reference number instead of NI number
- Fix date sent to user in three week reminder email
- Better handling of issues related to browser caching and session expiration/
timeouts

Release 050 🎉

---

CHANGELOG.md
app/assets/javascripts/components/school_search.js.erb
app/controllers/claims_controller.rb
app/controllers/school_search_controller.rb
app/models/school.rb
app/views/claims/_school_search.html.erb
spec/models/school_spec.rb
spec/requests/claims_spec.rb
spec/requests/school_search_spec.rb

The current school search only works if the search query you type matches exactly to part of the school's name. We've seen some queries come in to support where the user hasn't been able to find their school because the thing they've typed doesn't match exactly to the information in Get Information About Schools (eg. They omit an apostrophe).
This PR:
- allows users to search by typing the partial or full postcode of their school
- reduces the minimum character length of the search to 3 so the user doesn't have to remember the postcode sector

Allow claimants to search by school postcode

---

app/helpers/admin/claims_helper.rb
spec/helpers/admin/claims_helper_spec.rb

Previously, the `matching_attributes` helper was returning any attributes that were a blank string as 'matching'. This strips out any blank attributes before comparing.

Stop blank attributes showing as matching

---

CHANGELOG.md
app/models/claim.rb
app/models/claim/geckoboard_dataset.rb
spec/models/claim/geckoboard_dataset_spec.rb
spec/support/geckoboard_helpers.rb

Replaces a boolean "has this claim passed its check deadline" with a string representing the state of the claim relative to the deadline. A claim can either be "ok", "warning" or "passed".

Add "approaching SLA" state to Geckoboard dataset

---

app/helpers/claims_helper.rb
spec/helpers/claims_helper_spec.rb

This makes it so that visiting the check-your-answers page without having fully completed a claim will not result in an exception.
It's not something that should happen under normal usage, but we have seen at least one exception raised by a user visiting the check-your-answers page with a claim that doesn't have a value for
date_of_birth. This updates the helper that displays the answer for the question such that it won't raise an exception if the value is nil.

Check-your-answers copes with blank date-of-birth

---

CHANGELOG.md

- Allow claimants to search by school postcode
- Replace "passed SLA deadline" true/false with ok/warning/passed status in Geckoboard dataset
- Schools check email export no longer includes claims which have been checked
- Schools check email export now includes the claim school for claims made under the Student Loans policy

Release 051

---

azure/resource_groups/app/parameters/development.template.json
azure/resource_groups/app/parameters/test.template.json

Until now we have been putting all Rails logs into a single Logit stack.
We have been using the named_tags.environment field to distinguish
between log entries from production, development, test, and local
development. This means that we have to make sure that our Logstash
logger is always populating this field correctly, and we found out that
it is not. I will soon make a commit which fixes this.
But, for an extra level of safety, to make sure that production logs
don't get mixed up with non-production logs, we have decided to separate
them completely by using a separate Logit stack.
This commit sets the non-secret LOGSTASH_PORT environment variable. To
use the new Logit stack, we also need to change the value of
LOGSTASH_HOST in the development and test key vaults. I will do this
before …

Use a separate Logit stack for non-production environments

---

CHANGELOG.md
app/controllers/admin/payments_controller.rb
app/helpers/admin/payment_helper.rb
app/models/payment.rb
app/models/payment_confirmation.rb
app/models/payroll_run.rb
app/views/admin/payments/destroy.html.erb
app/views/admin/payments/remove.html.erb
app/views/admin/payroll_runs/index.html.erb
app/views/admin/payroll_runs/show.html.erb
config/locales/en.yml
config/routes.rb
spec/features/admin_payroll_runs_spec.rb
spec/models/payment_confirmation_spec.rb
spec/requests/admin_payroll_run_payments_spec.rb

This allows service operators to remove payments from a Payroll Run if Cantium have confirmed there is some problem (i.e. incorrect bank details) that has stopped a payment from taking place. I've also updated the guidance that a user sees if a payment has been missed off and the confirmation report cannot be uploaded.
Once a confirmation report has been uploaded, it's no longer possible to remove payments from a run

A Service Operator can remove problematic payments from a payroll run

---

config/application.rb
config/initializers/logstash.rb
lib/environment_log_formatter.rb
spec/lib/environment_log_formatter_spec.rb

We want to make sure that the named_tag.environment field is included in
all log entries sent by our application. It’s the only way for us to
distinguish between log entries from local development (if enabled),
development or test. This is because log entries from those environments
all go into the same Logit stack.
Until now we have relied on config.log_tags, but this only affects
request logging. This means that other messages such as custom log
messages, or Active Job's automatic start / end messages, do not get
tagged properly. So, we set up a custom SemanticLogger formatter which
appends the tag. This means that all calls that use the Rails logger now
send this field.
I’ve removed the fallback to sending a value of “unspecified” - I cannot
think of a legitimate time when the …

Make sure Logstash entries are always tagged with environment name

---

README.md
app/jobs/heartbeat_job.rb

We'll use the presence of this log message as evidence that the worker container is working correctly. We'll set up an alert in LogIt.io which sends us an email if too much time passes without observing one of these log messages.

Add a heartbeat job which emits a log message every minute

---

app/assets/javascripts/components/timeout_dialog.js
app/controllers/admin/base_admin_controller.rb
app/controllers/admin/sessions_controller.rb
app/controllers/application_controller.rb
app/controllers/base_public_controller.rb
app/controllers/concerns/admin_session_timeout.rb
app/controllers/sessions_controller.rb
app/views/application/_timeout_dialog.html.erb
app/views/layouts/admin.html.erb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/admin_timeout_spec.rb
spec/requests/admin_sessions_spec.rb
spec/requests/admin_timeout_spec.rb
spec/requests/sessions_spec.rb

We picked up a bug in development, where we noticed that it was possible to extend an admin session by visiting a page on the public side of the site.
The seperates out the management of `last_seen_at` into two parts - one to handle admins, and one to handle public users. When a user carries out an action on the public side, this updates `session[:last_seen_at]` and when a user carries out an action on the admin side, this updates `session[:admin_last_seen_at]`.
I've also seperated out the `SessionsController`s, which are used when a user using Javascript opts to extend their session. This means that both the admin and application layouts now pass an additional`refresh_session_path` variable, which is sent to the JS via data attributes, and tells the frontend code which URL to send a …

Don't share the last seen at session variables

---

db/migrate/20200210162032_remove_checked_by_from_decisions.rb
db/migrate/20200210162349_remove_created_by_from_payroll_runs.rb
db/migrate/20200210163354_remove_downloaded_by_from_payroll_runs.rb
db/schema.rb

This removes a bunch of redundant columns from before we were modelling the the actions of signed-in admin user as an association with a `DfeSignin::User` record: https://trello.com/c/fr9sNCXk/644-display-the-name-of-the-service-operator-who-took-an-action
One old-style string-based ID column remains: `confirmation_report_uploaded_by`. That hasn't been converted to the new-style of association and will get tackled as a separate piece of work.

Tidy up redundant columns

---

app/controllers/verify/authentications_controller.rb
app/models/claim.rb
app/models/claim/verify_response_parameters_parser.rb
db/migrate/20200211105406_remove_verify_response_from_claim.rb
db/schema.rb
spec/factories/claims.rb
spec/features/govuk_verify_spec.rb
spec/models/claim/verify_response_parameters_parser_spec.rb
spec/models/claim_spec.rb

This was introduced when we first started integrating with Verify, as we didn't have a huge amount of confidence in the data it would return, so kept the raw response against a claim too. It has come in handy in the past, but, as the Verify integration is more or less stable, it makes less sense (and is a big risk) for us to be storing this much PII, so we should remove it.

Remove `verify_response` from a Claim

---

app/assets/javascripts/components/school_search.js.erb

Out of the box, the Rails `submit_tag` helper sets a `data-disable-with` value, which tells the Unobstructive Javascript Scripting Adapter what to set the input's value to when disabling the submit button after it is clicked. In our JS, we don't change this when changing the value, so whe a user clicks on the "Continue" button, it switches back to "Search". This updates the JS so the `data-disable-with` attribute is changed whenever the value of the submit button is changed.

Fix school search button text changing when submitting

---

azure/templates/app_alerts.json
azure/templates/database_alerts.json

Reduces the sensitivity of Azure alerts.
* CPU and Memory alerts now trigger at 80% average usage sustained over 15 minutes (was previously 5 minutes).
* HTTP 500 errors now trigger at three or more errors within a minute (was previously two or more)

Reduce sensitivity of Azure alerts

---

app/views/claims/student_loan.html.erb
app/views/claims/student_loan_country.html.erb
app/views/claims/student_loan_how_many_courses.html.erb
app/views/claims/student_loan_start_date.html.erb
app/views/student_loans/claims/student_loan_amount.html.erb

This adds a couple of small improvements to the flow in the student loans questions, moving the explanation to a details component, and adding subheadings to every question in the flow.

Implement usability improvements for the student loans questions

---

config/locales/en.yml

This makes it clearer that the service operator doesn't need to carry out any other actions other than contacting the claimant in order to get the claim added to the next pay run.

New copy when claim has been removed from payrun

---

lib/generators/data_migration/data_migration_generator.rb

Before this change the generated data migration would not include the file extension in the `rails runner` line for running the data migration.

Ensure file extension appears in data migration

---

CHANGELOG.md

- Don't share the last seen at session variables
- Fix bug causing school search button text to change when user clicks on it
- Add subheader to student loans questions
- Add a component saying why ask about student loans
- New copy when claim has been removed from payrun

Release 053

---

CHANGELOG.md
app/views/admin/claims/show.html.erb
config/locales/en.yml
spec/features/admin_claim_check_spec.rb

Where a claim has had a decision made, do not show the message about needing a payroll gender to make a decision.

Hide unknown gender warning for decided claims

---

app/views/claim_mailer/submitted.text.erb
app/views/submissions/show.html.erb
spec/requests/submissions_spec.rb

This iterates the content (as outlined on this [Miro Board](https://miro.com/app/board/o9J_kwZcKg4=/?moveToWidget=3074457347168565426)) to make it clearer about next steps when a user cannot be verified using GOV.UK Verify.
\

Iterate content on the Verify without Verify journey

---

azure/resource_groups/app/parameters/development.template.json

As part of the work to reduce Azure alerts we should try to gain as much
parity between development and production as possible.
One of our alerts "High response time" commonly happens on development
but not on production. My theory is that the high response is caused
from the app service warming up from cold triggering the alert.
I've checked and there's no cost difference for having the resource
set to always on.

Make the development app service alwaysOn

---

app/controllers/base_public_controller.rb
app/controllers/concerns/part_of_claim_journey.rb
app/controllers/verify/authentications_controller.rb
app/helpers/application_helper.rb
app/models/claim.rb
app/models/policy_configuration.rb
db/data/20200212151005_set_current_academic_year_on_policy_configurations.rb
db/data/20200212154927_set_academic_year_on_claims.rb
db/migrate/20200212150805_add_current_academic_year_to_policy_configurations.rb
db/migrate/20200212154529_add_academic_year_to_claims.rb
db/schema.rb
spec/fixtures/policy_configurations.yml
spec/requests/claims_spec.rb
spec/support/request_helpers.rb

This lays some of the groundwork for supporting future academic years in the service, specifically it prepares the way for adjusting the QTS question to reflect the qualifying years that are eligible. What this PR covers:
- Introduces a `PolicyConfiguration#current_academic_year` attribute to represent the year each service currently is accepting claims for
- Introduces a `Claim#academic_year` attribute so we know the academic year each claim was made in
There are also two data migrations to run when this ships to backfill the data:
- `rails runner db/data/20200212151005_set_current_academic_year_on_policy_configurations.rb` to set current_academic_year to "2019/2020" for the two policies
- `rails runner db/data/20200212154927_set_academic_year_on_claims.rb` to back-fill all existing …

Introduce academic year modelling on policies and claims

---

Procfile
README.md
app.json
docs/heroku.md

We've had review apps set up for a while now, and they haven't worked properly. This fixes them up to use the correct buildpacks, as well as a script that correctly bootstraps the database, so we can use the app.

Update Heroku configuration to enable acceptance testing apps

---

docker-compose.test.yml

The `postgres` Docker image now requires a password to be set, so this sets a `POSTGRES_PASSWORD` env variable in the `db` container, and a corresponding `DFE_TEACHERS_PAYMENT_SERVICE_DATABASE_PASSWORD` var in the `test` container.
More info here https://github.com/docker-library/postgres/issues/681

Fix Docker test runs in CI

---

CHANGELOG.md
app/controllers/admin/policy_configurations_controller.rb
app/controllers/concerns/part_of_claim_journey.rb
app/helpers/admin/policy_configurations_helper.rb
app/models/claim.rb
app/models/policy_configuration.rb
app/views/admin/policy_configurations/edit.html.erb
app/views/admin/policy_configurations/index.html.erb
app/views/application/_admin_menu.html.erb
db/seeds.rb
spec/factories/claims.rb
spec/features/admin_configure_services_spec.rb
spec/helpers/admin/policy_configurations_helper_spec.rb
spec/models/claim_spec.rb
spec/models/policy_configuration_spec.rb

This updates the admin interface so that service operators can change the academic year that each policy is accepting claims for:
This is the second part of the work to support future claim years. The final part is to update the claimant journey and eligibility so that they reflect the academic year for which claims are being accepted for.

Allow service operators to change the current academic year on a policy

---

CHANGELOG.md
app/assets/stylesheets/components/task_list.scss
app/controllers/checks_controller.rb
app/models/maths_and_physics/admin_checks_presenter.rb
app/models/student_loans/admin_checks_presenter.rb
app/views/admin/checks/_claim_summary.html.erb
app/views/admin/checks/employment.html.erb
app/views/admin/checks/index.html.erb
app/views/admin/checks/qualifications.html.erb
app/views/admin/claims/_answer_section.html.erb
app/views/admin/claims/show.html.erb
config/locales/en.yml
config/routes.rb
spec/features/admin_claim_check_spec.rb
spec/models/maths_and_physics/admin_checks_presenter_spec.rb
spec/models/student_loans/admin_checks_presenter_spec.rb
spec/requests/admin_checks_spec.rb
spec/routes/routes_spec.rb

We chose to start with qualification and employment checks as they are common to each policy, with the exception that StudentLoans has some additional information but we can tackle that later.
Eventually we'll get to a point where a service operator can mark these checks as completed or not.

Introduce qualifications and employment checks

---

CHANGELOG.md
app/assets/stylesheets/components/text.scss
app/helpers/admin/claims_helper.rb
app/jobs/delete_pii_from_old_claims_job.rb
app/models/claim.rb
app/models/claim/pii_scrubber.rb
app/views/admin/claims/show.html.erb
db/migrate/20200205144103_add_pii_removed_at_timestamp.rb
db/schema.rb
spec/factories/claims.rb
spec/features/admin_claim_check_spec.rb
spec/helpers/admin/claims_helper_spec.rb
spec/jobs/delete_pii_from_old_claims_job_spec.rb
spec/models/claim/pii_scrubber_spec.rb

Claims will now have PII automatically removed from the database approximately two months after they are either rejected or paid.
Admins who view a claim which has had PII removed will be informed of the change to the claim.

Automatically remove PII from claims

---

bin/azure-console

Quick tweak to allow the `azure-console` script to access the test environment

Azure console script can access test environment

---

.dockerignore
Dockerfile
app.json

This is only for the test target and ensures that all the files that
could be linted locally are also linted on CI. We need to be mindful
of files that get added to the project, if they are secrets or
superfluous we should add them to the .dockerignore file.
This change doesn't increase the size of the Docker image by much but it
will increase build times slightly because of the way that Docker
caches layers of a Dockerfile, whenever a file is changed it will need
to redo that copy step.

Ensure prettier checks all the files in the project on CI

---

CHANGELOG.md
Gemfile
Gemfile.lock
azure/resource_groups/app/parameters/development.template.json
azure/resource_groups/app/parameters/production.template.json
azure/resource_groups/app/parameters/test.template.json
azure/resource_groups/app/template.json
azure/templates/app.json
bin/start-worker

This updates the worker container to run a command that spawns two worker processes and then tails the logs, so we can see what's going on. I don't think specifying the delayed_job log file location will interfere with logit, but I'll keep an eye on it.

Run two concurrent worker processes

---

azure/templates/app.json
bin/start-worker

The change in #874 explicitly launches the worker with `RAILS_ENV` set to `production`. It does this by overriding the `ENVIRONMENT_NAME` variable in the local scope of the worker boot script, instead of just lifting it from the global environment.
This changes that behaviour, so it relies on the `ENVIRONMENT_NAME` which is defined in the ARM templates.

Do not explicitly set worker environment name

---

config/locales/en.yml

This changes the result of I18n.format(Time.current) from e.g.
<pre>"20 February 2020  3:11pm"</pre>
to
<pre>"20 February 2020 3:11pm"</pre>
The repeated whitespace has no effect on the output when rendered in a
web browser. However, it makes it difficult to check for the presence of
a formatted time when writing a feature spec, since the have_content
matcher will not detect a string with repeated whitespace.
The hyphen is explained in the documentation for Time#strftime.

Don’t pad formatted hours with whitespace

---

CHANGELOG.md
app/helpers/application_helper.rb
app/views/admin/checks/employment.html.erb
app/views/admin/checks/index.html.erb
app/views/admin/checks/qualifications.html.erb
app/views/admin/claims/index.html.erb
app/views/admin/claims/search.html.erb
app/views/admin/claims/show.html.erb
app/views/admin/page/index.html.erb
app/views/admin/payroll_runs/index.html.erb
app/views/admin/payroll_runs/new.html.erb
app/views/admin/payroll_runs/show.html.erb
app/views/admin/policy_configurations/edit.html.erb
app/views/admin/policy_configurations/index.html.erb
app/views/layouts/admin.html.erb

This is the first of several PRs to fix accessibility issues within the claim admin area. It is looking at the A level of accessibility and includes
- fixing the order of headers
- ensuring inputs have associated headers
- checking that table headers do not have empty <th>
- Adding in meaningful page titles to individual pages

1025 accessibility testing admin area

---

app/models/claim/pii_scrubber.rb
spec/models/claim/pii_scrubber_spec.rb

Resolves a few issues with scrubbing PII from old claims:

Resolve bugs with scrubbed claims

---

CHANGELOG.md
app/models/reference.rb
config/locales/en.yml
spec/services/reference_spec.rb

- Don't use "1" or "I" characters in claim references to avoid confusion
- Adjust option for not teaching eligible subjects for student loans

Two small changes

---

CHANGELOG.md

- Fix skipped heading level on manage services screen
- Add label to Payroll Cantium link
- Fix empty th on view claims screen
- Add page titles to admin area
- Run multiple worker instances so long-running queued jobs don't entirely block
the queue
- Don't use "1" or "I" characters in claim references to avoid confusion
- Adjust option for not teaching eligible subjects for student loans

Release 055

---

CHANGELOG.md
app/controllers/admin/checks_controller.rb
app/models/check.rb
app/models/claim.rb
app/views/admin/checks/_check_outcome.html.erb
app/views/admin/checks/employment.html.erb
app/views/admin/checks/index.html.erb
app/views/admin/checks/qualifications.html.erb
config/routes.rb
db/migrate/20200219154337_create_claim_checks.rb
db/schema.rb
spec/factories/checks.rb
spec/features/admin_claim_check_spec.rb
spec/models/check_spec.rb
spec/requests/admin_checks_spec.rb

This allows service operators to mark each check of a particular type as completed, their name and the time of the the action will be displayed on the check page.

Allow service operators to mark a check as completed

---

CHANGELOG.md
app/models/school.rb
spec/models/maths_and_physics/school_eligibility_spec.rb
spec/models/school_spec.rb
spec/models/student_loans/school_eligibility_spec.rb

We determine state funded schools by two pieces of information: the school type group and the school type. We explicitly rule out schools that have a type group of independent as not being state funded. However it turns out that City Technology Colleges are state funded and
have a type group of independent. 
We have another card in the backlog to look at any other types of state funded schools that we're missing from our rules.
City Technology Colleges have a phase of "not_applicable", however they do teach secondary age students. We can determine this by looking at the statutory high age for the school.
Example of a City Technology College: "Emmanuel College" (URN 108420)
```
irb(main):002:0> MathsAndPhysics::SchoolEligibility.new(School.find_by(urn: "108420")).eligible_current_school? …
```

Update school eligibility to include City Technology Colleges

---

CHANGELOG.md
app/controllers/admin/checks_controller.rb
app/views/admin/checks/_claim_summary.html.erb
app/views/admin/claims/index.html.erb
spec/features/admin_claim_check_spec.rb
spec/requests/admin_checks_spec.rb

This is a temporary step to encourage service operators to check Maths and Physics claims using the new "checks" or "tasks" interface.

Maths & Physics claims use new tasks interface

---

CHANGELOG.md
app/models/payment_confirmation_csv.rb
spec/models/payment_confirmation_csv_spec.rb

The Payment Confirmation Report that Cantium sent for February 2019
contains a byte order mark. We weren't stripping out these characters
so the CSV was failing to parse correctly.
By passing an encoding of "BOM|UTF-8" to `CSV#read` we can handle when
a byte order mark is both present and absent.
https://bugs.ruby-lang.org/issues/15210

Handle byte order mark when reading payment confirmation CSV

---

azure/templates/app.json
azure/templates/vsp.json

The presence of `linuxFxVersion` (which is the Docker image) is telling the app service to deploy straight away. If we remove this, it keeps the previous version running in the background and only pulls down the latest version and starts the container once the slots have been swapped.

Remove `linuxFxVersion` from app service

---

CHANGELOG.md
app/controllers/admin/checks_controller.rb
app/controllers/admin/decisions_controller.rb
app/views/admin/claims/_claims_with_matching_details.html.erb
app/views/admin/claims/show.html.erb
app/views/admin/decisions/_decision_form.html.erb
app/views/admin/decisions/new.html.erb
config/routes.rb
spec/features/admin_claim_check_spec.rb
spec/requests/admin_checks_spec.rb
spec/requests/admin_decisions_spec.rb

As part of the changes to the new admin checks we want to show the claim decision form after the last check has been completed. There's currently no other way to get to this page, this might need revisiting later.
We've included the warnings associated with making a decision on a claim in the new decision form. The idea is to move these warnings in to their own checks, but until we get there it's important information for a service operator deciding on a claim's outcome.
Prototype for reference: https://fast-shelf-85846.herokuapp.com/claim/student-loan/decision

Claim decision page is shown at the end of the checks process

---

CHANGELOG.md
app/assets/stylesheets/components/_timeline.scss
app/assets/stylesheets/components/gds_kit_tweaks.scss
app/controllers/admin/amendments_controller.rb
app/helpers/admin/amendments_helper.rb
app/helpers/admin/timeline_helper.rb
app/models/amendment.rb
app/models/claim.rb
app/models/claim/pii_scrubber.rb
app/views/admin/amendments/new.html.erb
app/views/admin/amendments/not_amendable.html.erb
app/views/admin/checks/_claim_summary.html.erb
app/views/admin/claims/_amendments_timeline.html.erb
app/views/admin/claims/show.html.erb
config/routes.rb
db/migrate/20200217165600_create_amendments.rb
db/schema.rb
spec/factories/amendments.rb
spec/features/admin_amend_claim_spec.rb
spec/helpers/admin/timeline_helper_spec.rb
spec/models/amendment_spec.rb
spec/models/claim/pii_scrubber_spec.rb
spec/models/claim_spec.rb
spec/requests/admin_amendments_spec.rb
spec/requests/admin_claims_spec.rb

This adds an "Amend claim" button which service operators can use to amend certain attributes of a claim. The commit messages give lots of information about this and why we're doing it.
There are couple of technical things I was hoping for opinions on; I've left comments on the PR. Nothing massive.

A service operator can amend a claim

---

CHANGELOG.md
public/404.html
public/422.html
public/500.html

The 404, 422 and 500 pages contain broken links and hardcoded references to the student loans policy. This PR makes them more generic. More details in commit messages.

Make static error pages policy-agnostic

---

CHANGELOG.md

- QTS question will vary based on the year the service is accepting claims for
- QTS answer will vary in admin based on the year the claim was made
- Claim decision page is shown at the end of the checks process
- A service operator can amend a claim
- Update static error pages (404, 422, 500) to make them policy-agnostic

Release 057

---

CHANGELOG.md
app/views/static_pages/closed_for_submissions.html.erb

This sentence is potentially confusing for users that have missed the claim window as it suggests they'll be able to claim for the current year when the claim window re-opens for the next year.

Remove the last sentence from closed page

---

azure/resource_groups/alerts/template.json
azure/resource_groups/app/template.json
azure/templates/app.json
azure/templates/app_alerts.json
bin/azure-deploy

Unfortunately `CpuPercentage` and `MemoryPercentage` metrics aren't
available for container instance monitoring. We have to use `CpuUsage` and
`MemoryUsage` instead, this means the threshold has to be a concrete
value rather than a proportion.
- CpuUsage is measured in millicores (1,000 per core)
- MemoryUsage is measured in bytes (1,000,000 per MB)
I've set the values as 800 millicores (80% of our 1 core) and
1200MB (80% of our 1500MB available memory).
We could parameterise these units in the container instance deploy and
pass them in to the app_alerts.json then use `[mul(value, 0.8)]` however
these values aren't likely to change so it feels like overkill.
https://docs.microsoft.com/en-gb/azure/azure-monitor/platform/metrics-supported#microsoftcontainerinstancecontainergroups

Add CPU and memory alerts for worker container instance

---

db/migrate/20200304101213_remove_confirmation_report_uploaded_by_from_payroll_runs.rb
db/schema.rb

This removes the `confirmation_report_uploaded_by` column from the PayrollRuns table, which has been superceded by the `confirmation_report_uploaded_by_id` column, which references an actual user in the database.

Remove old column from Payroll Runs

---

Dockerfile
azure-pipelines.yml
config/initializers/rollbar.rb

When investigating a previous error in Rollbar, I wanted to know which
version of the code was running when the error occurred. We can achieve
this by setting Rollbar’s `config.code_version`.
I think it makes sense to bake the Git commit hash into the Docker
image, since it provides metadata about which code is contained inside
the image and the context in which the image was built. I’ve put the
ENV instruction below the COPY instructions for caching reasons, since
the commit hash changes more frequently than the copied files.
I haven’t found a way to test this end to end. I’ve confirmed that the
`web` image built by CI, which gets pushed to Docker Hub, contains the
GIT_COMMIT_HASH environment variable, but I don't know if there's an
easy way to actually test that the exceptions triggered …

Expose Git commit hash in Rollbar

---

app/controllers/admin/claims_controller.rb
app/controllers/admin/decisions_controller.rb
app/models/claim.rb
app/models/claim/pii_scrubber.rb
app/models/decision.rb
spec/factories/claims.rb
spec/features/admin_claim_check_spec.rb
spec/models/claim_spec.rb
spec/models/decision_spec.rb
spec/requests/admin_payroll_runs_spec.rb

This lays the groundwork for decisions being undoable (setting the claim back to an undecided status) and allowing a subsequent change of decision whilst still retaining a complete history of decision changes.
The new `decision` method returns the latest decision on a `Claim`, and is functionally identical to current behaviour.
There is one notable pair of changes to specs, which is the removal of the spec ensuring payroll runs cannot be generated when there would be two claims containing the same personal details but different bank numbers. Reaching this point should not be possible, as claims with matching details but different bank numbers cannot be approved. This behaviour is now explicitly tested in `decision_spec.rb` to prevent regressions.
The original test now fails where it …

Allow claims to have multiple decisions

---

azure/resource_groups/app/template.json
bin/azure-deploy
bin/docker-release

This updates our deployment script to deploy the Docker images that have been tagged with build numbers directly. 
Previously we'd pull down the image that has been tagged with a specific build number, and then tag it with `development` or `production` as part of our deployment process. This caused problems because once an infrastructure deploy had happened, this triggered a restart on our app services, which then pulled down the latest version of the code, rather than waiting for the slots to be swapped over. 
Doing it this way ensures that each version of the app service is tightly coupled to the version of the code, so changes don't sneak in too early.
**Once this is approved, I'll need to make changes to the deployment script before merging.**

Get the Azure deployment slots feature working

---

CHANGELOG.md
app/assets/stylesheets/components/tag.scss
app/views/admin/checks/index.html.erb
spec/features/admin_claim_check_spec.rb
spec/requests/admin_checks_spec.rb

Currently if a service operator exits the journey on the last check they
are unable to navigate back to the decision page.
So that service operators can get back to the decision page at any time
we now include a link to the decision on the index of tasks
along with the result of the decision if there is one.
I've extracted out `govuk-tag--warning` and `govuk-tag--alert` as these
supplement the GOV.UK tag component and reused the classes in our
custom tag component styles.
The link to "Approve or reject this claim" exists on claims that already
have a decision. If a user clicks this link on decided claims they will
see a notice saying "Claim outcome already decided" and redirects to
the claim#show page. This isn't a great user experience but it's a bit
of an edge case in the current …

Allow service operators to navigate to decision page

---

CHANGELOG.md
app/assets/stylesheets/components/tag.scss
app/helpers/admin/claims_helper.rb
app/views/admin/amendments/new.html.erb
app/views/admin/payments/remove.html.erb
spec/helpers/admin/claims_helper_spec.rb

This is the last of the PRs for accessibility within the Admin area. I think the current outstanding items would be for a level higher than we need and more costly to implement than we have time to spend.
The main change has been to the Verify without Verify tag shown when viewing claims, which can be seen below. The commit provides some more in-depth information on this.
I have also changed the code on the cancel buttons that are styled to look like links, this allows the baked in JS that comes with the design system to honour the expected keyboard behaviour to trigger these buttons.

Accessibility testing admin area part 3

---

azure-deploy-template.yml
azure-pipelines.yml

This commit refactors the CI pipeline so it has three distinct stages:
- The first stage is as before - build the Docker container and run tests
- The second stage then only runs on a push to the master branch, and deploys the app to development
- The third stage only runs when a tag has been pushed, and this deploys the app to production
Both deploy stages use the `azure-deploy-template.yml` file, which DRYsthings up quite a bit.

Run deployment as part of the CI pipeline

---

azure-deploy-template.yml

We had a hardcoded `test` environment name, which has busted development deploys. This should fix it.

Fix Development deploys

---

CHANGELOG.md
app/views/admin/payroll_runs/index.html.erb
app/views/claims/_school_search_results.html.erb
app/views/claims/timeout.html.erb
app/views/layouts/admin.html.erb
app/views/layouts/application.html.erb
app/views/student_loans/claims/_ineligibility_reason_ineligible_claim_school.html.erb
app/views/student_loans/claims/_ineligibility_reason_not_taught_eligible_subjects.html.erb
app/views/verify/authentications/failed.html.erb
app/views/verify/authentications/no_auth.html.erb

This adds some attributes to links that are styled as buttons so that
they will function as expected for keyboard users (press space to
trigger when it has focus).
This does not work for users that do not have JS enabled.

Links that looks like buttons work on keyboard

---

app/models/claim/matching_attribute_finder.rb
app/views/admin/claims/_claims_with_matching_details.html.erb
app/views/admin/claims/show.html.erb
config/locales/en.yml
spec/features/admin_duplicate_claims_spec.rb
spec/models/claim/matching_attribute_finder_spec.rb

We've had reports of a number of false positives when searching for matching attributes, because a number of applicants are eligible for both policies.
This adds the source claim's policy to the `claims_to_compare` query, ensuring that only claims for the source claim's policy are returned when searching for potential duplicate claims.
I've also removed the optional `claims_to_compare` parameter as it's not used anywhere, and complicates the class somewhat without any real benefit.
This also comes with some slight copy tweaks, which should make things easier to understand:

Exclude claims for the other policy from claims with matching details

---

CHANGELOG.md
app/views/student_loans/claims/claim_school.html.erb

This was accessing the locale directly, instead of using the question helper, which was resulting in a visual regression for the question as the `financial_year` interpolation value wasn't being provided.

Use question helper when displaying search results

---

CHANGELOG.md
app/assets/stylesheets/components/gds_kit_tweaks.scss
app/controllers/admin/decisions_controller.rb
app/models/claim.rb
app/views/admin/checks/employment.html.erb
app/views/admin/checks/index.html.erb
app/views/admin/checks/qualifications.html.erb
app/views/admin/decisions/_incomplete_checks.html.erb
app/views/admin/decisions/new.html.erb
config/locales/en.yml
spec/models/claim_spec.rb
spec/requests/admin_decisions_spec.rb

This adds a list of incomplete checks to the `admin/decisions#new` screen. If a service operator goes to the decision screen before completing all the checks, they will see this warning.
More details in commit messages.

Show incomplete checks warning on decision screen

---

spec/features/admin_checks_maths_and_physics_claim_spec.rb
spec/features/admin_checks_student_loan_claim_spec.rb
spec/features/admin_claim_check_spec.rb
spec/features/admin_claim_with_inconsistent_payroll_information_spec.rb
spec/features/admin_claim_with_missing_payroll_gender_spec.rb
spec/features/admin_claim_without_personal_data_spec.rb
spec/features/admin_claim_without_verified_identity_spec.rb
spec/features/admin_claims_filtering_spec.rb
spec/fixtures/schools.yml

This splits out some of the high-level claim-checking features into their own feature files:
- admin_claim_with_inconsistent_payroll_information_spec.rb
- admin_claim_with_missing_payroll_gender_spec.rb
- admin_claim_without_personal_information_spec.rb
- admin_claim_without_verified_identity_spec.rb
Plus two separate feature files for checking each type of policy.
The aim is to reduce the size and scope of the existing `admin_claim_check_spec.rb` so it does less and is more focused. What's left relates to: approving/rejecting claims the old way, plus some specs related to claim checks with the new interface. We'll be able to tidy these specs up further once we've got the remaining checks in place and have replaced the existing warning messages.

Re organise claim checking specs

---

CHANGELOG.md

- Fix question bug on school search results page
- Show a list of incomplete checks on the claim decision page
- Exclude claims for the other policy from claims with matching details

Release 060

---

CHANGELOG.md
app/controllers/admin/decisions_controller.rb
app/controllers/admin/tasks_controller.rb
app/models/claim.rb
app/models/claim_checking_tasks.rb
app/models/student_loans/admin_tasks_presenter.rb
app/views/admin/claims/index.html.erb
app/views/admin/decisions/_incomplete_tasks.html.erb
app/views/admin/decisions/new.html.erb
app/views/admin/tasks/index.html.erb
app/views/admin/tasks/student_loan_amount.html.erb
config/locales/en.yml
config/routes.rb
spec/factories/tasks.rb
spec/features/admin_checks_maths_and_physics_claim_spec.rb
spec/features/admin_checks_student_loan_claim_spec.rb
spec/features/admin_claim_check_spec.rb
spec/features/admin_claim_with_inconsistent_payroll_information_spec.rb
spec/features/admin_claim_with_missing_payroll_gender_spec.rb
spec/features/admin_claim_without_verified_identity_spec.rb
spec/features/admin_duplicate_claims_spec.rb
spec/models/claim_checking_tasks_spec.rb
spec/models/claim_spec.rb
spec/models/student_loans/admin_tasks_presenter_spec.rb
spec/requests/admin_decisions_spec.rb
spec/requests/admin_tasks_spec.rb

This introduces a task to check the student loan amount on student loans claims. Now that we have this task, we can switch student loans claims to default to the new task-based claim checking interface.
This PR introduces a new `ClaimCheckingTasks` class that we can use to model the various checks that may or may not be possible on any given claim.

Add a task for checking the student loan amount on student loans claims

---

CHANGELOG.md
app/views/admin/decisions/new.html.erb
app/views/admin/tasks/_claim_summary.html.erb
app/views/admin/tasks/employment.html.erb
app/views/admin/tasks/index.html.erb
app/views/admin/tasks/qualifications.html.erb
app/views/admin/tasks/student_loan_amount.html.erb

Some content tweaks to more closely follow the prototype. Each task now has a task-specific heading to better orientate the user.
**Before:**
**After:**

Claim checking content tweaks

---

CHANGELOG.md
app/views/admin/tasks/_claim_summary.html.erb

This was a request from claim checkers. If a claimant's TRN can't be found in our systems they will often search using their NI number instead. Putting this information front-and-center makes it easier for them to do so without switching to another screen.
**Before:**
**After:**

Include NI number in claim summary

---

spec/fixtures/schools.yml

Else it thinks that the leading zero is an octal representation of a
number.

Make school fixtures’ phone numbers be strings

---

CHANGELOG.md
app/assets/stylesheets/components/tag.scss
app/controllers/admin/tasks_controller.rb
app/helpers/admin/claims_helper.rb
app/models/task.rb
app/views/admin/claims/_answer_section.html.erb
app/views/admin/claims/_answers.html.erb
app/views/admin/decisions/_incomplete_tasks.html.erb
app/views/admin/tasks/_form.html.erb
app/views/admin/tasks/employment.html.erb
app/views/admin/tasks/index.html.erb
app/views/admin/tasks/qualifications.html.erb
app/views/admin/tasks/student_loan_amount.html.erb
config/locales/en.yml
db/data/20200311111523_set_passed_status_on_old_tasks.rb
db/migrate/20200310114405_add_outcome_to_tasks.rb
db/schema.rb
spec/factories/tasks.rb
spec/features/admin_checks_maths_and_physics_claim_spec.rb
spec/features/admin_checks_student_loan_claim_spec.rb
spec/features/admin_claim_check_spec.rb
spec/helpers/admin/claims_helper_spec.rb
spec/requests/admin_tasks_spec.rb

This updates the claim checking tasks to have a boolean value of `passed` and allows users to set this via a Yes/No interface on each task. It also shows the state of each task on the task list page and has a data migration to update older tasks that have already been created to set an explicit `passed` state.

Add Yes/No option to claim checking tasks

---

app/controllers/admin/payments_controller.rb
app/helpers/admin/claims_helper.rb
app/views/admin/payments/destroy.html.erb
app/views/admin/payments/remove.html.erb
config/initializers/inflections.rb
config/locales/en.yml
spec/features/admin_payroll_runs_spec.rb
spec/requests/admin_payroll_run_payments_spec.rb

Some adjustments to the content when removing a payment to make it clearer to the service operator what the next steps might be.
**Before**
**After**

Update payment removal content

---

azure-pipelines.yml

There's currently an [issue with Azure Devops pipelines](https://status.dev.azure.com/_event/179641421), which means that builds without a specific trigger aren't getting built. This commit adds that specific trigger. It can be removed once this is fixed, but it can't hurt to leave it in either.

Add specific trigger to pipelines

---

CHANGELOG.md
app/controllers/admin/tasks_controller.rb
app/models/claim_checking_tasks.rb
app/views/admin/claims/_claims_with_matching_details.html.erb
app/views/admin/claims/show.html.erb
app/views/admin/decisions/new.html.erb
app/views/admin/tasks/matching_details.html.erb
config/locales/en.yml
spec/features/admin_checks_maths_and_physics_claim_spec.rb
spec/features/admin_checks_student_loan_claim_spec.rb
spec/models/claim_checking_tasks_spec.rb

This adds the a new task that allows service operators to review any claims with matching details before approving a claim.

Add the claims with matching details task

---

CHANGELOG.md
app/models/claim_checking_tasks.rb
app/models/maths_and_physics/admin_tasks_presenter.rb
app/models/student_loans/admin_tasks_presenter.rb
app/views/admin/decisions/new.html.erb
app/views/admin/tasks/_form.html.erb
app/views/admin/tasks/identity_confirmation.html.erb
config/locales/en.yml
spec/features/admin_checks_maths_and_physics_claim_spec.rb
spec/features/admin_checks_student_loan_claim_spec.rb
spec/features/admin_claim_check_spec.rb
spec/models/claim_checking_tasks_spec.rb
spec/models/maths_and_physics/admin_tasks_presenter_spec.rb
spec/models/student_loans/admin_tasks_presenter_spec.rb

This replaces the existing banner which is displayed on the full claim page and on the claim decision page, which tells the service operator to contact the claimant at their school to verify their identity.
Was it safe to remove the existing banners? Do we think that there's a chance that a claims checker might still use the full claim page to approve a claim?

Add the identity confirmation task for claims that didn't go through GOV.UK Verify

---

CHANGELOG.md

- Add a task to check claims with matching attributes
- Add a claim checking task to verify identity of claimants who didn’t use  GOV.UK Verify

Release 063

---

CHANGELOG.md
app/views/admin/decisions/new.html.erb
app/views/admin/tasks/index.html.erb

A couple of small usability issues fixed:
- Add "Back" link and page title to claim decision screen
- Link claim tasks view back to the list of claims

Adjust back links

---

CHANGELOG.md
app/controllers/admin/payroll_gender_tasks_controller.rb
app/models/claim.rb
app/models/claim_checking_tasks.rb
app/views/admin/amendments/new.html.erb
app/views/admin/decisions/_decision_form.html.erb
app/views/admin/tasks/payroll_gender.html.erb
config/locales/en.yml
config/routes.rb
spec/features/admin_amend_claim_spec.rb
spec/features/admin_claim_check_spec.rb
spec/features/admin_claim_with_missing_payroll_gender_spec.rb
spec/models/amendment_spec.rb
spec/models/claim_checking_tasks_spec.rb
spec/requests/admin_payroll_gender_tasks_spec.rb
spec/requests/admin_tasks_spec.rb

This adds another task to the claim checking workflow to allow a user to specify the gender that HMRC have recorded for an applicant for payroll purposes. It's slightly different to other tasks in that, as well as creating a completed task, it also updates the user's payroll gender according to their response:
~Two~ One question~s~:
- I'm a bit unhappy about the way the routes are written - currently, as it stands, a user could _potentially_ bypass this task and mark it as passed by POSTing to the normal Tasks#create endpoint, or we could end up with a regression if a future dev misses that payroll gender tasks are created differently
- ~We now have **two** ways of updating the payroll gender - this way, or we can edit a claim. After discussion with Mark, we decided that this option was …

Add the missing payroll gender task

---

azure/resource_groups/app/template.json
bin/azure-deploy

We're having issues deploying due to a change in the way ARM templates are handled. For some reason, running `string` against a created array now appears to flatten out the array into a comma seperated list, so we need to change how we build the `SERVICE_ENTITY_IDS` JSON array. This builds up the array using a combination of a `[`, an (escaped) single quote `''`, the VSP entity ID and a `]`. The means if the value of `VSP.VERIFY_ENTITY_ID` was `http://example.com`, the resulting JSON string would be `['http://example.com']`.
I've also updated the command we use to create deployments, as we were getting a deprecation warning.

Fix deployments

---

CHANGELOG.md
app/views/admin/amendments/new.html.erb
app/views/admin/amendments/not_amendable.html.erb
app/views/admin/claims/show.html.erb
app/views/admin/tasks/_claim_summary.html.erb

When the new claim window opens we will start accepting claims for the
new academic year and want a way to easily distinguish between claims
made in different academic years:

Show the academic year when viewing a claim

---

app/views/admin/decisions/_incomplete_tasks.html.erb
app/views/admin/tasks/_form.html.erb
app/views/admin/tasks/index.html.erb
config/locales/en.yml
spec/features/admin_checks_maths_and_physics_claim_spec.rb
spec/features/admin_checks_student_loan_claim_spec.rb
spec/features/admin_claim_with_missing_payroll_gender_spec.rb

Reduces some duplication and nesting of the locale data that we use for displaying the claim checking tasks.

Refactory admin tasks locales

---

config/locales/en.yml

Not sure why we weren't seeing exceptions raised when the specs run, but
going to investigate and fix that separately.

Fix typo in translation file

---

app/controllers/admin/claims_controller.rb
app/controllers/admin/decisions_controller.rb
app/models/claim.rb
app/models/claim/geckoboard_dataset.rb
app/models/decision.rb
app/views/admin/tasks/index.html.erb
db/migrate/20200316100421_make_decisions_undoable.rb
db/schema.rb
spec/factories/decisions.rb
spec/features/admin_checks_maths_and_physics_claim_spec.rb
spec/features/admin_checks_student_loan_claim_spec.rb
spec/features/admin_claim_check_spec.rb
spec/features/admin_claim_with_missing_payroll_gender_spec.rb
spec/features/admin_claim_without_verified_identity_spec.rb
spec/models/amendment_spec.rb
spec/models/claim/personal_data_scrubber_spec.rb
spec/models/claim_spec.rb
spec/models/decision_spec.rb
spec/requests/admin_decisions_spec.rb
spec/support/geckoboard_helpers.rb

All decisions now have a boolean `undone` column which defaults to `false`. Setting this to `true` indicates that a decision has been undone.
When a decision is marked as `undone` it is no longer included in any of the scopes which return `accepted`/`rejected`/`awaiting decision` claims, nor in a `Claim`'s `decision` method (which returns the latest valid decisions).
Changes to specs are to reflect the fact that these scopes now rely on an actual database query, which doesn't apply to objects brought into existence with `build` instead of `create`.

Make decisions on a claim undoable

---

app/controllers/claims_controller.rb
app/helpers/admin/claims_helper.rb
app/helpers/application_helper.rb
app/helpers/claims_helper.rb
app/helpers/student_loans_helper.rb
app/mailers/claim_mailer.rb
app/mailers/payment_mailer.rb
app/models/admin/presenter_methods.rb
app/models/maths_and_physics/admin_tasks_presenter.rb
app/models/maths_and_physics/eligibility_admin_answers_presenter.rb
app/models/maths_and_physics/eligibility_answers_presenter.rb
app/models/student_loans/admin_tasks_presenter.rb
app/models/student_loans/eligibility_admin_answers_presenter.rb
app/models/student_loans/eligibility_answers_presenter.rb

Following up on https://github.com/DFE-Digital/dfe-teachers-payment-service/pull/980, I've figured out why we didn't get an early warning about missing translation keys.
Rails’ `translate` method delegates to `I18n#translate`, but also performs additional functions, including raising an exception when a translation key is missing and the application is configured with `ActionView::Base.raise_on_missing_translations` set to true. By using this method we make it less likely that we will ship code where translations are missing as we should see exceptions raised in the specs.

Use Rails’ translate method over I18n.translate

---

CHANGELOG.md
app/controllers/admin/claims_controller.rb
app/models/claim/search.rb
app/views/admin/claims/search.html.erb
config/brakeman.ignore
spec/features/admin_search_spec.rb
spec/models/claim/search_spec.rb
spec/requests/admin_claims_spec.rb

This adds a class to search claims for a number of different attributes, and updates the search 
page to list the search results, rather than just redirecting to a single claim.

Support searching for claims with more than just the reference

---

azure/templates/app.json

This tells Azure to monitor the healthcheck endpoint every 2 minutes. If an instance does not respond within 10 minutes, the instance is taken out of the pool. It's a manual process to put the app back in the pool, and we're not (currently) able to be alerted if something is taken out of the pool (this is a Windows-only thing at the moment). That said, it's better than us accidentally routing people to a broken instance.
Ideally, we'll want to have autohealing, but this is (again) a Windows-only thing.
More on the Health Check functionality is [here](https://github.com/projectkudu/kudu/wiki/Health-Check-%28Preview%29)

Set healthcheck endpoint to monitor

---

CHANGELOG.md
app/models/claim.rb
app/models/claim/matching_attribute_finder.rb
spec/models/claim/matching_attribute_finder_spec.rb
spec/models/claim_spec.rb

This adds a new scope to filter by academic year, and then uses that scope in the matching attribute finder to only find claims that are for the same academic year as the source claim.

Exclude claims from previous academic years on matching claims screen

---

CHANGELOG.md
app/models/automated_checks/dqt_report_consumer.rb
app/models/automated_checks/dqt_report_csv_to_records.rb
app/models/maths_and_physics/dqt_record.rb
app/models/student_loans/dqt_record.rb
spec/fixtures/files/example_dqt_report.csv
spec/models/automated_checks/dqt_report_csv_to_records_spec.rb
spec/models/maths_and_physics/dqt_record_spec.rb
spec/models/student_loans/dqt_record_spec.rb

When we built the automated DQT checks we were working on the assumption
that there would be a single row for each record. It turns out there
can be multiple rows for each claimant.
We need to munge these rows down to unique records so we can iterate
through them and safely create checks for each claim.
The claim reference, date of birth and QTS award year are all consistent
between grouped rows so we can use the first row's value. For the ITT
subject and degree JAC codes we need to collate and combine these values
from the multiple grouped rows.
As this new class is responsible for transforming the data in to a shape
we expect I used the opportunity to move the logic to do with
parsing the dates and transforming columns to arrays.

Transform DQT report rows to unique records

---

azure/resource_groups/app/parameters/development.template.json

We're now self-signing certificates for the GOV.UK Verify VSP. This updates development to use the newly created key and certificate that we generated for testing purposes.

Update vsp keys and certs on development

---

CHANGELOG.md
app/controllers/admin/decisions_undo_controller.rb
app/models/amendment.rb
app/models/claim.rb
app/views/admin/amendments/new.html.erb
app/views/admin/decisions_undo/new.html.erb
config/locales/en.yml
config/routes.rb
spec/features/admin_amend_decision_spec.rb
spec/models/amendment_spec.rb
spec/models/claim_spec.rb
spec/requests/admin_amendments_spec.rb
spec/requests/admin_claims_spec.rb
spec/requests/admin_undo_decisions_spec.rb

This builds on #972 to add a UI to allow a decision to be undone. It works in a similar way to how other amendments are made, by adding creating an Amendment record with notes and details on what changes have been made.

User interface for undoing a decision

---

app/controllers/admin/amendments_controller.rb
app/controllers/admin/claims_controller.rb
app/views/admin/claims/show.html.erb
spec/features/admin_amend_claim_spec.rb
spec/features/admin_checks_maths_and_physics_claim_spec.rb
spec/features/admin_checks_student_loan_claim_spec.rb
spec/features/admin_claim_with_inconsistent_payroll_information_spec.rb
spec/features/admin_claim_without_verified_identity_spec.rb
spec/requests/admin_amendments_spec.rb
spec/requests/admin_claims_spec.rb

We have now switched both policies to using the new "task"-based UI as the primary interface for viewing and checking claims, but there are still a few things that either only exist on the old "full view", or bits of interaction that assume the old "full view" is the main screen for viewing a claim.
- Remove the "decision" form from the "full claim" view. There should only be one place where a user decides the outcome of a claim.
- Searching for a claim should take the user to the "tasks" view, not the "full claim" view.
- Amending a claim should take the user back to the "tasks" view, not the "full claim" view.

Make the new task view primary

---

app/controllers/admin/qualification_report_uploads_controller.rb
app/models/automated_checks/dqt_report_consumer.rb
spec/requests/admin_qualification_report_upload_spec.rb

There's a potential race condition where a user could manually complete
a qualification task at the same time (after `Claim.awaiting_task`) and
cause an exception to occur. By wrapping the process in a transaction
we can make the script fail gracefully.

Run the automated DQT checks in a transaction

---

CHANGELOG.md
app/models/automated_checks/dqt_report_consumer.rb
app/models/automated_checks/dqt_report_csv_to_records.rb
spec/features/admin_automated_qualification_check_spec.rb
spec/fixtures/files/example_dqt_report.csv
spec/models/automated_checks/dqt_report_consumer_spec.rb
spec/models/automated_checks/dqt_report_csv_to_records_spec.rb
spec/support/fixture_helpers.rb

Currently claims checkers do an extra informal identity verification
on the record in DQT to make sure it matches the claimant. They check
the name and National Insurance number (NiNo). The NiNo doesn't always
exist in DQT so instead we can add the extra verification step as a
match against the surname.
We recognise that names are subject to change and can legitimately not
match, but these claims will still be checked just manually by a person
instead of automatically.
Surnames that come back from GOV.UK Verify can be all upper case. To
allow for this we need to make the comparison case insensitive.

Ensure the surname in DQT matches the one in the claim
